README.md

the link in README.md is currently broken, this fixes it

fix broken link to quickstart

---

bokeh/_glyph_functions.py

never use name as a substitute id

---

bokehjs/src/coffee/common/selection_manager.coffee
bokehjs/src/coffee/renderer/overlay/poly_selection.coffee
bokehjs/src/coffee/tool/gestures/lasso_select_tool.coffee
bokehjs/src/coffee/tool/gestures/poly_select_tool.coffee
bokehjs/src/coffee/tool/gestures/tap_tool.coffee

per-renderer selector, handle appends correctly

---

bokeh/models/plots.py

Plot.add_tool wrong error message

---

bokeh/plotting.py
bokeh/tests/test_plotting.py

Don't use unminified resources in bokeh.plotting

---

bokeh/resources.py
bokeh/tests/test_resources.py

issues: fixes #1606 
This should get some additional hand checking.

don't use global $

---

bokehjs/src/coffee/tool/inspectors/hover_tool.coffee

issues: fixes #1644 
This implements the "short term fix" described in the issue.

check for sx, sy for snap_to_data

---

bokeh/charts/__init__.py
bokeh/charts/gmap.py
examples/charts/gmap.py

Add new GMap chart implementation

---

bokeh/mpl.py
examples/compat/ggplot/density.py
examples/compat/ggplot/line.py
examples/compat/ggplot/step.py
examples/compat/ggplot/xkcd_density.py
examples/compat/mpl/lc_dashed.py
examples/compat/mpl/lc_offsets.py
examples/compat/mpl/listcollection.py
examples/compat/mpl/polycollection.py
examples/compat/mpl/subplots.py
examples/compat/mpl/test.ipynb
examples/compat/mpl/test.py
examples/compat/pandas/dataframe.py
examples/compat/pandas/series.py
examples/compat/seaborn/kde.py
examples/compat/seaborn/sinerror.py
examples/compat/seaborn/violin.py

Replace mpl.show(...) with show(...)

---

bokeh/charts/_charts.py

change charts show behaviour when server and notebook are specified

---

bokehjs/src/coffee/common/grid_plot.coffee
examples/plotting/file/grid.py
examples/plotting/server/grid.py

issues: fixes #1636
ping  @tr8dr also note `None` will work in grid plots in 0.7.1

accept None as a placeholder for empty cells in a grid plot

---

bokeh/mpl.py

Fixes #1557.
Just using the @fpliger refactored tools to use default tool on mpl converted plots.

Default tools on mpl.to_bokeh

---

bokeh/server/views/data.py
bokeh/transforms/line_downsample.py

Closes #1654.  Uses same return path for the code path where there are so few points that downsampling is skipped.
Change to data.py makes debugging easier by not reusing a variable name.

Fixing line downsample bug. 

---

bokeh/enums.py
bokeh/models/widgets/tables.py
bokehjs/src/coffee/common/base.coffee
bokehjs/src/coffee/widget/cell_editors.coffee
bokehjs/src/coffee/widget/cell_formatters.coffee
bokehjs/src/coffee/widget/data_table.coffee
examples/glyphs/widgets_server.py

This partially addresses #1563.

Add support for date formatter/editor to DataTable

---

bokeh/charts/_chartobject.py

Fix issue with categorical charts allowing pan/zoom tools 

---

bokeh/models/widgets/inputs.py
examples/app/sliders_applet/sliders_app.py

allow sliders to have float step size

---

sphinx/json_ref.py
sphinx/source/docs/reference/models.rst

issues: closes #1581
needs to be re-run by hand to replace source/docs/reference/models.rst for now

initial cut at script to autodoc json models

---

sphinx/source/docs/user_guide/objects.rst

Fix parameter name

---

scripts/travis_install

Temporary fix until conda get fixed with python3.

---

examples/plotting/server/selection_histogram.py
examples/plotting/server/selection_update.py

isses: fixes #1709 
NOTE: also renamed to `selection_histogram.py`

fix zeros reset bug in selection histogram

---

examples/app/sliders_applet/sliders_app.py

Some quick fixes to get the sliders app working again, plus some additional clean up.

Clean up, some documentation, and fixes for slider app to work with the figure class

---

bokeh/properties.py
bokeh/tests/test_properties.py

issues: closes #889 
* Dashpattern accepts tuples
* Tests for dashpattern with tuples

Dashpattern accept tuples

---

bokeh/__init__.py

Issues fixes: #1761 
Let's see if this works...

Detect if you are inside an IPython instance to load the notebook.

---

bokeh/crossfilter/models.py
bokeh/crossfilter/plotting.py
bokeh/models/ranges.py
examples/app/crossfilter/crossfilter_app.py

Issues: fixes #1703
Going ahead and opening this pull request for discussion. It is nearly complete, containing a lot of documentation additions, and fixes a few bugs. Might be a little overboard with comments/docs, but good for an example application.
I left some todos in there that I'll clean up before finalizing it and there is one remaining bug I've found that I cannot track down. Result is an error on the javascript side when creating a scatter plot with categorical data on the x axis and continuous on the y axis. The result is an empty plot area.

Crossfilter bug fixes and documentation

---

scripts/travis_install

Removing lines introduced by #1755

Remove debugging lines.

---

examples/app/stock_applet/README.md
examples/app/stock_applet/stock_app.py
examples/app/stock_applet/stock_data.py

This should provide the other part of bokeh/bokeh#1758. I need to look back through this to make sure it is working correctly when I have some time, so not quite ready. It at least pops up and appears to work.
I also added a script to more easily download the data required.

Stock app fixes for new api

---

bokeh/plotting.py

Remove name arg from plotting.gridplot

---

bokeh/crossfilter/models.py
bokeh/crossfilter/plotting.py
bokeh/crossfilter/plugins.py
bokehjs/src/coffee/widget/crossfilter_template.eco

This was quickly done in response to #1768. Basically, I'm just wrapping the previously highest level plotting method and passing down a single facet per tab, which is then getting used to filter the data further.
I want to take a better look at it to see if I can make the "getting filtered data" and "getting facets" a bit more consistent. I think I have a bug left there in the 2d one as well, but haven't tested it yet.
[Here are some screenshots](http://imgur.com/a/MemMe) of it working.

Add facet tab to Crossfilter

---

bokeh/_glyph_functions.py

issues: fixes #1798 
quick fix for setting properties of selection/nonselection glyphs now that glyphs are not Fill/LineProps subclasses

fix visible selection 

---

bokeh/models/axes.py
sphinx/source/docs/user_guide/objects.rst

issues: fixes #1721
Also made some minor corrections removing references to "curplot". However, UG needs a more rigorous pass over it.

update some docs about axes/grids

---

bokeh/plotting.py
bokeh/tests/test_plotting.py

Also removes relative import in test_plotting, add main function
Closes #897

Alias width and height to plot_width/plot_height with tests in figure()

---

bokeh/plotting.py
examples/embed/slideshow/app_reveal.py
examples/plotting/file/linked_panning.py
examples/plotting/notebook/linked_brushing.ipynb
examples/plotting/notebook/linked_panning.ipynb
examples/plotting/server/linked_panning.py

Removing curplot leftovers and make show ask for an object.

---

bokehjs/src/coffee/common/cartesian_frame.coffee
bokehjs/src/coffee/common/plot.coffee

remove broken, unused function

---

sphinx/source/docs/user_guide/ar.rst
sphinx/source/docs/user_guide/objects.rst

Some docs fixes 

---

bokeh/mixins.py
bokeh/properties.py
sphinx/source/docs/dev_guide.rst

Maintain {Data,Color}Spec's default value properly

---

sphinx/source/docs/user_guide/embedding.rst

update embedding section

---

bokeh/charts/builder/step_builder.py
bokeh/charts/builder/tests/test_step_builder.py
examples/charts/steps.py

Use Line for steps chart

---

scripts/travis_install

`conda-build` seems broken... pinning to get TravisCI running again...
I need this one merged to make the devel build...

Pin conda-build to get TravisCI running again

---

.travis.yml

Use ruby regex to enable those specific branches...

Enable runs of TravisCI in branches tagged with xxx.dev[rc].xxxxxxxx form

---

.travis.yml

I tested with numeric character, but I need to support the git hashes too...

Fix any caracther in the ruby regex to support the tag containing sha.

---

bokeh/resources.py

Fix the variable name in the comment/documentation

Fix parameter name: host -> root_url

---

bokeh/server/utils/reload.py

From: http://stackoverflow.com/questions/28241579/error-when-trying-to-run-bokeh-server

Fix broken werkzeug import in bokeh-server

---

bokeh/charts/builder/horizon_builder.py
bokeh/models/axes.py
bokeh/models/renderers.py
bokehjs/src/coffee/renderer/guide/axis.coffee

This allows to skip the rendering of the axis and possible other rendered elements.
https://github.com/bokeh/bokeh/issues/1730

1730 hide axis

---

scripts/test_matrix.py

Add test matrix script

---

bokeh/document.py
bokeh/models/sources.py
bokeh/server/serverbb.py
bokehjs/src/coffee/common/base.coffee
bokehjs/src/coffee/source/ajax_data_source.coffee
examples/plotting/file/ajax_source.py
tests/travis/test.yaml

issues: closes #1682 
also includes bugfix for bokeh server garbage collection
@bryevdv please review

ajax data source

---

bokeh/charts/_builder.py
bokeh/charts/builder/area_builder.py
bokeh/charts/builder/bar_builder.py
bokeh/charts/builder/boxplot_builder.py
bokeh/charts/builder/donut_builder.py
bokeh/charts/builder/dot_builder.py
bokeh/charts/builder/heatmap_builder.py
bokeh/charts/builder/histogram_builder.py
bokeh/charts/builder/horizon_builder.py
bokeh/charts/builder/line_builder.py
bokeh/charts/builder/scatter_builder.py
bokeh/charts/builder/step_builder.py
bokeh/charts/builder/tests/test_histogram_builder.py
bokeh/charts/builder/timeseries_builder.py

rename get_data, get_source, prepare_values, draw builders methods to `_adapt_values`, `_process_data`, `_set_sources`, `_yield_renderers`

rename get_data, get_source, prepare_values, draw builders methods

---

bokehjs/src/coffee/tool/gestures/resize_tool.coffee
bokehjs/src/less/continuum.less

place resize handle overlay more carefully

---

bokeh/charts/builder/boxplot_builder.py
examples/charts/boxplot.py

Fix BoxPlot broken with iterable(list) inputs

---

bokeh/_glyph_functions.py
sphinx/source/_static/my-styles.css

closes #1746
docstring plot examples.

docstring plot examples

---

setup.py

Just commenting out for now until we decide if we really want to use it for the cli

Remove click for dependencies.

---

bokeh/charts/builder/horizon_builder.py
bokeh/models/axes.py
bokehjs/src/coffee/renderer/guide/axis.coffee

Rename and reverse logic: Axis.hide -> Axis.visible

---

bokeh/cli/core.py
conda.recipe/meta.yaml

We forgot to delete click from the recipe too... merging as soon as TravisCI pass...

Delete click from the conda recipe.

---

bokeh/charts/builder/horizon_builder.py

Change docstring example data to show nicer exaples (still with small dataset).
Previous was:
now is:

change docstring example with better data

---

sphinx/source/docs/gallery.rst
sphinx/source/docs/server_gallery/aw_animate.rst
sphinx/source/docs/server_gallery/crossfilter_server.rst
sphinx/source/docs/server_gallery/line_animate.rst
sphinx/source/docs/server_gallery/sliders_server.rst
sphinx/source/docs/server_gallery/stocks_server.rst

server gallery

---

bokehjs/src/coffee/tool/inspectors/hover_tool.coffee
bokehjs/src/coffee/util/util.coffee

Fix issues with placeholder formatting in hover tool

---

sphinx/source/docs/user_guide/charts.rst

fix error in interface output charts section

---

sphinx/source/docs/reference/glyphs.rst
sphinx/source/docs/user_guide/plotting.rst

fix broken links

---

bokeh/plotting.py
examples/plotting/server/selection_histogram.py

remove spurious curplot

---

examples/embed/slideshow/app_reveal.py

Delete old plotting import stuff.

---

bokehjs/src/coffee/api/figure.coffee
bokehjs/src/coffee/renderer/annotation/tooltip.coffee
bokehjs/src/less/main.less
project/src/main/scala/LessPlugin.scala

This fixes a long standing issue where tooltip arrow (indicator) was incorrectly centered.

Make tooltips properly centered on data points

---

examples/embed/spectrogram/spectrogram.py

update spectrogram to new API

---

examples/embed/README.md
examples/embed/publishing.py

Mention --multi-user mode requirement for some embed examples

---

setup.py

issues: fixes #1918 
Replace check against hardcoded list of commands with simple check that there are some arguments.

Make setup.py more flexible with other commands

---

CHANGELOG
bokehjs/package.json
bokehjs/src/coffee/main.coffee
sphinx/source/docs/release_notes.rst
sphinx/source/docs/releases/0.8.1.rst

All the steps done (including the fiddles update) except from:

Release 0.8.1

---

bokehjs/src/coffee/common/layout_box.coffee
bokehjs/src/coffee/main.coffee
bokehjs/src/coffee/mapper/categorical_mapper.coffee
bokehjs/src/coffee/range/data_range1d.coffee
bokehjs/src/coffee/renderer/glyph/glyph.coffee
bokehjs/src/coffee/renderer/glyph/rect.coffee
bokehjs/src/coffee/ticking/log_ticker.coffee

Use _.isXXX(x) instead of typeof(x) == "XXX"

---

bokeh/__init__.py
bokeh/settings.py
sphinx/source/docs/dev_guide/notes.rst

Make logging false by default

---

scripts/interactive_tester.py
scripts/test_matrix.py

Issues: fixes #1949 
It also adds the following improvements:
* interactive tester now have the notion of "session" to store progress of the tests. It store every single example file ran and the results. If it crashes before registering the result it will as for the result of the unregistered test.
* windows compatibility (now test_matrix script works also on window)

Tests scripts enhancements

---

bokeh/server/configure.py
bokeh/server/tests/cow_tests.py
bokeh/server/tests/test_utils.py

issues: fixes #1961 
uses `mock.patch`

Suppress logging of known warnings and error during tests.

---

sphinx/source/_static/bokeh-docs.css
sphinx/source/docs/quickstart.rst

quickstart edits

---

bokeh/charts/__init__.py
bokeh/plotting.py
examples/plotting/file/categorical.py
examples/plotting/file/correlation.py
examples/plotting/file/glucose.py
examples/plotting/file/histogram.py
examples/plotting/file/legend.py
examples/plotting/file/rect.py
examples/plotting/file/scatter.py
examples/plotting/file/scatter_selection.py
examples/plotting/file/stocks.py
examples/plotting/file/vector.py
examples/plotting/server/correlation.py
examples/plotting/server/glucose.py
examples/plotting/server/legend.py
examples/plotting/server/rect.py
examples/plotting/server/scatter.py
examples/plotting/server/scatter_selection.py
examples/plotting/server/stocks.py
examples/plotting/server/vector.py

Deprecate VBox/HBox.

---

bokeh/charts/__init__.py
bokeh/server/__init__.py
bokeh/server/blaze/__init__.py
bokeh/server/blaze/config.py
bokeh/server/blaze/views.py
bokeh/server/configure.py
bokeh/server/server_backends.py
bokeh/server/serverbb.py
bokeh/server/settings.py
bokeh/server/start.py
bokeh/server/tests/auth_test.py
bokeh/server/tests/cow_tests.py
bokeh/server/tests/multiuser_auth_test.py
bokeh/server/tests/remotedata_tests.py
bokeh/server/tests/test_utils.py
bokeh/server/tests/wsmanager_test.py
bokeh/server/views/backbone.py
bokeh/server/views/bbauth.py
bokeh/server/views/main.py
bokeh/transforms/ar_downsample.py

Start on making code pyflake compliant

---

bokeh/charts/builder/boxplot_builder.py
bokeh/charts/builder/tests/test_boxplot_builder.py
examples/plotting/file/boxplot.py
examples/plotting/notebook/boxplot.ipynb
examples/plotting/server/boxplot.py
sphinx/source/tutorial/exercises/boxplot.py
sphinx/source/tutorial/solutions/boxplot.py

Fix boxplot equations

---

examples/embed/spectrogram/spectrogram.coffee
examples/embed/spectrogram/static/js/spectrogram.js

Use Bokeh.$ in spectrogram

---

sphinx/source/docs/user_guide/interfaces.rst

issues: none
@bryevdv asked via flowdock to check on http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html a short while ago. I opened the page to look at it soon, only to find a week later, with the PR already merged.
Anyway, it's a very nice overview IMO. Here are some small style issues.

Minor style changes to interfaces docs

---

bokeh/charts/_chart_options.py

set chart axis labels default to empty string

---

examples/app/stock_applet/README.md

With the quotes this is interpreted as a single argument.

typo in stock_applet docs for moving quantquote data.

---

sphinx/source/_templates/layout.html
sphinx/source/docs/user_guide.rst
sphinx/source/docs/user_guide/intro.rst

issues: closes #2073
New docs at: http://bokeh.pydata.org/en/test/docs/user_guide.html
Merged glossary and interfaces sections into Intro section

edits to UG

---

bokeh/embed.py

issues: fixes #1956 
I'm pretty sure this wasn't intentional?

Removed duplicated autoload_server method

---

setup.py

better error messags and build artifact size information

---

bokeh/protocol.py

issues: closes #2098 
Fix the issue with BokehJSONEncoder not being able to encode decimal.Decimal correctly. Casting to a float solves the issue, although, it very very slightly inaccurate and maybe casting to a string would be better?

Fix for issue #2098

---

bokeh/util/functions.py

fix missing import on simpleapp

---

examples/plotting/server/selection_histogram.py

Updated selection_histogram.py example with three different populations.

update selection histogram with multiple populations

---

bokehjs/src/coffee/mapper/categorical_mapper.coffee
bokehjs/src/coffee/renderer/glyph/annular_wedge.coffee
bokehjs/src/coffee/renderer/glyph/annulus.coffee
bokehjs/src/coffee/renderer/glyph/circle.coffee
bokehjs/src/coffee/renderer/glyph/glyph.coffee
bokehjs/src/coffee/renderer/glyph/marker/marker.coffee
bokehjs/src/coffee/renderer/glyph/patches.coffee
bokehjs/src/coffee/renderer/glyph/rect.coffee
bokehjs/src/coffee/renderer/glyph/wedge.coffee
bokehjs/test/test_mapper/test_categorical_mapper.coffee

handle categorical coords correctly in hit testing

---

sphinx/source/docs/user_guide/embedding.rst

add CDN links in embedding docs, components section

---

bokeh/models/widgets/layouts.py

Bugfix for Issue #2124
https://github.com/bokeh/bokeh/issues/2124

Fixed updating of setup_events

---

examples/app/stock_applet/stock_app_simple.py

Issues: closes #2128 
Fixes the issue by returning a dict with the histograms to replace the current ones

fix stocks simpeapp selection

---

.travis.yml
bokeh/colors.py
bokeh/models/tests/test_glyphs.py
conda.recipe/meta.yaml

issues: closes #2078
This adds pyflakes (and minor style) checking to Travis CI. This will prevent introducing new pyflakes violations and potential bugs.
WIP: need to verify that it actually works.

Add pyflakes checking to Travis CI

---

bokeh/io.py
bokeh/models/actions.py
bokeh/models/widgets/buttons.py
bokeh/models/widgets/inputs.py
bokehjs/src/coffee/action/callback.coffee
bokehjs/src/coffee/action/open_url.coffee
bokehjs/src/coffee/common/base.coffee
bokehjs/src/coffee/widget/button.coffee
bokehjs/src/coffee/widget/checkbox_button_group.coffee
bokehjs/src/coffee/widget/checkbox_group.coffee
bokehjs/src/coffee/widget/date_picker.coffee
bokehjs/src/coffee/widget/date_range_slider.coffee
bokehjs/src/coffee/widget/dropdown.coffee
bokehjs/src/coffee/widget/multiselect.coffee
bokehjs/src/coffee/widget/radio_button_group.coffee
bokehjs/src/coffee/widget/selectbox.coffee
bokehjs/src/coffee/widget/slider.coffee
bokehjs/src/coffee/widget/text_input.coffee
bokehjs/src/coffee/widget/toggle.coffee
bokehjs/src/less/continuum.less
bokehjs/src/less/widgets.less
bokehjs/test/index.coffee
bokehjs/test/test_action/index.coffee
bokehjs/test/test_action/test_callback.coffee
bokehjs/test/test_ticking/test_numeral_tick_formatter.coffee
examples/plotting/file/slider.py

issues: closes #2174 
Accepts a dictionary that maps plot objects to names that will be available to the JS code, as well as a snippet of JS code that serves as the function body. The function also receives a "value" parameter,
which is, for instance, the new value of a widget when it is updated.

Add a simple "callback" action

---

bokehjs/npm-shrinkwrap.json

Swap all URLs to be main registry.npmjs.org repo

---

bokehjs/src/coffee/widget/multiselect.coffee

fix scope/context issue breaking multiselect

---

bokehjs/src/less/widgets.less
examples/plotting/file/slider.py

remove float on vbox div

---

bokeh/crossfilter/models.py
bokeh/models/sources.py
examples/app/stock_applet/stock_app.py
examples/app/stock_applet/stock_app_simple.py
examples/glyphs/linked_tap_server.py
examples/plotting/server/selection_histogram.py

fix broken selections

---

scripts/devdeps.py
scripts/test_matrix.py
sphinx/source/docs/dev_guide/building.rst

Create script that checks for dev and docs dependencies.

---

conda.recipe/meta.yaml
setup.py
sphinx/source/tutorial/quick_install.rst

Delist gevent as a dependency.

---

examples/glyphs/data_tables.ipynb

Old DataRange1D interface was not supported anymore

Update DataRange1d that wasn't updated on notebook after last API change

---

scripts/build_upload.sh
scripts/release_upload.sh

Run binstar upload in the correct 'scripts' location

---

scripts/build_upload.sh
scripts/release_upload.sh

This is another test... locally the script is working so it does not make sense that do not work on TravisCI unless there is something weird with the `i` var... I don't think so, but let's try this... it is not harmful because the var now have a better name.

Use another env variable is case of weird previous use of the i var.

---

sphinx/source/docs/quickstart.rst

possibly to easily -> possible to easily, having all many language options -> having many language options

fix two small typos

---

scripts/travis_install

Just that, I will report later the issue in the binstar repo...

Pin binstar until binstar build fix the platform path problem.

---

bokeh/charts/builder/boxplot_builder.py
bokeh/charts/builder/tests/test_boxplot_builder.py

Fix boxplot chart palette

---

bokeh/models/sources.py
bokehjs/src/coffee/common/selection_manager.coffee
bokehjs/src/coffee/source/column_data_source.coffee

add callback on selection changes

---

scripts/release_upload.sh

Fixes #2105, just deleting the first build of the bokeh...

Delete first build to avoid uploading to binstar.

---

bokehjs/src/less/flexbox.less

Issues: fixes #2269 
Fix hbox rendering issue using newer ```display: flex;``` rule so multiple (older) definitions don't clash for random browsers

Fix broken hbox

---

bokeh/models/widgets/dialogs.py
bokehjs/src/coffee/widget/dialog.coffee
bokehjs/src/coffee/widget/dialog_template.eco
examples/glyphs/taylor_server.py

Change Dialog widget to support BaseBox content and list of Buttons

---

sphinx/source/docs/reference/models.rst

Just noticed this and thought it might be better to put it on the evolving docs branch than master. If you want me to move it let me know. Sorry to open a PR, it just took longer to write an issue. :)

DOC: Grammar fix for intro to Models

---

bokeh/server/blaze/config.py

Also some changes to make is more readable.

Add info in the warn message about some missing dependecies.

---

examples/plotting/file/color_sliders.py

I've changed the name of the script to better match your naming conventions. At my end it's been called colorPicker.py so far\*.
I tested the script on my system and it runs just fine. I get a warning:  
`No handlers could be found for logger "bokeh.resources"`  
but this seems to be harmless.
The only big difference that I can see in terms of code style is my inclusion of a namespace for bokeh.plotting  e.g  
`from bokeh import plotting as bkplt`  
`source = bkplt.ColumnDataSource(# etc etc`  
which I use because it seems more explicit to me. Happy to change if you would prefer absolute consistency.
\*TBH I think the new name is more descriptive - color picking was always the intended end goal of this script, but I haven't yet had time to devote to figuring out a way to get the two plots …

initial commit of color_sliders.py

---

bokehjs/src/coffee/tool/actions/help_tool.coffee

Fix broken link in help tool.

---

bokehjs/src/coffee/api/figure.coffee
bokehjs/src/coffee/common/random.coffee
bokehjs/src/coffee/renderer/guide/categorical_axis.coffee
bokehjs/src/coffee/renderer/guide/linear_axis.coffee
bokehjs/src/coffee/renderer/guide/log_axis.coffee

BokehJS API fixes

---

sphinx/source/docs/user_guide/tools.rst

[doc] changed `tap_select` to `tap`

---

bokeh/plotting.py

Small self contained code cleaning

remove extra whitespace

---

sphinx/source/docs/tutorials/exercises/brushing.py
sphinx/source/docs/tutorials/exercises/lines.py
sphinx/source/docs/tutorials/solutions/brushing.py
sphinx/source/docs/tutorials/solutions/lines.py

Should reduce confusion for people just getting started.

Keep output HTML filename consistent with exercise name.

---

bokehjs/src/coffee/renderer/glyph/marker/diamond_cross.coffee

Crosses now display correctly in DiamondCross.

---

sphinx/source/docs/dev_guide/building.rst
sphinx/source/docs/installation.rst

Will merge ASAP we have the indication to go live with the change...
Then we need to redeploy the docs...

Change binstar.org references to anaconda.org references.

---

bokeh/models/tools.py

Addresses #2357. The online documentation already says that the property ought to exist, and therefore doesn't need to be changed.

Update tools.py to add dimensions property to CrosshairTool

---

scripts/test_matrix.py

Improve test matrix

---

bokeh/mpl.py

Add alpha to patches.

---

conda.recipe/build.sh

Remove additional point in version specification.

---

bokeh/models/plots.py
bokeh/plotting_helpers.py

add tab completion for splattable lists

---

bokeh/models/map_plots.py
bokeh/properties.py
bokehjs/src/coffee/common/gmap_plot.coffee
examples/glyphs/maps.py

support map styles for GMapPlot

---

bokehjs/src/coffee/main.coffee

Refers to issue https://github.com/bokeh/bokeh/issues/2392. Adds an error prompt that instructs user to check console or refresh page.

Added error prompt wth message

---

sphinx/source/docs/installation.rst

add info about configuring sample data location

---

bokehjs/src/coffee/range/data_range1d.coffee
bokehjs/test/test_range/index.coffee
bokehjs/test/test_range/test_datarange1d.coffee

issues: fixes #2431 
Quick fix for a fairly severe annoyance

Have datarage1d respect user bounds

---

bokeh/embed.py
bokeh/tests/test_embed.py

If you'd like to use this but would prefer I write a test first or make some stylistic changes let me know. Also feel free to shoot it down if you feel it's unnecessary.

Allow users to specify Jinja2 template variables

---

bokehjs/gulp/tasks/scripts.coffee
bokehjs/gulp/tasks/styles.coffee
bokehjs/package.json
sphinx/source/docs/dev_guide/building.rst

add debug flag to enable source maps

---

bokeh/models/plots.py

Make GridPlot.select api to follow Plot.select

---

conda.recipe/meta.yaml

Last seaborn release seems to break compatibility for our violin example.. pining to the working version for now...

pin seaborn version

---

bokeh/server/settings.py

Fix url-prefix not detected.

---

bokeh/models/tools.py
bokehjs/src/coffee/tool/gestures/box_select_tool.coffee
sphinx/source/docs/user_guide/interaction.rst
sphinx/source/docs/user_guide/styling.rst

ref issue: #2465 
Add callback on BoxSelectTool pan end event.

Add BoxSelectTool callback initial commit

---

.travis.yml

WO this, we have 3x increase in our packages, check the binstar (anaconda.org) to see the huge packages... merging immediately to build the RC packages...

Deactivate tests before building to avoid huge packages.

---

scripts/build_upload.sh

Just a tiny error preventing upload of the pypi package. Will merge right now because it is a blocker.

Use the correct extension.

---

bokeh/models/map_plots.py

@damianavila I don't have a strong opinion about merging this for 0.9.1, though I do think it is completely safe to do so.

elide some unnecessary checks for map plots

---

bokeh/mpl.py

issues: fixes #2365 
Verified with all current MPL/pandas/ggplot/searborn .py examples. Self contained in mpl.py.

create new data source per glyph for MPL compat

---

bokeh/embed.py
bokeh/models/tools.py
bokeh/properties.py
bokeh/validation/decorators.py
bokeh/validation/errors.py
bokeh/validation/exceptions.py
bokeh/validation/warnings.py
sphinx/source/docs/faq.rst
sphinx/source/docs/reference.rst
sphinx/source/docs/reference/validation.rst
sphinx/source/docs/user_guide/interaction.rst
sphinx/source/docs/user_guide/styling.rst

General PR for docs (only) changes during  0.9.1 freeze.

Open docs PR for 0.9.1 release

---

sphinx/source/docs/release_notes.rst
sphinx/source/docs/releases/0.9.1.rst

Merging immediately to start the release.

Add 0.9.1 release highlights.

---

bokehjs/src/coffee/renderer/glyph/patches.coffee

Fix vanishing patches bug.

---

scripts/build_upload.sh
scripts/deploy.sh

Fixes #2513 
The problem, as usual, is the first build... but these changes should fix the issues.

Several fixes to the release automation

---

bokeh/embed.py

Fix typo in components deprecation message

---

.travis.yml

Enable test on dev branches.

---

sphinx/source/docs/quickstart.rst

major change is IPython -> Jupyter, others are just minor edits.

editing up to concepts

---

setup.py

https://github.com/bokeh/bokeh/issues/2530

remove dependancy for un-needed pytz and  Websocket

---

examples/plotting/file/texas.py
examples/plotting/notebook/texas.ipynb

For issue #2496.
I am not sure how to handle the metadata information in the notebook.

Improve mouseover information in Texas example.

---

bokeh/sphinxext/bokeh_plot.py

add console warning when bokeh-plot fails

---

bokehjs/src/coffee/renderer/glyph/glyph_renderer.coffee

set visuals on decimated glyph

---

bokeh/models/tickers.py
bokehjs/src/coffee/common/base.coffee
bokehjs/src/coffee/ticking/fixed_ticker.coffee
sphinx/source/docs/user_guide/source_examples/styling_fixed_ticker.py
sphinx/source/docs/user_guide/styling.rst
tests/travis/test.yaml

Support for fixed tick locations

---

bokeh/plotting_helpers.py

handle values correctly in glyph functions 

---

bokeh/util/serialization.py

Related to issue https://github.com/bokeh/bokeh/issues/2582

Utilizing numpy arrays to speed up column data scrubbing

---

bokeh/tests/test_serialization.py
bokeh/util/serialization.py

Resolves issue mentioned in PR https://github.com/bokeh/bokeh/pull/2594

Serializing data with NumPy optional

---

sphinx/source/docs/dev_guide/building.rst

Small changes to clarify the development setup.

Small changes to development documentation

---

bokehjs/src/coffee/widget/dropdown.coffee

resolves issue https://github.com/bokeh/bokeh/issues/2631

"Sticky" last item bug in dropdown

---

bokehjs/src/coffee/renderer/glyph/bokehgl.coffee
examples/plotting/file/scatter10k.py
sphinx/source/docs/user_guide/webgl.rst

issues: #2590
Implements a workaround to deal with the fact that the indexbuffer is 16 bit.

Webgl: make selections work also for over 65k points

---

sphinx/source/conf.py
sphinx/source/docs/dev_guide/documentation.rst

resolves issue https://github.com/bokeh/bokeh/issues/2651

Removed sphinx-napoleon extension name from docs

---

sphinx/source/docs/includes/colors.txt

fix link format

---

examples/glyphs/linked_tap_server.py

issues: fixes #2508
Example now handles case when you hold down shift and select different indices

Allow for multiple indices to be tapped

---

bokehjs/src/coffee/renderer/glyph/quad.coffee

use spatial index for point hit testing

---

bokeh/models/formatters.py

Small documentation update after not fully understanding DatetimeTickFormatter (see #2450)

Add an example to DatetimeTickFormatter docs

---

sphinx/source/docs/user_guide/server.rst

Insert missing closing bracket.

Fix typo in example code of server deployment docu

---

.travis.yml
conda.recipe/build.sh
scripts/travis_install

Also remove pin for binstar...

Setting Node to current stable (0.12) on TravisCI

---

bokehjs/src/coffee/renderer/glyph/text.coffee

issues: fixes #2698 
Fix bug in draw legend method of text glyph.

Fix bug in draw legend method of text glyph

---

scripts/build_upload.sh

For completeness of some previous changes to use anaconda-client instead of binstar...

Change binstar to anaconda after some name changes in the anaconda stuff.

---

bokehjs/src/coffee/common/ui_events.coffee
bokehjs/test/test_common/test_ui_events.coffee

@birdsarah maybe `_trigger_event()` broken out would be more testable?

Broke out into functions for more testable code

---

setup.py

Cause setup.py clean to delete .pyc files.

---

bokehjs/src/coffee/tool/inspectors/hover_tool.coffee

Fix value escaping in hover tool

---

bokeh/util/notebook.py

'notebook previously loaded' warning only appears if verbose set to True

---

bokeh/models/widgets/panels.py
bokehjs/src/coffee/widget/tabs.coffee

includes PR https://github.com/bokeh/bokeh/pull/2648

Add Callback to Tabs Widget

---

bokeh/models/widgets/panels.py

Merge of #2649 and #2675 generated a conflict making our testing machinery to fail... let's see if this fix it...
ping @mistakevin and @birdsarah

Fix comflict (not merge conflict) because of those inter-related PRs.

---

scripts/build_upload.sh

Now the CloudFiles endpoints live at the top of the Service Catalog list... grrr... anyway, this should fix it...

Fix upload of JS and CSS into the CDN

---

bokeh/embed.py

It was breaking the notebooks with sintax errors in the JS console about.

Remove hash from elementid.

---

scripts/travis_install

Pin ipython and ipython notebook to 3.2.1.

---

bokeh/models/widgets/buttons.py
bokehjs/src/coffee/widget/dropdown.coffee
examples/glyphs/buttons_server.py

Resolves issue https://github.com/bokeh/bokeh/issues/2631#issuecomment-137748555

Changed 'action' to 'values' in dropdowns

---

.travis.yml
scripts/build_upload.sh

According to https://github.com/bokeh/bokeh/pull/2743#issuecomment-132731963

Remove 3.3 from testing and building.

---

.travis.yml

With the new devel build names, we need to catch the proper names in the branches.
I will merge this immediately to trigger a new devel build.

Fix regex again.

---

bokeh/charts/builder/donut_builder.py

fix sources that resulted with different column lenght in some cases

---

scripts/travis_install

Workaround to local installation

---

scripts/build_upload.sh

Fix how you get the id from Rackspace selectively looking for the cloudFiles info.

Be more selective when you look for the ID

---

sphinx/source/docs/contributing.rst

Add scientific notation to contributing.rst

---

conda.recipe/meta.yaml
setup.cfg

pytest-selenium is now on pypi: https://pypi.python.org/pypi/pytest-selenium/1.0b1
ping @damianavila

pytest-selenium 1.0b1 does not use the --destructive argument

---

bokeh/charts/_builder.py
bokeh/charts/utils.py
bokeh/mixins.py
bokeh/models/plots.py
bokehjs/src/coffee/common/plot.coffee
bokehjs/src/coffee/renderer/annotation/legend.coffee
bokehjs/src/coffee/renderer/guide/axis.coffee
bokehjs/src/coffee/renderer/guide/grid.coffee
bokehjs/src/less/main.less

This isn't intended to become the default, we'd want to
figure out a theme system that can affect these same
properties.

Hardcode some dark colors for theme idea "1b"

---

examples/interactions/interactive_bubble/gapminder.ipynb
examples/interactions/interactive_bubble/gapminder.py

~~passing in the slider as an argument stopped working apparently, using `cb_obj` works fine.~~
Also updated notebook since Callback change (which I missed before) and remove unecessary trigger calls.
EDIT - Was my mistake, no longer in this PR.

Fix gapminder notebook & clean-up unecessary triggers

---

bokeh/sampledata/__init__.py
bokeh/sampledata/world_cities.py
examples/glyphs/maps.py
examples/glyphs/maps_cities.py
examples/glyphs/trail.py

The maps_cities example demoing cities over a google map was showing all the
cities offset from the map tile. The problem appears to have been in the
us_cities dataset. This commit adds a new world_cities dataset and updates
the example to use it.

Update example - cities gmap

---

sphinx/source/conf.py
sphinx/source/index.rst

Minor sidebar fixes

---

.travis.yml

try specify nvm explicitly

---

bokeh/models/renderers.py
bokeh/models/tests/test_renderers.py
bokeh/validation/warnings.py

category checks should only check range labels, not values

---

bokehjs/src/coffee/renderer/annotation/legend.coffee

Check for "None" border color

---

examples/embed/.gitignore
examples/interactions/.gitignore

Small thing - it was annoying me that git was picking up generated html files under embed and interactions.

Add .gitignore files to examples directories that didn't have it.

---

.travis.yml
conda.recipe/build.sh
conda.recipe/meta.yaml
scripts/dev_environment
scripts/devdeps.py
scripts/travis_install
setup.py

Replace nvm for a conda package.

---

bokehjs/src/coffee/common/properties.coffee

Fixed lineJoin buglet.

---

bokehjs/gulp/paths.coffee
bokehjs/gulp/tasks/scripts.coffee
bokehjs/gulp/tasks/watch.coffee

issues: fixes #2928 
Corrects path to watchSources in watch.coffee

Fix path to watchSources in watch.coffee

---

.travis.yml
conda.recipe/build.sh
scripts/travis_install

Trying some things where I research how speed up our testing machinery...

Exploration on splitting our tests

---

bokeh/compat/bokeh_renderer.py

I tried to make fix as less intrusive as possible. If I had to pass the complete props dictionary to make_axis the code needed restructuring. As **bryevdv** mentioned in #2973 the code is a bit hackish anyways. 
Please review the change

to_mpl fix for DateTimeAxis

---

bokeh/compat/mplexporter/renderers/base.py

Fix for the issue in https://github.com/bokeh/bokeh/issues/2643

Fix for issue #2643

---

bokehjs/src/coffee/common/tool_manager.coffee
bokehjs/src/coffee/common/ui_events.coffee
bokehjs/src/coffee/tool/gestures/gesture_tool.coffee
bokehjs/test/test_common/test_ui_events.coffee
bokehjs/test/test_tool/index.coffee
bokehjs/test/test_tool/test_gestures_tap_tool.coffee
tests/integration/interaction/test_pan_tool.py
tests/integration/interaction/test_wheel_zoom.py

Fixes: #1450 
This fixes the second part of #1450 - the wheel tool is off by default, and can be toggled on and off by user.

1450 wheel zoom off by default

---

bokeh/charts/builder.py
bokeh/properties.py
bokeh/tests/test_properties.py

Make .clone private.

---

bokeh/application/spellings/script.py
examples/plotting/server/glyphs.py

Fixes #3066 
Started out as a typo fix and small clean-up but ended up fixing #3066 - not sure why. Maybe new server doesn't like things being manually added to vplot().
* fixes a title typo
* adds plots to a list and then uses that to construct vplot
* imports vplot, output_server, show from bokeh.io

Clean-up glyphs.py

---

bokehjs/src/coffee/common/base.coffee
bokehjs/src/coffee/mapper/log_mapper.coffee
bokehjs/test/test_mapper/index.coffee
bokehjs/test/test_mapper/test_log_mapper.coffee

issues: fixes #3022 
Still needs tests and documentation support.

simplify log mapper and fix logic error in nan/inf handling

---

.travis.yml
sphinx/source/docs/dev_guide/testing.rst

Enable examples by default, but keep the possibility to disable by commit.

---

bokehjs/test/test_common/test_client.coffee

This should reduce flakiness on Travis.

Lengthen timeout on test_client.coffee to 7500 from 2000 millis

---

bokeh/command/__init__.py
bokeh/server/server.py

Add Server.show() and `bokeh serve --show`

---

bokeh/models/tiles.py
bokehjs/src/coffee/renderer/tile/mercator_tile_source.coffee
bokehjs/src/coffee/renderer/tile/tile_renderer.coffee
bokehjs/src/coffee/renderer/tile/tile_source.coffee

More work to sync coffee and python for TileRenderer / TileSource

---

bokehjs/src/coffee/common/has_parent.coffee

HasParent: share one instance of display_defaults per class, not per instance

---

bokehjs/src/coffee/common/embed.coffee

Always pass websocket_url as a parameter, don't set a global

---

bokeh/server/tornado.py

This was breaking if you ran two apps in one server since all of
them would go to the same websocket.

Set correct websocket_path on each app pattern in the server

---

sphinx/source/docs/gallery.rst

change "static" to "locally executing" for interactive but non server plots
Closes #3196

change "static" to "locally executing"

---

bokeh/properties.py

Rename PropertyGenerator to PropertyFactory

---

.travis.yml
conda.recipe/meta.yaml
scripts/travis_install
tests/travis/nbexecuter.py
tests/travis/test
tests/travis/test.js
tests/travis/test.yaml
tests/travis/test_examples.py

Eventually this one should close: #2978 and #3100.
Also, it seems a pre-requisite for #3122 
Let see first what is broken...

Remove ipython pin and update to jupyter

---

tests/travis/test

try forcing inline resources for notebooks

---

examples/interactions/interactive_bubble/gapminder_styles.css
examples/interactions/interactive_bubble/gapminder_template.jinja

Just makes it look a bit nicer

Add bokeh logo and a link to the gapminder demo

---

bokeh/server/views/autoload_js_handler.py

Figured I'd make a pull request for this issue.
https://github.com/bokeh/bokeh/issues/3172

Corrected the js_urls bug #3172

---

bokehjs/src/coffee/common/properties.coffee
bokehjs/src/coffee/renderer/glyph/glyph.coffee
bokehjs/test/test_common/test_properties.coffee
bokehjs/test/test_renderer/index.coffee
bokehjs/test/test_renderer/test_glyphs.coffee

Some fixes to how the JS side handles distance/angle _units

Coffee units handling

---

bokeh/models/sources.py

I think it's not necessary any more, but lets see if tests pass.

Remove ColumnsRef

---

bokeh/command/subcommands/serve.py
bokeh/command/subcommands/tests/test_serve.py
bokeh/server/connection.py
bokeh/server/server.py
bokeh/server/tornado.py
bokeh/server/views/ws.py

Add keep-alive ping

---

bokeh/document.py
bokeh/models/sources.py
bokeh/server/session.py
examples/plotting/server/fourier_animated.py

Correct Bokeh periodic callback to take period in milliseconds

---

bokeh/models/callbacks.py

Remove unnecessary paren in error message.

---

bokeh/document.py
bokeh/tests/test_document.py

issues: fixes #3253 
ping @havocp @mattpap

preserve root insertion order in documents

---

bokeh/server/connection.py
bokeh/server/views/ws.py
bokeh/tests/test_client_server.py

Fix ping data encoding for Python 3, add test_ping unit test

---

bokeh/client/session.py
bokeh/document.py
bokeh/server/session.py
bokeh/server/views/ws.py
bokeh/tests/test_client_server.py

Session callback fixes

---

bokeh/resources.py

load BokehJS resources from https

---

scripts/interactive_tester.py

about ipython-notebook dependency.

Add charts/plotting and charts/file to testing locations, warning

---

bokeh/command/subcommands/serve.py
bokeh/command/subcommands/tests/test_serve.py
bokeh/resources.py
bokeh/server/server.py
bokeh/server/tornado.py
bokeh/server/urls.py
bokeh/tests/test_client_server.py

Will add tests in the morning, but review appreciated anytime. @bokeh/dev

support --prefix for server

---

examples/app/clustering/README.md
examples/app/clustering/main.py
examples/app/clustering/theme.yaml

Not for this PR, but some "nice to haves" that could improve this app if there is time:
* spinner when computing/busy
* deactivate widgets when computing/busy
* auto layout (ping @havocp)
* visual style tweaks (ping @SaraSchnadt )

add chdoig's scikit-learn clustering demo

---

bokeh/_templates/autoload_js.js
bokeh/_templates/autoload_tag.html
bokeh/embed.py
bokeh/io.py
bokeh/properties.py
bokeh/resources.py
bokeh/server/views/autoload_js_handler.py
bokeh/server/views/doc_handler.py
bokeh/server/views/session_handler.py
bokeh/state.py
bokeh/tests/test_embed.py
bokeh/tests/test_io.py

Allow server to create session id with autoload_server

---

examples/interactions/Hover callback.ipynb
examples/interactions/Linked panning.ipynb
examples/interactions/Range update callback.ipynb
examples/interactions/us_marriages_divorces/us_marriages_divorces_interactive.ipynb
examples/interactions/us_marriages_divorces/us_marriages_divorces_interactive.py

All the examples under `examples/interactions` work and are cleaned up/made consistent
Diff has extra junk util #3330 is merged

Cleanup interactions examples

---

sphinx/source/bokeh_theme/includes/ga.html
sphinx/source/bokeh_theme/includes/searchbox.html

Add in remaining html templates

---

.travis.yml
conda.recipe/build.sh
scripts/travis_install

Let's see how we perform without caching...

Remove caching mechanism

---

bokeh/core/enums.py
bokeh/models/annotations.py
bokeh/models/tools.py
bokeh/tests/test_objects.py
bokehjs/src/coffee/renderer/annotation/span.coffee
bokehjs/src/coffee/renderer/annotation/tooltip.coffee
bokehjs/src/coffee/renderer/overlay/box_selection.coffee
bokehjs/src/coffee/renderer/overlay/poly_selection.coffee
bokehjs/src/coffee/ticking/datetime_ticker.coffee
bokehjs/src/coffee/tool/inspectors/crosshair_tool.coffee
bokehjs/src/coffee/tool/inspectors/hover_tool.coffee
bokehjs/src/coffee/tool/inspectors/inspect_tool.coffee
bokehjs/src/coffee/widget/selectbox.coffee
examples/app/stocks/main.py
examples/glyphs/maps.py

Reverts bokeh/bokeh#3401
Investigating a problem with timeout callbacks that seems to originate in referenced PR

Revert "Server annotations"

---

conda.recipe/meta.yaml
setup.py

force tornado version in requirements

---

bokeh/plotting/helpers.py
examples/app/ohlc/main.py
examples/app/ohlc/theme.yaml

To run, execute: 
```
bokeh serve --show ohlc
```
In the `examples/app` directory.
Note: "ready" here indicates ready enough to go into a `dev6` release.

Add streaming OHLC and MACD indicator example

---

bokehjs/src/coffee/common/plot.coffee

use the right attributes for canvas width/height

---

bokehjs/src/coffee/widget/slider.coffee

fix plumbing for slider updates

---

bokeh/command/subcommands/serve.py
bokeh/command/subcommands/tests/test_serve.py

Make host arg play nicer.

---

bokehjs/src/coffee/renderer/glyph/glyph.coffee
bokehjs/src/coffee/renderer/glyph/line.coffee
examples/plotting/file/line_select.py

ping @mattpap @havocp 
This works. Is not great, but it works.

possible solution to store model instead of view on 0d selections

---

bokeh/charts/glyphs.py
bokeh/charts/tests/test_comp_glyphs.py

replace min and max function so they ignore nan values

---

examples/plotting/file/dynamic_map.py

https://github.com/bokeh/bokeh/issues/3466

Dynamic Map Example: Fixed issue with dynamic image becoming unhinged from basemap

---

bokeh/charts/builder.py
bokeh/charts/builders/bar_builder.py
bokeh/charts/glyphs.py

Hotfix for boxplot whisker, marker styles ignored 

---

bokehjs/src/coffee/common/grid_plot.coffee

issues: fixes #3469 
Missed some fixes and changes applied to ToolManager. This fixes two small issues 1) the inability to swtich wheel zoom back on mentioned in #3469 and also 2) wheel zoom should be off by default.

Bring GridToolManager up to date

---

scripts/build_upload.sh

issues: closes #3491
ping @mattpap @damianavila is there a way to test this before tagging an RC1?

upload compiler js files

---

bokeh/resources.py

Update resources.py to not leak paths

---

bokeh/server/views/ws.py
sphinx/source/docs/dev_guide/bindings.rst
sphinx/source/docs/dev_guide/bokehjs.rst
sphinx/source/docs/dev_guide/documentation.rst
sphinx/source/docs/dev_guide/setup.rst
sphinx/source/docs/reference/core.rst
sphinx/source/docs/releases/0.7.0.rst
sphinx/source/docs/releases/0.7.1.rst
sphinx/source/docs/releases/0.8.1.rst
sphinx/source/docs/releases/0.8.2.rst
sphinx/source/docs/releases/0.9.0.rst
sphinx/source/docs/server_gallery/stocks_server.rst
sphinx/source/docs/user_guide/charts.rst
sphinx/source/docs/user_guide/cli.rst
sphinx/source/docs/user_guide/embed.rst
sphinx/source/docs/user_guide/geo.rst
sphinx/source/docs/user_guide/interaction.rst
sphinx/source/docs/user_guide/plotting.rst
sphinx/source/docs/user_guide/quickstart.rst
sphinx/source/docs/user_guide/styling.rst
sphinx/source/docs/user_guide/tools.rst

Fix spelling and other issues in docs

---

bokeh/sphinxext/collapsible_code_block.py
sphinx/source/bokeh_theme/layout.html
sphinx/source/bokeh_theme/search.html
sphinx/source/bokeh_theme/static/js/main.js
sphinx/source/conf.py

Starts working on #3404 
Includes:
- search fix
- collapsible code fix
- make logo direct to bokehplots.com

Start cleaning up docs

---

examples/charts/notebook/excel.ipynb
examples/charts/server/interactive_excel.py

Add examples with excel files

---

bokeh/charts/builders/area_builder.py
bokeh/charts/builders/bar_builder.py
bokeh/charts/builders/boxplot_builder.py
bokeh/charts/builders/donut_builder.py
bokeh/charts/builders/dot_builder.py
bokeh/charts/builders/heatmap_builder.py
bokeh/charts/builders/histogram_builder.py
bokeh/charts/builders/horizon_builder.py
bokeh/charts/builders/line_builder.py
bokeh/charts/builders/scatter_builder.py
bokeh/charts/builders/step_builder.py
bokeh/charts/builders/timeseries_builder.py
sphinx/source/docs/reference/charts.rst

This is to remove any remaining legacy charts language and to include the more recently implemented charts in the sphinx documentation.

Update charts docstrings and sphinx documentation

---

bokeh/core/_templates/doc_js.js
bokeh/embed.py
bokeh/server/views/autoload_js_handler.py

Revert "HOTFIX: don't exec bokeh embed until dom ready"

---

examples/interactions/Range update callback.ipynb
examples/interactions/ajax_source.py

Fixing two more examples... I hope the last ones :wink:

Fix more examples

---

bokeh/core/_templates/notebook_div.html

Use correct order of div and script in notebook_div template

---

sphinx/source/docs/user_guide/geo.rst

Specify x and y so plot renders

Fix geojson user guide plot

---

examples/charts/server/interactive_excel.py

changing the plots on the right box

Fix interactive excel example

---

bokeh/embed.py
sphinx/source/bokeh_theme/layout.html
sphinx/source/conf.py
sphinx/source/docs/releases/0.11.0.rst

- Update header and footer links in docs site
- Add migration note about js_resources, css_resources
- Update file_html docstring

docs updates

---

.travis.yml
bokehjs/package.json

issues: fixes #3636
Pin phantomjs@1.9.7-15

Pin phantomjs@1.9.7-15

---

bokeh/sphinxext/bokeh_sitemap.py
sphinx/README.txt
sphinx/source/conf.py
sphinx/source/docs/reference/sphinxext.rst

Useful for google search index

Add a sitemap builder

---

bokeh/io.py
examples/howto/notebook_comms/Basic Usage.ipynb

issues: fixes #3680 
Need to keep track of last JSON pushed *per document*, otherwise end up constructing messages with "root added" events, etc.

Notebook comms fix

---

examples/app/movies/main.py

join path to filename when opening

---

bokehjs/src/coffee/renderer/tile/dynamic_image_renderer.coffee
bokehjs/src/coffee/renderer/tile/tile_renderer.coffee

Both the the above renderers were missing `bind_bokeh_events` methods which I've added in so that updates using bokeh server work as expected.

Add `bind_bokeh_event` methods to `TileRenderer` and `DynamicImageRenderer`

---

bokeh/command/subcommands/serve.py
sphinx/source/docs/dev_guide/notes.rst
sphinx/source/docs/user_guide/server.rst

These create confusion and misunderstanding a  poor user experience.
Things that we'd like to document should be noted in an issue. The items removed in this PR are stored on #3688

Remove not filled out portions of docs

---

sphinx/source/docs/releases/0.11.1.rst
sphinx/source/docs/user_guide/compat.rst
sphinx/source/docs/user_guide/embed.rst
sphinx/source/docs/user_guide/server.rst
sphinx/source/index.rst

Fixes #3695 
Continues work from #3688

Docs cruft and #3695

---

sphinx/README.txt
sphinx/source/conf.py

Auto-update releases link in docs nav

---

bokehjs/src/coffee/renderer/annotation/annotation.coffee
bokehjs/src/coffee/renderer/glyph/glyph_renderer.coffee
bokehjs/src/coffee/renderer/guide/guide_renderer.coffee
bokehjs/src/coffee/renderer/renderer.coffee
bokehjs/src/coffee/renderer/tile/dynamic_image_renderer.coffee
bokehjs/src/coffee/renderer/tile/tile_renderer.coffee

ref issue #3651 
Simply add Renderer base class to *_renderer models to mirror python API

Add Renderer base class to *_renderer models

---

bokeh/core/json_encoder.py
bokeh/document.py
bokeh/model.py
bokehjs/gulp/tasks/generate_defaults.py

Just to note, the first commits handles the regression part of this PR and the other adds uniform behavior across source base.

Restore pretty JSON formatting and make sort_keys=True the default

---

bokeh/plotting/helpers.py

Change data_source to source which is the attribute expected for glyph construction

Fix #3698 attribute name in doctemplate / helpers.py

---

bokehjs/src/coffee/renderer/glyph/rect.coffee

saw this debugger statement and removed...

removed rogue debugger statement

---

bokehjs/src/coffee/renderer/glyph/oval.coffee

correctly render oval legends

---

sphinx/source/docs/reference/models.rst
sphinx/source/docs/reference/models/layouts.rst
sphinx/source/docs/reference/models/widgets.layouts.rst

issues: fixes #3742 
Simple docfix

Updated autodoc for models.layouts (refactored from models.widgets.layouts)

---

.gitignore
bokehjs/gulp/tasks/generate_defaults.py
bokehjs/gulp/tasks/scripts.coffee
bokehjs/test/test_common/test_defaults.coffee

issues: fixes #3749 
Move generated coffee models and widgets defaults:
/src/coffee/common/defaults.coffee -> /test/test_common/defaults/models_defaults.coffee
/src/coffee/models/widgets/defaults.coffee -> /test/test_common/defaults/widgets_defaults.coffee

Move generated coffee defaults file location to test directory

---

bokehjs/gulp/labeler.coffee
bokehjs/gulp/tasks/defaults.coffee
bokehjs/gulp/tasks/scripts.coffee
bokehjs/gulp/tasks/test.coffee

Also move some code around to make `tasks/scripts.coffee` more readable.

Generate defaults for test task, not scripts:coffee

---

bokeh/model.py

remove Chart from preload

---

bokeh/models/plots.py

fix deprecation messages

---

bokehjs/src/coffee/models/widgets/multiselecttemplate.eco
sphinx/source/docs/user_guide/interaction.rst

use multiselect template correctly

---

bokeh/sampledata/elements.csv

First row in elements.csv was one column short: the data has an 'id' column, but the header row is missing the 'id' key.
Adding a comma at the beginning of the whole file does the trick

Update elements.csv 

---

.travis.yml

Merging immediately to trigger a dev build...

Add new creds for Rackspace

---

bokeh/core/compat/mpl.py

Functino docstring were not synced with the current funcitno arguments.

Sync mpl.to_bokeh docstrings with current available parameters.

---

bokehjs/src/coffee/models/plots/plot.coffee

Apply patch from 3769 issue

---

bokeh/models/plots.py

Fix typo in docstring

---

bokeh/core/state.py

Fix docstring

---

bokehjs/gulp/tasks/test.coffee
bokehjs/src/coffee/base.coffee
bokehjs/src/coffee/core/util/bbox.coffee
bokehjs/src/coffee/core/util/math.coffee
bokehjs/src/coffee/core/util/text.coffee
bokehjs/src/coffee/core/util/throttle.coffee
bokehjs/src/coffee/core/util/underscore.coffee
bokehjs/src/coffee/models/annotations/legend.coffee
bokehjs/src/coffee/models/glyphs/annular_wedge.coffee
bokehjs/src/coffee/models/glyphs/glyph.coffee
bokehjs/src/coffee/models/glyphs/wedge.coffee
bokehjs/src/coffee/models/plots/plot.coffee
bokehjs/src/coffee/models/ranges/data_range1d.coffee
bokehjs/src/coffee/models/renderers/renderer.coffee
bokehjs/test/all.coffee
bokehjs/test/core/util/bbox.coffee
bokehjs/test/core/util/index.coffee
bokehjs/test/index.coffee

this was the start of my canvas layout PR but I think it makes more sense as a smaller PR of its own. It:
* adds test selection, e.g. `gulp test:core`
* moves more things into `core/utils` that make sense there

more bokehjs cleanup

---

bokeh/charts/builders/histogram_builder.py
bokeh/charts/stats.py
bokeh/charts/tests/test_stats.py

fix hist bin autosize with unique values

---

bokeh/charts/builder.py
bokeh/charts/builders/donut_builder.py

update call to pandas sort to new API

---

bokehjs/src/coffee/models/glyphs/bokehgl.coffee
bokehjs/src/coffee/models/glyphs/glyph.coffee
bokehjs/src/coffee/models/glyphs/line.coffee
examples/plotting/file/line_compare.py

issues:
* fixes #3795
* fixes #3800 
* fixes part of #3635 
* might have fixed #3464

A series of WebGL fixes (regression, precision, data update, miter limit)

---

sphinx/source/docs/user_guide.rst

Creating -> Create

---

bokeh/models/callbacks.py
bokeh/models/tests/test_callbacks.py
conda.recipe/meta.yaml
examples/plotting/file/python_callback.py
sphinx/source/docs/user_guide/interaction.rst
sphinx/source/docs/user_guide/source_examples/interaction_callbacks_in_python.py
tests/travis/test.yaml

issues: closes #3675, continues #3121
Wait with merging this until we've got a new Flexx release and corresponding conda package.

PyScript now also works on py27

---

sphinx/source/docs/dev_guide/documentation.rst

remove second instance of seaborn in list of required packages.

remove duplicate of seaborn from req'd pkgs [ci disable examples]

---

bokeh/core/_templates/plot_div.html
bokeh/tests/test_embed.py
bokehjs/src/less/bokeh-widgets.less
bokehjs/src/less/bokeh.less

Revert "Changed .bk-plot to .bk-root for style wrapper"

---

.travis.yml

Fixes: #3927
External contributors can't use saucelabs, so fallback to firefox on travis instead of using Saucelabs

Handle external contributors accessing saucelabs

---

.travis.yml

Try and make it easy to find the report location on a travis log

Demo more prominant report location

---

setup.py

Add checking for __conda_version__.py

---

sphinx/source/docs/user_guide/concepts.rst

- add 'screen units' and 'data-space units' to glossary
- 'to server' -> 'to serve'
- small rewrite about high level and low level interfaces

concepts file changes [ci disable examples]

---

sphinx/source/docs/user_guide/compat.rst

issues: fixes #3951
Trivial update for https://github.com/bokeh/bokeh/pull/3953 to fix broken image.

Fixed path to image

---

examples/app/weather/README.md

Fix filename in `weather` example README

---

bokehjs/src/coffee/common/tool_manager.coffee
bokehjs/src/coffee/models/layouts/grid_plot.coffee
bokehjs/src/coffee/models/plots/plot.coffee
bokehjs/src/less/continuum.less

issues: fixes #4012 
This fixes the visible table borders in notebooks and also problems occurring with toolbar lines.

fix notebook and toolbar css handling

---

bokeh/application/handlers/code.py
bokeh/application/handlers/code_runner.py
bokeh/application/handlers/directory.py
bokeh/application/handlers/notebook.py
bokeh/application/handlers/script.py
bokeh/application/handlers/server_lifecycle.py
bokeh/application/handlers/tests/test_code.py
bokeh/command/subcommands/file_output.py
bokeh/command/subcommands/serve.py
bokeh/command/subcommands/tests/test_html.py
bokeh/command/subcommands/tests/test_json.py
bokeh/command/subcommands/tests/test_serve.py
bokeh/command/util.py

support --args to pass command line args to bokeh apps

---

bokeh/io.py
bokeh/util/notebook.py

Fix output_notebook(resources) default docstring

---

bokeh/sphinxext/bokeh_plot.py

Add the new bk-root wrapper

---

.travis.yml

Try no capture for examples tests

---

bokehjs/examples/stocks/.gitignore
bokehjs/examples/stocks/stocks.html
bokehjs/examples/stocks/stocks.ts
bokehjs/examples/stocks/tsconfig.json
bokehjs/gulp/tasks/examples.coffee

Adds a stock example making use of the new ts api. Based against #4037

Add stock example using ts api

---

bokeh/command/subcommands/serve.py
bokeh/server/tests/test_tornado.py
bokeh/server/tornado.py

Support * in `--host` keyword 
Fixes #4051

Star whitelist

---

.travis.yml

For the record:
1. `conda create -n ruby -c bioconda ruby`
2. `gem install travis`
3. `anaconda auth --create -n travisci_anaconda -o bokeh -s 'api:read api:write'`
4. `travis encrypt ANACONDA_TOKEN=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`
5. Add secret to `.travis.yml`
Will merge immediately and test the devel build again... we have to be sure the scopes in the `anaconda auth` are the correct ones.

Update Anaconda token

---

scripts/build_upload.sh

Point to the correct location when you look for the noarch package

---

sphinx/source/bokeh_theme/layout.html

add canonical link to sphinx template

---

bokeh/models/widgets/buttons.py
bokeh/models/widgets/groups.py

Add deprecation for {AbstractButton,ButtonGroup}.{->button_}type

---

bokeh/command/subcommands/serve.py
bokeh/server/tornado.py

change unused-session-lifetime to 15 seconds:

---

bokeh/core/_templates/notebook_load.html
bokeh/resources.py
bokeh/util/notebook.py

Remove unused logo_url

---

sphinx/source/docs/user_guide/source_examples/styling_tool_overlays.py
sphinx/source/docs/user_guide/styling.rst
sphinx/source/docs/user_guide/tools.rst

Update tool overlays section

---

bokehjs/package.json
bokehjs/src/coffee/api/typings/bokeh.d.ts
bokehjs/src/coffee/api/typings/views.d.ts
bokehjs/typings.json

Change type of Bokeh.index to Map<View<Component>>

---

.travis.yml

Hotfix - Fix path to phantomjs executable

---

bokehjs/src/coffee/api/typings/models/plots.d.ts
bokehjs/src/coffee/models/plots/plot.coffee
examples/embed/embed_responsive_width_height.py
tests/integration/integration_tests_plugin.py
tests/integration/interaction/test_responsive.py

Fix resizing of embedded plots

---

examples/app/simple_hdf5/README.md
examples/app/simple_hdf5/Run.bat
examples/app/simple_hdf5/create_hdf5.py
examples/app/simple_hdf5/main.py

Added simple hdf5 example app.

---

bokehjs/examples/legends/legends.ts
bokehjs/src/coffee/api/plotting.coffee

We have to test bokehjs' examples on travis ci, otherwise we will get more PRs like this.
fixes #4155

Fix bokehjs plotting API after making HasProps.set() strict

---

bokehjs/src/coffee/models/annotations/span.coffee

properly redraw span annotations on updates in canvas render mode

---

bokehjs/src/coffee/models/annotations/legend.coffee
bokehjs/src/coffee/models/layouts/grid_plot.coffee

Use model.document.solver() instead of plot.solver

---

bokeh/models/tools.py
bokehjs/src/coffee/models/tools/gestures/box_zoom_tool.coffee
examples/models/tile_source.py

issues: #4065
@bokeh/dev please review 
There are a few slightly rough edges. In particular, there seems to be an off by pixel error somewhere, if the aspect controlled box hits up against plot range ends (left or bottom).
But, I think this is important and useful enough as-is to merge and make issues to fix any small things later.

add option to have box zoom respect plot frame aspect

---

bokehjs/src/coffee/embed.coffee

protect notebook comms init against unexpected exceptions

---

bokeh/command/subcommands/serve.py

Add process id logging on bokeh serve startup

---

bokeh/core/properties.py
bokeh/core/property_containers.py
bokeh/model.py
bokeh/tests/test_document.py
examples/app/ohlc/main.py

issues: closes #4077
@mrocklin can you compare/benchmark and see if this PR offers improvement?
@havocp the only thing I was slightly wary of was using a `hint` to short circuit the `unchanged` computation. It seems ok, but if you have any thoughts, please share.

update in streaming lists in place

---

bokeh/core/property_containers.py
bokeh/document.py
bokeh/server/session.py
bokeh/tests/test_document.py
sphinx/source/docs/user_guide/server.rst

add a decorator to allow callbacks to execute without a lock

---

sphinx/make.bat

Add serve subcommand to make.bat in Sphinx docs

---

sphinx/source/docs/user_guide/interaction.rst
sphinx/source/docs/user_guide/source_examples/interaction_div.py

issues: fixes #4122 
Though a lot of the text could use some work.

Add 'div' widget to interaction.rst, create example

---

setup.py

fixes  #4119, fixes #4178
* Try to import setuptools, ignore if not available. If installing with pip (in which case setuptools is available) this will make the entry_points being picked up, and thus the .exe being created on Windows.
* Change how the `packages` is constructed (automatic instead of manually).
* Fix `site_packages` detection on Windows
* Able to cleanup existing bokeh installs that were installed via setuptools, (e.g. `bokeh-0.11.1 blabla`)

Use setuptools if available in setup.py

---

bokehjs/src/coffee/api/plotting.coffee
bokehjs/src/coffee/api/typings/plotting.d.ts

Expose {x,y}axis in TS plotting API

---

.travis.yml
tests/examples/examples.yaml

issues: closes #4194
This has caused me a lot of problems in the past and is causing problems again.

Skip pandas_dataframe test

---

bokeh/charts/__init__.py
bokeh/charts/builders/chord_builder.py
bokeh/charts/glyphs.py
bokeh/charts/utils.py
examples/charts/file/chord_from_df.py
sphinx/source/docs/reference/charts.rst

issues: closes #844
Hello Bokeh team :grin:, finally found some time to do this!
I want to create a PR to add Chord Graphs interface to Bokeh. (issue #844)
I have already shown that creating chord graphs with Bokeh is [possible](https://www.continuum.io/blog/developer-blog/redrawing-brain-bokeh), now I want to make it available to everyone with an easy to use interface. My hope is also that making this PR I can get some help from some of the __Bokeh gurus__ to resolve some of the features I've tried to do but I got lost.
- Add hoverTool to arcs
- Add tapTool to arcs
- WebGL rendering for arcs
- WebGL rendering for beziers
I'll be working on this actively and I take the compromise of maintining it but any help is **very** welcomed :grimacing:, not a super expert, yet !
Thanks !!

Add Interface for Chord Graphs

---

bokeh/models/tools.py
bokehjs/src/coffee/api/typings/models/tools.d.ts
bokehjs/src/coffee/models/tools/actions/reset_tool.coffee

issues: closes #4201 
@mattpap This is done except for whatever changes are needed to update the TypeScript API. Please make those ASAP
ping @dwillmer

make reset tool behaviour configurable

---

bokeh/models/plots.py
bokeh/models/tests/test_plots.py
bokeh/tests/test_objects.py

Fix #4224: make extra_x_ranges accept CategoricalAxis / FactorRange

---

bokehjs/.npmignore
bokehjs/package.json

Steps to publish are documented in #4210

Adding built assets to npm

---

bokeh/document.py
sphinx/fabfile.py
sphinx/source/bokeh_theme/layout.html
sphinx/source/bokeh_theme/static/js/main.js
sphinx/source/conf.py
sphinx/source/docs/reference/bokehjs.rst
sphinx/source/docs/user_guide/embed.rst
sphinx/source/docs/user_guide/plotting.rst

Add a prominent banner to previous and development docs

---

sphinx/source/docs/dev_guide/testing.rst

Small docs addition
Fixes: #4253

Add note to testing docs about installing bokeh

---

sphinx/source/docs/user_guide/server.rst

add sample apache config

---

sphinx/source/docs/dev_guide.rst
sphinx/source/docs/dev_guide/bokehjs.rst
sphinx/source/docs/dev_guide/documentation.rst
sphinx/source/docs/dev_guide/env_vars.rst
sphinx/source/docs/dev_guide/models.rst
sphinx/source/docs/dev_guide/server.rst
sphinx/source/docs/dev_guide/setup.rst
sphinx/source/index.rst

In this PR:
* make it clear the dev guide has content
* fix some broken references
* rename section "objects" -> "models" for consistency
* delete hopelessly out of date BokehJS info

minor dev guide tweaks

---

bokehjs/src/coffee/models/grids/grid.coffee

issues: fixes #3434
Additionally simplifies grid implementation by converting computed properties to method calls. 
@birdsarah @canavandl I'd be interested in adding a test based on the code in the linked issue to prevent regressions, but I might need some help.

fix "missing last grid band" problem

---

bokehjs/src/less/continuum.less
bokehjs/src/less/flexbox.less

Remove problem styles for SASS/Autoprefixer support

---

bokehjs/src/coffee/models/glyphs/bokehgl.coffee
examples/plotting/file/webgl_tests.md

* Fixes #4265 
* Partly address #4240
* Partly address #4279
* Leaving as WIP to include a fix for #4248 if necessary

Make webgl work again

---

sphinx/source/docs/dev_guide/models.rst

extremely minor grammar correction, didn't feel it was appropriate to create an issue for this.

it at all -> if at all

---

bokeh/charts/attributes.py
bokeh/charts/builders/histogram_builder.py
bokeh/charts/glyphs.py
bokeh/charts/stats.py
bokeh/charts/tests/test_stats.py
examples/charts/file/heatmap.py
examples/charts/file/histogram_multi.py
examples/howto/charts/heatmap.ipynb

issues: fixes #3576
Also includes support for list of scalars as bins, to allow customized non uniform bins

add new Histogram stat to expose np.histogram

---

bokeh/charts/builders/step_builder.py
bokeh/charts/glyphs.py
bokeh/charts/tests/test_comp_glyphs.py

Fix step plot fail on Windows with datetime data

---

bokehjs/src/coffee/models/canvas/canvas.coffee
bokehjs/src/coffee/models/glyphs/glyph.coffee
bokehjs/src/coffee/models/glyphs/webgl/base.coffee
bokehjs/src/coffee/models/glyphs/webgl/line.coffee
bokehjs/src/coffee/models/glyphs/webgl/markers.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee

Reverts bokeh/bokeh#4348
Having problems merging with layout - need to talk to @almarklein

Revert "Make hidpi work for webgl"

---

bokehjs/src/coffee/models/canvas/canvas.coffee
bokehjs/src/coffee/models/glyphs/glyph.coffee
bokehjs/src/coffee/models/glyphs/webgl/base.coffee
bokehjs/src/coffee/models/glyphs/webgl/line.coffee
bokehjs/src/coffee/models/glyphs/webgl/markers.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee

Merges the hipdi work into the layout PR

---

bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee

issues: fixes #4356 
Needed update glyph.x -> glyph._x after properties PR

Use correct "property names"

---

bokehjs/src/coffee/models/glyphs/image_url.coffee

Addressing changes needed to fix [issue 4355: problem enabling zoom on Image_url object](https://github.com/bokeh/bokeh/issues/4355#)

addressing issue 4355

---

bokeh/command/subcommands/serve.py
bokeh/command/subcommands/tests/test_serve.py
bokeh/server/server.py
bokeh/server/tornado.py
bokeh/server/urls.py
bokeh/server/views/root_handler.py

Implement a RootHandler to `/` that lists available applications or redirects

Server: Implement a RootHandler to `/`

---

bokehjs/src/coffee/common/ui_events.coffee

Fixes Issue #2997 
only tested on desktop with dual touch mouse

Initial fix for touch events with multiple plots

---

README.md

Closes #4440.
This PR makes the following enhancements to the introduction:
- Edit the introduction text
- Reorder the phrases that link to docs/quickstart/social media and add headings
- Add install command using conda to give experienced users a way to quickly install Bokeh

Update README structure and edit grammar

---

sphinx/source/docs/dev_guide/documentation.rst

Closes #4446 
This PR was created during the PyCon sprints run by @birdsarah. The PR adds commands to assist documentarians and edits the text for increased end user clarity.

Edit dev guide's documentation section

---

bokeh/core/json_encoder.py
bokeh/core/tests/test_json_encoder.py

added encoder for timedeltas AND a test to confirm

---

sphinx/source/docs/dev_guide/setup.rst

explicitly document installing into the bokehjs directory

---

bokeh/core/json_encoder.py
bokeh/core/properties.py
bokeh/core/tests/test_json_encoder.py
bokeh/models/ranges.py
bokeh/util/serialization.py
bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/src/coffee/models/ranges/data_range1d.coffee
bokehjs/src/coffee/models/ranges/factor_range.coffee
bokehjs/src/coffee/models/ranges/range1d.coffee
bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee
examples/howto/prevent_user_zooming_or_panning_too_far.py

fixes #572
Implemented by allowing a third parameter in the `bounds` argument.

Ranges can have minimum range to constrain min zoom level

---

bokeh/charts/builder.py
bokeh/charts/data_source.py
bokeh/charts/tests/test_builder.py
examples/charts/file/horizon.py
examples/charts/file/timeseries.py
examples/howto/charts/deep_dive-attributes.ipynb

4344/Better handle pd.DatetimeIndex in bokeh.charts 

---

examples/compat/pandas_dataframe.py
tests/examples/examples.yaml

issues: fixes #4195
Maybe this will help. Will run CI tests on it repeatedly.

simplify erroring test

---

bokehjs/src/less/flexbox.less

extending https://github.com/bokeh/bokeh/pull/4276

Removing more non-spec CSS

---

tests/plugins/upload_to_s3.py

quiet boto log level

---

bokehjs/src/coffee/models/widgets/date_picker.coffee

partially addresses #4204 
This PR provides a functioning (but unstyled) date picker. It is attached to an `<input>` and the input shows the currently selected date. If someone else can get the styling working, great. Otherwise at least it functions correctly. 
Note: I removed the code from the "render" method because it seems to be getting called alot, unnecessarily, and there is no reason to recreate the objects every time (also doing so cleared the input so that the date did not show)

functioning but poorly styled datepicker

---

bokehjs/src/coffee/models/widgets/dropdown.coffee

Resolved issue #4498 by changing @mget("type") to @mget("button_type"))

Fixed Dropdown Type Bug

---

bokeh/charts/glyphs.py
bokeh/charts/tests/test_chart.py
bokeh/core/enums.py
bokeh/core/properties.py
bokeh/core/tests/test_properties.py
bokeh/layouts.py
bokeh/models/layouts.py
bokehjs/src/coffee/core/enums.coffee
bokehjs/src/coffee/models/layouts/layout_dom.coffee
bokehjs/src/coffee/models/layouts/widget_box.coffee
bokehjs/src/coffee/models/plots/plot.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/src/coffee/models/tools/toolbar_box.coffee
bokehjs/src/less/bokeh-layout.less
bokehjs/test/core/enums.coffee
bokehjs/test/document.coffee
bokehjs/test/models/layouts/box.coffee
bokehjs/test/models/layouts/layout_dom.coffee
bokehjs/test/models/layouts/spacer.coffee
bokehjs/test/models/layouts/widget_box.coffee
bokehjs/test/models/plots/plot.coffee
bokehjs/test/models/plots/plot_canvas.coffee
bokehjs/test/models/tools/toolbar.coffee
examples/embed/embed_responsive_width_height.py
examples/howto/layouts/words_and_plots.py
tests/integration/interaction/test_responsive.py

issues: fixes #4396
ping @birdsarah could use some help verifying this set of change is complete, etc.

update all the responsive modes

---

bokehjs/src/coffee/document.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee
examples/plotting/file/iris.py

Tweaks to almar's resize PR

---

bokehjs/src/coffee/api/typings/document.d.ts
bokehjs/src/coffee/api/typings/models/annotations.d.ts
bokehjs/src/coffee/api/typings/models/plots.d.ts

I think this can be considered part of the layout work #4392
* Add new legend prop introduced in #4452 
* Remove `resize_width_height`
* Add `Document.resize` which should now be used in place of `resizie_width_height`
cc @mattpap

A few fixes to the typings

---

bokeh/models/__init__.py

Add missing import

---

bokeh/models/annotations.py

Update docstring on Title.title_padding

---

bokeh/models/annotations.py
bokeh/models/plots.py
bokeh/models/tests/test_annotations.py
bokehjs/src/coffee/models/annotations/title.coffee
examples/howto/layouts/dashboard.py
examples/models/iris.py
tests/integration/annotations/test_title.py

Change Title.title_padding to Title.offset and Title.title_align to title.align

---

tests/test_code_quality.py

test_code_quality.py use explicit utf-8 encoding to read source files

---

bokeh/layouts.py
bokehjs/src/coffee/models/layouts/spacer.coffee
examples/howto/layouts/manual_grid.py

Partially fixes: #4384 
The other part of #4384 is for layout functions to accept arbitrarily nested lists. But this can wait till later. These functions should make it quick enough to spell out layouts.

Add new layout functions for row & column

---

bokeh/charts/builders/horizon_builder.py
bokeh/charts/tests/test_chart.py
bokeh/plotting/figure.py
bokehjs/src/coffee/api/plotting.coffee

remove ResizeTool from set of default tools

---

examples/app/clustering/main.py
examples/app/clustering/theme.yaml

fixes for recent changes

---

bokehjs/src/coffee/models/plots/plot.coffee
tests/integration/interaction/test_sizing_mode.py

Fixes #4537
Still having some trouble to run Selenium locally, so trying like this first.

Fix scale_both

---

examples/app/movies/main.py

New layout does better when not specifying sizes for boxes

---

bokeh/core/validation/check.py
bokeh/core/validation/warnings.py
bokeh/models/plots.py

validation warning when sticky toolbars might overlap

---

bokeh/layouts.py
examples/howto/layouts/dashboard.py

Fix broken layouts

---

bokeh/charts/chart.py
bokeh/core/compat/bokeh_renderer.py
bokeh/models/tests/test_tools.py
bokeh/models/tools.py
bokeh/plotting/figure.py
bokeh/plotting/helpers.py
bokehjs/src/coffee/models/tools/toolbar.coffee
bokehjs/src/coffee/models/tools/toolbar_base.coffee
sphinx/source/docs/user_guide/tools.rst

implement a scheme to be able to select active gesture tools programatically

---

bokeh/core/compat/bokeh_renderer.py
examples/README.md
examples/plotting/notebook/README.md

Replaced some deprecated title_parameter with the new title.parameter.
Solves issues #4547 also

Changed title_text and issue #4547

---

bokeh/core/_templates/notebook_load.html
bokehjs/src/less/continuum.less

fix bokeh logo in notebook load

---

bokeh/layouts.py

Set default gridplt toolbar position to above

---

bokeh/layouts.py

Fix toolbar display in fixed mode gridplot

---

bokeh/models/layouts.py

Undeprecate HBox and VBox and add docstrings explaining behavior and return value (instances of Row and Column).

Undeprecate HBox and VBox and add docstrings

---

examples/app/weather/main.py

Work around pandas bug in weather app example

---

examples/howto/ajax_source.py

specify columns explicity in ajax source

---

bokehjs/src/coffee/models/plots/plot_canvas.coffee
tests/integration/interaction/test_reset_tool.py

Execute range callbacks on reset_range (called by reset_tool)

---

bokehjs/src/coffee/models/tools/toolbar_base.coffee

Remove hack unneeded since #4607 introduced in #4312

---

bokeh/core/compat/bokeh_renderer.py

issues: fixes #4626
Some very tiny changes to shore up mpl compat. ping @bokeh/dev

small updates to compat

---

bokehjs/src/coffee/models/canvas/canvas.coffee
bokehjs/src/coffee/models/layouts/layout_dom.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/test/models/axes/axis.coffee
bokehjs/test/models/callbacks/customjs.coffee
bokehjs/test/models/layouts/layout_dom.coffee
bokehjs/test/models/plots/plot.coffee
bokehjs/test/models/plots/plot_canvas.coffee
bokehjs/test/models/ranges/data_range1d.coffee
bokehjs/test/utils.coffee

Keep fixed listen to and solve zoom issue

---

bokeh/models/tests/test_tools.py
bokeh/models/tools.py

Should not have a toolbarbox warning when making a grid plot

---

bokehjs/src/coffee/models/widgets/button.coffee
bokehjs/src/coffee/models/widgets/checkbox_button_group.coffee
bokehjs/src/coffee/models/widgets/checkbox_group.coffee
bokehjs/src/coffee/models/widgets/multiselect.coffee
bokehjs/src/coffee/models/widgets/radio_button_group.coffee
bokehjs/src/coffee/models/widgets/radio_group.coffee
bokehjs/src/coffee/models/widgets/selectbox.coffee
bokehjs/src/coffee/models/widgets/text_input.coffee

Fixes: #4663 
I started using super - and put it in the wrong place - in the recent widgets PR.

Fix widget calls in wrong order

---

bokehjs/src/coffee/models/tools/actions/reset_tool.coffee

Correctly call resize

---

bokeh/core/validation/errors.py
bokeh/models/map_plots.py
bokehjs/src/coffee/api/typings/models/map_plots.d.ts
bokehjs/src/coffee/models/plots/gmap_plot.coffee
bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee
examples/models/maps.py
examples/models/maps_cities.py
examples/models/trail.py

Fixes: #4658 
Rough around the edges still, but tested locally with my own api key and works.
We should probably add a python warning.
@bryevdv - I have some thoughts about what to do about docs, but that should probably be in a seperate PR.

Add support for Google Maps API Key

---

examples/howto/Hover callback.ipynb
examples/howto/Linked panning.ipynb
examples/howto/Range update callback.ipynb
examples/howto/charts/bar.ipynb
examples/howto/charts/boxplot.ipynb
examples/howto/charts/deep_dive-composite_glyphs.ipynb
examples/howto/charts/deep_dive.ipynb
examples/howto/charts/donut.ipynb
examples/howto/charts/dots.ipynb
examples/howto/charts/excel.ipynb
examples/howto/charts/heatmap.ipynb
examples/howto/charts/histograms.ipynb
examples/howto/charts/horizon.ipynb
examples/howto/charts/lines.ipynb
examples/howto/charts/palettes.ipynb
examples/howto/charts/scatter.ipynb
examples/howto/charts/steps.ipynb
examples/howto/charts/timeseries.ipynb
examples/howto/interactive_bubble/gapminder.ipynb
examples/howto/notebook_comms/Basic Usage.ipynb
examples/howto/notebook_comms/Continuous Updating.ipynb
examples/howto/notebook_comms/Jupyter Interactors.ipynb
examples/howto/notebook_comms/Numba Image Example.ipynb
examples/howto/us_marriages_divorces/us_marriages_divorces_interactive.ipynb
examples/plotting/notebook/color_scatterplot.ipynb
examples/plotting/notebook/glyphs.ipynb

Clean up notebook examples

---

bokeh/charts/builders/heatmap_builder.py

remove call to deprecated attribute and replace with new ones

---

bokeh/models/sources.py

undeprecate from_df

---

bokeh/charts/builders/heatmap_builder.py
examples/app/crossfilter/main.py
examples/app/surface3d/main.py
examples/app/surface3d/templates/index.html
examples/charts/file/area.py
examples/charts/file/heatmap.py
examples/models/daylight.py
examples/models/donut.py
examples/models/gauges.py
examples/plotting/file/image.py
examples/plotting/server/geojson_points.py

This should try to collect the last set up examples updates.

more examples tweaks for 0.12

---

bokeh/models/plots.py

add deprectated getter/setter for Plot.responsive

---

examples/app/gapminder/main.py
examples/app/gapminder/templates/index.html
examples/app/gapminder/templates/styles.css
examples/app/gapminder/theme.yaml

Just some aesthetic choices and some streamlining

Pretty-up gapminder example

---

sphinx/source/conf.py

Replace additional 0.11.1 to 0.12.0 in confy.py

---

bokeh/core/properties.py
bokeh/util/serialization.py

Improve PyPy compatibility

---

sphinx/source/docs/user_guide/quickstart.rst

Corrected error in first quickstart example

---

bokehjs/src/coffee/api/plotting.coffee
bokehjs/src/coffee/embed.coffee

Testing: this code isn't very well tested. I'm not sure the best way to ensure against regressions.
Example code: https://github.com/beenje/flask_bokeh_app
ping @beenje for testing

Change div class to bk-root from bokeh-container

---

bokehjs/src/coffee/models/plots/plot_canvas.coffee
examples/webgl/iris_blend.py

Fixes #4679 
cc @bryevdv @brendancol

Draw annotation level after WebGL blitting

---

conda.recipe/meta.yaml

add missing test dependency

---

sphinx/source/docs/installation.rst

Provide minimum pandas version in installation doc

---

bokehjs/package.json
bokehjs/src/coffee/common/hittest.coffee
bokehjs/src/coffee/core/util/bbox.coffee
bokehjs/src/coffee/models/glyphs/annular_wedge.coffee
bokehjs/src/coffee/models/glyphs/annulus.coffee
bokehjs/src/coffee/models/glyphs/bezier.coffee
bokehjs/src/coffee/models/glyphs/circle.coffee
bokehjs/src/coffee/models/glyphs/glyph.coffee
bokehjs/src/coffee/models/glyphs/multi_line.coffee
bokehjs/src/coffee/models/glyphs/patches.coffee
bokehjs/src/coffee/models/glyphs/quad.coffee
bokehjs/src/coffee/models/glyphs/quadratic.coffee
bokehjs/src/coffee/models/glyphs/rect.coffee
bokehjs/src/coffee/models/glyphs/segment.coffee
bokehjs/src/coffee/models/glyphs/wedge.coffee
bokehjs/src/coffee/models/markers/marker.coffee
bokehjs/src/coffee/models/ranges/data_range1d.coffee
bokehjs/test/core/util/bbox.coffee
bokehjs/test/models/ranges/data_range1d.coffee

update to rbush 2.0.1

---

examples/plotting/file/categorical.py

Fixed typo in plot title

---

bokehjs/src/coffee/models/glyphs/image.coffee
bokehjs/src/coffee/models/glyphs/image_rgba.coffee
bokehjs/test/size.coffee

fix overlooked change for rbush update

---

bokehjs/src/coffee/models/tools/toolbar_box.coffee
bokehjs/test/models/tools/toolbar_box.coffee

don't overwrite previously merged tools

---

sphinx/source/docs/user_guide/server.rst

Small fix in example code for bokeh.client

---

bokehjs/package.json

jqui 1.12 breaks everything, pin to old version

---

bokeh/tile_providers.py
examples/plotting/file/airports_map.py

Note: I assume retina or non-retina could be detected somehow on the fly and switched. But this is useful as it is at least for me.

add cartodb tile provider

---

bokeh/charts/chart.py

[x] issues: fixes #3383
@bokeh/dev thoughts on when to merge this? I'm fine with it going in a `0.12.1`

remove all 0.11 io-related deprectations

---

sphinx/source/docs/gallery.rst

Fix broken source code link in gallery.rst

---

bokeh/models/plots.py

fix docstring of add_tools

---

bokeh/models/plots.py

Updates add_glyph docstring

---

bokehjs/src/coffee/models/glyphs/webgl/base.coffee
bokehjs/src/coffee/models/glyphs/webgl/line.coffee
bokehjs/src/coffee/models/glyphs/webgl/markers.coffee
bokehjs/src/vendor/gloo/gloo2.js

Fixes #4795 
Fixes #2683 
The main fix has been applied in https://github.com/vispy/vispy.js/blob/master/scripts/gloo2.py, which is the code that generates gloo2.js. While in there I also improved the API a bit, so this PR also updates the Bokeh code accordingly. Further, I snuck in a quick fix for #4795.
Todo:

Make WebGL work on Safari

---

conda.recipe/bld.bat
conda.recipe/meta.yaml

add npm install to win build; add nodejs to win build deps

---

bokeh/models/tools.py
bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee

Reverts bokeh/bokeh#4826
Need to update "defaults checking" tests.

Revert "moved the wheel speed zoom from internal to defined."

---

examples/plotting/file/les_mis.py

added black outline and hover color

---

conda.recipe/bld.bat
conda.recipe/meta.yaml

Make conda recipe work on Windows

---

bokehjs/src/coffee/models/glyphs/circle.coffee

update to use new bounds format

---

bokeh/models/widgets/inputs.py
bokehjs/src/coffee/models/widgets/multiselecttemplate.eco
bokehjs/src/coffee/models/widgets/selecttemplate.eco
sphinx/source/docs/user_guide/source_examples/interaction_multiselect.py

fix multiselect to allow values or values and labels

---

bokeh/models/glyphs.py
bokeh/models/markers.py
bokehjs/src/coffee/common/models.coffee
bokehjs/src/coffee/models/glyphs/hexagon.coffee
examples/models/iris_hex.py

Wrote the python code and started writing the coffee code to draw hexagon glyphs.  Not fully functional yet.  In the coffee code, the `_hit_` sections and `_mask_data` section are commented out.

Stvn66 4786 hex markers

---

bokehjs/src/coffee/models/plots/plot.coffee
bokehjs/src/less/continuum.less

Fixes #4853 
I have tested this manually, I don't think we have any other tests for this - and I'm not sure what that would be off the top of my head.
Note to test this thoroughly you need to test all combinations of:
* sizing_modes 
* toolbar in below and right position (note that the below toolbar was suffering from the same problem as right toolbar, but no-one had caught it yet)
* toolbar_sticky is True and False
* single plots and more complex layouts

Use correct toolbar positioning and not hacky css

---

bokehjs/src/coffee/common/ui_events.coffee
bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee

Fixes #4862 
Also partially fixes wheel zoom tool on Edge #4863 - WheelZoom Tool now enables pinch.

Support wheelzoom on dual touch monitors better

---

bokehjs/src/coffee/models/annotations/poly_annotation.coffee

Remove duplicated override member from PolyAnnotation

---

bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/src/coffee/models/tools/actions/reset_tool.coffee
bokehjs/src/coffee/models/tools/gestures/resize_tool.coffee
bokehjs/test/models/plots/plot_canvas.coffee
bokehjs/test/models/tools/gestures/index.coffee
bokehjs/test/models/tools/gestures/resize_tool.coffee
bokehjs/test/models/tools/index.coffee

Correctly perform resize

---

bokehjs/src/vendor/gloo/gloo2.js

Fixes #4884 
A very small change.

Gloo2 typo in Int32Array/Uint32Array

---

sphinx/source/docs/reference.rst
sphinx/source/docs/user_guide.rst
sphinx/source/docs/user_guide/quickstart.rst

Some punctuation, some stylistic suggestions, all copy editing goodness.

Made a couple copy edits to User Guide pages.

---

sphinx/source/docs/releases/0.12.1.rst

0.12.1 release notes

---

examples/app/spectrogram/audio.py
examples/app/spectrogram/main.py
examples/app/spectrogram/waterfall.coffee
examples/app/spectrogram/waterfall.py

issues: fixes #4737
@birdsarah when you return I'd like to just collaborate on this one PR to improve the spectrogram in various ways.

spectrogram improvements

---

bokeh/charts/builder.py
bokeh/charts/data_source.py
bokeh/charts/glyphs.py
bokeh/charts/utils.py
bokeh/core/compat/mplexporter/utils.py
bokeh/document.py
bokeh/models/widgets/inputs.py
bokeh/resources.py
bokeh/server/protocol/server_handler.py
bokeh/server/server.py
examples/plotting/file/vector.py
tests/plugins/constants.py

Maggie m/4840 quantified code

---

examples/plotting/file/line_on_off.py

This fixes #4928 by changing the js to look for the specific values rather than the indices of the array.
The is a possibility that ``examples/app/line_on_off.py`` also has the original problem but I couldn't test it as don't have much experience with the server/app mode.

Fixing value checking to work with js arrays rather than with python

---

CHANGELOG
bokeh/document.py
bokeh/server/application_context.py
bokeh/server/tests/test_server.py
bokeh/server/views/session_handler.py

This is a pull request that extends on pull request. Note that it is relative to the branch of bryanv and not to master.

pass http requests arguments to app documents

---

bokeh/resources.py
bokeh/tests/test_resources.py
examples/models/external_resources.py
sphinx/source/docs/user_guide/extensions.rst
sphinx/source/docs/user_guide/extensions_gallery/latex.rst
sphinx/source/docs/user_guide/source_examples/extensions_example_latex.py

Add support for loading external resources in output template

---

bokeh/models/sources.py
bokehjs/src/coffee/common/hittest.coffee
bokehjs/src/coffee/models/glyphs/multi_line.coffee
bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
examples/plotting/file/multi_line.py

Adds hit test support for MultiLine glyph

Add hit testing support for multiline

---

bokeh/application/handlers/directory.py
bokeh/application/handlers/function.py
bokeh/application/handlers/tests/test_code.py
bokeh/application/handlers/tests/test_directory.py
bokeh/application/handlers/tests/test_function.py

extend safe_to_fork reporting to all handlers

---

bokeh/resources.py
bokeh/tests/test_resources.py

Keep ordering of resources

---

bokeh/models/mappers.py
bokehjs/src/coffee/models/glyphs/image.coffee
bokehjs/src/coffee/models/mappers/color_mapper.coffee
bokehjs/src/coffee/models/mappers/linear_color_mapper.coffee
bokehjs/src/coffee/models/mappers/log_color_mapper.coffee
bokehjs/test/models/glyphs/image.coffee
bokehjs/test/models/glyphs/index.coffee
bokehjs/test/models/mappers/color_mapper.coffee
bokehjs/test/models/mappers/index.coffee
bokehjs/test/models/mappers/log_color_mapper.coffee

Add color_mapper model listener to Image glyph for callback driven updates

---

bokehjs/src/coffee/models/annotations/arrow.coffee

arrow.coffee typo correction

---

sphinx/source/docs/user_guide/embed.rst

Fixes documention issue #5001
per discussion here: http://stackoverflow.com/a/39070704/528729

noted CDN resources are available via HTTPS

---

bokeh/models/glyphs.py
bokeh/models/mappers.py
bokeh/models/tests/test_mappers.py
bokehjs/src/coffee/api/typings/models/mappers.d.ts
bokehjs/src/coffee/models/mappers/color_mapper.coffee
bokehjs/src/coffee/models/mappers/linear_color_mapper.coffee
bokehjs/src/coffee/models/mappers/log_color_mapper.coffee
bokehjs/test/models/mappers/linear_color_mapper.coffee
bokehjs/test/models/mappers/log_color_mapper.coffee

ColorMapper - support NaN's and clamp_data

---

bokehjs/src/coffee/models/mappers/linear_color_mapper.coffee
bokehjs/src/coffee/models/mappers/log_color_mapper.coffee

`_.isNaN` seems to be too strict.

Switch to isNaN

---

bokehjs/src/coffee/models/annotations/label_set.coffee

Update LabelSet visual properties on model and model.source change

Update LabelSet visual properties on model and model.source change 

---

bokehjs/src/coffee/models/glyphs/image.coffee
bokehjs/src/coffee/models/glyphs/image_rgba.coffee
bokehjs/src/coffee/models/glyphs/image_url.coffee
bokehjs/test/models/glyphs/glyph_utils.coffee
bokehjs/test/models/glyphs/image.coffee
bokehjs/test/models/glyphs/image_rgba.coffee
bokehjs/test/models/glyphs/image_url.coffee
bokehjs/test/models/glyphs/index.coffee

Refactor ImageURl.Model 's w, h attributes to be DistanceSpecs (not NumberSpec), to match Bokeh model. Also implement support for data/screen units.

bugfix: w_units, h_units support for ImageURL glyph

---

bokeh/models/annotations.py
bokeh/models/tests/test_annotations.py
bokehjs/src/coffee/api/models.coffee
bokehjs/src/coffee/api/typings/models/annotations.d.ts
bokehjs/src/coffee/models/annotations/color_bar.coffee
bokehjs/test/models/annotations/color_bar.coffee
tests/integration/annotations/test_color_bar.py

Add ColorBar JS API
fixes #4989

Add ColorBar JS API

---

bokehjs/src/coffee/models/glyphs/hbar.coffee
bokehjs/src/coffee/models/glyphs/quad.coffee
bokehjs/src/coffee/models/glyphs/vbar.coffee

fix spatial indexing for vbar/hbar

---

bokehjs/src/coffee/models/annotations/color_bar.coffee

Fixes #5056
I've opened a separate issue about testing for this: #5058

Use underscore map function in ColorBar

---

examples/plotting/file/boxplot.py

Minor Fix: boxplot example indexing

---

.travis.yml

Fixes #5077 
Assuming this passes, can merge and then can test with bgyarfas' PR

Only run integration tests for non external contributors

---

scripts/travis_install

Pin conda-build version to 1.21.14

---

setup.py

one-liner to include .html files from bokeh/server/views/

Fixes #5074. need to package .html in bokeh/server/views

---

sphinx/source/docs/releases/0.12.2.rst

Add 0.12.2 release notes

---

bokeh/models/annotations.py
bokeh/models/mappers.py
bokehjs/src/coffee/common/models.coffee
bokehjs/src/coffee/models/mappers/categorical_color_mapper.coffee
bokehjs/src/coffee/models/mappers/color_mapper.coffee
bokehjs/src/coffee/models/mappers/linear_color_mapper.coffee
bokehjs/src/coffee/models/mappers/log_color_mapper.coffee
bokehjs/test/models/mappers/categorical_color_mapper.coffee
bokehjs/test/models/mappers/index.coffee
examples/howto/interactive_bubble/data.py
examples/howto/interactive_bubble/gapminder.py

Add categorical color mapper

---

scripts/update_bokehjs_versions.py

handle non dev/rc last release

---

bokehjs/src/coffee/models/widgets/data_table.coffee

Revert "fix bad merge"

---

examples/app/movies/README.md

Fix IMDB typo

---

bokehjs/src/coffee/models/tools/inspectors/crosshair_tool.coffee

This was an oversight in PR #5147.

Replace obj.unset('prop_name') with obj.prop_name = null

---

bokeh/models/mappers.py
bokeh/models/tests/test_mappers.py
bokehjs/src/coffee/models/mappers/linear_color_mapper.coffee
bokehjs/src/coffee/models/mappers/log_color_mapper.coffee
bokehjs/test/models/mappers/linear_color_mapper.coffee
bokehjs/test/models/mappers/log_color_mapper.coffee
examples/plotting/file/color_data_map.py

Add support for low color and high color for linear and log mappers

---

bokeh/core/compat/bokeh_renderer.py

should fix https://github.com/bokeh/bokeh/issues/5180

matplotlib2.0.0b4 compatibility fix

---

bokehjs/src/coffee/models/widgets/slider.coffee
bokehjs/src/coffee/models/widgets/slidertemplate.eco

1. `title=None` means no title and no current value.
2. `title=""` means just no title (without the annoying colon).
fixes #5175

Make Slider handle title=None and title="" properly

---

bokehjs/src/coffee/document.coffee
bokehjs/test/document.coffee

Support passing suggested height/width values to document.resize method

---

bokehjs/src/coffee/api/models.coffee
bokehjs/src/coffee/api/plotting.coffee

Restore original definition of API for markers using new paths

---

bokehjs/src/coffee/models/mappers/log_color_mapper.coffee

Add a polyfill for Math.log1p()

---

bokeh/charts/builders/boxplot_builder.py

BoxPlot outlier_line_color

---

bokehjs/src/coffee/models/canvas/cartesian_frame.coffee
bokehjs/test/models/canvas/cartesian_frame.coffee

Fix memory usage regression introduced in PR #5106

---

sphinx/source/docs/reference/models.rst
sphinx/source/docs/reference/models/transforms.rst

Add transforms to reference guide and toc tree

---

bokeh/models/formatters.py
bokeh/models/tools.py

Change 0.12.{4->3} deprecation due to delayed release

---

sphinx/docserver.py

Output is now:
```
Press <ENTER> to exit...
Asked Server to shut down.
Server shut down.
```

Changed input to raw_input

---

bokehjs/src/coffee/api/typings/models/mappers.d.ts

Add typings for {Log,Categorical}ColorMapper

---

bokeh/util/compiler.py
bokeh/util/tests/test_compiler.py
bokehjs/gulp/eco.coffee
bokehjs/gulp/index.coffee
bokehjs/gulp/tasks/scripts.coffee
bokehjs/src/js/compile.coffee

This should be used in PR #5258.
fixes #5279

Add support for Eco template in custom models

---

examples/app/spectrogram/waterfall.py
examples/app/surface3d/surface3d.py

quick fix for custom model implementations in apps

---

examples/app/clustering/main.py

Behaves much better (no flickering, etc.)

best practice for updating source.data in cluster app

---

scripts/issues.py
sphinx/source/docs/releases/0.12.3.rst
sphinx/source/index.rst

* Add release notes for `0.12.3`
* make it so that dupe issues do not require a type
@canavandl the func tick formatter section needs text from you.
@bokeh/dev If there are any small last minute example or docs fixes, this is the place for them

issues release notes

---

examples/plotting/file/hover.py
examples/plotting/file/tap.py

fix deprecations

---

examples/embed/simple/simple.py

update simple.py example to remove deprectated usage and bad links

---

bokeh/core/properties.py
bokeh/core/tests/test_properties.py

Took list of units from here:
http://www.w3schools.com/cssref/css_units.asp
Tested every unit by hand to see that:
* it rendered
* it changed size when the value changed

check for all valid CSS font size units

---

bin/bokeh-server
setup.py
sphinx/source/docs/user_guide/quickstart.rst

remove old bokeh-server completely

---

bokeh/application/application.py
bokeh/command/subcommands/serve.py
bokeh/command/subcommands/tests/test_serve.py
bokeh/server/application_context.py
bokeh/server/server.py
bokeh/server/tornado.py

remove develop mode stub code for server

---

bokeh/embed.py
bokeh/server/tests/test_server.py
bokeh/server/views/autoload_js_handler.py
sphinx/source/docs/user_guide/embed.rst

Don't set browser title for autoload_server

---

bokeh/core/compat/bokeh_renderer.py
bokeh/core/compat/mpl.py
examples/compat/mpl_stem.py

Add tool argument

---

examples/app/movies/description.html

Add IMDb notice per IMDb usage page, http://www.imdb.com/help/show_leaf?usedatasoftware.

Add IMDb usage notice

---

bokehjs/examples/donut/donut.ts
bokehjs/examples/electron/renderer.js
bokehjs/examples/hover/hover.ts
bokehjs/examples/stocks/stocks.ts
bokehjs/examples/tap/tap.ts

Prefer const over let in *.ts

---

examples/embed/animated.py

fix animated example

---

bokehjs/src/coffee/models/widgets/cell_editors.coffee
bokehjs/src/coffee/models/widgets/data_table.coffee
bokehjs/src/coffee/models/widgets/text_input.coffee

Use className instead of attributes: {class: "name"}

---

bokeh/models/widgets/inputs.py
bokehjs/src/coffee/models/widgets/text_input.coffee
bokehjs/src/coffee/models/widgets/text_input_template.eco

Extend TextInput with `placeholder` attribute

---

.travis.yml

Fake API key for external PRs.

---

bokeh/palettes.py

Include Greys256 in Palettes enumeration

---

bokeh/charts/data_source.py
bokeh/core/properties.py
bokehjs/package.json

Sphinx 1.5 seems to more aggresively try to automatically create ref
targets. Two issues resulted in duplicate targets causing a build error

small fixups to make sphinx 1.5 work

---

bokeh/command/subcommands/serve.py
bokeh/command/subcommands/static.py
bokeh/server/server.py
bokeh/server/tests/test_server.py
bokeh/server/tests/utils.py
bokeh/server/tornado.py
sphinx/source/docs/user_guide/server.rst

Fix #5494: make Tornado server library-friendly

---

bokeh/core/enums.py
bokeh/models/annotations.py
bokeh/models/glyphs.py
bokeh/models/tools.py
bokehjs/src/coffee/api/charts.coffee
bokehjs/src/coffee/api/typings/enums.d.ts
bokehjs/src/coffee/core/enums.coffee
bokehjs/src/coffee/models/annotations/color_bar.coffee
bokehjs/src/coffee/models/annotations/legend.coffee
bokehjs/src/coffee/models/glyphs/image_url.coffee
bokehjs/src/coffee/models/glyphs/quad.coffee
sphinx/source/docs/user_guide/styling.rst

Make location/anchor naming consistent (and add aliases)

---

sphinx/source/docs/includes/hero.txt

Get IE docs page rendering correctly

---

bokeh/layouts.py
bokeh/tests/test_layouts.py

merge gridplot tools in nested cases

---

bokeh/core/_templates/autoload_nb_js.js
bokeh/embed.py
bokeh/tests/test_resources.py
bokeh/util/compiler.py
bokeh/util/notebook.py
bokehjs/src/coffee/base.coffee
bokehjs/src/coffee/index.coffee
bokehjs/src/coffee/main.coffee
bokehjs/src/js/plugin-prelude.js
sphinx/source/docs/user_guide/embed.rst
tests/integration/interaction/test_tools.py

Deprecate Bokeh.$ and Bokeh._

---

bokeh/command/subcommands/tests/test_serve.py
bokeh/server/server.py
bokeh/server/tornado.py

I gave up writing a test for this because it appears Tornado's bult-in process-forking is fragile and can leave processes around: https://github.com/tornadoweb/tornado/issues/1912

Fix #5524: fix --num-procs following Bokeh server refactor

---

scripts/travis_install

disable conda nb extension on travis

---

bokehjs/src/coffee/models/sources/column_data_source.coffee
bokehjs/test/models/sources/column_data_source.coffee

fix JS logic for CDS col lengths check

---

bokehjs/src/coffee/models/layouts/index.coffee
bokehjs/src/coffee/models/ranges/index.coffee

Next logical step is to add support for bokehjs examples' test automation.
fixes #5555

Fix bokehjs' examples

---

conda.recipe/meta.yaml
setup.cfg
sphinx/source/docs/dev_guide/testing.rst
tests/integration/integration_tests_plugin.py

Fix up running selenium tests locally

---

tests/examples/collect_examples.py
tests/examples/examples.yaml

Enable custom models examples' automation

---

bokeh/core/properties.py
bokeh/models/glyphs.py
bokeh/models/sources.py

Deprecate ImageRGBA.{rows,cols}

---

.travis.yml

Try sudo=true for travis ci problem

---

.travis.yml

Revert "Try sudo=true for travis ci problem"

---

bokeh/util/notebook.py

This was revealed after PR #5533. Switching from jquery to less forgiving APIs is definitively step in right direction.
fixes #5570

Don't use FINALIZE_JS if hide_banner is True

---

.travis.yml
scripts/travis_install

explicitly kill stray processes on travis

---

bokehjs/src/coffee/models/sources/column_data_source.coffee

Return stable value from ColumnDataSource.get_length()

---

bokeh/models/glyphs.py

#5587: Fixed a typo in MultiLine docstring

#5587: Fixed a NumberSpec typo

---

bokeh/models/widgets/inputs.py
bokehjs/src/coffee/models/widgets/multiselect.coffee
examples/models/widgets.py
sphinx/source/docs/dev_guide/setup.rst
sphinx/source/docs/user_guide/layout.rst

Closes #5579
* Adds size attribute to MultiSelect model
* Small note in docs about BOKEH_MINIFIED env var, as it took me a while to figure out how to directly use the unminified JS.

Adding size attribute to MultiSelect model

---

bokeh/util/compiler.py

Make custom models work in Notebook again

---

bokeh/core/_templates/plot_div.html
bokeh/core/properties.py
bokeh/core/tests/test_properties.py
bokeh/model.py
bokeh/models/plots.py
bokeh/util/callback_manager.py
bokehjs/gulp/tasks/generate_defaults.py
bokehjs/src/coffee/models/plots/plot.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/src/less/bokeh.less
examples/howto/interactive_bubble/gapminder_styles.css
examples/plotting/server/responsive.py
sphinx/source/docs/user_guide/embed.rst

Add support for readonly properties

---

bokeh/charts/chart.py

Add VBar and HBar glyphs to chart.py

---

bokeh/core/json_encoder.py
bokeh/core/tests/test_json_encoder.py

Fixes issue #4918. I didn't make a changelog entry because I didn't see a heading for version 0.12.4 and I wasn't sure what to do.

Deserialize a deque as a JSON list.

---

bokeh/core/properties.py
bokeh/models/formatters.py
bokeh/models/glyphs.py
bokeh/palettes.py
bokeh/plotting/figure.py
bokeh/plotting/helpers.py
bokeh/util/__init__.py
bokeh/util/browser.py
bokeh/util/compiler.py
bokeh/util/tests/test_browser.py
bokeh/util/warnings.py
sphinx/source/conf.py
sphinx/source/docs/reference.rst
sphinx/source/docs/reference/models.rst
sphinx/source/docs/user_guide/server.rst
sphinx/source/index.rst

issues: fixes #3931 fixes #4778 fixes #5595 fixes #4991 fixes #5602

Various small docs updates for 0.12.4

---

bokeh/util/compiler.py

Use proc.returncode to detect failed node/npm run

---

bokeh/command/subcommands/info.py
bokeh/command/subcommands/tests/test_info.py
bokeh/util/compiler.py

Show node/npm version numbers in `bokeh info`

---

setup.py

Remove invalid classifier

---

scripts/deploy.py

Remember to commit CHANGELOG on deploy

---

scripts/build_upload.sh

Only upload one sdist to pypi

---

bokeh/command/subcommands/serve.py
bokeh/command/subcommands/tests/test_serve.py

Fixes the issue with "None" reported by Bokeh server. I apologize in advance if the PR is not made as intended.

Add default_server_port to server_kwargs

---

bokeh/palettes.py

Minor fix in palettes documentation

---

bokeh/core/state.py
bokeh/io.py
tests/test_no_client_server_common.py

Open to suggestions for more places to remove or testing strategies

limit heavyweight imports to only when used

---

bokehjs/src/coffee/models/markers/marker.coffee

have legends respect marker angle

---

conda.recipe/meta.yaml
scripts/travis_install

pin conda version to 4.2.15

---

bokehjs/src/coffee/models/widgets/data_table.coffee

Wire up DataTable for streaming and patching events

---

bokehjs/src/less/toolbar.less

added tooltip font color to avoid being masked by color:white property from outside css

---

examples/app/weather/main.py

removed unnecessary for loop on source data update

---

bokeh/core/_templates/autoload_nb_js.js

Show bokehjs version in "successfully loaded" message

---

scripts/build_upload.py

break up conda operations to prevent timeout

---

scripts/build_upload.py

fix path for CSS upload

---

scripts/build_upload.py

globs don't work in subprocesses w/o shell=True

---

scripts/build_upload.py

correctly implement PUT

---

bokehjs/src/coffee/embed.coffee

Use Element.dataset instead of $(...).data()

---

examples/embed/autoload_static.py
examples/howto/server_embed/flask_embed.py
examples/howto/server_embed/templates/embed.html
examples/howto/server_embed/tornado_embed.py

issues: fixes #5742 
This also adds a missing example for `autoload_static` requested in #5798

Add missing template

---

bokeh/models/layouts.py
bokeh/models/tests/test_layouts.py
bokeh/models/widgets/panels.py
bokeh/tests/test_objects.py

deprecate VBox and HBox

---

bokeh/models/tools.py
bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
sphinx/source/docs/releases/0.12.5.rst

Change hovertool default for line to closest instead of previous point

---

scripts/travis_install

bump conda and conda-build versions

---

bokehjs/gulp/tasks/test.coffee

Allow to debug tests with `gulp test --debug`

---

bokeh/models/map_plots.py
bokehjs/src/coffee/models/plots/gmap_plot.coffee
bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee

add support for GMap scale control

---

sphinx/source/docs/installation.rst
sphinx/source/docs/releases/0.12.4.rst

Documented dependency on python versions

---

sphinx/source/docs/installation.rst

Addresses one component of #5858

Update installation.rst to include note on `bokeh-api`

---

scripts/travis_install

bump conda and conda-build verision

---

bokeh/models/tests/test_formatters.py
bokeh/util/tests/test_compiler.py
bokehjs/package.json

Fix failing tests on travis ci

---

bokeh/server/application_context.py
bokeh/server/views/ws.py
bokehjs/src/coffee/client.coffee
bokehjs/src/coffee/embed.coffee
bokehjs/test/client.coffee
sphinx/source/docs/releases/0.12.5.rst

pass HTTP request args more explicitly to session

---

bokeh/command/subcommands/serve.py
bokeh/command/subcommands/static.py
bokeh/document.py
bokeh/util/logconfig.py

Fix #5793: remove logging.basicConfig() calls from library

---

bokeh/util/tests/test_api_crawler.py

Adding a test for this would probably require a whole extra CI build, unless you feel like changing one to run on the installed copy.

TST: Don't assume current dir is source directory.

---

bokehjs/package.json

Force proj4 < 2.4 because of source code incompatibility

---

bokehjs/src/coffee/core/dom.ts
bokehjs/src/coffee/core/jsx.d.ts
bokehjs/src/coffee/core/util/array.ts
bokehjs/src/coffee/core/util/callback.ts
bokehjs/src/coffee/core/util/math.ts
bokehjs/tsconfig.json

Enable noImplicitAny and fix any errors

---

bokeh/core/has_props.py
bokeh/core/properties.py
bokeh/core/property/bases.py
bokeh/core/property/containers.py
bokeh/core/property/descriptors.py
bokeh/core/property/tests/test_containers.py
bokeh/core/property/tests/test_descriptors.py
bokeh/core/tests/test_has_props.py
bokeh/core/tests/test_properties.py
bokeh/tests/test_objects.py
bokeh/themes/theme.py

Handle theming of property value containers

---

bokehjs/package.json
bokehjs/src/coffee/core/layout/side_panel.coffee
bokehjs/src/coffee/core/layout/solver.coffee
bokehjs/src/coffee/models/canvas/canvas.coffee
bokehjs/src/coffee/models/layouts/box.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee

I'm submitting this to run examples' and integration tests. There will be obvious unit failures.
fixes partially #5518

Attempt to make layout less fragile

---

sphinx/source/docs/user_guide/examples/extensions_example_latex.py
sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py

Fix scripts in user_guide/examples/extensions_*.py

---

bokeh/sphinxext/bokeh_plot.py

add linenos flag option to sphinxext.bokeh_plot

---

bokehjs/src/coffee/models/callbacks/customjs.coffee
bokehjs/test/models/callbacks/customjs.coffee

Provide exports variable in CustomJS's callback function

---

bokehjs/src/coffee/core/ui_events.coffee
bokehjs/src/coffee/models/annotations/legend.coffee

Set pointer cursor on Legend only when click_policy != "none"

---

bokeh/models/annotations.py
bokehjs/src/coffee/models/annotations/legend.coffee
examples/plotting/file/interactive_legend.py

Update interactive legend inactive defaults

---

bokeh/application/handlers/code.py
bokeh/charts/__init__.py
bokeh/command/subcommands/serve.py
bokeh/core/state.py
bokeh/core/tests/test_state.py
bokeh/document.py
bokeh/io.py
bokeh/plotting/__init__.py
bokeh/sphinxext/example_handler.py
bokeh/tests/test_client_server.py
bokeh/tests/test_io.py
sphinx/source/docs/releases/0.12.5.rst

remove output_server and support functions

---

bokeh/models/sources.py
bokeh/models/tests/test_sources.py
bokeh/util/serialization.py
bokeh/util/tests/test_serialization.py

ColumnDataSource.from_dataframe using arrays

---

bokeh/client/session.py
bokeh/command/subcommands/serve.py
bokeh/command/subcommands/tests/test_serve.py
bokeh/core/_templates/autoload_js.js
bokeh/core/_templates/doc_js.js
bokeh/embed.py
bokeh/resources.py
bokeh/server/server.py
bokeh/server/tests/test_tornado.py
bokeh/server/tests/utils.py
bokeh/server/tornado.py
bokeh/server/views/autoload_js_handler.py
bokeh/server/views/doc_handler.py
bokeh/sphinxext/example_handler.py
bokeh/tests/test_client_server.py
bokeh/tests/test_embed.py
bokeh/tests/test_resources.py
bokehjs/src/coffee/embed.coffee
examples/howto/server_embed/flask_embed.py
examples/howto/server_embed/notebook_embed.ipynb
examples/howto/server_embed/tornado_embed.py
scripts/tests/test_api_report.py
sphinx/source/docs/releases/0.12.5.rst
sphinx/source/docs/user_guide/server.rst
tests/test_no_request_host.py

Support relative URLs / deprecate --host arg 

---

bokehjs/examples/hover/hover.ts
bokehjs/examples/tap/tap.ts

This fixes the last two examples that constantly fail image diff.
fixes #5254

Use custom PRNG in bokehjs examples that participate in image diff

---

bokeh/application/application.py
bokeh/core/_templates/notebook_cell_observer.js
bokeh/core/state.py
bokeh/core/templates.py
bokeh/core/tests/test_state.py
bokeh/io.py
bokeh/server/server.py
bokeh/server/tests/test_server.py
bokeh/server/tests/test_tornado.py
bokeh/server/tornado.py
bokeh/tests/test_io.py
bokeh/util/notebook.py
examples/howto/server_embed/notebook_embed.ipynb

This PR continues on from #5717 but using a local branch. See #5717 for previous comments and discussion.

Automatically destroying servers in the notebook embed example

---

bokehjs/src/coffee/core/has_props.coffee
bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
bokehjs/test/core/has_props.coffee

check for transform listener on glyph

---

bokehjs/src/less/toolbar.less

Set tooltips' foreground color to black

---

bokehjs/package.json

Upgrade numbro

---

bokeh/util/compiler.py
bokeh/util/tests/test_compiler.py

Make sure `node --version` terminates and is evaluated lazily

---

_setup_support.py

fix typo that breaks sdists

---

bokeh/models/plots.py
bokehjs/src/coffee/models/plots/plot.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee

Adding readonly layout_width and layout_height

---

examples/models/file/sprint.py

empty string for filtered-out names instead of None

---

bokeh/command/subcommands/serve.py
bokeh/command/subcommands/tests/test_serve.py
bokeh/server/server.py

restore --host behavour to copy values to --allow-websocket-origin to preserve compat

---

bokeh/models/sources.py
bokehjs/src/coffee/core/has_props.coffee
bokehjs/src/coffee/core/hittest.coffee
bokehjs/src/coffee/core/selector.coffee
bokehjs/src/coffee/models/glyphs/multi_line.coffee
bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
bokehjs/test/core/util/array.coffee
examples/models/server/linked_tap.py
tests/integration/interaction/test_patches_preselection.py
tests/integration/interaction/test_selection.py

Make multiple selection work again

---

bokeh/embed.py

added back in _ModelInEmptyDocument to improve notebook performance

---

bokehjs/src/coffee/core/ui_events.coffee
bokehjs/test/common/ui_events.coffee
tests/integration/interaction/test_selection.py

This fixes the problem, but this logic is very cumbersome. This needs to be revisited in the next dev cycle.
fixes #6030

Improve propagation of events in UIEvent._trigger()

---

bokeh/util/serialization.py

Math is much faster than NumPy for scalar checks

Use math library instead of numpy for nan/inf checks

---

examples/plotting/file/airports_map.py

Added a tiler with a valid URL for second plot in plotting/file/airport_map

---

bokehjs/src/coffee/core/dom.ts

Use cross-browser compatible offset()

---

scripts/build_upload.py

issues: fixes #5827
Merging to try out more tasks before full release

upload sdists dev builds

---

sphinx/source/docs/gallery.rst

Changed from:
https://github.com/bokeh/bokeh-demos/tree/master/weather
To:
https://github.com/bokeh/bokeh/tree/master/examples/app/weather

fixed href

---

sphinx/source/docs/user_guide/embed.rst

fixed broken link to gapminder example

---

bokeh/sampledata/elements.csv

Issues: fixes #6071 
Updated chemical element names in elements.csv. Trivial fix.

Updated chemical element names in elements.csv (in sampledata)

---

examples/plotting/server/animated.py

fix missing glyph and color  in plotting/server/animated.py

---

bokeh/embed.py
bokeh/io.py
bokeh/tests/test_embed.py
examples/howto/server_embed/flask_embed.py
examples/howto/server_embed/tornado_embed.py

change default for relative_url to False

---

examples/embed/animated.py

Same as 6084 but for version of animated in embed.

fixed animated example in embed

---

bokehjs/src/coffee/core/util/eq.ts

Fix bokehjs to work in IE again

---

bokeh/server/views/app_index.html
bokeh/server/views/root_handler.py

Properly apply --prefix to links on the app index page

---

bokeh/util/tornado.py

issues: fixes #6152
Explicitly check for None and do not rely on BadYieldError being raised

Updates to maintain compat with Tornado >= 4.5

---

bokehjs/src/coffee/models/tools/gestures/box_select_tool.coffee
bokehjs/src/coffee/models/tools/gestures/box_zoom_tool.coffee
bokehjs/src/coffee/models/tools/gestures/lasso_select_tool.coffee
bokehjs/src/coffee/models/tools/gestures/poly_select_tool.coffee

Properly configure vectorized properties of overlays

---

bokehjs/src/coffee/core/bokeh_events.ts
bokehjs/src/coffee/core/util/array.ts
bokehjs/src/coffee/core/util/callback.ts
bokehjs/src/coffee/core/util/string.ts
bokehjs/src/coffee/core/util/wheel.ts
bokehjs/tsconfig.json

Enable TS' strict options and fix errors

---

sphinx/source/docs/user_guide/interaction/callbacks.rst

Fix callback docs errors

---

bokehjs/src/coffee/models/markers/marker.coffee

implement _hit_span for all markers

---

bokeh/command/__init__.py
bokeh/command/subcommands/serve.py
bokeh/core/has_props.py
bokeh/core/properties.py
bokeh/embed.py
bokeh/models/formatters.py
bokeh/plotting/helpers.py
bokeh/util/serialization.py
bokeh/util/string.py
bokeh/util/tests/test_string.py
tests/test_python_execution_with_OO.py

I just added some simple if-clauses before using accessing ```__doc__```s.
[x] issues: fixes #6156

Optimized python execution fails due to missing __doc__ instantiation.

---

bokeh/core/property/descriptors.py
bokeh/core/property/tests/test_descriptors.py

properly trigger events on del m.foo

---

bokeh/core/properties.py
bokeh/core/tests/test_properties.py

be more strict about valid dataspec keys

---

bokeh/core/json_encoder.py

Fix deprecated call to datetime64 for NP_EPOCH.

---

bokehjs/package.json
bokehjs/src/coffee/core/layout/layout_canvas.coffee
bokehjs/src/coffee/models/annotations/annotation.coffee
bokehjs/src/coffee/models/annotations/arrow.coffee
bokehjs/src/coffee/models/annotations/color_bar.coffee
bokehjs/src/coffee/models/annotations/legend.coffee
bokehjs/src/coffee/models/annotations/span.coffee
bokehjs/src/coffee/models/annotations/title.coffee
bokehjs/src/coffee/models/annotations/tooltip.coffee
bokehjs/src/coffee/models/axes/axis.coffee
bokehjs/src/coffee/models/canvas/canvas.coffee
bokehjs/src/coffee/models/canvas/cartesian_frame.coffee
bokehjs/src/coffee/models/glyphs/image_url.coffee
bokehjs/src/coffee/models/glyphs/ray.coffee
bokehjs/src/coffee/models/layouts/box.coffee
bokehjs/src/coffee/models/layouts/layout_dom.coffee
bokehjs/src/coffee/models/layouts/widget_box.coffee
bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee
bokehjs/src/coffee/models/plots/plot.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/src/coffee/models/tiles/dynamic_image_renderer.coffee
bokehjs/src/coffee/models/tiles/tile_renderer.coffee
bokehjs/src/coffee/models/tools/gestures/resize_tool.coffee
bokehjs/src/coffee/models/tools/toolbar_base.coffee
bokehjs/test/core/layout/side_panel.coffee
bokehjs/test/models/annotations/color_bar.coffee
bokehjs/test/models/glyphs/rect.coffee

Remove confusing aliases from LayoutCanvas

---

bokeh/models/tests/test_formatters.py
bokeh/models/tests/test_transforms.py
bokeh/util/tests/test_compiler.py
bokehjs/package.json

Upgrade typescript and fix tests

---

sphinx/source/docs/installation.rst
sphinx/source/docs/user_guide/bokehjs.rst

Update documentation regarding BokehJS API split

---

bokehjs/package.json
bokehjs/tsconfig.json

Use tslib instead of per module generated helpers

---

bokeh/sphinxext/bokeh_plot.py
sphinx/source/conf.py

Shinxext plot

---

bokehjs/src/coffee/models/plots/gmap_plot.coffee
bokehjs/src/coffee/models/plots/plot.coffee

Initialize properly plot canvas in plot's subclasses

---

bokehjs/package.json

rev coffee-script to >= 0.12.5

---

bokeh/models/plots.py
bokeh/models/tests/test_plots.py
bokeh/plotting/helpers.py
bokeh/plotting/tests/test_figure.py
bokehjs/src/coffee/api/plotting.coffee
bokehjs/src/coffee/api/typings/models/plots.d.ts
bokehjs/src/coffee/models/canvas/cartesian_frame.coffee
bokehjs/src/coffee/models/plots/plot.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/test/models/canvas/cartesian_frame.coffee

Reverts bokeh/bokeh#6235
There was an uncaught incompat with a recently merged PR to master.

Revert "Deprecate x/y_mapper_type Plot kwargs in place of first-class Scale models"

---

examples/embed/embed_multiple.py

example had mismatching lengths
https://github.com/bokeh/bokeh/issues/6252

fix mismatched length

---

bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee

issues: fixes #6248
Unfortunately I can't think of any god way to unit test this code as-is. Suggestions welcome, an image test is probably difficult with gmaps, too.

have gmap canvas retrieve ranges from the frame

---

bokeh/application/application.py
bokeh/application/tests/test_application.py
bokeh/document.py
bokeh/embed.py
bokeh/settings.py
bokeh/tests/test_embed.py
sphinx/source/docs/dev_guide/env_vars.rst

Validate document inside of _ModelInDocument and _ModelInEmptyDocument

Validate document inside of _ModelInDocument and _ModelInEmptyDocument

---

bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/test/models/ranges/data_range1d.coffee

Make bokehjs work in IE again and improve tests

---

bokeh/io.py

edits to bokeh.io docstrings

---

conda.recipe/meta.yaml
sphinx/source/conf.py
sphinx/source/docs/dev_guide/documentation.rst

* Pin to sphinx=1.5.1
* Remove duplicate `packaging` entry in meta.yaml
* Clean up dev_guide/documentation deps sections

Pin sphinx==1.5.1 and clean up dev_guide/documentation deps section

---

examples/plotting/file/interactive_legend.py
sphinx/source/docs/user_guide/examples/interaction_legend_hide.py
sphinx/source/docs/user_guide/examples/interaction_legend_mute.py
sphinx/source/docs/user_guide/examples/plotting_datetime_axis.py

Use stock data from bokeh.sampledata.stocks instead of yahoo ichart api
Use stock data from bokeh.sampledata.stocks instead of yahoo ichart api

Use stock data from bokeh.sampledata.stocks instead of yahoo ichart api

---

bokehjs/src/coffee/core/build_views.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
bokehjs/src/coffee/models/widgets/abstract_button.coffee

Make HoverTools' tooltips reconfigurable

---

bokeh/server/server.py

add tornado version to server.py string

---

examples/examples.yaml

disabling for now should evaluate more later

downstream URL for dynamic_map.py has SSL issue

---

bokeh/charts/__init__.py
setup.py

Add compat shim for `bokeh.charts` and dependency on `bkcharts` (both to be removed at `1.0`)

add bkcharts shim and dependency

---

sphinx/source/docs/user_guide/concepts.rst

Otherwise, the resulting document is empty.
Closes #5634.

Add curdoc().add_root() to bokeh command example

---

examples/models/server/population.py

Fix scale/range incompat

---

bokehjs/src/coffee/core/layout/side_panel.coffee
bokehjs/test/core/layout/side_panel.coffee

Fix memory leak when updating panel constraints

---

bokehjs/src/coffee/models/annotations/legend.coffee

Revert "Fix regression in legend location"

---

bokeh/server/server.py

Configurable maximum upload size, see  #6338
Fixes  #6338

server.py: add max_buffer_size argument

---

scripts/spec.py

add script to dump complete JSON specification for all Bokeh models

---

bokehjs/src/coffee/models/annotations/box_annotation.coffee
bokehjs/src/coffee/models/annotations/span.coffee
bokehjs/src/coffee/models/annotations/text_annotation.coffee
bokehjs/src/coffee/models/annotations/tooltip.coffee
bokehjs/src/coffee/models/glyphs/image.coffee
bokehjs/src/coffee/models/grids/grid.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/src/coffee/models/ranges/factor_range.coffee
bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
bokehjs/src/coffee/models/sources/columnar_data_source.coffee
bokehjs/src/coffee/models/tiles/dynamic_image_renderer.coffee
bokehjs/src/coffee/models/tiles/tile_renderer.coffee
bokehjs/src/coffee/models/tools/actions/action_tool.coffee
bokehjs/src/coffee/models/tools/gestures/lasso_select_tool.coffee
bokehjs/src/coffee/models/tools/gestures/poly_select_tool.coffee
bokehjs/src/coffee/models/tools/tool_proxy.coffee
bokehjs/src/coffee/models/tools/toolbar.coffee
bokehjs/src/coffee/models/widgets/abstract_button.coffee
bokehjs/src/coffee/models/widgets/checkbox_button_group.coffee
bokehjs/src/coffee/models/widgets/checkbox_group.coffee
bokehjs/src/coffee/models/widgets/markup.coffee
bokehjs/src/coffee/models/widgets/multiselect.coffee
bokehjs/src/coffee/models/widgets/radio_button_group.coffee
bokehjs/src/coffee/models/widgets/radio_group.coffee
bokehjs/src/coffee/models/widgets/range_slider.coffee
bokehjs/src/coffee/models/widgets/selectbox.coffee
bokehjs/src/coffee/models/widgets/slider.coffee
bokehjs/src/coffee/models/widgets/text_input.coffee

I went ahead and fixed everything, besides:
```
bokehjs/src/coffee/models/tools/toolbar.coffee:        @connect(tool.properties.active.change, @_active_change.bind(null, tool))
bokehjs/src/coffee/models/tools/toolbar_box.coffee:          @connect(proxy.properties.active.change, @_active_change.bind(null, proxy))
```
which looks suspicious on its own.
fixes #6365

Don't use implicit slots, e.g. `@connect(@change, @set_data)`

---

bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee

issues: fixes #6091
As motioned in the issue this does not seem to be a 100% fix, but an improvement. Tested also that notebook usage was not affected.

attempt to properly redraw when gmaps change size

---

bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee

@mattpap `@_set_bokeh_ranges` implies `request_render` so I've just reduced to that. It performs OK, or at least better than nothing in any case.

rely on request_render and fix up CS code

---

bokehjs/src/coffee/core/selection_manager.coffee
bokehjs/test/core/selection_manager.coffee

handle renderers that return null hit test results

---

bokehjs/package.json

Use @types/gulp 3.x with gulp 3.x

---

bokeh/core/property/bases.py
bokeh/core/property/tests/test_bases.py

@philippjfr @mattpap please test/have a look at this

fix property match checking when there are dicts of arrays

---

bokeh/core/property/bases.py

Fix properties to work in when pandas is not installed

---

bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee

issues: fixes #6416
Tested with the code in the issue. All this complicated code in HoverTool needs much better unit tests at some point.

fix nearest mode for hover on multi-lines

---

bokeh/model.py
bokehjs/src/coffee/model.coffee

Move js_on_change() connections to connect_signals()

---

bokeh/embed.py
bokeh/tests/test_embed.py
examples/embed/arguments/bokeh_server.py
examples/embed/arguments/flask_server.py
sphinx/source/docs/user_guide/embed.rst

Needed that feature for an app so I figured I'd do a PR. 
It's my first one though, so all suggestions are welcome :)

Pass HTTP arguments to autoload_server (#5992)

---

.travis.yml

update TravisCI to latest (supported) linux dist

---

sphinx/source/docs/reference/models/scales.rst

add scales automodule

---

bokeh/model.py
bokeh/plotting/figure.py
bokeh/plotting/helpers.py
examples/app/spectrogram/audio.py
examples/plotting/file/line_missing_data.py
sphinx/source/docs/user_guide/layout.rst
sphinx/source/docs/user_guide/notebook.rst
sphinx/source/docs/user_guide/plotting.rst
sphinx/source/docs/user_guide/styling.rst

issues: fixes #6453 fixes #6507 fixes #6377 fixes #4859 fixes #3245 fixes #4752

Collect small docs and examples improvements

---

bokeh/io.py
bokeh/tests/test_io.py

Maximize window for png screenshot to capture whole output

Maximize window for png screenshot to capture whole output

---

bokeh/command/subcommands/serve.py
bokeh/command/subcommands/tests/test_serve.py
bokeh/server/server.py

issues: fixes #5431
Additionally, this makes `--show` work correctly with `--address`

log more verbose app paths

---

.travis.yml

only run js tests on py3 builds for now

---

.travis.yml

try using --self-contained-html to fix report CSS

---

.travis.yml

try self contained report for integration test call too

---

bokeh/tests/test_io.py

clean up phantomjs procs in unit tests

clean up phantomjs procs in unit tests

---

.travis.yml
scripts/ci/build
scripts/ci/deploy
scripts/ci/install
scripts/ci/install:build
scripts/ci/install:deploy
scripts/ci/install:test
scripts/ci/test

This PR attempts to 
* prevent installs when they are not needed
* make sure installs happen when they are needed in the deploy stage

Fix up stages install order issues

---

.travis.yml

issues: fixes #6568
ping @canavandl @mattpap just FYI

hotfix for Travis log truncation

---

bokeh/sampledata/daylight.py
conda.recipe/meta.yaml
setup.py

Remove unused daylight data download func to remove requests build dep

Remove unused daylight data download func to remove requests build dep

---

bokehjs/gulp/labeler.ts
bokehjs/gulp/paths.ts
bokehjs/gulp/tasks/build.ts
bokehjs/gulp/tasks/clean.ts
bokehjs/gulp/tasks/compiler.ts
bokehjs/gulp/tasks/index.ts
bokehjs/gulp/tasks/scripts.ts
bokehjs/gulp/tasks/styles.ts
bokehjs/gulp/tasks/test.ts
bokehjs/gulpfile.js
bokehjs/package.json
bokehjs/src/coffee/index.coffee
bokehjs/test/index.coffee
bokehjs/test/size.ts

Clean up and simplify bokehjs' build

---

bokeh/command/subcommands/png.py
bokeh/command/subcommands/svg.py
bokeh/command/subcommands/tests/__init__.py
bokeh/command/subcommands/tests/test_png.py
bokeh/command/subcommands/tests/test_svg.py
bokeh/io.py
bokeh/tests/test_io.py

Add width and height kwargs to export_png

Add width and height kwargs to export_png

---

bokeh/io.py

- 1 issue: fixes #6598
- 0 tests added / passed
- 0 release document entry (if new feature or API change)

fix localhost for autoload_server in io.py

---

bokeh/models/tools.py
bokehjs/src/coffee/models/callbacks/customjs.coffee
bokehjs/src/coffee/models/callbacks/open_url.coffee
bokehjs/src/coffee/models/tools/gestures/tap_tool.coffee
sphinx/source/docs/releases/0.12.7.rst

normalize tap tool callback calling convention

---

bokehjs/src/coffee/models/glyphs/hbar.coffee
bokehjs/src/coffee/models/glyphs/vbar.coffee

Update hbar and vbar

---

bokeh/core/_templates/autoload_js.js
bokeh/core/_templates/autoload_nb_js.js
bokeh/util/compiler.py
bokehjs/gulp/prelude.ts

I ended up commenting UMD code. This is suboptimal, but a proper solution is much harder than I expected, and requires deeper changes to how autoload works.
fixes #6679

Make bokehjs work in notebook

---

sphinx/source/docs/user_guide/server.rst

Fixes a type (missing parenthesis) in the code for the [server docs](http://bokeh.pydata.org/en/latest/docs/user_guide/server.html).

issues: closes #6687

---

sphinx/source/docs/dev_guide/setup.rst

Add a note on jinja2 and pyyaml dependencies

---

bokeh/models/graphs.py
bokehjs/src/coffee/core/selection_manager.coffee
bokehjs/src/coffee/models/glyphs/multi_line.coffee
bokehjs/src/coffee/models/graphs/graph_hit_test_policy.coffee
bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
bokehjs/src/coffee/models/renderers/graph_renderer.coffee
bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
bokehjs/test/models/graphs/graph_hit_test_policy.coffee
bokehjs/test/models/renderers/glyph_renderer.coffee

Add EdgesAndLinkedNodes policy

---

bokeh/models/tools.py
bokehjs/src/coffee/models/tools/gestures/poly_select_tool.coffee

This brings PolySelectTool in alignment with the other selection tools

Add PolySelectTool.callback

---

bokeh/models/plots.py

Remove orphaned Plot.add_graph method

Remove out-dated Plot.add_graph method

---

examples/examples.yaml
examples/models/file/graphs.py

needs to be merged after #6686 
looks like (each with different interactions):

Add examples/models/files/graphs.py example

---

bokeh/io.py
bokeh/models/layouts.py
bokeh/models/tests/test_layouts.py
sphinx/source/docs/releases/0.12.7.rst

Remove deprecated functions

---

examples/models/file/widgets.py

Set initial value of DatePicker() in models/file/widgets

---

bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
bokehjs/src/coffee/models/sources/ajax_data_source.coffee

Make sure AjaxDataSource is initialized only once

---

bokeh/sphinxext/bokeh_plot.py
sphinx/source/docs/dev_guide/env_vars.rst

fix BOKEH_DOCS_CDN handling

---

bokeh/io.py

Expose webdriver as kwarg to export_png and export_svgs

Expose webdriver as kwarg to export_png and export_svgs

---

examples/app/spectrogram/audio.py

pass SAMPLE_RATE as integer

---

conda.recipe/meta.yaml
examples/app/ohlc/main.py
examples/examples.yaml
examples/models/server/widgets.py
examples/plotting/server/responsive.py
examples/plotting/server/selection_histogram.py
tests/examples/collect_examples.py
tests/examples/test_examples.py

Example test improvements

---

bokehjs/src/coffee/models/ranges/data_range1d.coffee
bokehjs/test/models/ranges/data_range1d.coffee

Fix zero range_padding causing empty plot

---

bokeh/core/_templates/autoload_nb_js.js
bokeh/io.py
bokeh/util/notebook.py

Add mime message for jupyter lab load mime renderer

Add mime message for jupyter lab load mime renderer

---

bokeh/io.py
bokeh/tests/test_io.py
bokeh/util/notebook.py

cc @canavandl @zjffdu @mattpap @clairetang6

add mechanism to install external notebook display hooks

---

bokeh/models/widgets/sliders.py
bokehjs/src/coffee/models/widgets/range_slider.coffee
bokehjs/src/coffee/models/widgets/slider.coffee

Use 0[.]00 format in numerical sliders

---

bokehjs/src/coffee/models/annotations/label.coffee

Position labels relative to frame if in center region

---

bokeh/core/_templates/autoload_nb_js.js
bokeh/util/notebook.py

use separate display_data to display status div

---

examples/plotting/file/aspect.py

Add example for the new aspect ratio control behavior introduced in #6784

Add aspect example

---

bokeh/models/widgets/sliders.py
bokehjs/src/coffee/models/widgets/abstract_slider.coffee
bokehjs/src/less/widgets/nouislider.less

Improve styling of slider widget

---

bokeh/resources.py

Don't fail silently when inline resources aren't available

---

examples/plotting/file/brewer.py

Simplify data frame length calculation.

---

.travis.yml
bokeh/models/tests/test_sources.py
sphinx/source/docs/dev_guide/testing.rst
sphinx/source/docs/installation.rst
sphinx/source/docs/releases/0.12.8.rst

Don't test on Python 3.4 anymore

---

sphinx/source/docs/reference/models/widgets.sliders.rst

Add missing widgets.sliders doc

Add widgets.sliders doc

---

bokeh/util/compiler.py
bokeh/util/tests/test_compiler.py
conda.recipe/meta.yaml
sphinx/source/docs/installation.rst

Check nodejs version number in bokeh.util.compiler

---

bokehjs/src/coffee/models/widgets/tables/cell_formatters.coffee

Don't double encode text in StringFormatter

---

bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/src/coffee/models/tools/actions/reset_tool.coffee
bokehjs/src/less/canvas.less
bokehjs/test/models/plots/plot_canvas.coffee
sphinx/source/docs/user_guide/quickstart.rst

Remove leftover code after PR #6752

---

bokeh/events.py
bokehjs/src/coffee/core/bokeh_events.ts
bokehjs/src/coffee/models/tools/actions/reset_tool.coffee
examples/howto/events_app.py

added new Reset event

---

bokehjs/src/coffee/models/tiles/tile_renderer.coffee

Align attribution to frame's lower right corner

---

bokeh/models/annotations.py
bokehjs/src/coffee/core/layout/layout_canvas.coffee
bokehjs/src/coffee/core/layout/side_panel.coffee
bokehjs/src/coffee/models/annotations/legend.coffee
bokehjs/src/coffee/models/axes/axis.coffee
bokehjs/src/coffee/models/canvas/cartesian_frame.coffee
bokehjs/src/coffee/models/layouts/layout_dom.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee
bokehjs/test/core/layout/layout_canvas.coffee
bokehjs/test/core/layout/side_panel.coffee
bokehjs/test/models/annotations/legend.coffee
bokehjs/test/models/canvas/canvas.coffee
bokehjs/test/models/canvas/cartesian_frame.coffee
bokehjs/test/models/plots/plot_canvas.coffee
examples/howto/layouts/words_and_plots.py
examples/models/file/legends.py
examples/models/file/panels.py
examples/models/file/synthetic.py
examples/models/server/linked_tap.py
examples/plotting/file/custom_tooltip.py
examples/plotting/file/logplot.py

This takes advantage of axis' panel to position axis label. ~~Note that currently this results in incorrect positioning, because panels are aligned to canvas and not frame (see #6472). I intentionally went with the correct solution and not using frame for alignment, so that we finally start using proper tooling (assuming #6472 is fixed).~~
fixes #6850
fixes #6472

Fix positioning of axis label

---

bokeh/io.py

Fairly simple fix, just return the handle. Not sure what tests could be added.

return comms handles to show

---

bokehjs/package.json

DataTable should prefer global jquery if available

---

bokeh/models/graphs.py

Typo in EdgesAndLinkedNodes docstring

---

bokeh/core/property_mixins.py
bokeh/models/tests/utils/property_utils.py
bokehjs/src/coffee/core/property_mixins.coffee
bokehjs/src/coffee/models/glyphs/text.coffee
examples/plotting/file/text.py

Add support for multi line text

---

bokeh/layouts.py

@bryevdv If this is not a reasonable request, never mind, just discard...
When submitting this pull request it says:
> All pull requests must have an associated issue in the issue tracker. If there
> isn't one, please go open an issue describing the defect, deficiency or desired
> feature. You can read more about our issue and PR processes in the
> [wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management).
> 
> - [ ] issues: fixes #xxxx
> - [ ] tests added / passed
> - [ ] release document entry (if new feature or API change)
Great.
I wonder whether for such small corrections like I'm doing now there could be a simpler approach (create an issue). On my side I am almost ashamed of submiting such small correction to you, but since I think documentation is really important …

[doc] Adjust docstring indentation

---

bokeh/models/widgets/sliders.py
bokeh/models/widgets/tests/test_slider.py

Add convenience function for datetime values

---

bokeh/core/has_props.py
bokeh/core/tests/test_has_props.py
bokeh/io.py
bokeh/util/notebook.py
bokeh/util/platform.py
tests/test_no_ipython_common.py

ensure all ipython imports are deferred

---

bokeh/models/widgets/sliders.py
bokehjs/src/coffee/models/widgets/date_range_slider.coffee
bokehjs/src/coffee/models/widgets/date_slider.coffee

This is my first pull request, please let me know if I did something wrong.

Jan 1st display incorrect - Changed %G to %Y

---

bokeh/application/application.py
bokeh/application/handlers/code.py
bokeh/events.py
bokeh/models/mappers.py

Just a few typos I noticed while reading the project documentation.

Fix docstrings

---

bokeh/embed.py
bokeh/io/notebook.py
bokeh/io/tests/test_notebook.py
bokeh/tests/test_embed.py
bokehjs/src/coffee/embed.coffee

@bokeh/dev I am marking this as `ready` I still plan to add some docs and tests later today but no implementation changes.

Use Bokeh protocol to implement push_notebook

---

bokeh/models/glyphs.py
bokehjs/src/coffee/models/glyphs/ray.coffee
bokehjs/test/models/glyphs/index.coffee
bokehjs/test/models/glyphs/ray.coffee

fix missing screen units handling for Ray

---

bokeh/sphinxext/bokeh_plot.py

use uuid's for script id instead of serial nos or filename hash

---

bokeh/plotting/helpers.py
bokeh/plotting/tests/test_helpers.py

Allow range_input to be an np.ndarray

Update helpers.py #6951

---

bokehjs/src/coffee/embed.coffee

issues: fixes #6982
no URL in IE

Fix bug : no URL in IE

---

bokeh/models/plots.py
bokeh/models/tools.py
bokeh/plotting/helpers.py
bokehjs/src/coffee/api/typings/models/tools.d.ts
sphinx/source/docs/releases/0.12.10.rst

Remove stub ResizeTool

---

bokehjs/src/coffee/models/annotations/color_bar.coffee

Remove custom ColorBar's positioning code

---

scripts/ci/install
scripts/ci/install:build
scripts/ci/install:deploy
scripts/ci/install:examples
scripts/ci/install:js
scripts/ci/install:test
scripts/ci/install:unit

This silences progress bars from `git`, `conda` and `npm`.
fixes #7009

Make travis ci logs smaller

---

bokeh/embed/standalone.py
sphinx/source/docs/installation.rst

PRs from external contributors currently untestable due to miniconda installer bug.

fix codebase issues

---

bokehjs/src/coffee/models/widgets/tables/data_table.coffee

force cds view indices to be recomputed on table updates

---

bokehjs/src/coffee/models/widgets/date_picker.coffee

Fix bug : DatePicker errors on input from Chrome on Windows 8.1

---

examples/models/file/graphs.py

Changed to handle nx2 scale "kwarg error

---

bokeh/models/graphs.py

This is not backward compatible Views were added in nx 2.0

Updated to handle networkx 2.0 Views

---

bokehjs/src/coffee/models/widgets/date_picker.coffee

Replaces my former PR for #4965.

fixes: Datepicker returns one day earlier than picked in IE (#7048)

---

bokehjs/gulp/linker.ts
bokehjs/package.json

Upgrade TypeScript to version 2.5.3

---

bokeh/palettes.py
bokeh/tests/test_tile_providers.py
bokeh/tile_providers.py

@mattpap given the limited scope of this PR I intent to merge tomorrow for an RC2

use class module hack to always return new copies of tile providers

---

bokehjs/src/coffee/models/axes/axis.coffee
examples/models/file/twin_axis.py

Fix axis label positioning

---

bokehjs/src/coffee/models/tools/gestures/select_tool.coffee

@mattpap do you have any suggestions for putting this better under test?

only consider renderers on the selection tool's associated plot

---

examples/examples.yaml

no diff for random jitter example

---

bokeh/io/showing.py
bokeh/server/server.py
bokeh/server/tests/test_server.py
examples/howto/server_embed/flask_embed.py
examples/howto/server_embed/flask_gunicorn_embed.py
examples/howto/server_embed/notebook_embed.ipynb
examples/howto/server_embed/standalone_embed.py
examples/howto/server_embed/tornado_embed.py

allow passing callables to Server as a convenience

---

bokeh/io/notebook.py
bokeh/io/showing.py
bokeh/io/tests/test_notebook.py

allow notebook URLs to specify protocol

---

bokeh/models/sources.py
bokeh/models/tests/test_sources.py

@nleclercq can you test this PR to confirm that it matches your expectations?

slice indices must be non-negative, not positive

---

sphinx/source/docs/user_guide/server.rst

Fix typo in server.rst

---

sphinx/source/docs/user_guide/extensions.rst

No issue number as per gitter conversation.

Renamed Custom attribute from range to slider

---

sphinx/source/docs/installation.rst

Fixes issue #7103 by updating documentation on BokehJS standalone installation guidelines

---

bokehjs/src/coffee/api/typings/models/ranges.d.ts
bokehjs/src/coffee/models/ranges/range.coffee

Allow using a function for range.callback in bokehjs

---

bokeh/util/compiler.py

Suggest to install nodejs from defaults channel

---

bokeh/core/properties.py

Fix copy&paste error in documentation.

Fix documentation for properties.RGB
