- bokeh/models/axes.py
- bokeh/models/formatters.py
- bokeh/models/tickers.py
- bokehjs/src/coffee/ticking/log_tick_formatter.coffee
- bokehjs/src/coffee/ticking/log_ticker.coffee
issues: closes #1590 
This was a little more involved. To get the properties correct on the python side, make tickers follow JS inheritance hierarchy properly. However, log axes had hard coded 10 as a base. Plumbed up ticker and formatter on JS side to properly use and display ticks for bases other than 10. Requires that `LogTickFormatters` be configured with a corresponding `LogTicker` (otherwise they default to `base=10` and warn in the console).
> allow log tickers to use base, etc.

- bokehjs/src/coffee/common/plot.coffee
This is the first commit of PR #1543.
> Don't request_render() twice during plot initialization

- sphinx/source/tutorial/exercises/stocks.py
- sphinx/source/tutorial/solutions/stocks.py
- sphinx/source/tutorial/topical.rst
Pull requests with the fixes suggested in #1728. In the timeseries tutorial:
- Displaying the X-axis values as dates (not the numerical representation of the date)
- Customizing the format of the dates
- Naming the axis
> In the timeseries tutorial, formatting the X-axis as dates

- scripts/get_bump_version.py
Ideally this doesn't fail, but at least this allows it to fail the way it's intended to. :-)
> Make sure sys is available for sys.exit() call on failure

- bokehjs/src/coffee/common/canvas.coffee
- bokehjs/src/coffee/common/plot.coffee
- examples/plotting/file/burtin.py
- examples/plotting/notebook/burtin.ipynb
- examples/plotting/server/burtin.py
issues: fixes #165 
Fix is actually to reduce the cartesian_frames width/height by 1, and keep canvas size exactly set to what the user specifies. 
Not entirely happy about this fix, there is an asymmetry --- canvas frame is reduced in `plot.coffee` but fixup for view/screen transform happens in `canvas.coffee`. But this is due to a poor separation of concerns and I would rather address that in a larger PR that cleans up some of the layout code.
> effectively dilate canvas by 1px

- bokehjs/src/coffee/common/base.coffee
If the bokeh-server host name contains `bokeh` keywork `Config.prefix` value is not the expected value.
For example if the url is `http://bokeh-test.com/bokeh/` the `Config.prefix` value will be `http:/` while the expected value is `http://bokeh-test.com`. It resolved #1775 issue.
> Resolving bokeh keyword problem in host name.

- .travis.yml
Just a test... this seems to deactivate building in other branches except from master... let's see if the PR is built (I don't think so, but maybe Travis surprise me)... if that's the case, this little changes will improve a lot our TravisCI run avoid duplicated builds from the pushed branch and PRs...
> Try to only build on master.

- examples/glyphs/linked_tap_server.py
This example shows how to connect two plots using tap tools and data sources. Clicking on circles in `plot1`, will change color of respective glyphs in `plot2`. Clicking on circles in `plot2`, will change size of respective glyphs in `plot1`.
> Add glyphs/linked_tap_server example

- bokehjs/src/coffee/common/cartesian_frame.coffee
issues: fixes #833
The upshot of this is that when users specify "screen" coordinates,
they are really specifying "view" (vx, vy) coordinates.
Furthermore, when mapping from a cartesian frame, the (0,0) is
the lower left corner of the central frame region.
**NOTE**: I believe our terminology and perhaps even some of the concepts around this are still a bit muddled, but I think this is an improvement, and that further improvements or changes can come as more layout work is pursued.
> include the frame offset in the screen mapping

- build_and_upload.sh
- setup.py
- versioneer.py
closes: #1148
It essentially injects the conda version into the get_version function, so it can return the dict correctly, with the devel tag as the `version` and the commit sha as the `full` version...
> Make versioneer aware of our devel build.

- bokeh/settings.py
This enables all debugging capabilities of bokeh, e.g. development resources, JSON pretty printing, debug mode logging, simple IDs.
Note that JSON pretty printing doesn't work. The code was removed during session refactoring. I will fix this later.
> Add support for BOKEH_DEV=True python something.py

- bokeh/resources.py
- bokeh/settings.py
- sphinx/source/docs/dev_guide.rst
This just add an entry point using an env variable to build the docs and get the plot rendered when you are working locally. This let's you use any released BokehJS or any devel version uploaded to the CDN (there could be the case, although not frequently, that you need a newer version that the released one and then, the devel version makes more sense).
> Hotfix to support local docs with a correct BokehJS

- sphinx/source/docs/dev_guide/building.rst
Take II.
- One section to install node and npm
- One section to install grunt et al.
- etc.
I think this makes the procedure a bit more clear. At least to people new to grunt and node and friends.
I also removed the note to execute the commands in the bokehjs subdir, because I found that it killed the flow of the text and structure of the docs. Instead I just mentioned it right before the command in question.
> Clearer docs, new section about installing npm and nodejs

- bokeh/charts/_chart.py
- bokeh/charts/_chart_options.py
- bokeh/plot_object.py
- examples/charts/server/line_animate.py
After builders design refactoring charts were not working with bokeh-server anymore because Chart object was not included in the preloaded_models of plot object. Also, chart id was not being created properly.
> Fix charts not working with server

- examples/charts/notebook/donut.ipynb
- examples/charts/notebook/scatter.ipynb
- examples/charts/notebook/timeseries.ipynb
Changed [x,y]_label to [x,y]label in charts/scatter example.
Update '[x,y]label' args
> Change [x,y]_label to [x,y]label in charts examples.

- sphinx/source/tutorial/solutions/.gitignore
- sphinx/source/tutorial/solutions/gallery/boxplot.rst
- sphinx/source/tutorial/solutions/gallery/brushing.rst
- sphinx/source/tutorial/solutions/gallery/histogram.rst
- sphinx/source/tutorial/solutions/gallery/hover.rst
- sphinx/source/tutorial/solutions/gallery/image.rst
- sphinx/source/tutorial/solutions/gallery/les_mis.rst
- sphinx/source/tutorial/solutions/gallery/lines.rst
- sphinx/source/tutorial/solutions/gallery/olympics.rst
- sphinx/source/tutorial/solutions/gallery/periodic.rst
- sphinx/source/tutorial/solutions/gallery/scatter.rst
- sphinx/source/tutorial/solutions/gallery/stocks.rst
- sphinx/source/tutorial/solutions/gallery/style.rst
- sphinx/source/tutorial/solutions/gallery/unemployment.rst
issues: fixes #1921
These files can be deleted when entire the gallery gets generated with the ``bokeh-gallery`` sphinx extension. Right now only the individual plots are, with ``bokeh-plot``.
> restore tutorial gallery

- sphinx/source/docs/dev_guide/process.rst
issues: fixes issue #1945
The problem was a malformatted rst link.
> Fix broken links to BEP in dev docs

- sphinx/source/docs/user_guide/charts.rst
Removes reference to old functionality input types examples section on user guide charts (from bug report on [m.l.](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/bokeh/sy0HabwWzj0/HU9fL5UOg7gJ) . As this is related also to #1901 (which may have different outcomes) this PR just remove the specific reference to axis labels. Builders new design separates charts axis labels creation and builders so the same previous behaviour is not obvious to restore.
> fix charts on userguide showing old functionality

- bokeh/models/glyphs.py
issues: closes issue #1929, closes #1928
Question: we don't currently have any code that does *not* provide a palette to an image, so this change will not be tested anywhere. Should I add an example for this?
> image glyph has standard palette Greys9

- bokeh/protocol.py
- bokehjs/src/coffee/renderer/glyph/line.coffee
- examples/glyphs/line_missing_data.py
- examples/plotting/file/line.py
issues: closes #1784
Also adds an example to show what happens with inf/nan/masked values.
One thing that the example shows is that inf/-inf is handled different from nan. Not sure if this is intentional. Edit: bokehjs now also ignores data values that are inf/-inf.
> BokehJSONEncoder sets masked values to nan

- setup.py
issues: closes #1953
- the returned list now only contains directories that actually exist
- some changes in ordering to make it more consistent with Debian.
- removed "lib-dynload" dir; that's not site-packages at all, is it?
> Fix getsitepackages() in setup.py

- examples/glyphs/trail.py
Issues: fixes #1978
I restored the trail.py examples but I removed the hover tool... it makes not sense to add something we know it is not working.
I split the PR in two commits as @mattpap has requested.
> Restore the glyph/trail.py example (2)

- sphinx/source/_static/my-styles.css
#1998 
Here's a first go incorporating all the feedback.
I think there are still areas of the docs that don't look as good as they could, but I don't *think* this PR makes them worse. 
For example, in the below, the section heading `bokeh.models.mappers` fades in comparison to the class heading. But messing with the section headings spreads throughout the entire website, so wasn't a quick fix.
> Add new styles to tweak visual hierarchy

- bokeh/resources.py
- bokeh/settings.py
- bokeh/tests/test_resources.py
- bokeh/util/paths.py
- sphinx/source/docs/dev_guide/building.rst
issues: closes issue #2038 
When `BOKEH_RESOURCES` is in dev mode (e.g. "relative-dev" or "absolute-dev"), the JS files are taken from `bokehjs/build` instead of `bokeh/server/static`. This  means that you can simply edit the coffeescript file, grunt will generate JS, and you can refresh the page to get the new result.
> Enable fast development simply by running grunt watch

- bokeh/plotting_helpers.py
- bokeh/properties.py
- bokeh/query.py
- bokeh/server/utils/reload.py
- bokeh/server/views/__init__.py
- bokeh/server/zmqpub.py
- bokeh/sphinxext/bokeh_github.py
- bokeh/transforms/ar_downsample.py
issues: closes #1983
I searched the code for `={}` and `=[]`. Assuming pep8 is followed and no arguments are specified as `foo = {}`, I should have got them all.
> change some empty dicts/lists as default args to None

- bokeh/cli/__init__.py
- bokeh/cli/core.py
- bokeh/cli/utils.py
- bokeh/models/__init__.py
- bokeh/models/axes.py
- bokeh/models/glyphs.py
- bokeh/models/plots.py
- bokeh/models/renderers.py
- bokeh/models/sources.py
- bokeh/models/tests/test_plots.py
- bokeh/models/tools.py
- bokeh/models/widgets/__init__.py
- bokeh/models/widgets/groups.py
- setup.cfg
issues: ref #2078 
These changes make the `bokeh.cli` and `bokeh.models` subpackages compliant with pyflakes. Especially the latter needed significant changes in the `__init__`; pyflakes does not allow `from x import *`, so I had to make them all explicit imports. But the list of names to import became so long that I wrote a small function to collect these names. The names to import is particularly long for the widgets module.
To shut pyflakes up about unused imports, apparently you can also use `__all__` which I personally found a bit nicer than just stating the names.  Happy to revert this to just stating a tuple of names though.
I am generally in favor of explicit imports, but in the case of importing all widgets, a star-import would be justified IMO. However, there is no way to shut …
> Make models and cli subpackages pyflakes compliant

- sphinx/source/docs/installation.rst
Found small typo in docs. Fixed.
> fix typo, example has two css, one should be js

- bokeh/sampledata/unemployment1948.csv
Obviously this is a very minor change, so I haven't created a corresponding issue.
> Remove extraneous comma from unemployment csv.

- bokehjs/npm-shrinkwrap.json
- bokehjs/package.json
This adds the `npm shrinkwrap --dev` output to ensure that versions are installed as expected.  It also upgrades to jsdom@5.x to avoid a bug that was apparently present in 4.5.1.
> Add shrinkwrap to lock to versions and upgrade jsdom

- bokeh/models/tickers.py
- bokehjs/src/coffee/ticking/abstract_ticker.coffee
- examples/plotting/file/line.py
issues: fixes #2185
Exposes `desired_num_ticks` on ticker objects to allow users to suggest
a target number of ticks. Adds an example of use in:
https://github.com/bokeh/bokeh/blob/feature/2185_num_ticks/examples/plotting/file/line.py
> Expose desired_num_ticks on tickers

- bokeh/embed.py
- bokeh/models/widgets/layouts.py
- bokeh/resources.py
- bokeh/tests/test_embed.py
- bokeh/tests/test_resources.py
- bokehjs/gulp/tasks/watch.coffee
continuing from #2210
This makes `relative-dev` work again. Basically, in this mode we now simply use the `bokeh.js` and `bokeh.css` (the composed, but not-minified versions).
Also, since the last time I touched the gulp code, we now load the js from `bokehjs/build` instead of `bokeh/server/static`, which means that `gulp watch` does not need the install step.
Is this the way to move forward with this?
> Make relative dev work again

- bokeh/models/widgets/layouts.py
Avoid layout breaking when simpleapp managing buttons (or any other widget without `value` attribute)
> avoid layout breaking when simpleapp managing buttons

- scripts/build_upload.sh
- scripts/release_upload.sh
Reverts bokeh/bokeh#2253
Because the packages are generated at the top directory:
Travislog:
```
Uploading: osx-64
Using binstar api site https://api.binstar.org
[BinstarError] file scripts/osx-64/bokeh*61605853*.tar.bz2 does not exist 
Uploading: linux-64
Using binstar api site https://api.binstar.org
[BinstarError] file scripts/linux-64/bokeh*61605853*.tar.bz2 does not exist 
Uploading: win-64
Using binstar api site https://api.binstar.org
[BinstarError] file scripts/win-64/bokeh*61605853*.tar.bz2 does not exist 
Uploading: linux-32
Using binstar api site https://api.binstar.org
[BinstarError] file scripts/linux-32/bokeh*61605853*.tar.bz2 does not exist 
Uploading: win-32
Using binstar api site https://api.binstar.org
[BinstarError] file scripts/win-32/bokeh*61605853*.tar.bz2 does not …
```
> Revert "Run binstar upload in the correct 'scripts' location"

- bokehjs/src/coffee/renderer/glyph/glyph.coffee
In some very specific cases missing beginPath leads to weird behaviours. For instance, creating a patch glyph with an empty source right after a line glyph would create a patch under all the line.
> force glyphs to always beginPath before rendering

- bokeh/charts/builder/boxplot_builder.py
- bokeh/charts/builder/tests/test_boxplot_builder.py
ref issue: #2338 
When boxplot_builder.py would check the self.outliers attribute (default=True) to see if it had to change the y_range of the figure to include outlier points as scatters, there was no check to see if there existed any outlier points. This caused min to be evaluated over an empty list in the case that there were no outliers.
I didn't add/modify any tests, let me know if/what I should do about that.
> Fix bug in outlier attribute handling

- bokehjs/src/coffee/common/plot.coffee
issues: closes #2365 
The order of "glyph" renderers wasn't being preserved due to a bug in the order that they were called (they were called by the order their unique identifier renderer.model.id versus their index renderer.id).
> Fix bug in renderer ordering

- bokeh/protocol.py
See issue #2416
I am not sure if the protocol can handle decimal places (whether we should use `obj.microsecond / 1000.` or `obj.microsecond / 1000`), but since `isinstance(obj, dt.time)` line already used the float way, I will do the same.
> Stop datetime scalar transformation throwing away microsecond 

- bokeh/server/__init__.py
- bokeh/server/start.py
Addresses #2213 
Tested implementation of a bokeh-server running with HTTPS enabled.
To run:
```
bokeh-server --https --https-certfile=/path/to/certfile.crt --https-keyfile=/path/to/keyfile.pem --script script_name.py
```
To be clear: This has not been successfully tested to work in conjunction with Session, just using --script works however...
What I didn't manage to do was to make session.py compatible with this because I don't think urllib3/requests was configured to know any certificate authorities (including the CERN certificate authority, the one which was used for testing) even after consulting the requests documentation and passing the exact same paths to the certificates. When running a test, a session was started from one computer to the same computer. One process ran the …
> Feature #2213: bokeh-server with HTTPS enabled

- bokehjs/src/coffee/renderer/glyph/patches.coffee
issues: fixes #2366 
Issue was passing `(start, end)` to index search, needs to always be `(min, max)`
> patches should work with reversed ranges

- bokehjs/src/coffee/renderer/glyph/glyph_renderer.coffee
- bokehjs/src/coffee/renderer/glyph/image_rgba.coffee
- examples/embed/spectrogram/spectrogram.coffee
- examples/embed/spectrogram/spectrogram.py
- examples/embed/spectrogram/static/js/spectrogram.js
issues: closes #2433 
This is a quick little PR to make the spectrogram usable again. This brings the CPU usage reliably down to < 50% on Chrome on OS X, making it suitable to demo at conference tables, etc. 
ping @SaraSchnadt @birdsarah I'd like to take this opportunity to also use the new `embed.components` to remove the `vplot`, `hplot` etc and just style this in a visually attractive custom jinja template. Is that something one or both of you could take a quick look at?
> Spectrogram

- examples/plotting/server/line_animate_widget.py
Including an example showing widgets together with animations in the plotting interface (using a background thread for updating data)
Related with #2452
Demo:
> add example plotting widget with play stop

- bokehjs/src/coffee/jquery-private.coffee
- bokehjs/src/coffee/main.coffee
- bokehjs/src/vendor/jquery-event-2.2/jquery.event.drag.js
This PR supersedes #2437. The real issue wasn't lack of `noConflict(true)`, but one missing `var`. `noConflict(true)` is not needed at all because jquery doesn't modify `window` in a nodejs-like module environment which browserify emulates. I will add tests in another PR, so that this one doesn't stall.
> Don't overwrite window.$

- bokeh/server/templates/oneobj.html
This hotfix enables examples/charts/server/line_animate.py (and probably others) to render.
> Use Bokeh's jQuery for server template

- bokeh/compat/mpl.py
- examples/compat/ggplot/density.py
- examples/compat/ggplot/ggplot.ipynb
- examples/compat/ggplot/line.py
- examples/compat/ggplot/step.py
- examples/compat/ggplot/xkcd_density.py
- examples/compat/mpl/lc_dashed.py
- examples/compat/mpl/lc_offsets.py
- examples/compat/mpl/listcollection.py
- examples/compat/mpl/mpl.ipynb
- examples/compat/mpl/polycollection.py
- examples/compat/mpl/sincos.py
- examples/compat/mpl/subplots.py
- examples/compat/pandas/dataframe.py
- examples/compat/pandas/pandas.ipynb
- examples/compat/pandas/series.py
- examples/compat/seaborn/boxplot.py
- examples/compat/seaborn/factorplot.py
- examples/compat/seaborn/kde.py
- examples/compat/seaborn/seaborn.ipynb
- examples/compat/seaborn/sinerror.py
- examples/compat/seaborn/stripplot.py
- examples/compat/seaborn/tsplot.py
- examples/compat/seaborn/violin.py
This change removes all the code from to_bokeh dealing with output, since everything can be accomplished with the standard bokeh.io machinery.
> clean up examples, use standard bokeh.io output

- bokeh/compat/bokeh_renderer.py
Issues: fixes issue #2621 
The mpl --> bokeh converter was indexing unconditionally into the list of MPL ticks, which would cause an error if there were no ticks on the MPL axis; this is now fixed by checking if the ticks are empty and setting the bokeh tick and label colors to `None`.
Note: this fix still doesn't handle MPL custom tick properties
> Better MPL support for empty ticks

- bokeh/models/renderers.py
- bokehjs/src/coffee/renderer/annotation/legend.coffee
- sphinx/source/docs/user_guide/source_examples/styling_legend_background.py
- sphinx/source/docs/user_guide/styling.rst
Since there's no option right now (according to docs) for moving legend outside of a plot, I think it makes sense to document how to set the legend's background transparency. If this commit is ok I'll update the docs too. Commit message:
Enable legend properties background_fill_color and background_fill_alpha to set the canvas fill property instead of inheriting the plot background color and legend.border_line_alpha, respectively.
I don't know if it was intended that border_line_alpha was to also be used as the legend fill alpha but it
doesn't seem to be documented anywhere. This change might be slightly backwards incompatible as far as legend styles go, maybe it should inherit the old properties if not set? Or maybe it should inherit a 0.0 alpha if not set?
> Add background fill properties for legend

- conda.recipe/meta.yaml
This isn't used directly by conda, but at least let reader know in the metadata that we use extra channels. This information could be later used programatically, e.g. by conda-env. Yeah, I'm working on conda-env accepting `meta.yaml` as well, which isn't that straightforward unfortunately. Note that this requires most recent conda-build, so update your root environment.
> Add channels to "extra" section in meta.yaml

- bokeh/charts/builder/timeseries_builder.py
Prompted by the scipy2015 Bokeh tutorial.  The docstring on `values` for `TimeSeries` is currently quite opaque and difficult to understand.  This change makes things a bit more verbose for the Bokeh novice who just does ``TimeSeries?`` in an IPython notebook.
> Clarify docstrings on TimeSeries

- bokehjs/src/coffee/common/plot.coffee
I thought I had a fallback in place by setting `ctx.glcanvas = false`, but this does not work if you later use `ctx.glcanvas?` :)  This fixes it and also warns about falling back.
> webgl: fall back to 2D canvas when webgl is not available.

- sphinx/source/conf.py
- sphinx/source/docs/reference/models.rst
- sphinx/source/docs/reference/models/actions.rst
- sphinx/source/docs/reference/models/axes.rst
- sphinx/source/docs/reference/models/formatters.rst
- sphinx/source/docs/reference/models/glyphs.rst
- sphinx/source/docs/reference/models/grids.rst
- sphinx/source/docs/reference/models/map_plots.rst
- sphinx/source/docs/reference/models/mappers.rst
- sphinx/source/docs/reference/models/markers.rst
- sphinx/source/docs/reference/models/plots.rst
- sphinx/source/docs/reference/models/ranges.rst
- sphinx/source/docs/reference/models/renderers.rst
- sphinx/source/docs/reference/models/sources.rst
- sphinx/source/docs/reference/models/tickers.rst
- sphinx/source/docs/reference/models/tools.rst
- sphinx/source/docs/reference/models/widget.rst
- sphinx/source/docs/reference/models/widgets.buttons.rst
- sphinx/source/docs/reference/models/widgets.dialogs.rst
- sphinx/source/docs/reference/models/widgets.groups.rst
- sphinx/source/docs/reference/models/widgets.icons.rst
- sphinx/source/docs/reference/models/widgets.inputs.rst
- sphinx/source/docs/reference/models/widgets.layouts.rst
- sphinx/source/docs/reference/models/widgets.markups.rst
- sphinx/source/docs/reference/models/widgets.panels
- sphinx/source/docs/reference/models/widgets.tables
made **models.rst** into a table of contents page and moved the contents on to individual .rst files in *reference/models*.
> Clean up models section of reference guide

- bokehjs/src/coffee/common/plot.coffee
- bokehjs/src/coffee/tool/actions/preview_save_tool.coffee
- sphinx/objects.graffle
- sphinx/source/docs/user_guide/tools.rst
When a plot view is removed corresponding previewsavetool views (and their associated dialog div's) are not getting removed, which looks a bit worrying from an html console especially if a large number of plots are being refreshed.
Also renamed SaveTool to PreviewSaveTool at a couple of points in the documentation, and updated the documentation to use `dimensions` instead of `dimension`.
> Fix PreviewSaveTool dom elements not being removed

- bokehjs/gulp/paths.coffee
- bokehjs/gulp/tasks/scripts.coffee
- bokehjs/gulp/tasks/styles.coffee
- sphinx/source/docs/dev_guide/building.rst
This will be useful when using gulp build from other build systems, like sbt. This commit also fixes the build to not use hard-coded paths. Also uses `path.join()` instead of naive path string concatenation.
> Add support for --build-dir argument to gulp build

- bokeh/_glyph_functions.py
As reported on [m.l.](https://groups.google.com/a/continuum.io/forum/?utm_medium=email&utm_source=footer#!msg/bokeh/b_4YOgI7psM/dadCL7qlJQAJ)
> fix typo on image glyph docstring

- bokehjs/src/coffee/common/plot.coffee
- sphinx/source/docs/user_guide/webgl.rst
issues: #2590 
All plots in one page share the same gl context.
> webgl: use a global gl context (no more limit of 16 webgl plots)

- bokehjs/package.json
- bokehjs/test/utils.coffee
- conda.recipe/build.sh
- conda.recipe/meta.yaml
- scripts/travis_install
- sphinx/source/docs/dev_guide/building.rst
Pretty sure we don't need jsdom. It's very bulky, causing problems with node, and we can use [cheerio](https://github.com/cheeriojs/cheerio) which seems more user friendly for a dummy DOM. See [here](https://github.com/bokeh/bokeh/pull/2666/files#diff-f32e449a1ce9901c770335f031be8e65R22) for an example of cheerio in a test
resolves issue https://github.com/bokeh/bokeh/issues/2629
> Remove jsdom

- scripts/build_upload.sh
- sphinx/README.txt
- sphinx/fabfile.py
Simplify fab script (removes duplication) and make fab deploy to take a version. Also fix the version in the build machinery.
With this change:
`fab deploy`, will deploy the current version at `/version`
`fab deploy:0.9.2`, will deploy/redeploy 0.9.2 version at `/0.9.2`
`fab deploy:test` and `fab deploy:dev`, the same as before...
`fab deploy:0.9.3,latest` should be used for the next release (latest makes the symlinks available). if you are doing manually, you can also use `fab deploy:latest=latest` and it will take the current version, but this is not recommended way to use it because you need to live in the release point (0.9.3 in this example). In addition, this is not longer made manually, it is automated...
> Fix to take version into the fab deploy script

- bokeh/models/formatters.py
Is there a recommended way to link from docstring to a code example? I feel like a code example is the easiest way to explain how to call DatetimeTickFormatter.
Closes #2413 
Note in DatetimeTickFormatter documentation:
- that only the first format string of a list seems to be used right now
- leading zeros are stripped
- %n, %t whitespace directives do nothing due to canvas limitations
> Add to DatetimeTickFormatter docstring

- bokehjs/gulp/tasks/scripts.coffee
- bokehjs/gulp/tasks/styles.coffee
- bokehjs/package.json
This solves a conflict when requirejs is preloaded on the page. Backbone
looks for `define` before looking for `module.exports`, which eats up our Backbone.
> Resolving conflict between RequireJS and Browserify with Backbone

- bokehjs/src/coffee/common/plot.coffee
Sorting was broken in PR #2393. This restores the original approach and improves naming convention, so that we explicitly see that we sort renderer views and not models.
I don't know what caused the original issue (#2365), but it doesn't seem to be renderer order dependent, see https://s3.amazonaws.com/bokeh-travis/0.9.1dev-5ce7a15-27-g25610e6/report.html (search for `sinerror`). There is a difference, but it's caused by an offset, so perhaps ranges are different.
fixes #2674
> Restore method of sorting renderers and improve naming convention

- bokeh/models/plots.py
- bokeh/models/renderers.py
- bokeh/models/tests/test_renderers.py
- bokeh/validation/warnings.py
Show warning when category labels contains `:`. See #516 for details.
Warning message contains field name in data source and first broken value.
```
ERROR:/home/abele/Devel/bokeh/bokeh/validation/check.py:W-1003 (COLON_IN_CATEGORY_LABEL): Category label contains colons: [field:a] [first_value: 1:0] [field:b] [first_value: 1:0] [renderer: GlyphRenderer, ViewModel:GlyphRenderer, ref _id: b6d6665e-70b1-4255-a9c5-baddca45e419]
```
Resolves #2614
> Add a warning for : in categorical strings

- bokehjs/src/coffee/tool/gestures/box_zoom_tool.coffee
As far as I know, there is no way to cancel out of a BoxZoomTool selection after the mouse is held down (and then there's no way to undo the zoom after the mouse is released). To get around this,
use the behavior of the zoom on other plotting tools like matplotlib: if either dimension of the range selection is <= 5 pixels, do not apply the zoom.
Happy to make this more configurable, however I do feel that this is a more natural default then the current behavior.
> Do not zoom if BoxZoomTool selects range <= 5 pixels

- bokehjs/src/coffee/common/properties.coffee
- bokehjs/test/test_common/test_properties.coffee
The `?` operator in coffeescript treats `null` and `undefined` the same, so when we want to distinguish between those values and ask only if a property exists (but allow it to have `null` value), then we need to use `_.isUndefined()` instead.
Also, this entire module should be reexamined, as there might be more cases like this.
fixes #2664
> Use _.isUndefined() instead of ? when checking for undefined

- bokehjs/src/coffee/common/canvas.coffee
- bokehjs/src/coffee/common/plot.coffee
- tests/integration/file/test_tap.py
Canteen is a performance bottleneck and should only be running in test
environment. This commit disables it globally and xfails the integration test
that expects it to be present.
This is a short-term measure while we work on a better solution to enable it
only for testing.
> Disable canteen and xfail integration test

- scripts/travis_install
To enable the test machinery. This is a temporary fix, we need to address the Jupyter update in a general way...
> Pin ipython and ipython notebook to 3.2.1

- bokehjs/src/coffee/renderer/glyph/image_url.coffee
issues: fixes #2785 
Current behavior unconditionally renders the image as part of the onload callback. This changes the render to a render_request, which uses the whole bokeh render sequence.
Question: Is it worth adding any sort of logic in the case of a 404 for the image?
> change image_url onload callback to render request

- bokeh/server/templates/bokeh.html
Fixes #2787, and by the sound of it, a lot of other open issues.
The problem boiled down to the removal of jQuery and Bootstrap JS files from the `_base.html` template, which had the unintended side effect of removing them from inclusion on the index page.
This didn't affect code using e.g. `Bokeh.$(...)` but the index page (rendered by template `bokeh.html`) relies on the third-party versions being loaded as all of that stuff seems to be driven by some combination
of those two JS files and CSS classes attached to elements.
It turns out the `_page_base.html` template already has a slot for things like this so I've shoved these includes inside the existing `extra_scripts` block from within `bokeh.html`.
> Re-enable UI behaviors on bokeh-server index page.

- bokehjs/src/coffee/mapper/linear_color_mapper.coffee
Fixes #2801, by correctly converting non-number values for the last value of the passed in palette when assigning to the last entry in the new palette.
Note that I am unclear on why extending the palette by one entry is necessary in the first place. It seems like a better solution to just make `new_palette.length` equal to `palette.length`, and delete the offending line after the loop.
> Fix bug in LinearColorMapper.build_palette.

- .travis.yml
Fixed regex to enable builds with versions containing more than on digit in the server scheme
> Fix regex to take 0.10.0 versions

- bokeh/compat/mpl_helpers.py
> Add clearer error message when scipy is not installed.

- .travis.yml
- conda.recipe/build.sh
- scripts/build_upload.sh
- scripts/deploy.sh
Using `TRAVIS_JOB_ID` to have smaller number than now... BUT also changing to a tag-based name for devel builds... so the `TRAVIS_JOB_ID` is only relevant for the testing machinery without conflicting with conda...
> Better names for the devel builds

- sphinx/source/docs/user_guide/embed.rst
> Add missing closing tag to <script> examples.

- .travis.yml
- scripts/build_upload.sh
Since anaconda dropped support for 3.3, let do the same and make our testing and building tools faster than now :wink:
> Remove 3.3 

- bokeh/__init__.py
Without this, the move of a bunch of utils into util.testing
combined with with the reference to util.testing in bokeh.__init__
meant that users would need a bunch of testing dependencies installed
just to run bokeh!
> Wrap testing import so testing libraries aren't required.

- bokeh/models/formatters.py
- bokehjs/src/coffee/ticking/datetime_tick_formatter.coffee
Expands %f string format directive to 6-digit microsecond string
in strftime via regex. Python's built-in datetime library supports
the %f directive in its version of strftime. I believe but have not
checked that this should be accurate to the hundreds of nanoseconds
precision. Removed the previous millisecond / microsecond functions,
as they can't be supplied via python.
Updating docstring to mention %f and %N.
Closes #2332
Change-Id: Ia85051c6d99c1d52349e61869dddcfa390adec32
> Microsecond support in DatetimeTickFormatter

- bokehjs/src/coffee/common/mathutils.coffee
- bokehjs/src/coffee/renderer/glyph/glyph.coffee
Previously `Math.max.apply(null, array)` idiom was used to compute the maximum value of an array. This was prone to the maximum call stack limitation, not allowing bokehjs to render more than a few hundred thousand points.
> Use custom function to compute the maximum value of a large array

- bokehjs/src/coffee/renderer/glyph/glyph.coffee
issues: closes #2945 
Problem was in the calculation of the data-to-screen transformation. A vector of size ~1 was used, which on a scale of 1e15 gives rise to significant roundoff errors. Changed to use a vector size that depends on the transform itself.
> Fix #2945: webgl fails for large numbers

- sphinx/source/docs/includes/line_props.txt
issues: fixes #2954
The current line_dash prop in user_guide/styling.rst only mentions an array of ints as an acceptable argument. This PR expands that description to include the string arguments ('solid', 'dashed') as well as a string that matches a specific regex.
> Added standard string props and note of regex match to line_props docs

- setup.py
The copy was not being called when doing `python setup.py develop` and
so tests were failing locally, this fixes it - thanks to @bryevdv for the fix
> Move location of LICENSE copy in setup.py

- bokehjs/src/coffee/renderer/annotation/span.coffee
There's was a debugger statement left in the render call of span.coffee. This is a hotfix to remove it.
> remove leftover debugger statement from render loop

- sphinx/source/index.rst
Change NumFOCUS contact email from info@pydata.org (bounces back) to info@numfocus.org
> Update NumFOCUS contact email in docs

- bokehjs/src/coffee/widget/data_table.coffee
#2904 - fixed a bug when a table was sorted by a column other than the index then edited.
supersede #2906 
This changes the semantics of getItem/setItem to use an offset into the data array, while getField/setField still take an item index.  The index and the offset will be the same for a data array that is sorted by the index field and has not been filtered.
> #2904 - fixed a bug editing a sorted or filtered datatable

- bokeh/models/widgets/tables.py
- bokehjs/src/coffee/widget/cell_formatters.coffee
The goal here is to add support for a flexible cell formatter in DataTables.  More specific goals:
1. Support for HTML in the cells.
1. Support column sorting based on the value of the cell, not the resulting HTML.
1. Templates can reference values from other columns within the row.
This PR adds the `HTMLTemplateFormatter` class.  This object takes a `template` argument which follows the template style of Underscore.js.  http://underscorejs.org/#template
Some examples:
```Python
HTMLTemplateFormatter(template='<code><%= value %></code>')
HTMLTemplateFormatter(template='<a href="https:/www.google.com/search?q=<%= manufacturer %>+<%= model %>" target="_blank"><%= value %></a>')
```
This is related to issue #2923 
Any feedback would be greatly appreciated.
thanks,
Dennis
> support for flexible datatable formatters

- README.md
- bokeh/models/tests/test_annotations.py
- bokeh/models/tests/test_glyphs.py
- bokeh/themes/default.yaml
issues: fixes #3094 
The default text_font_size props in default.yaml were set as deprecated string types. This PR updates them to single element lists, e.g. ``['20pt']``
> Change text_font_size prop defaults to list-style from deprecated str

- sphinx/source/docs/dev_guide/building.rst
It seems that I cannot run the tests locally with these two ``addopts``, even though the packages listed as dependencies [1] are installed. 
```
bsipocz@tegla2:~/munka/devel/bokeh$ py.test -m 'not (js or examples)'
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --driver=Firefox --sensitive-url=None
```
[1] http://bokeh.pydata.org/en/latest/docs/dev_guide/building.html#dependencies
> testing addopts are note recognized with listed dependencies installed

- bokeh/charts/attributes.py
- bokeh/models/widgets/icons.py
- bokeh/properties.py
- bokeh/tests/test_properties.py
There's one bugfix (using the wrong cache from base classes), one optimization (always cache the merged __properties__ from base classes), one new warning (when a subclass tries to override a base class property, which seems to be a bug in the two cases TODO-commented here), and a refactor to decrease LOC by sharing cache logic. Also, rename accumulate_from_subclasses to be accurate.
> Property cache cleanups

- bokeh/plot_object.py
- bokeh/tests/test_objects.py
These are like vm_serialize but don't expose the ugly implementation
detail of our magic JSON encoder that "fixes" certain types into
plain JSON types.
> Add PlotObject.to_json and to_json_string

- bokeh/models/sources.py
Not all DataSources will have columns in the future. In particular, this is setting up creating a new GeoJSONDataSource.
I have tested this on the AjaxDataSource examples in plotting and they still work but nothing else.
Some questions / notes:
1) I'm thinking selected property should stay on DataSource, is that correct? I think it's ok if DataSources have to implement some way of populating that. If we don't then it will be hard to have a common infrastructure for handling selections. ping @bryevdv 
2) remove ServerDataSource (made a note on #3140)
3) Worth noting that the class hierarchy is DataSource -> RemoteDataSource -> AjaxDataSource in python, but on JS side it's ColumnDataSource -> RemoteDataSource -> AjaxDataSource. Don't think we need to change this now (esp as I'm about to do …
> Move columns out of DataSource into ColumnDataSource.

- bokeh/document.py
- bokeh/plot_object.py
- bokeh/tests/test_document.py
- bokeh/validation/warnings.py
- bokehjs/src/coffee/common/document.coffee
- bokehjs/src/coffee/common/has_properties.coffee
- bokehjs/test/test_common/test_document.coffee
This is a request from @birdsarah we talked about yesterday. Some motivating examples for this.
* @birdsarah wants to allow one glyph to pull from multiple data sources, so an idea is to allow them to refer to fields prefixed by a model name. It could look like `MyGlyph(x="name1:x", fill_color="name2:color")` for example (syntax TBD, colon-separator is one idea).
* @fpliger was talking about a way for an app directory to have data files that are auto-loaded, say for example you have `foo.xls` or `foo.csv` in your app directory, we could have a spelling handler which would automatically load that into a data source model and name it `foo` or `data_source_foo` or whatever. Then you could refer to it from syntax like @birdsarah's or you could `curdoc().get_model_by_name('foo')` in the script …
> Add Document.get_model_by_name

- bokeh/client/connection.py
- bokeh/server/connection.py
- bokeh/server/protocol/message.py
- bokeh/server/session.py
- bokeh/server/views/ws.py
- bokeh/tests/test_client_server.py
This is supposed to close #3133 
TLDR fixes here are:
* avoid backlog by waiting for writes and periodic callbacks to finish before queueing up more
* take the session._lock when we run periodic and timeout callbacks
The avoid-write-backlog thing only "really" works with Tornado 4.3, which isn't in conda right now - so I'm testing here with compat shims that simulate 4.3 without actually waiting on the writes.
I guess that's better than hard-requiring 4.3, though with 4.3 things should work better on a loaded server.
> Async writes and session lock fixes

- bokehjs/src/less/main.less
Fixes #3167 (at least the blue bit - the tools are working fine for me)
> Remove blue :focus styling from chrome

- bokehjs/gulp/tasks/build.coffee
- sphinx/source/docs/dev_guide/building.rst
Add `gulp dev-build`, an equivalent to `gulp scripts:build styles:build` (no minification step).
> Add gulp dev-build task for faster development

- bokeh/models/widgets/tables.py
- bokehjs/src/coffee/widget/data_table.coffee
Partially closes #2732
On a selection change, inform slickgrid to scroll to the [row
before the] first row of the selected values in the ColumnDataSource.
If the slickgrid table does not have enough rows to have a vertical scrollbar,
then this will do nothing, i.e. retain the current behavior.
Happy to make this more configurable, however I do feel that this is a more natural default then the current behavior.
> Scroll to first row of selection in DataTable

- sphinx/source/docs/quickstart.rst
The example in the section "Linked panning and brushing"
in the Quickstart documentation appear to be missing a call to
bokeh.plotting.output_file. Without this call, running the example
produces no output.
> Add missing call to output_file in quickstart.rst

- sphinx/source/docs/user_guide/source_examples/plotting_ovals.py
- sphinx/source/docs/user_guide/source_examples/plotting_rectangles.py
- sphinx/source/docs/user_guide/source_examples/plotting_rectangles_rotated.py
Examples in subsection "Rectangles and Ovals" lack
calls to output_file
> Add more missing calls to output_file in plotting

- bokehjs/src/coffee/common/has_properties.coffee
- bokehjs/src/coffee/renderer/glyph/glyph.coffee
- bokehjs/test/test_common/test_document.coffee
This is pulling some work out of #3099 in order to shrink that PR. We will probably close #3099 after pulling everything out but for now #3099 is useful for coordinating the remaining tasks to sync defaults.
> Add tags default in coffeescript

- bokeh/models/annotations.py
- bokeh/models/glyphs.py
- bokeh/models/markers.py
- bokeh/models/tests/test_glyphs.py
(continuing to break up #3099)
This reverts to Bokeh 0.10 behavior.
In Bokeh 0.10, the CoffeeScript default was undefined
(or 0, for some angles). After the tornado merge, we were sending
the field name default from Python when we did not ever use that
name before. In 0.10, we'd never send the default so CoffeeScript
never saw it.
The field name doesn't seem like a good default because in general
it ends up being very magical and unclear; if I type
`Line(source=source)` then it magically uses the `x` and `y` columns,
but if I later rename those columns, or if I'm adapting an example
and my columns aren't named that, it gets confusing what's going on.
Requiring the field name to be written out is better for "programming
by example."
If we do want to default to the field name, we should …
> Do not default NumberSpec/AngleSpec/DistanceSpec to field name

- .gitignore
- bokehjs/gulp/paths.coffee
- bokehjs/gulp/tasks/generate_defaults.py
- bokehjs/gulp/tasks/scripts.coffee
- bokehjs/src/coffee/common/base.coffee
- bokehjs/src/coffee/tool/inspectors/crosshair_tool.coffee
- bokehjs/src/coffee/widget/main.coffee
- bokehjs/test/test_common/index.coffee
- bokehjs/test/test_common/test_defaults.coffee
- conda.recipe/meta.yaml
- setup.py
The fix to CrosshairTool is in here because it breaks the test code (when it tries to use display_defaults
on an object that isn't a HasParent)
> Add skipped test to compare Python and Coffee defaults

- bokeh/charts/attributes.py
Removes pandas deprecation when using some charts due to `df.sort` rename to `df. sort_values`
> Remove pandas deprecation

- .travis.yml
issues: ref #3236 
ping @damianavila 
This results in the following build matrix:
This a little different from the changes suggested in the referenced issue. Basically:
* Python+JS unit tests everywhere, but together to save on install times. (The tests suites themselves are both very fast compared to install time)
* Integration tests only once, on Py 3.4 
* flake_docs only once, on py2.7 (since that is where they are deployed from)
* examples tests everywhere (except disabled for py3.5 temporarily for now)
***NOTE***: the 3.5 examples tests are unfortunately disabled (for now) because we simply cannot afford three "long" tests with only five workers, with the volume of PRs we have. It results in an immediate logjam.  Looking into adding resources.
> try some other build matrix configurations

- bokeh/model.py
- bokeh/tests/test_objects.py
Checking 500 large plots is not testing more than checking 10,
and this test took 1.5 seconds (out of 5.5 seconds for the entire
test suite).
> Shrink test_objects.py::TestCollectModels::test_references_large

- bokeh/sphinxext/bokeh_github.py
- sphinx/source/docs/gallery.rst
issues: ref #3186 
And update the "examples" link in the main gallery to use it to point to the correct checkout for the actual docs version being viewed.
> add sphinx directive to create versioned links into the repo

- bokeh/__init__.py
- bokeh/charts/chart.py
- bokeh/charts/chart_options.py
- bokeh/compat/bokeh_renderer.py
- bokeh/deprecate.py
- bokeh/enums.py
- bokeh/models/annotations.py
- bokeh/models/tests/test_annotations.py
- bokeh/models/tests/test_glyphs.py
- bokehjs/src/coffee/renderer/annotation/legend.coffee
- examples/embed/slideshow/app_reveal.py
- examples/glyphs/legends.py
- examples/glyphs/population_server.py
- examples/glyphs/taylor_server.py
- examples/plotting/file/histogram.py
- sphinx/source/docs/quickstart.rst
- sphinx/source/docs/user_guide/source_examples/styling_legend_background.py
- sphinx/source/docs/user_guide/source_examples/styling_legend_location.py
- sphinx/source/docs/user_guide/styling.rst
Now we have total of ten locations: four corners, five centered and absolute locations. See `glyphs/legends`. This PR won't implement automatic location at this point. `Legend.orientation` is deprecated, but `@deprecated` decorator doesn't seem to work.
TODO:
> Rename Legend.{orientation->location} and implement more locations

- bokehjs/src/coffee/common/client.coffee
Also improve the log messages about connection status.
We were doing a _schedule_reconnect(0) that never did anything
and then all the actual code did a manual connect() call.
This resulted in a bogus "connection lost" message every time
on startup in the JS console, which was confusing.
> Don't _schedule_reconnect on ClientConnection creation

- bokeh/command/subcommands/serve.py
`--keep-alive` option was being silently ignored.
> Use the correct name for the Server(keep_alive_milliseconds) kwarg

- examples/plotting/file/custom_datetime_axis.py
issues: fixes #3193
By defining a custom TickFormatter model, we are able to remove the weekend/holiday gaps in the candlestick financial chart. Dates are formatted into an array of Strings, e.g. ['Sep 01', 'Sep 02', ...], which is passed to the custom ticker as a property and then rendered on the axis.
The downside to this approach is that we lose the dynamic nature of Datetimei. This can be overcome by making DateGapTickFormatter receive more than one list of Strings, each one representing a different Date format, e.g. List 1 = ['Sep 01', 'Sep 02', ...]; List 2 = ['Sep', 'Sep', ... 'Oct', ...] and so on. This remains as a suggestion only and is not implemented by this commit.
> New example - custom axis tickformatter

- bokehjs/test/test_common/test_defaults.coffee
Instead of commenting out the assertion entirely, we can require
that the problem doesn't get any worse.
> Test that coffee/python sync issues are not increasing

- bokehjs/src/coffee/common/tool_manager.coffee
Fixes a bug that caused the toolbar to be unresponsive on streaming updates. 
@birdsarah @mattpap @brendancol any comments welcome, I am sure this is a simplistic fix but it does seem to be an improvement.
> hotfix to only render toolbar once

- bokehjs/src/coffee/common/has_properties.coffee
- bokehjs/test/test_common/test_document.coffee
This should fix the voluminous errors reported by the `stocks` app example when it replaces the Histogram charts, e.g.
This is from a patch from @havocp
> fix problem where replacing children did not update document

- bokeh/document.py
- bokeh/model.py
- bokeh/properties.py
- bokeh/server/protocol/messages/tests/test_patch_doc.py
- bokeh/tests/test_document.py
- bokeh/tests/test_properties.py
TLDR the client in examples/plotting/server/glyphs.py ended up with `inner_radius = { value: 10 }` instead of `inner_radius = { value: 10, units: 'screen' }` and now it keeps the units.
This fixes a problem with examples/plotting/server/glyphs.py where
we'd have AnnularWedge.inner_radius as a single value, we'd send it
to the client as a dict, at some point the client sent it back to us
as a dict, we then stripped the units out and emitted a ModelChangedEvent
as a dict sans units (because ModelChangedEvent contains the new regular
value, not the new serializable_value()). This new units-less dict was
then sent to the client causing the client to use default units instead
of the originally-provided units.
To fix this we need the serializable_value() in ModelChangedEvent.
We also need to be …
> When we customize property serialization, also customize deserialization

- bokeh/command/bootstrap.py
- bokeh/command/subcommand.py
- bokeh/command/subcommands/__init__.py
- bokeh/command/subcommands/file_output.py
- bokeh/command/subcommands/html.py
- bokeh/command/subcommands/json.py
- bokeh/command/subcommands/tests/__init__.py
- bokeh/command/subcommands/tests/test_html.py
- bokeh/command/subcommands/tests/test_json.py
- bokeh/command/subcommands/tests/test_subcommands_package.py
- bokeh/command/tests/test_bootstrap.py
The main point here is to keep these consistent from the perspective of someone using the bokeh command.
But also we're sharing implementation so that adding any new file output formats should be straightforward.
(To support a binary output format like png, some minor tweaks to the `FileOutputSubcommand` base class will be needed, since it assumes text output right now.)
> Make `bokeh json` and `bokeh html` work in a similar way

- bokeh/client/connection.py
- bokeh/client/session.py
- bokeh/embed.py
- bokeh/io.py
- bokeh/resources.py
- bokeh/server/views/doc_handler.py
- bokeh/server/views/ws.py
- bokeh/settings.py
- bokeh/state.py
- bokeh/tests/test_client_server.py
- bokeh/tests/test_io.py
- bokeh/tests/test_state.py
- bokeh/util/session_id.py
- bokeh/util/tests/test_session_id.py
- examples/embed/animated.py
- examples/embed/widget.py
This is intended to fix #3324 and fix #3171 and also fix output_server to have an app_path which is in the wiki (https://github.com/bokeh/bokeh/wiki/Issue-list:-new-Bokeh-server ) but not an open issue.
Signed sessions are a partial step toward https://github.com/bokeh/bokeh/issues/3287 but there's a missing piece (doc_handler.py will still autogenerate an ID, there has to be a way to disable that).
> Signed session IDs and consistent session/url/app_path params

- bokeh/properties.py
This fixes an error in `bokeh server examples/app/sliders.py` for example.
```
File "/home/hp/checkout/bokeh/bokeh/properties.py", line 1523, in set_from_json
if 'value' in json:
TypeError: argument of type 'int' is not iterable
```
> DataSpecProperty.set_from_json: check whether json is a dict before assuming

- bokeh/resources.py
- bokeh/server/tornado.py
- bokeh/server/views/static_handler.py
- bokeh/tests/test_resources.py
This allows an nginx configuration to set aggressive caching
headers, as described at http://www.tornadoweb.org/en/stable/guide/running.html
This isn't especially important in the short term but I was reading the docs and saw it and it was easier to just do it than file an issue.
The point of this is to avoid using up server CPU serving static assets.
> Add ?v=CONTENTHASH to static paths served by the server

- bokehjs/src/coffee/source/column_data_source.coffee
This was causing problems with `us_marriages_divorce` it seemed especially highlighted by line inspections. Some day might be nice to offer serializations of inspections as an option but this keeps the status quo working for now.
> inspected is a non-serializable attr at least for now

- bokeh/client/connection.py
- bokeh/server/protocol/__init__.py
- bokeh/server/protocol/message.py
- bokeh/server/views/ws.py
- bokeh/tests/test_client_server.py
Keeps us from interleaving websocket frames that belong to distinct messages.
> Add connection write_lock

- examples/embed/README.md
- examples/embed/animated.py
- examples/embed/embed_multiple.py
- examples/embed/embed_multiple_responsive.py
- examples/embed/embed_responsive_width_height.py
- examples/embed/simple/README.md
- examples/embed/simple/simple.py
- examples/embed/slideshow/slideshow.py
- examples/embed/slideshow/templates/app_plot.html
- examples/embed/spectrogram/README.md
- examples/embed/widget.py
This PR cleans up, normalizes and verifies that (almost) all the example in `examples/embed` work. 
The one current exception is the slideshow. There appears to be something about the way reveal.js "renders everything" but only "shows one part at a time" that confuses the Bokeh server's tab-per-session (or something) the plots/widgets show up, but do not animate/respond. ping @havocp @damianavila if there is some alternate way to organize things that can work, I'd love to keep it (maybe simplify the examples a bit) otherwise we should just remove the example. 
Note, this is based off #3330 so has some extra junk in the diff
> Cleanup embed examples

- bokeh/core/properties.py
- bokeh/core/tests/test_properties.py
- bokeh/server/protocol/messages/patch_doc.py
- bokeh/tests/test_client_server.py
One issue created by this was to defeat patch-doc should_suppress_on_change,
since we compared two dicts and one of them had the units accidentally
stripped out.
> Fix change suppression on units-spec values

- bokehjs/gulp/tasks/scripts.coffee
- bokehjs/src/coffee/common/base.coffee
- bokehjs/src/coffee/main.coffee
- bokehjs/src/js/plugin-prelude.js
- bokehjs/src/js/prelude.js
- examples/glyphs/custom.py
This allows bokeh to know about plugins' modules, to allow custom models to require such modules. Previously this resulted in module not found exception. The new approach is to register plugins' modules in the main bundle (so there is one set of modules, instead of 1 + n), resulting in one `require()` being used by all involved parties (main bundle, plugins and custom models).
fixes #3339
> Register modules from plugins in the main bokeh bundle

- bokeh/client/session.py
- bokeh/server/session.py
- bokeh/tests/test_client_server.py
- bokeh/util/tornado.py
I was hoping this would fix the test_lots_of_concurrent test taking forever, but I guess that's due to message backlog not periodic callback pileup.
Anyway, what this does: ClientSession now uses _AsyncPeriodic from the server, which means it shouldn't "pile up" async periodic callbacks that take longer than the period.
Also redid _AsyncPeriodic to work in a simpler way with gen.sleep, avoiding the math that was there before.
> Periodic callback refactor

- bokeh/models/widgets/inputs.py
issues: fixes #2448
Add callback attribute to TextInput child class (override from InputWidget parent), in order to specify when the callback is executed.
> Docfix/2448 TextInput widget callback description

- bokehjs/src/coffee/common/document.coffee
only update models from references in a patch-doc message when it is
required, otherwise existing models can get erroneously overwritten
Note: branch against `movies_example` because that demo most easily showed the problem.
> fix refefences clobbering

- bokehjs/src/coffee/renderer/annotation/box_annotation.coffee
This restores the box annotation functionality, which was broken by a typo
> add missing logical connective

- bokeh/client/connection.py
- bokeh/client/session.py
- bokeh/document.py
- bokeh/server/session.py
- bokeh/tests/test_client_server.py
- bokeh/tests/test_document.py
- bokeh/util/tests/test_tornado.py
- bokeh/util/tornado.py
This is sort of overkill to fix the two bugs, but it also lays the groundwork for the lifecycle hooks PR because `_CallbackGroup` could be used in that PR for callbacks that don't go with a Document.
Also `_DocumentCallbackGroup.remove_all_callbacks()` will be used in ServerSession in that PR to remove callbacks when a session expires.
But, other than being kind of overkill without seeing the next PR, this PR does stand alone I hope - it fixes a couple of bugs, removes some duplicate code, and adds `Document.add_next_tick_callback`.
> Refactor document callbacks

- bokehjs/src/coffee/renderer/tile/tile_renderer.coffee
This was a bug that showed itself when defaults were no longer sent from python.  `plot.get('outline_line_width').value` now changed to `plot.get('outline_line_width')`
> removed .value when retrieving outline_line_width for tile attribution

- bokeh/charts/chart.py
- bokeh/core/properties.py
- bokeh/document.py
Defaults should now all be in sync. We will only send theme values and user-set values to BokehJS.
Let's see how Travis, the report, and some hand testing look.
> turn off sending defaults to BokehJS

- bokeh/resources.py
Raises ResourceWarning in python 3.4.
> Fix unclosed file in resources _inline()

- bokehjs/src/coffee/renderer/tile/tile_renderer.coffee
bug I discovered while making example.  This logic will probably be replace in the future but at least it won't throw error.  Tiles are now not request beyond min / max zoom.
> fix error in snap_back. Now will not request tiles outside of min/max zoom

- bokeh/models/plots.py
- bokehjs/src/coffee/common/layout_box.coffee
- bokehjs/src/coffee/common/plot.coffee
Requires the following changes:
* modify LayoutBox so the solver can be set post-initialization
* in Plot, set 'title_panel' name on the LayoutBox, then
use the name to find an existing LayoutBox if any
Another approach could be to create the layout box on the server
always and then set the solver on it in Plot, but this way is
less of a change perhaps so could be safer during a release
freeze.
> Make Plot use the title_panel from the server if one is provided

- bokehjs/src/coffee/common/document.coffee
- bokehjs/src/coffee/common/has_properties.coffee
- bokehjs/test/test_common/test_document.coffee
Fixes #3479 
This is not the safest patch on earth, but without it we send a ton of extra events on application load, which is a performance problem and also makes it pretty hard to debug anything else that's going wrong on application load.
Careful review/test probably a good idea...
> Fix extra events on initial application load

- bokehjs/src/coffee/common/has_properties.coffee
- bokehjs/test/test_common/test_document.coffee
The issue here was that HasProperties._value_record_references
ignored its 'recurse' flag which led to bogus behavior when
_tell_document_about_change tried to do its attach_document
and detach_document.
This fixes #3361, where for Plot.renderers in particular, we
thought the new Span was already in the document, because
_value_record_references was messed up and recursed too far.
In the long run, a better fix would be to port the way we do
_all_models in Python (constantly reconstructing it from scratch),
because the way we do it in Coffee cannot avoid leaks when there
are cycles. However, with this fix we avoid failing to include
models in _all_models that should be there. In memory management
terms we're replacing an early free (memory corruption) with
a leak.
The test case added here …
> Fix tracking of _all_models with list-of-instance properties

- sphinx/source/docs/dev_guide/setup.rst
Update dev_guide/setup.rst to match dependencies required (and tested for) in scripts/devdeps.py
Note: I removed pdiff and boto from the listed deps in setup.rst because they're only used by Travis CI and not the developer. They're not tested for in devdeps.py because they're not required to develop/test locally. Removing them may be a point of debate.
> Update dev_guide/setup.rst to align develop deps in line with scripts/devdeps.py

- bokehjs/src/coffee/common/selection_manager.coffee
The problem was `clear` calling a method to set the indices that used to exist, but no longer exists. Obviously a test would have helped here. Adding more unit tests for BokehJS after `0.11` a high priority. 
This PR also removes the completely unused `set_selection` method. Proof:
```
bryan@0199-bryanv (git:master) ~/work/bokeh/bokehjs/src/coffee $ grin set_selection
bryan@0199-bryanv (git:master) ~/work/bokeh/bokehjs/src/coffee $ 
```
Tested with standalone and server apps for correct behaviour.
> fix selection clear calling nonexistent method

- bokehjs/src/coffee/common/selection_manager.coffee
- bokehjs/src/coffee/renderer/glyph/glyph_renderer.coffee
issues: fixes #3467 
@birdsarah this was a pretty simple one: we added a `request_render` on `inspect` events. But the code that triggered `inspect` events was mistakenly looking for `null` to indicate no hits, not an "empty" selection object. So it was triggering every hit-test, even if there was no result. 
There's a slight complication in that we do need to trigger the *first* empty inspection, so e.g., that hover tools turn off when they are supposed to. 
This stops all the over-rendering. I will say it did not improved the `texas.py` hover as much as I thought maybe it should. There is still a slight lag, but maybe there always was, and I am just imagining that it was better. In any case, I do think this should be merged. I tested it behaving correctly with every hover and hover …
> fix 'over-render' due to hover inspections

- bokehjs/src/coffee/common/selection_manager.coffee
issues: closes #3467 
With this tweak, hover tool also behaves as expected when there are multiple tools configured on different renderers.
> need to check if last selection was empty on a per renderer basis

- bokeh/server/tests/test_tornado.py
- bokeh/server/tornado.py
- bokeh/server/views/ws.py
Reference: https://github.com/request/request/issues/515
Many programs strip the port from the host header when it is 80, and this breaks our whitelist checking. This prevents the server from being run behind a proxy on port 80.
> accept implicit port 80 on whitelist

- bokeh/server/tests/utils.py
- bokeh/tests/test_client_server.py
Wanting to be sure that the HTTP stack doesn't break anything.
Looks good.
Not urgent to merge this for 0.11, the thing I wanted to do for 0.11 was run the tests, which will happen just by submitting the PR.
Should be harmless to merge whenever though (only affects tests).
> Add some more Host and Origin tests

- bokeh/core/_templates/autoload_js.js
- bokeh/core/_templates/autoload_tag.html
- bokeh/core/_templates/notebook_div.html
- bokeh/core/_templates/notebook_load.html
- bokeh/embed.py
- bokeh/resources.py
- bokeh/server/views/autoload_js_handler.py
- bokeh/tests/test_embed.py
- bokeh/util/notebook.py
- bokehjs/src/coffee/common/embed.coffee
- bokehjs/src/js/plugin-prelude.js
- examples/embed/custom_server/color_scatter_server.py
- sphinx/source/docs/user_guide/embed.rst
This makes autoload support raw javascrip, te.g. logging through resources, not some custom code. Added an example showing that `autoload_static()` works (`embed/custom_server`). Notebook now uses autoload for initialization bokeh and rendering plots. Fixed `plugin-prelude.js` and `sever-dev`. There is some unfortunate code duplication around `AUTOLOAD_JS` template, but that can be improved in a follow-up PR. ~~Tests may fail at this point~~.
fixes #3500
> Support raw javascript in autoload and use autoload in the notebook

- examples/plotting/file/glyphs.py
- examples/plotting/notebook/glyphs.ipynb
- scripts/interactive_tester.py
- sphinx/source/docs/releases/0.11.0.rst
issues: related to #3543
* Mention that annulus glyph is broken on IE
* Fix typo in titles
* Also snuck in a fix for a reference to `bokeh-server`
> Report that annulus is broken in release notes (+ typo fixes)

- bokeh/core/_templates/doc_js.js
- bokeh/embed.py
- bokeh/server/views/autoload_js_handler.py
Not waiting breaks many `embed.components` examples.
> HOTFIX: don't exec bokeh embed until dom ready

- examples/plotting/notebook/scatter.ipynb
There was one plot in this example that specified a `nonselection_fill_color`, but did not allow a way to make a selection. I assumed the intention was to demonstrate how scatter glyphs behave under a selection, so I added the lasso tool.
> Small fix in scatter.ipynb - allow making selection

- bokeh/server/tests/test_tornado.py
- bokeh/server/tornado.py
We might want this on the demo server, though we should wait to merge to master until post-release.
Essentially it adds session counts by app, and unused session counts.
> Log more detailed stats information from the server

- setup.cfg
When a new release of selenium comes out this should be fixed, this is a
workaround in the meant time. For more information see:
https://github.com/davehunt/pytest-selenium/issues/48
> Latest versions of firefox have a heavy to load startpage that we don't need

- examples/glyphs/image_url.py
- tests/glyphs/ImageURL.py
issues: fixes #3569 
Docfix - update url argument of ImageURL examples to use new bokeh logo static location.
> Updated ImageURL url path to new image static url

- bokeh/sampledata/elements.csv
I added Ununoctium (118), renamed Ununquadium to Flerovium, renamed
Ununhexium to Livermorium, and added the estimated atomic weight for
element 117.
Fixes #3599.
> Update periodic table sample data

- examples/glyphs/glyphs.py
Potential solution for broken bokeh master:
The url arg in the ImageURL glyph test example in examples/glyphs/glyph.py is wrong and gives a 404 warn. It's unclear why the tests seem to pass for py27 and not py34 though
I'm unable to reproduce the failed test w/ py34 locally, so if the hotfix doesn't work I'll add a print statement on the stdout of glyph.py to see what response TravisCI is getting that I'm not.
> Fix bad path to bokeh logo static

- bokeh/resources.py
This won't allow `BOKEH_RESOURCES=INLINE` anymore.
> Use self.mode instead of mode in BaseResources.__init__()

- bokehjs/src/coffee/common/plot.coffee
issues: fixes #3468
The problem described in #3468 was related to a resize event being handled before the plot was fully initialized. This is why there was a `this.el.parentNode is null` error in the console, causing the initial sizing to fail. The solution is to test for this situation and schedule a new event in a future event-loop iteration.
> Improve initialization of plot size

- bokehjs/src/coffee/common/plot.coffee
- examples/plotting/file/scatter10k.py
issues: fixes #3605
Previously, we blitted without interpolation. Apparently this causes problems for firefox. Now we do it with interpolation, but align the image such that the pixel correspondence is one-to-one, and the resulting visualization is crisp.
> Improve how webgl canvas is blitted into the visible canvas

- bokeh/command/subcommands/serve.py
- bokeh/command/subcommands/tests/test_serve.py
- bokeh/server/server.py
- bokeh/server/tests/test_server.py
- sphinx/source/docs/user_guide/server.rst
This PR adds support and docs for a `--use-xheaders` flag for `bokeh serve`. This is needed to run a Bokeh server behind an SSL-terminated proxy.
> Support using X-headers 

- examples/embed/embed_multiple.py
issue: fixes #3705 
Remove inline style of div tag that overrides bokeh button icon style. Plots are now vertically aligned (as consecutive divs) and not horizontal. It's be possible to wrap them in an HBox, but that seems to detract from demonstration of embedding/jinja templating of multiple components.
> Remove inline style from embed_multiple.py

- bokeh/application/handlers/code_runner.py
- bokeh/document.py
- bokeh/embed.py
- bokeh/io.py
- bokeh/tests/test_embed.py
This restores support for custom ID generators and simple IDs in particular, which is useful for debugging.
> Use make_id() instead of str(uuid.uuid4())

- bokehjs/gulp/tasks/scripts.coffee
> Don't generate source maps for *.min.js files

- bokehjs/src/coffee/renderer/guide/axis.coffee
This resolves #3626 based on the research outlined in the issue. In short, there were two methods of supporting swapping axes out after the chart has been rendered. This approach is probably the least desired option because we should have a simple method to add axes as, as needed, but it is the most simple. Currently, the only alternative approach to this problem is to recreate the entire plot.
Whether more work will be done or not to fix this issue upstream in the rendering logic, this simple change should be there, otherwise layout constraints will be solved for non visible axes, which kiwi will error out on when arguments provided are 0, -0.
> Fix layout update for non-visible axes

- conda.recipe/meta.yaml
- setup.cfg
Latest 1.1 is on bokeh's conda package (along with other up-to-date related packages)
> Remove version pin from pytest-selenium

- bokeh/models/__init__.py
- bokeh/models/widgets/__init__.py
- bokeh/models/widgets/layouts.py
- examples/app/movies/main.py
- examples/app/sliders.py
- examples/app/stocks/main.py
supersedes #3756 
Todo:
deprecate `bokeh.models.widgets.layouts` import path
> Fix bad layouts imports in examples

- bokeh/core/json_encoder.py
- bokeh/core/tests/test_json_encoder.py
- bokeh/tests/test_objects.py
- bokehjs/gulp/tasks/defaults.coffee
- bokehjs/gulp/tasks/generate_defaults.py
This reduces size of choropleth.html by ~10% (1MB).
> Don't use spaces in JSON separators to reduce data size

- bokeh/charts/builders/bar_builder.py
- bokeh/charts/builders/tests/test_bar_builder.py
- bokeh/charts/glyphs.py
Fixes: issue #2935
This fixes two issues:
1) an issue where the order of grouped elements wasn't being maintained during the grouping operations
2) an issue where the stack/group flags weren't getting set correctly within the bar builder
This also adds a test to check the final order of the glyphs as they would be rendered.
> Fix issue with bar chart grouping/stacking order

- bokeh/core/_templates/autoload_js.js
- bokeh/core/_templates/notebook_load.html
- bokeh/util/notebook.py
- bokehjs/src/less/continuum.less
Publishing separately as `application/json` allows to use a different code path in ipython notebook, which doesn't require jquery (just a simple eval) and thus allows to load bokehjs without issues. I also added simple notification when bokehjs is actually loaded and improved styling of bokehjs' notebook banner.
> Publish bokehjs separately in a notebook to avoid parsing issues in jquery

- sphinx/source/docs/user_guide/quickstart.rst
fix quotes around links to examples notebooks
> fix quotes around links to examples notebooks

- bokeh/application/handlers/notebook.py
Use import_required for nbformat and nbconvert and move the import
into __init__ so that not having Jupyter Notebook installed doesn't
cause errors when attempting unrelated uses of Bokeh.
> use import_required for nbformat and nbconvert

- sphinx/source/conf.py
0.11.1 is the latest 0.11 release, so we don't need to reference it in the
dropdown (following the previous pattern)
> Remove 0.11.0 versions from ALL_VERSIONS tag which controls dropdown

- bokeh/core/compat/bokeh_renderer.py
Fix issues #3774, #3130, #2277
Issue 2277 was already working (as commented there). This fix took care of that.
[notebook](http://nbviewer.jupyter.org/github/chbrandt/pynotes/blob/4c8eab1508105ddaf32d24178cd10634d65cebaf/issues/bokeh/boxplot_report.ipynb) updated with examples from those issues.
> Fix boxplot shifting when using 'mpl' from matplotlib and seaborn.

- bokehjs/src/coffee/models/widgets/multiselect.coffee
Remove the {‘silent’: true} option in the MultiSelect coffee script to
debug issue #3871 in the Bokeh master. It seems to have fixed the issue.
> Issue #3871: MultiSelect - Remove 'silent': true

- sphinx/source/docs/includes/colors.txt
issues: fixes #3891 
This PR removes the mention of hexadecimal RGBA strings from the list of supported color formats.
Per this thread: http://stackoverflow.com/questions/7015302/css-hexidecimal-rgba, hex-encoded RGBA color notation isn't supported by CSS3 (and therefore HTML 5 Canvas). It's expected to be added in CSS4, but it's not currently supported by any browser.
Our color property code only supports 6-character hex colors, so there's no code changes necessary.
https://github.com/bokeh/bokeh/blob/master/bokeh/core/properties.py#L1378
> Remove mention of hex RGBA as supported color prop

- bokehjs/src/coffee/models/glyphs/text.coffee
issues: fixes #3226 
Added `doit` conditional to text glyph render method to be inline w/ all other glyphs.
The same code as in issue #3226 now doesn't render the text:
> Add doit conditional for null handling in text render method

- bokeh/charts/data_source.py
- bokeh/charts/tests/test_data_source.py
Avoids modifying the input DataFrame inplace
Fixes #3899
> Take shallow copy of DataFrame in `ChartDataSource`

- sphinx/source/docs/user_guide/tools.rst
The docs say:
> Try running the code and changing the `toolbar_position` value.
(http://bokeh.pydata.org/en/0.11.1/docs/user_guide/tools.html#positioning-the-toolbar)
This is incorrect, the parameter name is `toolbar_location`.
> Fix typo in docs: toolbar_position -> toolbar_location

- bokehjs/src/coffee/models/widgets/button.coffee
Added 
```
@$el.attr("type","button")
```
to `Class ButtonView` in order to fix the issue of the page reloading/redirecting as described in issue #3895.
> added type=button attribute to ButtonView class

- bokehjs/gulp/labeler.coffee
This should fix #3581. Originally I attributed this to newer version of node.js/npm being installed, but apparently even older versions cause problems when gulp is run from `node_modules/.bin` instead of the conda-installed one. This PR helps, but I'm not sure where the difference comes from.
> More robust (?) way of labeling _process module

- bokeh/core/_templates/plot_div.html
- bokeh/tests/test_embed.py
- bokehjs/src/less/bokeh-widgets.less
- bokehjs/src/less/bokeh.less
This is to help the namespace clash with the other `.bk-plot` class in use.
Follow-up to https://github.com/bokeh/bokeh/pull/3797
> Changed .bk-plot to .bk-root for style wrapper

- sphinx/source/docs/user_guide/server.rst
SSH can be used to create tunnels between a remote host with a running instance of the Bokeh server and a local machine, and to access the remote Bokeh server as if it were running on the local machine.  The documentation attached to this PR describes how to create such tunnels.
> Document use of SSH tunnels with Bokeh. #3968.

- tests/examples/examples.yaml
Looking at recent examples failures data_tables_server often seems to be the source of hang-ups. This particular example offers little incremental benefit over others:
* we have another test for the data table
* the server tests have no image diff at the moment
* other server tests test dropdowns
It could be that data_tables_server isn't the problem it's just an early test and so because we now bail out early it's just always looking like this one, but I don't see any harm in trying disabling it (due to reasons above)
In addition:
* ~~i can't seem to get it to run locally~~
* has out-dated bokeh code in it
Edit: I can get it running locally
The code has a deprecation warning in it: 
```sh
data_tables_server.py:134: BokehDeprecationWarning: bokeh.models.sources.from_df was deprecated in …
```
> Disable data_tables_server example

- conda.recipe/meta.yaml
- setup.cfg
- tests/integration/integration_tests_plugin.py
- tests/integration/interaction/test_wheel_zoom.py
Fixes #3827 
Builds on #3975 (which should be merged first)
Supersedes #3974 
cross browser tests need to be explicitly written to be cross browser so the author can take care with any selenium nuances. This implements a marker that marks a test to be run as a cross browser test, rather than providing a global option. 
This should make it easier to get started with cross-browser tests and provides ongoing flexibility to write targeted tests (e.g. just something for touch).
> Add cross browser capabilities

- bokeh/application/handlers/code_runner.py
- bokeh/application/handlers/tests/test_code.py
- examples/app/crossfilter/main.py
- examples/app/crossfilter/models/models.py
issues: closes # 3994
To summarize, this PR causes code runner to:
* set CWD to app location
* prepend the empty string to `sys.path`
before `exec`ing code, and then undoes those afterward.
@bokeh/dev  ready for review
> simulate sys.path behavior of regular python script in Bokeh app

- sphinx/source/docs/user_guide/plotting.rst
- sphinx/source/docs/user_guide/styling.rst
- link 'screen units' and 'data-space units' to glossary
- make "reference documentation linked above" a link
- per Bryan in bokeh flowdock channel 2016-02-17, infinite pan/zoom
is now default, although max and min range may still be set.
> fixes to 'plotting' [ci disable examples]

- bokeh/io.py
- sphinx/source/docs/user_guide/quickstart.rst
Clarify that default mode for output_file() is 'cdn' rather than
'inline'.
> clarify that default mode is 'cdn' rather than 'inline'

- sphinx/source/docs/user_guide/interaction.rst
Added more information to "Adding Widgets" section, including:
- what a widget is
- how to use widgets
-add them to document
-program their callbacks/handlers
- event handlers 
-example with .on_change
-example with .on_click 
- link to bokeh.models in the reference guide. 
I also think adding a link to the Javascript section from the bullets in this section would be nice, but I wasn't sure how to do that.
> Issue #3656: added more documentation for how to use widgets in the user guide

- bokehjs/package.json
The git protocol often doesn't work in a windows/corporate setting
Fixes #4035
> Use the https protocol in favour of git

- sphinx/source/docs/user_guide/server.rst
On the server documentation, there is a typo in the calls to `supervisorctl`.
> Fix typo: supervisctl -> supervisorctl

- sphinx/docserver.py
issues: closes #4027
See the discussion in [this issue](https://github.com/bokeh/bokeh/issues/4027).
I exchanged the use of `os.fork()` in `sphinx/docserver.py` against using the `threading` module, which should work regardless of the os. I also added the possibility to shutdown the server.
My implementation is mainly due to [this GH answer](http://stackoverflow.com/a/17325148/2207840).
Caution: My experience with web programming in python is near-zero, so there is a real chance that what I did is plain nonsense. I tried the new version on both Win 7 and Arch linux and it seemed to work on both systems.
Happy to provide further relevant information!
> Make docserver.py run on both windows and unix by using threading instead of os.fork.

- bokeh/sampledata/__init__.py
The previous version attempted to create a top level directory on Windows.
This resolves: RuntimeError: could not create bokeh config directory at ...
> Fix default bokeh dir on Windows

- bokeh/charts/builders/bar_builder.py
- bokeh/charts/tests/test_chart.py
Fixes #3661 
There was code to explicitly hide the x-axis, ticks and labels when there is but one item in the bar chart. But when the label is explicitly specified, it should be shown regardless.
> Fix that a bar chart with one "item" does not show a label

- bokehjs/src/coffee/core/has_props.coffee
This fixes the problem with `_doc_attach()` being called multiple times, specifically `Canvas._doc_attached()`, which caused substantial performance degradation.
> Don't attach document multiple times when traversing the graph

- bokeh/server/application_context.py
- bokeh/server/session.py
- bokeh/server/tornado.py
Fixes #3730.
Units were originally in seconds and are now in milliseconds.
> Change units of unused session lifetime

- examples/models/calendars.py
Not sure when this got a bit borked, but this is what master was looking like for me:
and here's after this PR:
> Fix up formatting of calendars example

- bokehjs/examples/anscombe/anscombe.ts
- bokehjs/src/coffee/api/typings/bokeh.d.ts
- bokehjs/src/coffee/embed.coffee
This makes server work again. Why this wasn't caught earlier? Because server code in bokehjs catches all errors, even if they are unrelated to user input. Logging programming errors isn't the right approach. Wrong code should fail as soon as possible. This also raises a question if our testing framework could do a better job in such situation.
> Fix function naming in embed.coffee

- sphinx/source/docs/dev_guide/setup.rst
- sphinx/source/docs/user_guide/server.rst
Issues: fixes #4092 
The ability to use `python -m bokeh` was added when we implemented `__main__.py` sometime ago. It is mentioned in the docs [here](http://bokeh.pydata.org/en/latest/docs/user_guide/server.html) but there are two places where it makes sense mentioning it too (which is what this PR does).
> Improve docs for python -m bokeh command

- bokehjs/src/coffee/common/hittest.coffee
- bokehjs/src/coffee/models/glyphs/annular_wedge.coffee
- bokehjs/src/coffee/models/glyphs/annulus.coffee
- bokehjs/src/coffee/models/glyphs/circle.coffee
- bokehjs/src/coffee/models/glyphs/patches.coffee
- bokehjs/src/coffee/models/glyphs/rect.coffee
- bokehjs/src/coffee/models/glyphs/wedge.coffee
- bokehjs/src/coffee/models/markers/marker.coffee
- bokehjs/test/test_common/index.coffee
- bokehjs/test/test_common/test_selection_manager.coffee
This PR fixes the bug where the box select tool doesn't work if any of the ranges are reversed. 
I added a function ```validate_bbox_coords([x0, x1], [y0, y1])``` to the hittest module, which takes x and y coords and returns the correct bounding box coordinates for [rbush](https://github.com/mourner/rbush), making sure it's ```[minX, minY, maxX, maxY]```.
I also added some tests for the selection manager. The last test, ```it "should work when mappers are reversed"```, fails before the fix.  
~~- [ ] release document entry (if new feature or API change)~~
> Fix box select for reversed ranges

- bokehjs/src/coffee/models/annotations/box_annotation.coffee
- bokehjs/src/coffee/models/annotations/poly_annotation.coffee
- bokehjs/src/coffee/models/tools/gestures/box_select_tool.coffee
- bokehjs/src/coffee/models/tools/gestures/box_zoom_tool.coffee
- bokehjs/src/coffee/models/tools/gestures/lasso_select_tool.coffee
- bokehjs/src/coffee/models/tools/gestures/poly_select_tool.coffee
issues: fixes #3992
Noticed that `PolyAnnotation` almosts had the same issue. Also realized that the `update` functions only purpose was to be for silent updates (normal updates that trigger `change` can just use standard `.set`) so removed that internal property and simplified associated logic)
> overlay annotations respond to backbone changes

- bokehjs/examples/linked/.gitignore
- bokehjs/examples/linked/linked.html
- bokehjs/examples/linked/linked.ts
- bokehjs/examples/linked/tsconfig.json
- bokehjs/gulp/tasks/examples.coffee
- bokehjs/src/coffee/api/plotting.coffee
- bokehjs/src/coffee/api/typings/models/plots.d.ts
- bokehjs/src/coffee/api/typings/plotting.d.ts
- bokehjs/src/coffee/models/layouts/grid_plot.coffee
> Add linked plotting example to bokehjs

- bokeh/application/application.py
- bokeh/application/handlers/directory.py
- bokeh/application/handlers/handler.py
- bokeh/application/handlers/tests/test_directory.py
- bokeh/application/tests/test_application.py
- bokeh/command/bootstrap.py
- bokeh/server/tornado.py
- bokeh/server/views/static_handler.py
- sphinx/source/docs/user_guide/server.rst
This PR causes an `app/static` route to be added whenever a directory format app has a `static` subdirectory. It also improves the startup logging output to make the available routes more legible:
```
DEBUG:bokeh.server.tornado:Patterns are:
DEBUG:bokeh.server.tornado:  [ ( '/movies/?',
DEBUG:bokeh.server.tornado:      <class 'bokeh.server.views.doc_handler.DocHandler'>,
DEBUG:bokeh.server.tornado:      { 'application_context': <bokeh.server.application_context.ApplicationContext object at 0x107be5128>,
DEBUG:bokeh.server.tornado:        'bokeh_websocket_path': '/movies/ws'}),
DEBUG:bokeh.server.tornado:    ( '/movies/ws',
DEBUG:bokeh.server.tornado:      <class 'bokeh.server.views.ws.WSHandler'>,
DEBUG:bokeh.server.tornado:      { 'application_context': …
```
> Add per-app static file handling

- bokehjs/src/coffee/models/sources/geojson_data_source.coffee
This PR address the issue: https://github.com/bokeh/bokeh/issues/3881
A Geometry Collection means that a feature has multiple geometries and those geometries map to a single properties object.  This PR handles that scenario by flattening that list of geometries and repeating the properties object for each geometry.  I feel this is an acceptable approach for supporting this feature. 
Example:
```python
from bokeh.io import output_file, show
from bokeh.models import Range1d, GeoJSONDataSource
output_file('test_multigeometry.html')
x_range=(-122.44255, -122.44285)
y_range=(37.80, 37.81)
def base_plot(tools='pan,wheel_zoom,reset',plot_width=900, plot_height=600, **plot_args):
p = figure(tools=tools, plot_width=plot_width, plot_height=plot_height, …
```
> added support for GeoJSON GeometryCollection

- bokeh/command/subcommands/serve.py
- bokehjs/src/coffee/models/widgets/toggle.coffee
Fixes #4190 
The problem was the `<button ... data-bk-bs-toggle="button">` which made bootstrap override the style that we set in the render method. Also snuck in a typo-fix in the server-code.
> Let toggle button have consistent state (#4190)

- bokeh/core/_templates/autoload_js.js
> Force JS execution after page/DOM fully loads

- sphinx/source/docs/user_guide/interaction.rst
- sphinx/source/docs/user_guide/source_examples/interaction_paragraph.py
- sphinx/source/docs/user_guide/source_examples/interaction_pretext.py
> Add paragraph and pretext widgets and examples to user guide.

- bokeh/models/formatters.py
- bokehjs/src/coffee/models/formatters/datetime_tick_formatter.coffee
This PR makes the "internal" formats dict on a datetime tick formatter actually be internal. This PR also removes some unused "function" formats that were not compatible with serialization. 
Note that it is less than ideal that the `formats` bokeh property is always set from the JS side, it migh tbe better to set "base formats" and overlay the "diff formats" from python. This PR does not address that.
> store computed final props on a private attribute

- bokeh/models/glyphs.py
- bokeh/plotting/figure.py
- bokehjs/src/coffee/api/models.coffee
- bokehjs/src/coffee/api/plotting.coffee
- bokehjs/src/coffee/api/typings/models/glyphs.d.ts
- bokehjs/src/coffee/api/typings/plotting.d.ts
- bokehjs/src/coffee/common/models.coffee
- bokehjs/src/coffee/core/util/canvas.coffee
- bokehjs/src/coffee/models/canvas/canvas.coffee
- bokehjs/src/coffee/models/glyphs/ellipse.coffee
- examples/plotting/file/glyphs.py
- examples/plotting/notebook/glyphs.ipynb
- sphinx/source/docs/reference/bokehjs.rst
- sphinx/source/docs/user_guide/plotting.rst
- sphinx/source/docs/user_guide/source_examples/plotting_ellipses.py
- tests/glyphs/Ellipse.py
The Ellipse glyph is implemented with the CanvasRenderingContext2D.ellipse()
function, which is currently marked as experimental, and unsupported on some
mobile platform. A more robust implementation would need to use Bezier curves
until more platforms support the function.
> Add Ellipse glyph

- bokeh/charts/builders/histogram_builder.py
- bokeh/charts/stats.py
Fixes #3660 
I played with different approaches to deal with this problem, but this seemed to be the least intrusive. The problem can be considered an upsteam problem of pandas: Pandas selects bin bounds that are 1% wider than the actual min/max range, to ensure inclusion of all values. When the data is no range (e.g. `[3, 3, 3]`), the bin width seems to be 1% of the (mean) *value* of the data. This breaks down for values that are zero or smaller than zero though. This PR fixes this by specifying bin bounds when the data std is zero.
> Histogram deals better with ill-defined ranges (#3660)

- bokeh/core/json_encoder.py
- bokeh/core/tests/test_json_encoder.py
This PR changes the JSON encoder to not use `calendar.timegm`, which converts to local timestap, assuming that the datetimes provided are already GMT, causing them to be offset incorrectly.
> send date without TZ as-is, do not assume gmt

- bokeh/core/_templates/autoload_js.js
- bokeh/embed.py
issues: fixes #4254
This PR changes the embedding code to only wrap the JS for `autoload_static` in a document `onload` handler, and reverts the notebook embedding code to the way it was previously. 
I have verified that the notebook functions with this PR. 
@seanlaw if possible, can you check whether `autoload_static` functions as expected for you? (Looking at the output in an ipython console, it looks good, but independent verification is certainly welcome)
@mattpap I do want to take a deeper dive into all of our embedding/templating soon, but I'd like to get your opinion if this is acceptable as an immediate fix.
> only wrap autoload_static in an onload handler

- bokehjs/src/coffee/models/canvas/canvas.coffee
- bokehjs/src/coffee/models/glyphs/bokehgl.coffee
- bokehjs/src/coffee/models/glyphs/circle.coffee
- bokehjs/src/coffee/models/glyphs/glyph.coffee
- bokehjs/src/coffee/models/glyphs/line.coffee
- bokehjs/src/coffee/models/markers/square.coffee
- bokehjs/src/coffee/models/plots/plot.coffee
- examples/plotting/file/marker_compare.py
- examples/plotting/file/webgl_tests.md
- sphinx/source/docs/user_guide/webgl.rst
Implements part of #2590
Markers that we already have:
* circle
* square
Markers that can be done:
Markers that we can/should (probably) not do:
* annulus - can make the shape, but cannot parametrize at this point and API has no default ratio, so skipping for now
* oval, ellipse - same as annulus, but is also more difficult to make shape (can be done though, I think)
* rect
* bezier stuff, etc.
Other tasks in this PR:
> Add WebGL support for more kinds of markers

- bokeh/command/subcommands/serve.py
- bokeh/server/server.py
- bokeh/server/tests/test_tornado.py
- bokeh/server/tornado.py
Fix #4325. Apparently the `match_host` function in `bokeh/server/tornado.py` was not designed to handle a port number while the `_create_hosts_whitelist` function in `bokeh/server/server.py` always append a port number (`:80`) if none is provided in the CLI therefore setting the whitelist to `*:80` which would previously not match anything.
This PR changes two things:
- Setting `--host '*'` will result in accepting requests on any port (instead of just ":80")
- It's now also possible to use the wild card with a specific port, e.g.: `--host *:8080` or with any port with a specific hostname or ip `--host hostname:*`  explicitly.
The behavior that `:80` is appended to non-wildcard host names is preserved to follow what was previously documented.
> Fix handling of host wildcard: --host '*'

- bokehjs/src/coffee/models/canvas/canvas.coffee
- bokehjs/src/coffee/models/glyphs/glyph.coffee
- bokehjs/src/coffee/models/glyphs/webgl/base.coffee
- bokehjs/src/coffee/models/glyphs/webgl/line.coffee
- bokehjs/src/coffee/models/glyphs/webgl/markers.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
Issues: fixes #4293. This is like #4346 but without the browser-zoom update stuff.
This PR:
* makes WebGL aware of the pixel_ratio for HDPI support. 
* improves/simplifies the blitting of the gl canvas into the 2d canvas. 
* tweaks some WebGL markers to look better when zoomed in.
* ~~makes plot update when the browser zoom is changed.~~
Consequently, our WebGL glyphs have never looked so nice! Maybe even nicer than the 2D glyphs (due to better aa). Should also look great on retina displays now.
> Make hidpi work for webgl

- bokehjs/src/coffee/models/tools/button_tool.coffee
Fixes: #1848 
This is effectively a revert of commit 9e57a12
Couldn't do an actual clean revert due to file having been subsequently moved.
Ping @bryevdv - the original commit is yours. I have done a quick test and I found that, on my phone, I could still click toolbar buttons - but this was not a thorough test. 
We have lots of woes in touch support land (#2997) so I would propose putting this change back in to get desktop users working again and then we can focus on touch later.
I haven't added a test, as I have a lot going on at the moment, and it would be a somewhat involved selenium tests to detect the regression. There's already a test that detects whether buttons can be selected or deselected. But to test the regression we'l'l need to have that test not only run against standard …
> Fix toolbar for chrome

- sphinx/docserver.py
As commented on my previous PR #4033, changed message during docserver startup from 
Press any key to exit...
to
Press <ENTER> to exit...
> Changed docserver shutdown instruction.

- bokehjs/src/coffee/models/canvas/canvas.coffee
- bokehjs/src/coffee/models/glyphs/webgl/line.coffee
- bokehjs/src/coffee/models/glyphs/webgl/markers.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
Supersedes #4378. Fixes #4345 and fixes #4367.
This makes the hidpi pixel ratio adapt when the browser zoom changes. This turned out to be easier than the original PR that I made against master earlier (#4346), because we already get an update now when the browser zoom changes.
I tested that all the HIDPI stuff works in embedded plots as well. This means that the document does an update when it gets a `window.resize` event, regardless whether the size did not actually change, and regardless whether the plot is embedded or not. In case someone ever tries to add efficiency here, please keep in mind this use-case.
> Adjust hidpi on browser zoom

- bokeh/charts/builders/chord_builder.py
- bokeh/charts/builders/tests/test_chord_builder.py
Color generation in the chord builder is on line 138. 
```python
colors = [color_in_equal_space(area / areas_in_radians.shape[0]) for area in range(areas_in_radians.shape[0])]
```
In Python 2.7, ```colors``` becomes a list of all the same color because ```area / area_in_radians.shape[0]``` is always 0. 
To fix this, I added ```division``` to the ```from __future__``` import statement. 
- [ NA ] release document entry (if new feature or API change)
> Chord diagram colors

- sphinx/source/docs/dev_guide/testing.rst
Small addition to the dev docs as discussed in #4450. 
cc @birdsarah
> DOC: mentioning ``ulimit -n`` in dev guide

- bokehjs/src/coffee/core/util/throttle.coffee
This PR fixes a bug where multiple calls to ```request_render``` in the same throttling interval will cause two renders when it should only cause one.
The fix is to make sure that any calls to ```request_render``` don't generate a new render (through setTimeout) when one is already pending. 
I didn't add any tests for this. I would need some guidance on how that should be done if anyone has any ideas. 
- [ NA ] release document entry (if new feature or API change)
> Fix bug in throttling of render

- bokehjs/src/coffee/models/tools/toolbar_box.coffee
Fixes #4385
Helptools that have the same `redirect` attribute are "combined" (as in only the first is used). The `help_tooltip` attribute is ignored in the comparison.
To test (a variation on the code mentioned in #4385):
```python
from bokeh.plotting import figure, gridplot, output_file, show
from bokeh.models.tools import HelpTool, WheelZoomTool
n = 50
x = np.linspace(0, 4*np.pi, n)
y = np.sin(x)
tools = "pan,wheel_zoom,box_zoom,reset,save,crosshair,help"
l = figure(title="line", tools=tools, plot_width=300, plot_height=300)
l.line(x,y, line_width=3, color="gold")
aw = figure(title="annular wedge", tools=tools, plot_width=300, plot_height=300)
aw.annular_wedge(x, y, 10, 20, 0.6, 4.1, color="navy", alpha=0.5,
inner_radius_units="screen", outer_radius_units="screen") …
```
> De-duplicate helptools with the same redirect

- bokeh/models/annotations.py
- bokeh/models/tests/test_annotations.py
- bokehjs/src/coffee/models/annotations/legend.coffee
Fixes #4390
There were several things wrong with the current implementation of the legend rendering:
* It followed a rather peculiar version of the box model:
* the `legend_padding` was used as padding *and* as margin
* the `legend_spacing` was used as spacing *and* as padding
* the legend items were not rendered at their correct position (which was the main cause of #4390)
* The text height was not correctly taken into account
* the `label_standoff` was not used, instead the `legend_spacing` was used as standoff.
It now should follow the standard box model. I added a `legend_margin` property to complete it. Further I reduced the default value of the `label_width`, because some labels are just real short (and the actual text length is taken into account anyway), an of the `label_standoff` …
> Fixes to legend rendering

- bokeh/command/subcommands/serve.py
- bokeh/command/subcommands/tests/test_serve.py
- bokeh/server/server.py
- bokeh/server/tornado.py
- bokeh/server/views/app_index.html
- bokeh/server/views/root_handler.py
- sphinx/source/docs/user_guide/server.rst
Solves issue #4425 
This makes the server app index presentable
Here is a screenshot of the index page for two running applications:
> Add styling to bokeh apps index page and add docs

- setup.py
From https://github.com/tartley/colorama#initialisation: on Windows `colorama.init()` should be called. On other platforms initialization call should not have any effect, but anyway I limited the call only for Windows
closes #4480
> Initialize colorama on Windows

- bokeh/models/plots.py
- bokeh/models/tools.py
- bokehjs/src/coffee/models/plots/plot.coffee
- bokehjs/src/coffee/models/tools/toolbar_base.coffee
- bokehjs/src/coffee/models/tools/toolbar_box.coffee
- bokehjs/test/models/plots/plot.coffee
- examples/howto/layouts/dashboard.py
- examples/howto/layouts/words_and_plots.py
- examples/models/choropleth.py
- examples/plotting/file/candlestick.py
- examples/plotting/file/choropleth.py
- examples/plotting/file/custom_datetime_axis.py
- examples/plotting/file/elements.py
- examples/plotting/file/unemployment.py
- tests/integration/annotations/test_arrow.py
- tests/integration/interaction/test_hover.py
issues: fixes #4399
The new toolbar location leaves the top of the y-axis flush with the top of the browser window
> Move toolbar to right of plots

- sphinx/source/docs/includes/colors.txt
This PR fixes the hyperlink in [this file](https://github.com/bokeh/bokeh/blob/9491d517a84edc528ac84970cb338b5c24ac1d66/sphinx/source/docs/includes/colors.txt)
Associated with issue #4530
> Update link to w3schools.com

- bokehjs/src/coffee/models/widgets/toggle.coffee
issues: fixes #4572
`@$el.empty()` does not remove classes, so CSS classes for the type were
simply accumulating. Use `@$el.removeClass()` to properly remove all CSS
classes on start of render.
> properly update button appearance on button_type

- bokeh/layouts.py
- examples/howto/layouts/dashboard.py
- examples/plotting/notebook/glyphs.ipynb
Don't have an issue on this yet. Have just been tweaking as I have been using layout and wanting to improve my convenience.
1) supply a plot_width and plot_height to griplot and it sets them all for you (great for a fixed layout with lots of plots and less typing) `gridplot([[p1, p2, p3, p4], [p5, p6, p7, p8]], plot_width=200, plot_height=200)`
2) supply a list of plots (and/or None's) to gridplot and a number of columns (as opposed to a list of lists) and it'll make the grid for you. `gridplot([p1, p2, p3, p4, p5, p6, p7, p8], ncols=4, plot_width=200, plot_height=200)`
> Improvements to layout functions

- bokehjs/src/coffee/models/annotations/title.coffee
issues: fixes #4587
make text_align and text_baseline internal and set up text @visuals by
hand. Also, protect the ctx change in the initializer with a
save/restore.
Side question: seems like JS tests should have complained about this before
> fix title props mismatch

- scripts/travis_install
This is needed as part of #4559, otherwise when new ggplot pkgs are uploaded, the tests will break. The open should be removed when #4559 is completed.
> pin ggplot version preceding uploading new versions to anaconda.org

- bokehjs/src/coffee/models/layouts/layout_dom.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
- bokehjs/test/models/layouts/layout_dom.coffee
This fixes #4611, but reverts #4493, so #4488 performance regression is still there. I shouldn't be using the word *fixes* at all right now, because I don't fully understand what is going on in the rendering pipeline.
> Revert performance regression "fix" from #4493

- bokehjs/src/coffee/models/glyphs/webgl/line.coffee
I'm not entirely sure of the consequences of the changes. It seems that the computed attributes were being set on the wrong object (self and not the mainGlGlyph arg), so I just changed it.
The webgl examples still seem to work... 
ping @almarklein 
Discussion:
* Any good strategies for preventing regressions beyond a selenium test?
> Update scale on mainGlGlyph obj and not self

- bokehjs/test/models/plots/plot.coffee
- bokehjs/test/models/plots/plot_canvas.coffee
Flaky JS tests are really slowing things down.
I have an open issue to go back and really figure out what's going on. All seem to be the same problem of a poorly stubbed Solver.
> Skip 3 more flaky JS tests

- bokeh/core/compat/mplexporter/exporter.py
- examples/compat/ggplot_density.py
- examples/compat/ggplot_line.py
- examples/compat/ggplot_step.py
- scripts/travis_install
Fixes #4559
Partially Fixes #4424 (geom_point with colors still unpredictable at best)
Supersedes #4628 
Updated .draw() to .make() to match yhat ggplot API changes.
Replaced mpl exporter legend line drawing with a warning due to it causing issues with seaborn_tsplot and ggplot_density by graphing the legend as line glyphs.
> Updated ggplot & mpl_exporter Legend Fix

- bokeh/models/tools.py
Fix 'defult' -> 'default' in TapTool.behavior attr
> Fix 'defult' -> 'default' in TapTool.behavior attr

- sphinx/source/docs/user_guide/tools.rst
issues: none
Latest (0.12.0) [docs](http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#resizetool) specify `'resize_select'` as the name for ResizeTool tool, but correct name is just `'resize'`. Fixes doc.
> Fix documented name for ResizeTool

- bokeh/core/compat/bokeh_renderer.py
- examples/compat/ggplot_point.py
Fixed issue mentioned in #4424 
Previously converting mpl Paths or PathCollections to Bokeh glyphs was not supported. Unfortunately, mpl.gcf() for whatever reason returns a PathCollection instead of a Line2D when handling geom_point from ggplot. This caused the geom_point-turned-PathCollection not to render on the Bokeh plot. Shamelessly copying the draw_markers function from bokeh_renderer into a new draw_path_collection and modifying it a bit to work allows for the paths to be turned into Bokeh glyphs.
Unfortunately there are three limitations:
1. Since the PathCollection stores the shape of the glyph as a path and Bokeh does not yet handle custom glyph shapes, all converted paths default to circle.
2. If someone were to pass a PathCollection for a type of graph other than a scatter …
> Geom_Point Fix

- bokehjs/gulp/tasks/scripts.coffee
issues: fixes #4525
The problem was that the `scripts` task was configured to "log" errors, instead of letting them fail the build, as described here:
https://github.com/contra/gulp-coffee#error-handling
With this change, e.g. a syntax error now results in:
> allow scripts failures to fail the build

- bokeh/charts/chart.py
Old PR from before `flake8` was made strict again.
> remove unused import

- bokehjs/src/coffee/models/glyphs/ellipse.coffee
- bokehjs/src/coffee/models/glyphs/glyph.coffee
- bokehjs/src/coffee/models/glyphs/oval.coffee
- bokehjs/src/coffee/models/glyphs/rect.coffee
issues: fixes #4793
glyphs notebook now fully works:
> update last bounds computations to use correct rbush format

- bokeh/models/annotations.py
- bokeh/sphinxext/bokeh_gallery.py
- bokeh/sphinxext/bokeh_github.py
- bokeh/sphinxext/bokeh_prop.py
- bokeh/tile_providers.py
- conda.recipe/meta.yaml
- scripts/devdeps.py
- sphinx/Makefile
- sphinx/make.bat
- sphinx/source/conf.py
- sphinx/source/docs/dev_guide/testing.rst
- sphinx/source/docs/reference/core.rst
- sphinx/source/docs/user_guide/bokehjs.rst
- sphinx/source/docs/user_guide/plotting.rst
* Fixes #4816 (if it still fails, its likely a `BOKEH_DOCS_CDN` issue; it works for me)
* Fixes the spew of warnings when running `make html` without having done a `make clean`.
* Fixes a few genuine errors and warnings
* Remove inheritance diagram --- which did not show up in the online docs anyway, thereby dropping the graphviz dependency.
> Improvements to docs

- bokeh/models/tools.py
- bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee
moved the wheel speed zoom from internal to defined. 
Default 1/600.
High values will be clipped.
> moved the wheel speed zoom from internal to defined.

- bokehjs/src/coffee/models/tools/gestures/tap_tool.coffee
issues: fixes #4839
ping @mattpap this seemed to be an overzealous optimization -- `select` and `inspect` have different function signatures.
> use specific call signatures for select and inspect

- bokehjs/src/coffee/version.coffee
- scripts/deploy.sh
This fixes a problem with committing the updated BokehJS version file. Note: because of this bug BokehJS `0.12.1` incorrectly reports `Bokeh.version` as `0.12.0`. Will need to have another point release very soon.
> deploy.sh needs explicit list of files updated

- bokehjs/src/coffee/document.coffee
- bokehjs/test/document.coffee
- scripts/deploy.sh
Fixes the problem of tagging between Bokeh and BokehJS. Development builds now also run `scripts/version_update.py`, to change the value of the version strings in `version.coffee` and `package.json`. 
Submitting a new release candidate or development release now requires a previous version argument in addition to a new version argument. 
fixes #4882
> Version Mismatch Fix

- bokeh/models/annotations.py
- bokeh/models/tools.py
- bokehjs/src/coffee/api/charts.coffee
- bokehjs/src/coffee/api/typings/models/tools.d.ts
- bokehjs/src/coffee/models/annotations/tooltip.coffee
- bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
- bokehjs/src/less/main.less
This patch adds a `show_arrow` to `HoverTool`. It is a simple boolean to disable arrow on toolip. `True` by default.
Usage (check the last line):
```python
hover = p.select_one(HoverTool)
hover.point_policy = "follow_mouse"
hover.tooltips = [
("Name", "@name"),
("Unemployment rate)", "@rate%"),
("(Long, Lat)", "($x, $y)"),
]
hover.show_arrow = False
```
> Add HoverTool.show_arrow

- bokehjs/src/coffee/models/glyphs/patches.coffee
- tests/integration/interaction/test_patches_preselection.py
- tests/integration/utils.py
This allows the sxss to be available for hit testing - which is not done on the main glyph (but on the selection and nonselection glyph)
> Store scss on renderer not on glyph

- scripts/devdeps.py
fixes #4824 
Added `flake8` and `boto` as well as the base dependencies required for bokeh: 
- `backports_abc`,
- `jinja2`,
- `markupsafe`,
- `mkl`, (pending correct import call)
- `bumpy`,
- `dateutil`,
- `pyyaml`, (pending correct import call)
- `requests`,
- `six`,
- `tornado`,
- `yaml`
> update `devdeps.py` to including the missing dependencies

- sphinx/source/docs/user_guide/styling.rst
This adds a link to the ``sizing_mode`` reference documentation in the Responsive Dimensions section of the Styling user guide. I'm not entirely sure whether ``responsive`` is deprecated in favor of ``sizing_mode`` or not (for my own purposes, it turned out that ``sizing_mode`` wouldn't even give me the behavior I want, so I ended up not using either), so I opted to just link to those docs. I'll be happy to rework this as needed.
- **N/A** tests added / passed
- **N/A** release document entry (if new feature or API change)
> add link to sizing_mode in Responsive Dimensions section of Styling user guide

- sphinx/source/docs/user_guide/embed.rst
Hotfix to remove trailing whitespace in docs/user_guide/embed.rst
> Remove trailing whitespace

- bokeh/core/_templates/autoload_js.js
- bokeh/core/_templates/autoload_nb_js.js
- bokeh/core/_templates/notebook_js.js
- bokeh/core/templates.py
- bokeh/embed.py
- bokeh/io.py
- bokeh/tests/test_io.py
- bokeh/util/notebook.py
- bokehjs/src/coffee/embed.coffee
- examples/howto/notebook_comms/Basic Usage.ipynb
- examples/howto/notebook_comms/Continuous Updating.ipynb
- examples/howto/notebook_comms/Jupyter Interactors.ipynb
- examples/howto/notebook_comms/Numba Image Example.ipynb
With this PR the code which initializes plots polls whether bokehJS is initialized, delaying rendering of the plot until it is fully loaded. It fixes the issue with Run All (#4987) and nbconvert works again (#4980). To test it you run ``output_notebook``, clear the notebook and reload the page to ensure bokehJS is no longer loaded and then display a plot. The plot will wait to display until you run ``output_notebook`` a second time to load bokehJS. 
Since keeping around a registry of handles is quite expensive maybe there should be some way to explicitly request a comms handle to be created.
> Notebook output waits until bokehJS is loaded

- bokeh/core/properties.py
- bokeh/core/tests/test_properties.py
- bokeh/models/sources.py
This is a follow up on issue #4932 and PR #4933. In principle this disallows `set` type to be used in `ColumnDataSource.data`. If you wonder why I still left `Any` there, then I already changed that locally, but speed penalty is too great to include it in this PR. I need to optimize property validation first.
fixes #5042
> Make ColumnDataSource.data stricter

- bokehjs/src/less/bokeh.less
- bokehjs/src/less/main.less
- examples/plotting/file/color_scatter.py
- examples/plotting/notebook/color_scatterplot.ipynb
Fixes: #5008
Updates the hover styling to match other bokeh elements. See #5008 for description.
Also adds a gray line between elements for when you're hovered over multiple elements.
Notebook was a big pain
> Update hover styling to match other bokeh elements

- bokeh/core/_templates/autoload_nb_js.js
- bokehjs/src/coffee/embed.coffee
Fixes #5081, ensuring that a comm is only initialized when a Jupyter.kernel.notebook is defined.
> Ensure Jupyter.notebook.kernel exists before connecting to comm

- sphinx/source/docs/releases/0.12.2.rst
hotfix to fix code block in 0.12.2 release document (was missing a carriage return)
> Fix code block in 0.12.2 release doc

- bokehjs/package.json
- bokehjs/src/coffee/common/proj4.coffee
- bokehjs/src/coffee/models/plots/gmap_plot.coffee
- bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee
- bokehjs/src/coffee/models/renderers/renderer.coffee
- bokehjs/src/coffee/models/tiles/tile_utils.coffee
This shaves off about 55 kB from bokeh.min.js. This PR removes unnecessary imports and projections from `proj4/index.js`, so this isn't the same "custom" approach as e.g. with backbone.js. Just make sure to use `common/proj4` instead of `proj4` in new code.
> Use custom proj4 to reduce bokeh.min.js' size

- bokehjs/src/coffee/core/backbone.js
- bokehjs/src/coffee/core/has_props.coffee
- bokehjs/test/core/has_props.coffee
Previously `id` was a special case in several places, so now it's a property.
> Make HasProps.id a first class citizen

- bokehjs/test/models/annotations/color_bar.coffee
addresses #5121
Fix ColorBar tests by overriding frame height and width getters with deterministic values
> Fix ColorBar tests by overriding frame height and width getters with deterministic values

- bokeh/client/session.py
- tests/test_no_tornado_common.py
I don't like this solution, but don't see anything better right now to make, e.g., `bokeh.io` (and related) not fail to import without tornado.
fixes #5119
> Don't require tornado to run non-server bokeh

- bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
~~@bryevdv's fix in a form of PR.~~ Nope, that didn't work, I had to restore `ttmodels` as a computed property. This needs to be changed appropriately in future.
fixes #5123
> Fix tooltips after replacing computed properties with getters

- bokeh/client/session.py
This little patch fixes the ignorance of `browser` and `new` keywords into `session.show()` and `show_session()`. 
Now, it is possible to call a customized browser:
session = push_session(curdoc())
custom_firefox = '/usr/bin/firefox -P ipython --new-tab %s'
session.show(browser=custom_firefox)
> session.show(): take into account browser and new keywords

- bokehjs/src/coffee/common/selection_manager.coffee
- bokehjs/src/coffee/common/selector.coffee
- bokehjs/src/coffee/common/ui_events.coffee
- bokehjs/src/coffee/core/backbone.js
- bokehjs/src/coffee/core/has_props.coffee
- bokehjs/src/coffee/core/properties.coffee
- bokehjs/src/coffee/document.coffee
- bokehjs/src/coffee/models/annotations/box_annotation.coffee
- bokehjs/src/coffee/models/annotations/poly_annotation.coffee
- bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee
- bokehjs/src/coffee/models/plots/plot.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
- bokehjs/src/coffee/models/ranges/data_range1d.coffee
- bokehjs/src/coffee/models/ranges/range1d.coffee
- bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
- bokehjs/src/coffee/models/renderers/renderer.coffee
- bokehjs/src/coffee/models/sources/column_data_source.coffee
- bokehjs/src/coffee/models/tiles/tile_renderer.coffee
- bokehjs/src/coffee/models/transforms/interpolator.coffee
- bokehjs/src/coffee/models/widgets/dialog.coffee
- bokehjs/test/core/properties.coffee
- bokehjs/test/document.coffee
This is to ease transition from `get,set` to getters and setters. This way using `get,set` will be discouraged. At some point in future I will change deprecation to a hard error. Additionally, `{get,set}v` are easier to distinguish from uses of different `get,set` in other contexts. Note that complete removal of at least `setv()` may not be possible, due to features like "simultaneous" and silent assignment.
fixes #5160
> Replace {get,set} ->{get,set}v and deprecate {get,set}

- scripts/travis_install
Our builds are currently failing with an exception, because there is API incompatibility between newest conda and obsolete pinned conda-build. This reverts #5084, because conda-build 2.0.1 fixes the original issue with building noarch package. Note that conda-build 2.0.1 was released several days ago, so if only there was a followup on issue #5084, then we wouldn't need to fix this in hurry and deal with a dozen of PRs which now need updating.
> Revert "Pin conda-build version to 1.21.14"

- bokehjs/package.json
- bokehjs/src/coffee/api/typings/bokeh.d.ts
- bokehjs/src/coffee/core/logging.coffee
- bokehjs/test/core/logging.coffee
- bokehjs/test/document.coffee
- bokehjs/typings.json
This implements a custom logger. It preserves line numbers and allows for logger naming (prefixes). This also slightly reduces bokehjs size and avoids issues that were present in jsnlog (`window.onerror` and AJAX requests). This should work across modern web browsers, but unfortunately it may be broken in some versions of Firefox (you will get '(unknown)' location). This is FF's bug.
fixes #5171
> Replace jsnlog with a custom, line number preserving logger

- bokeh/core/properties.py
- bokeh/core/tests/test_properties.py
- bokeh/model.py
- bokeh/models/layouts.py
- bokeh/models/tests/test_renderers.py
- bokeh/tests/test_model.py
By default this displays concise representation consisting of model's name, id and expand button. After expansion, it shows all model's properties and their values (formatted with `repr()`) and collapse button, which allows to return to concise representation. This is very crude, doesn't work recursively (thus `repr()`) and doesn't take too much advantage of HTML/CSS (colors, at al.). All this can be improved later, but for now we have something that works and doesn't interfere with notebook workflow. Note this is implemented in vanilla JS, so there are no assumptions about JQuery, etc. We shouldn't use bokehjs' JQuery, because HTML repr of a model may be displayed before `output_notebook()`. Also note that this makes original (commented out) `_repr_html_`, that displayed a plot …
> Add very crude HTML representation of models

- bokeh/models/formatters.py
- bokeh/models/tests/test_glyphs.py
- bokehjs/src/coffee/api/typings/models/formatters.d.ts
- bokehjs/src/coffee/models/formatters/datetime_tick_formatter.coffee
- examples/models/daylight.py
`formats` was deprecated and now `DatetimeTickFormatter` has all `format`'s keys as its properties. The second commit isn't strictly necessary, but shows usage of "expression statements" (switch and if) to produce more compact and, I think, more readable code.
fixes #5234
> Replace DatetimeTickFormatter.formats with individual fields

- bokeh/sampledata/__init__.py
- bokeh/sampledata/stocks.py
- bokeh/sampledata/unemployment.py
- bokeh/sampledata/us_counties.py
Fixes Issue #5029 where downloading sample US_Counties data on Ubuntu 16 with an ansi preferred local encountered issues decoding the csv encoded as utf-8.
Replaces Rejected/Abandoned PR #5030
> Fix CSV Reading of Samples for Py 3

- bokeh/util/dependencies.py
Imports can trigger side effects which may result in any exception
potentially being thrown. In this case simply return None rather than
crashing on an optional import.
Fixes #5242
> Catch any exception in `import_optional`

- bokeh/core/properties.py
- bokeh/core/tests/test_properties.py
- examples/models/trail.py
@bokeh/dev, please join and help out as time permits.
TODO:
fixes #5273
> Fix deprecation warnings

- bokehjs/src/coffee/document.coffee
- bokehjs/test/document.coffee
In #5205 we added support for width/height argument to the document.resize method, so that we could suggest resize sizes in non-window layouts (i.e. jupyterlab (phosphorjs) panels)). This causes a regression where ``jquery.proxy`` would pass the jquery event as an argument to the resize function as the first arg (this didn't fail previous because JS is fun and ignores extra arguments to functions signatures)
This PR adds a positional argument to placehold the jquery event
> Fix broken responsive layouts on window resize

- conda.recipe/meta.yaml
- scripts/travis_install
This PR:
* Appends (instead of prepends via the --add arg) the bokeh and conda-forge channels so that our channel precedence (high to low) is "defaults, bokeh, conda-forge" instead of "conda-forge,bokeh,default".
* This appears to reduce the CI unit test matrix times to 5:45-7:00min (as opposed to over 9min). It's unclear if the defaults CDN is faster or we're installing fewer dependencies. [ninja edit: it seems to be both]
* Also removes the (unused) javascript channel from our meta.yaml (we're now installing nodejs from conda-forge)
> Append conda channels to wrangle channel precendence

- bokeh/application/handlers/script.py
- bokeh/application/handlers/tests/test_script.py
- bokeh/sampledata/gapminder.py
- tests/examples/examples.yaml
@birdsarah @mattpap @canavandl @havocp would appreciate quick eyes on this. 
AFAICT the correct thing to do is to read the scripts in as bytes, then pass along any coding comment to `compile` to deal with, instead of using `codecs.open` to always read in `utf-8` (then we have to try and strip out coding comments which seems unreliable)
Additionally, gapminder data has unicode characters, so I added the encoding to `read_csv`. 
With this changes gapminder runs without error on py3 and py3
> Fix Gapminder on Py2 / handle source codings better

- bokeh/util/deprecation.py
- bokeh/util/tests/test_deprecation.py
> Replace JS' str.trim() with Python's str.strip()

- bokeh/models/mappers.py
- bokehjs/src/coffee/models/glyphs/image.coffee
- bokehjs/src/coffee/models/mappers/color_mapper.coffee
- bokehjs/src/coffee/models/mappers/linear_color_mapper.coffee
- bokehjs/src/coffee/models/mappers/log_color_mapper.coffee
- bokehjs/test/models/mappers/linear_color_mapper.coffee
- bokehjs/test/models/mappers/log_color_mapper.coffee
~~Todo: add tests~~
~~This PR is probably more proof that we need to outline our needs for the color mappers and then refactor.~~ was able to make relatively small changes
~~Note: only hex colors are now supported for Image glyph special colors (nan/high/low)~~ Resolved
> Support special colors on image glyph

- bokehjs/src/coffee/document.coffee
- bokehjs/test/document.coffee
In fixing the typo, I added a test, which uncovered other logic errors. Is this actually used anywhere? If not we can just remove it. 
ping @mattpap @havocp this is ready, comments welcome.
> fix errors in Document.destructively_move

- sphinx/source/docs/user_guide/source_examples/styling_dimensions.py
changed comment to apply to example content
> Correct comment in syling dimension example

- bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
> Fix $x and $y in hover tool by not shadowing variables

- bokeh/models/widgets/inputs.py
- bokehjs/src/coffee/core/has_props.coffee
@bryevdv, if I understand https://bugs.webkit.org/show_bug.cgi?id=164306#c4, this should fix the problem. We use other getters (setters are uncommon), but they aren't used as intensively as those used for property access.
fixes #5392
> Don't use tail calls in getters/setters to avoid a bug in Safari

- bokeh/palettes.py
- bokeh/tests/test_palettes.py
Fixes the implementation of `__dir__` on the dynamically generated
`palettes` module. Previously this would fail on python 2, due to a
quirk in how globals were handled (this is fixed in python 3).
Fixes #5453.
> Fix tab completion for bokeh.palettes

- bokehjs/src/coffee/models/transforms/interpolator.coffee
- bokehjs/src/coffee/models/transforms/linear_interpolator.coffee
- bokehjs/test/models/transforms/linear_interpolator_transform.coffee
There was no test that the final control point matched, which is how this bug crept in. The problem was the predicate for `_.findLastIndex`, which was `x >= num`. This could return the last index for `@_x_sorted`, and the subsequent `x2 = @_x_sorted[ind+1]` would then yield `null` -> `NaN`.
The predicate was changed to `num < x` which will always be at most the next to last index. But this also necessitates special casing the first control point, so the following check was added first:
```
if x == @_x_sorted[0]
return @_y_sorted[0]
```
> Fix off-by-one and missing test in LinearInterpolator

- sphinx/source/bokeh_theme/static/images/logo.svg
This adds the svg version of the Bokeh logo to the same location as the current png version.
> Add svg logo

- bokeh/io.py
#issues: fixes #5467
Correcting docstring for function push_notebook. Adding missing key word, "handle".
https://github.com/bokeh/bokeh/blob/master/bokeh/io.py#L572
> Correcting docstring for function push_notebook

- bokeh/models/tools.py
- bokehjs/src/coffee/core/util/templating.coffee
- sphinx/source/docs/user_guide/examples/tools_hover_custom_tooltip.py
- sphinx/source/docs/user_guide/tools.rst
Check if the format tag included in HoverTool templating
is == safe, and will disable any HTML escaping if true.
Updated docs, and updated existing example
> Hovertool safe tags

- bokehjs/src/coffee/safely.coffee
Adds `overflow-x: auto;` style to messages generated by `safely.coffee`
New output:
> Wrap long error output correctly

- bokeh/models/layouts.py
- bokehjs/src/coffee/models/layouts/layout_dom.coffee
- bokehjs/test/models/layouts/layout_dom.coffee
- examples/plotting/file/css_classes.py
Adds .css_classes property to LayoutDOM, which accepts a sequence of strings. These are added as-is to the LayoutDOM element.
> Add support for specifying CSS classes on all LayoutDOM

- bokehjs/src/coffee/api/charts.coffee
- bokehjs/src/coffee/core/backbone.js
- bokehjs/src/coffee/core/build_views.coffee
- bokehjs/src/coffee/core/events.js
- bokehjs/src/coffee/core/util/refs.coffee
- bokehjs/src/coffee/core/util/underscore.coffee
- bokehjs/src/coffee/document.coffee
- bokehjs/src/coffee/embed.coffee
- bokehjs/src/coffee/models/layouts/box.coffee
- bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
- bokehjs/src/coffee/models/sources/geojson_data_source.coffee
- bokehjs/src/coffee/models/tickers/composite_ticker.coffee
- bokehjs/src/coffee/models/tickers/days_ticker.coffee
- bokehjs/src/coffee/models/tickers/months_ticker.coffee
- bokehjs/src/coffee/models/tickers/years_ticker.coffee
- bokehjs/src/coffee/models/tools/toolbar.coffee
- bokehjs/src/coffee/models/tools/toolbar_box.coffee
- bokehjs/src/coffee/models/widgets/data_table.coffee
- bokehjs/src/coffee/models/widgets/multiselect.coffee
- bokehjs/src/coffee/models/widgets/tabs.coffee
Quick clean up. A lot more could be done, but those changes may be a lot more subtle than these. Note that compatibility isn't an issue, because all browsers and IE 9+ support these methods.
fixes #5507
> Use native methods instead of underscore

- bokehjs/src/coffee/models/annotations/color_bar.coffee
- bokehjs/src/coffee/models/canvas/canvas.coffee
- bokehjs/src/coffee/models/glyphs/image.coffee
- bokehjs/src/coffee/models/glyphs/image_rgba.coffee
- bokehjs/src/coffee/models/mappers/color_mapper.coffee
issues: fixes #5526
This is hard for me to test on different windows VMs from dev. I tested that `image.py` `image_url.py` and `color_data_map.py` work on Win7 + IE 11. I'd like to merge this and make a dev build, which will be much easier to test. 
ping @bokeh/dev
> fixups for some versions if IE11

- sphinx/source/bokeh_theme/layout.html
issues: fixes #5522 
Solves the problem for real. c.f. http://bokeh.pydata.org/en/test/ on Win7 IE11
Also:
> get fonts to load properly on IE11

- examples/embed/animated.py
- examples/embed/embed_multiple.py
- examples/embed/embed_multiple_responsive.py
- examples/embed/widget.py
- examples/howto/interactive_bubble/gapminder.py
issues: fixes #5306
Went ahead and updated all the examples that did an explicit `open` and `write`
> use io.open with encoding whenever file writing by hand

- bokeh/core/properties.py
- bokeh/core/tests/test_properties.py
- bokehjs/src/coffee/models/annotations/legend.coffee
The following code
```
from bokeh.plotting import figure, output_file, show
from bokeh.models import LinearColorMapper, ColumnDataSource
from bokeh.palettes import viridis
x = np.linspace(0, 1, 100)
z = np.linspace(0, 1, 100)
z[40:45] = np.NaN
p = figure(plot_width=800, plot_height=400)
source= ColumnDataSource(data=dict(x=x, z=z))
cmapper = LinearColorMapper(viridis(256), low=0.25, high=0.75, nan_color='#ff33dd',
low_color='grey', high_color=(100, 100, 255, 0.3))
p.scatter(x='x', y=1, size=10, color={'field': 'z', 'transform': cmapper}, source=source)
output_file("foo.html")
show(p)
```
Generates the output:
> have Color convert tuples to css rgb(a) values)

- bokehjs/package.json
- bokehjs/src/coffee/models/ranges/data_range1d.coffee
- bokehjs/test/models/ranges/data_range1d.coffee
Changing the way log ranges compute their `start` and `end` values in PR [5477](https://github.com/bokeh/bokeh/pull/5477) introduced a bug where plot bounds cannot be computed if there are values <= 0 in the data. 
This first commit is a hotfix and results in (check related issue #5549 for test code):
for `values = np.linspace(-0.1, 10, 21)`
and
for `values = np.linspace(-0.1, 0.9, 21)`
The reason the second one looks worse than the first is because the maximum value is less than the hotfixed minimum value of 1. Line plots where there is a value of 0 in the log axis also show lines pointing to -Infinity. 
I can add on to this PR once I've figured out a better solution (there's a comment in related issue #5549 about what would be necessary), or start another PR if this new bug needs a fast …
> hotfix for data<=0 in log axes

- bokeh/application/handlers/code_runner.py
- bokeh/application/handlers/tests/test_code.py
Apparently `__future__` flags (imports) from the parent environment (so `code_runner.py`) are forwarded to `compile()`. There exists `dont_inherit` boolean argument that doesn't allow that. I tested this manually, but we may want to write tests for this some how. It's sufficient to test for `exec("print 'XXX'")`, but I'm not sure what to do about Python 3. 
fixes #5590
> Don't inherit __future__ flags in compile()

- bokeh/document.py
- bokeh/embed.py
- bokeh/server/views/doc_handler.py
- bokeh/tests/test_document.py
- sphinx/source/docs/user_guide/server.rst
With this you can use something like:
```
curdoc().template_variables['myvariable'] = '42'
```
And add `{{ myvariable }}` to the `index.html`.
I wasn't quite sure if `Document.template_variables` needs a setter as well. Thoughts?
fixes #5583
> Custom context arguments for the jinja template

- bokeh/core/_templates/autoload_js.js
- bokeh/core/_templates/autoload_nb_js.js
- bokeh/core/templates.py
- bokeh/util/notebook.py
Previously we relied on Python's `str()` returning valid JS. Sometimes it actually and very deceptively does.
fixes #5558
> Fix autoload templates to inject data into JS templates properly

- bokeh/palettes.py
- bokeh/sphinxext/_templates/enum_detail.rst
- bokeh/sphinxext/_templates/palette_detail.html
- bokeh/sphinxext/_templates/palette_group_detail.html
- bokeh/sphinxext/bokeh_enum.py
- bokeh/sphinxext/bokeh_palette.py
- bokeh/sphinxext/bokeh_palette_group.py
- bokeh/sphinxext/templates.py
- setup.cfg
- sphinx/source/conf.py
- sphinx/source/docs/installation.rst
- sphinx/source/docs/reference/sphinxext.rst
* re-purpose `bokeh-palette` to display single palettes inline
* add `bokeh-palette` group to display groups of palette matrices
* add `:noindex:` option to `bokeh-enum`
* add complete docstrings to `bokeh.palettes`
* streamline property creation in `bokeh.palettes`
Regarding the last, it adds a little magic, in this instance I'd very much like the palettes to be expressed as near as possible to "just the data" without alot of dressing around them.
> Improve palettes docs and docs automation

- .travis.yml
Since Bokeh is moving towards Python3, it would make sense to use Python 3 fork of Fabric.
Reference Conversation: https://github.com/bokeh/bokeh/issues/5557
> Make use of Fabric3

- .travis.yml
Failed to notice `.travis.yml` build job was pinned also to python 2.7, when fabric3 PR went in
> pin build job to py3.4

- bokeh/.coveragerc
- bokeh/core/compat/__init__.py
- bokeh/core/enums.py
- bokeh/core/json_encoder.py
- bokeh/core/property_containers.py
- bokeh/core/property_mixins.py
- bokeh/core/query.py
- bokeh/core/state.py
- bokeh/core/templates.py
- bokeh/core/validation/__init__.py
- bokeh/core/validation/check.py
- bokeh/core/validation/decorators.py
- bokeh/core/validation/errors.py
- bokeh/core/validation/exceptions.py
- bokeh/core/validation/warnings.py
- examples/app/export_csv/main.py
- sphinx/source/docs/reference/core.rst
- sphinx/source/docs/reference/core/compat.rst
- sphinx/source/docs/reference/core/enums.rst
- sphinx/source/docs/reference/core/json_encoder.rst
- sphinx/source/docs/reference/core/properties.rst
- sphinx/source/docs/reference/core/property_containers.rst
- sphinx/source/docs/reference/core/property_mixins.rst
- sphinx/source/docs/reference/core/query.rst
- sphinx/source/docs/reference/core/state.rst
- sphinx/source/docs/reference/core/templates.rst
- sphinx/source/docs/reference/core/validation.rst
issues: fixes #5627 
This PR splits the overly long docs page for `bokeh.core` up into individual pages for each module [*]. It also adds expanded and complete docstrings for all public and private functions, with the exception of:
* `bokeh.compat` I have described this as unmaintained until MEP25, and have also removed the directory from the test reporting
* `bokeh.properties` A follow on PR is planned to move low level things into `property_bases.py` and will update the docs then. 
This PR also:
* removes the `encoder` argument to `serialize_json` as it was unused
* removes `bokeh.core.validation.exceptions` which was unused. 
* fixes a small bug in `export_csv` app example
[*] slight fib, the `bokeh.validation` package is documented as if it was a single module (which it probably …
> Overhaul bokeh.core docs

- bokeh/charts/stats.py
- bokeh/charts/tests/test_stats.py
Trivial fix that skips rounding of `center` position strings.
> Resolve overlapping histogram bars (#3315)

- bokehjs/gulp/tasks/test.coffee
- bokehjs/package.json
gulp-mocha doesn't work and is unmaintained, so just use `child_process.spawn()` and run mocha natively.
fixes #5659
> Use custom code instead of gulp-mocha for running tests

- bokehjs/src/coffee/core/util/templating.coffee
CoffeeScript variable substitution requires double quotes, not single quotes.
> safe-tag-fix

- bokeh/models/renderers.py
- bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
issues: fixes #2414 
Makes it possible to specify `selection_glyph=None` to mean no policy (i.e. use regular glyph)
Default behaviors are unchanged.
> allow auto for non/selection glyphs

- bokeh/charts/builders/donut_builder.py
Also fix a typo in the documentation for these options.
Related to issue #3621, though doesn't address every aspect discussed there.
> Make the default hover tooltip work for Donut charts.

- scripts/travis_install
MPL 2.0 is breaking our mpl compat tests. Assuming this pinning works, we should probably add a note to the release notes, and possibly an explicit version check and error in `bokeh.core.compat`
ping @bokeh/dev
> pin MPL < 2.0

- sphinx/source/docs/dev_guide/testing.rst
- tests/integration/interaction/test_datatable.py
- tests/integration/interaction/test_sizing_mode.py
Fixes integration tests that fail when run with python 2.7. 
I also added some additional documentation on running screenshot tests.
> Integration tests for python 2.7

- bokehjs/src/coffee/core/has_props.coffee
- bokehjs/test/core/has_props.coffee
This fixes #5706 by storing any materialized shape information under the canonical property name, not the field name. Also adds tests for `materialize_dataspecs`
> store materialized shape data under canonical property names

- bokeh/models/sources.py
fixes #5718
New section renders like this:
@birdsarah is this reasonable, is there anything else to add?
> improve the helpstring for CDS selected property

- bokehjs/src/coffee/core/util/spatial.ts
- bokehjs/src/coffee/models/glyphs/annular_wedge.coffee
- bokehjs/src/coffee/models/glyphs/annulus.coffee
- bokehjs/src/coffee/models/glyphs/arc.coffee
- bokehjs/src/coffee/models/glyphs/bezier.coffee
- bokehjs/src/coffee/models/glyphs/circle.coffee
- bokehjs/src/coffee/models/glyphs/ellipse.coffee
- bokehjs/src/coffee/models/glyphs/glyph.coffee
- bokehjs/src/coffee/models/glyphs/hbar.coffee
- bokehjs/src/coffee/models/glyphs/image.coffee
- bokehjs/src/coffee/models/glyphs/image_rgba.coffee
- bokehjs/src/coffee/models/glyphs/line.coffee
- bokehjs/src/coffee/models/glyphs/multi_line.coffee
- bokehjs/src/coffee/models/glyphs/oval.coffee
- bokehjs/src/coffee/models/glyphs/patch.coffee
- bokehjs/src/coffee/models/glyphs/patches.coffee
- bokehjs/src/coffee/models/glyphs/quad.coffee
- bokehjs/src/coffee/models/glyphs/quadratic.coffee
- bokehjs/src/coffee/models/glyphs/ray.coffee
- bokehjs/src/coffee/models/glyphs/rect.coffee
- bokehjs/src/coffee/models/glyphs/segment.coffee
- bokehjs/src/coffee/models/glyphs/text.coffee
- bokehjs/src/coffee/models/glyphs/vbar.coffee
- bokehjs/src/coffee/models/glyphs/wedge.coffee
- bokehjs/src/coffee/models/glyphs/xy_glyph.coffee
- bokehjs/src/coffee/models/markers/marker.coffee
- examples/custom/gears/gear.coffee
Originally this was supposed to fix issue #5783, but as kdbush doesn't support rectangles, it cannot be universally used, just as an optimization for point search, but a cleanup and addition of an abstraction layer is still useful. This can be used to add support for kdbush in fugure.
> Provide an abstraction layer on top of rbush

- bokeh/sampledata/us_counties.py
Deals with #5835. I did not add any tests. I put relevant info in the docstring of the us_counties module.
I know this is just sample data but it is actually an incredibly useful source of data. This PR enables people to match to counties by name and state (in the case that the FIPS code is not in the data). Here is some code showing the data contains duplicates on 'state' and 'name':
and here is an example of an occurrence of a duplicate in the data source:
This issue came about because I had some data without FIPS codes for the states and counties but had the names of the states and counties. I happened to be plotting Virginia and I immediately noticed that some of the counties were not being found in the sample data:
Then I did my little hack that I propose here so that I could match …
> add detailed name in counties sampledata api to enable matching by name

- bokehjs/test/models/annotations/annotation.coffee
- bokehjs/test/models/axes/axis.coffee
- bokehjs/test/models/canvas/canvas.coffee
- bokehjs/test/models/plots/plot.coffee
- bokehjs/test/models/plots/plot_canvas.coffee
- bokehjs/test/models/tools/actions/zoom_in_tool.coffee
- bokehjs/test/models/tools/actions/zoom_out_tool.coffee
- bokehjs/test/models/tools/gestures/wheel_pan_tool.coffee
- bokehjs/test/models/tools/gestures/wheel_zoom_tool.coffee
- bokehjs/test/models/tools/inspectors/crosshair_tool.coffee
issues: fixes #4539 
In this PR, I wrapped test functions with `sinon.test`. From ["Best Practices for Spies, Stubs and Mocks in Sinon.js"](https://semaphoreci.com/community/tutorials/best-practices-for-spies-stubs-and-mocks-in-sinon-js):
> Use sinon.test Whenever Possible
When you use spies, stubs or mocks, wrap your test function in sinon.test. This allows you to use Sinon's automatic clean-up functionality. Without it, if your test fails before your test-doubles are cleaned up, it can cause a cascading failure - more test failures resulting from the initial failure. Cascading failures can easily mask the real source of the problem, so we want to avoid them where possible.
These changes fix the errors from the layout tests for me. @mattpap
> use sinon.test to increase layout test robustness

- bokehjs/test/common/selection_manager.coffee
fixes #5121 
These tests originally relied on the `get` method which was removed in PR [5106](https://github.com/bokeh/bokeh/pulls/5106). I updated them and added a comment about why the stub objects are the way there are.
> fix selection manager tests after getter/setter PR 5106

- bokeh/command/subcommands/serve.py
issues: fixes #5834 
Usage such as `--host='*'` fails on windows, but not OSX or Linux. Only demonstrate usage such as `--foo bar`, which will work on all platforms, instead of `--foo=bar`
> demonstrate argparse usage that works across platofrms

- bokeh/document.py
- bokeh/server/session.py
- bokeh/server/tests/test_session.py
- bokeh/tests/test_document.py
Previously, due to circular references, a Document was never GC'd, and thus
sys.modules kept increasing for each page request.
This patch explicitly cleans up sys.modules after a session is destroyed.
Verified that `len(sys.modules)` does not increase over time (which it did before).
Fixes #5848
TODO: add tests
> Document: fix memory leak by explicitly deleting sys.modules on session destroy

- bokeh/tests/test_embed.py
- conda.recipe/meta.yaml
Beautiful soup was using different HTML parsers across different  builds, causing tests to fail. Explicitly require `lxml`, which `bs4` regards as the "best" (and which matches our current tests)
> explicitly require lxml for testing

- bokeh/models/sources.py
As described in https://github.com/bokeh/bokeh/issues/5871, the ColumnDataSource constructor triggers validation on all the columns for every column that is passed to the constructor, which is highly inefficient. By using ``self.data.update`` the validation is only triggered once resulting in considerably speed improvements for large datasets.
It would be important to know if there is any particular reason why it was using ``.add`` in the first place.
> ColumnDataSource constructor optimization

- tests/examples/examples_report_plugin.py
Using `origin` is presumptuous and works only for core dev workflow, but not necessarily in forks, which can have the origin (upstream) configured to something different than the literal `origin`.
fixes #5888
> Use `master@{upstream}` instead of `origin/master` as the default diff-ref

- bokeh/client/session.py
- bokeh/command/subcommands/serve.py
- bokeh/command/subcommands/tests/test_serve.py
- bokeh/core/_templates/autoload_js.js
- bokeh/core/_templates/doc_js.js
- bokeh/embed.py
- bokeh/resources.py
- bokeh/server/server.py
- bokeh/server/tests/test_tornado.py
- bokeh/server/tests/utils.py
- bokeh/server/tornado.py
- bokeh/server/views/autoload_js_handler.py
- bokeh/server/views/doc_handler.py
- bokeh/tests/test_client_server.py
- bokeh/tests/test_resources.py
- bokehjs/src/coffee/embed.coffee
- scripts/tests/test_api_report.py
- sphinx/source/docs/releases/0.12.5.rst
- sphinx/source/docs/user_guide/server.rst
- tests/test_no_request_host.py
This PR makes it possible for the server to supply relative URLs for resources, which may be needed for certain kinds of deployments behind proxies. It's not yet clear if the WS code also needs changing, awaiting more input from @dhuebner
> Allow configuring server to provide relative URLS for resources

- sphinx/source/docs/dev_guide/server.rst
* Just fixing a typo so that the link at the top of dev_guide/server.html
correctly points to user_guide/server.html
* doc change only.  locally built docs to confirm fixed link
> Fix broken link in top of dev_guide/server.html (#5891)

- sphinx/source/docs/user_guide/annotations.rst
Added missing comma to example code as described in Issue #5902
> Fixed typo in user_guide/annotations.rst

- examples/embed/simple/simple.py
- examples/embed/simple/templates/embed.html
The color information was passed to the template but was not used at all. I did very minor changes to:
1. Send the color name instead of the color numerical code in the simple.py app.
2. Use conditional `if` in the `embed.html` template in order to put the `selected` parameter in the right color.
With this changes, the selected color in the form is used for the default value.
> Including the color option in the embed simple example

- bokehjs/src/coffee/core/util/array.ts
- bokehjs/test/core/util/array.coffee
- bokehjs/test/core/util/index.coffee
The intersection method in core.util.array returns the intersection between an array and others by looping over values in the first array and seeing whether each value is in all other arrays. There was a small bug where the outer loop would terminate if any value in the first array was not in all others instead of continuing to the next value. 
The only place that intersection is used currently is [here in document.coffee](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/document.coffee#L463), and I didn't investigate that any further. 
I'm just probably going to need this method for CDS filtering/grouping.
I didn't create an issue since it was such a small fix, but let me know if anyone thinks I should. 
~- [ ] issues: fixes #xxxx~
> Fix for small bug in array intersection method

- bokehjs/src/coffee/core/has_props.coffee
- bokehjs/test/document.coffee
Previously, a call to `prop.update` for model properties happened in `attach_document`. But attach_document was not being called for new models added in patches to existing documents, causing problems. This PR adds a (deferred) initializer to HasProps that ensures proper property setup for all models is completed in a consistent way, always.
I don't have a good test to add at the moment. I am going to add a separate issue to improve/refactor BokehJS properties to split up the creation/initialization into more usable and testable chunks.
> Make sure properties are updated on (deferred) init

- .travis.yml
Disable Saucelabs tests until time can be set aside to diagnose the current unexpected failures.
> Disable Saucelabs tests for now

- bokeh/io.py
- sphinx/source/docs/releases/0.12.5.rst
> Creates tempfile when output_filename is not writable (notebook)

- bokeh/models/transforms.py
issues: fixes #5887 
Looks like the methods to be implemented were indented one space too many, and missed by sphinx.
> DOC : Transforms methods dedent for Sphinx

- examples/app/gapminder/main.py
issues: fixes #5152
The original code created a CDS for every year of data, but only used the first CDS in the document, switching out .data on upates. It's worth investigating why this caused a problem separately, but this usage is not advised in any case. (The new code is also faster) Bokeh models should be created when they are intended to be put in a Document. Internal data storage is best left to non-Bokeh data structures.
> Don't use "Dummy" bokeh models

- sphinx/fabfile.py
Can't SSH by DNS name any longer, must use IP address.
> Update docs upload to work now that host site is behind cloudflare

- bokeh/embed.py
- bokehjs/gulp/paths.coffee
- bokehjs/gulp/tasks/scripts.coffee
- bokehjs/src/coffee/core/util/color.coffee
- bokehjs/src/coffee/models/canvas/canvas.coffee
- bokehjs/src/coffee/models/glyphs/glyph.coffee
- bokehjs/src/coffee/models/glyphs/webgl/index.ts
- bokehjs/src/coffee/models/glyphs/webgl/main.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
- bokehjs/test/common/selection_manager.coffee
- bokehjs/test/size.coffee
- scripts/build_upload.py
- sphinx/source/docs/releases/0.12.5.rst
- sphinx/source/docs/user_guide/webgl.rst
Reduces `bokeh.min.js` size from 699 to 636 kB. `gloo2` and `models/glyphs/webgl` were moved to `bokeh-gl` bundle, which is automatically included if `Plot.webgl == True`. The logic is the same, i.e. there are no new models and `webgl` is left. This also means that the code is still a mess, with webgl popping up everywhere, but at least the bulk of the webgl code is in the new bundle.
fixes #4321
> Move webgl glyphs and related code to bokeh-gl bundle

- bokehjs/src/coffee/model.coffee
Small fix to code merged from #5941: in ``Model._process_event`` the variable``event_name`` is undefined and it should be ``event.event_name``. 
After this fix, there are no more exceptions in the web console when running ``events_app.py``. Note this code path isn't executed when running ``js_events.py`` which is why I didn't notice this problem earlier.
> Fixed bug in Model._process_event method

- bokeh/embed.py
- bokeh/resources.py
- bokeh/server/views/autoload_js_handler.py
- bokeh/util/compiler.py
- bokeh/util/notebook.py
This allows to use custom models with `components()` by moving custom models' bundles from resources to embed.
fixes #5353
> Make custom models' bundle part of embed instead of resources

- examples/embed/animated.py
- examples/embed/widget.py
> when embedding with autoload into a page with a different public URL need relative_urls=False

- bokeh/model.py
- bokeh/util/serialization.py
Isinstance checks can be surprisingly costly when applied to many small
objects.  This avoids many calls to isinstance in
_visit_value_and_its_immediate_references by doing two things:
1.  Short circuiting on common types.  These appear to be 90% of all
inputs to this funciton
2.  Rearranging the if-tree to prefer more commonly succeeding checks
before less commonly succeeding ones
In my benchmark isinstance calls took up around 5% of computation time
and now they take up around 2%
> Avoid isinstance checks in _visit_value_and_its_immediate_references

- bokehjs/src/coffee/models/ranges/data_range1d.coffee
- bokehjs/src/coffee/models/ranges/range1d.coffee
- bokehjs/test/models/ranges/range1d.coffee
- tests/integration/interaction/test_reset_tool.py
After discussing https://github.com/bokeh/bokeh/issues/6075 with @canavandl we determined that for the time being it should be safe to trigger Range1d change events on reset. Unlike DataRange1d the ranges on Range1d are not recomputed by ``PlotCanvasView.update_dataranges``, which ends up triggering a "loud" change when it eventually call ``DataRange1d.update``. So this change simply ensures that both trigger the appropriate changes. In future it might be nice to move some of the logic on PlotCanvasView onto the ranges and handle triggering of events more consistently but for the time being this addresses the immediate issue.
WIP as I probably need to update some tests.
> Ensure Range1d triggers start/end change events on reset

- bokehjs/gulp/tasks/install.coffee
tiny tweak. Use --install-js (not --install_js) in gulp install task to silence warn.
> Use --install-js not install_js to silence warn

- bokeh/events.py
- bokeh/tests/test_events.py
- bokehjs/src/coffee/document.coffee
- bokehjs/src/coffee/model.coffee
- examples/howto/events_app.py
- examples/howto/js_events.py
- sphinx/source/docs/reference/events.rst
- sphinx/source/docs/releases/0.12.5.rst
- sphinx/source/docs/user_guide/examples/js_events.py
- sphinx/source/docs/user_guide/interaction/callbacks.rst
This PR fixes the issue described in #6059 and tweaks how JS callbacks are used.
The fix was to make sure the event managers ``subscribed_models`` attribute was being updated when Python callbacks are registered without needing a corresponding JS callback. The model now also listens to changes to the ``subscribed_events`` property instead of just listening to changes to the ``js_event_callbacks`` property.
In addition, the event instance is now passed as the ``cb_obj`` which is more consistent with how the Python callbacks are defined as well as with other usage of ``CustomJS`` callbacks.
> Event system fixes and improvements

- bokehjs/src/coffee/core/ui_events.coffee
Only use crosshair cursor if inspector-type tool is active.
> Correct cursor handling

- bokeh/models/sources.py
Do this because it misled me for quite a while until I figured out what was going on.
I respect wanting matching issues, but I really couldn't bring myself to do so for such a small thing.  Feel free to reject of course.
> Fix typo in selection documentation.

- scripts/issues.py
issues: fixes #6102 
I ran this six times without a token and got a 403 Forbidden message.
With the token, I was able to consistently get the following output
``` 
$ BOKEH_GITHUB_API_TOKEN=<token> python issues.py -c -p 0.12.4
INFO:root:finding issues...
WARNING:root:issue with no type label: #6109 Notebook embed example is not working
WARNING:root:closed issue with no reso label: #6109 Notebook embed example is not working
```
> Add ability to use github api token

- bokehjs/src/coffee/core/dom.ts
This is wrong on top of being wrong. The problem is that DOM doesn't have a reasonable solution for maintaining a group of HTML elements. I'm gradually replacing templates with inline code, so this branch will be removed sooner or later.
fixes #6124
> Silence invalid type cast error in core/dom.ts

- sphinx/source/docs/user_guide/embed.rst
issues: fixes #6047
Also:
* updates versions for CDN example links
* edits some output text for line length
* adds a note that components does not apply to server apps
> Update obsolete output examples in bokeh.embed docs

- sphinx/source/docs/user_guide/examples/interaction_open_url.py
- sphinx/source/docs/user_guide/interaction.rst
- sphinx/source/docs/user_guide/interaction/callbacks.rst
- sphinx/source/docs/user_guide/interaction/widgets.rst
- sphinx/source/docs/user_guide/server.rst
issues: closes #5819
This makes it clear that OpenURL is only for TapTool and only happens on
selections. Offers link to CustomJS for UI events section for general
tap callbacks.
Also rationalizes sphinx link names in this section, and removes unused
link refs for "specialized" callbacks.
> update openurl docs

- bokeh/core/property/bases.py
- bokeh/core/property/tests/test_bases.py
- bokeh/models/glyphs.py
- bokeh/models/sources.py
- bokeh/models/tests/test_sources.py
issues: closes #6044
Previously, `Property.asserts` could be provided a function accepting no
arguments to call when an assertion failed. This PR modifies he Property
machinery to expect and call a function accepting `(obj, name, value)` so
that error messages can be more informative.
This PR also adds a new ``core/property/tests/test_bases.py`` to maintain the
property assertion functionality.
Finally, this PR removes an unused code path for assertions that would
automatically raise a ValueError if the assertion function returned a
value other than `True` or` False`, on the grounds that explicitly
separating th check and message is preferable, and to simplify the
logic. A (python) assertion was added to enforce that a (Bokeh) assertion
returns a bool, always.
> Allow for richer property assertion messages

- sphinx/source/docs/user_guide/examples/interaction_legend_mute.py
- sphinx/source/docs/user_guide/interaction/legends.rst
This updates the example by including the visual property `muted_color`.
> Steven c howell/6158 muted color

- bokeh/charts/chart.py
- bokeh/models/tests/test_tools.py
- bokeh/models/tools.py
- bokeh/plotting/figure.py
- bokeh/plotting/gmap.py
- bokeh/plotting/helpers.py
- bokehjs/src/coffee/core/ui_events.coffee
- bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
- bokehjs/src/coffee/models/tools/toolbar.coffee
- bokehjs/test/common/ui_events.coffee
- bokehjs/test/models/tools/toolbar.coffee
- sphinx/source/docs/user_guide/tools.rst
Add support for Toolbar.active_inspect property, so that users can specify which inspect tools are active on plot initialization.
> Add support for Toolbar.active_inspect property

- bokeh/models/annotations.py
- bokeh/models/formatters.py
- bokeh/models/tools.py
- bokeh/models/widgets/buttons.py
- sphinx/source/docs/releases/0.12.6.rst
@bokeh/dev this removes all deprecations up through `0.12.3` which includes some fairly gorpy code that will be good to jettison. Absent comments or concerns I will plan to merge this tomorrow.
> remove deprecations up to 0.12.3

- bokeh/models/tools.py
- bokehjs/src/coffee/models/glyphs/line.coffee
- bokehjs/src/coffee/models/glyphs/segment.coffee
issues: closes #6161
adds _hit_point and _hit_span to the Segment glyph so that it can work with hover tools.
Also updates HoverTool docstring to indicate segments is not functional with hover tools (as well as multi line which was erroneosly listed as unsupported)
Also makes a minor change to line hit-testing. From inspection the existing code would appear to fail on lines that "go backwards"
> Add hover tool support for Segment

- bokehjs/src/coffee/models/glyphs/multi_line.coffee
issues: fixes #6130
Not really a good way to add a  test for a view, definitely want to visit adding view models to hold "view state" that's not directly part of the model.
> Use cache select to get line_widths correctly in all cases

- bokehjs/src/coffee/core/layout/side_panel.coffee
issues: fixes #5914
with this fix:
> use proper alignment for vertical ticks below a plot

- bokeh/core/enums.py
- bokeh/core/tests/test_enums.py
- bokeh/models/ranges.py
- bokehjs/src/coffee/core/enums.coffee
- bokehjs/src/coffee/core/properties.coffee
- bokehjs/src/coffee/models/ranges/data_range1d.coffee
- bokehjs/test/models/ranges/data_range1d.coffee
Adds range_padding_units property to DataRange1d which can be either
"percent" or "absolute". The default is "percent" (matching existing
behaviour)
Also tightens up the follow property with a proper enum.
> Add support for absolute range padding amounts

- bokeh/core/properties.py
- bokeh/core/tests/test_properties.py
This PR doesn't add any validation on the JS side but should alert to bad values set from python. 
makes the assumption that column names do not begin with digits (or if they do, that `field` is used explicitly)
> better validation for font size values

- bokeh/embed.py
Currently, themes are only applied when using `components` to embed plots.
Trivial fix
> Support themes in file_html embedding

- bokehjs/.gitignore
- bokehjs/.istanbul.yml
- bokehjs/gulp/tasks/test.coffee
- bokehjs/package.json
issues: fixes #5694
I am sure there is a better way to do this but this gets this provides useful information now. This adds a new command `gulp test:coverage` which can be run locally. It adds general coverage stats to the end of the test run:
And also saves a detailed HTML coverage report
Obviously the report would be improved if it referenced the original coffee or TS source files instead of the built JS.
> add gulp test:coverage

- bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
issues: fixes #5198 
Ok this does not add any tests but the current hover tool code is basically untestable. Here is a screenshot for evidence:
I'd like to make a separate issue to cleanup and refactor all the hover tool code and add tests. I am fairly certain the multiglyph double loop is doing wasted work (i.e. it loops `'i` over 1d then masks `i` to loop over 2d inside that loop)
> fix up hit testing with 'next' policy

- bokehjs/src/coffee/models/widgets/cell_editors.coffee
- bokehjs/src/coffee/models/widgets/data_table.coffee
- bokehjs/test/models/widgets/data_table.coffee
- bokehjs/test/models/widgets/index.coffee
This PR allows for sorting and selection on data tables to work properly together. Except for explicit cell editing, this PR changes the table implementation so that no modifications are made to the input data source (except by explicit user edits). Instead, an index is created (and stored outside the source data). The index is permuted by sorts, and is used to inform get, set, and selections operations.
> stab at fixing selections + sorting in data table

- bokehjs/src/coffee/core/bokeh_events.ts
I came across a bug in the MouseWheel event. The bug can be shown by running this app from the howto section:
bokeh/examples/howto/events_app.py
The value for "delta" of the scroll event was showing up as NaN / None in both js_on_event and on_event callbacks.
Without fully understanding how everything's connected, I was able to trace the problem to line 162 of bokeh/bokehjs/src/coffee/core/bokeh_events.ts
Changing 
~~~
static from_event(e: any, model_id: string = null) {
return new this({
sx: e.bokeh['sx'],
sy: e.bokeh['sy'],
delta: e.delta,
model_id: model_id,
})
}
~~~
to 
~~~
static from_event(e: any, model_id: string = null) {
return new this({
sx: e.bokeh['sx'],
sy: e.bokeh['sy'],
delta: e.bokeh['delta'],
model_id: model_id,
})
}
~~~
fixes the problem, and allows the delta parameter …
> fixed reference to delta in scroll event - fixes #6238

- bokeh/core/_templates/file.html
- bokeh/tests/test_embed.py
This changes the default Jinja template to escape the title value.
> Escape HTML title

- bokeh/models/plots.py
- bokeh/models/tests/test_plots.py
- bokeh/plotting/helpers.py
- bokeh/plotting/tests/test_figure.py
- bokehjs/src/coffee/api/plotting.coffee
- bokehjs/src/coffee/api/typings/models/plots.d.ts
- bokehjs/src/coffee/models/canvas/cartesian_frame.coffee
- bokehjs/src/coffee/models/plots/plot.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
- bokehjs/test/models/canvas/cartesian_frame.coffee
Deprecate x/y_mapper_type Plot kwargs in place of first-class Scale models
> Deprecate x/y_mapper_type Plot kwargs in place of first-class Scale models

- bokeh/models/glyphs.py
- bokehjs/src/coffee/models/glyphs/image_url.coffee
- bokehjs/test/models/glyphs/image_url.coffee
- examples/models/file/image_url.py
The issue was that the view properties like `@_w` are now converted to lists `[null]` when `@model.w` is `null` (or `None` on the python side). I have no opinion on whether this is reasonable (it could probably be argued either way). So this PR fixes things by checking `@model.w` directly, which is an unequivocal and always-correct source of truth in this question. 
I have also removed the note about possibly changing the property names to `dw` and `dh`. That ship has sailed. 
Finally, I changed the example to pass an empty CDS to the last "values-only" call to `ImageURL`. This is because we normally "broadcast" values to the size of the CDS. this results in the same image being rendered 5 times. The broadcasting is a reasonable thing in general. It could be simply considered a usage …
> properly check for ImageURL w, h for None

- bokeh/sphinxext/bokeh_github.py
closes #6269
Standard URLs are not verified in any way in normal Sphinx usage, that should be the case here as well. Link checking should be left to other tools.
Also makes an internal helper function private.
> Disable URL checking in bokeh GH sphinx directives

- bokeh/core/json_encoder.py
- bokeh/core/properties.py
- bokeh/core/property_mixins.py
- bokeh/core/tests/test_json_encoder.py
- bokeh/core/tests/test_properties.py
- bokeh/models/annotations.py
- bokeh/models/glyphs.py
- bokeh/util/serialization.py
- bokeh/util/tests/test_serialization.py
- sphinx/source/docs/releases/0.12.6.rst
This PR adds a parameter `accept_datetime` to NumberSpec that defaults to True. When enabled, NumberSpecs will accept and immediately convert datetime values to serialized ms-since-epoch values. This allows glyphs and annotations to be positioned using datetime values.
NumberSpec was also modified to always accept and convert timedelta objects. 
This also fixes a future warning from pandas regarding `pd.tslib`
Datetime/timedelta detection and conversion was moved to `bokeh.util.serializtion` so that the code might be shared. As part of this, the handling of Python `datetime` values was corrected to match the handling of NumPy `datetime64`
@mattpap @canavandl I would appreciate a close review of this PR
> Allow datetime values for number specs by default

- bokehjs/src/coffee/models/annotations/arrow.coffee
- bokehjs/src/coffee/models/annotations/band.coffee
- bokehjs/src/coffee/models/annotations/label_set.coffee
fixes #4872
Arrow, Band, and LabelSet were missing signal connections to `source.streaming` and `source.patching` necessary for these annotations to update when their data sources are streamed or patched.
This PR adds the missing signal connections. When reasonable, a `request_render` was moved to `set_data` (this is ok when there is not any CSS/dom rendering path)
Test case:
```
from random import randrange
from bokeh.io import curdoc
from bokeh.layouts import layout
from bokeh.models import ColumnDataSource, Arrow, NormalHead
plot = figure(x_range=(0, 10), y_range=(0, 10))
source = ColumnDataSource(data={'x0': [], 'y0': [], 'x1': [], 'y1': []})
plot.circle(x=0, y=0)
plot.add_layout(
Arrow(end=NormalHead(size=4), x_start='x0', y_start='y0', x_end='x1', …
```
> Add plumbing for streaming and patching annoations

- bokehjs/gulp/tasks/scripts.ts
- bokehjs/package.json
- bokehjs/src/coffee/core/util/array.ts
- bokehjs/src/coffee/core/util/math.ts
- bokehjs/src/coffee/core/util/object.ts
- bokehjs/src/coffee/models/widgets/cell_formatters.coffee
- bokehjs/src/js/compile.coffee
- bokehjs/test/defaults.coffee
- bokehjs/test/document.coffee
- bokehjs/test/models/layouts/box.coffee
- bokehjs/test/models/layouts/spacer.coffee
- bokehjs/test/models/layouts/widget_box.coffee
- bokehjs/test/models/plots/plot.coffee
- bokehjs/test/models/tiles/tile_renderer.coffee
This removes last imports of underscore and uses underscore.template for templating and code under `core/util` otherwise.
fixes #6207
> Replace underscore with underscore.template

- bokeh/models/widgets/tables.py
- bokehjs/src/coffee/models/widgets/data_table.coffee
Addresses allowing fixed columns in datatable. https://github.com/bokeh/bokeh/issues/6286
Assuming no extra documentation is needed. 
If a test is needed I can do that too tomorrow.
> Enabling/ Disabling re-ordering of columns in DataTable (freezing columns in place)

- bokeh/core/json_encoder.py
- bokeh/core/property/containers.py
- bokeh/core/property/tests/test_containers.py
- bokeh/core/tests/test_json_encoder.py
- bokeh/models/sources.py
- bokeh/models/tests/test_sources.py
- bokehjs/src/coffee/models/glyphs/glyph.coffee
- bokehjs/src/coffee/models/glyphs/image_rgba.coffee
- bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
- bokehjs/src/coffee/models/sources/column_data_source.coffee
- bokehjs/src/coffee/models/sources/columnar_data_source.coffee
- bokehjs/test/models/sources/column_data_source.coffee
- examples/app/spectrogram/waterfall.coffee
- examples/howto/patch_app.py
This PR extends the CDS patch capability to more kinds of patch values. In particular, it can now patch sub-portions of "array" element. This is most useful for, e.g. updating data for image, patches, and multi-line glyphs.
Patches are still of the form `(index, new_data)` but now the index can be a slice, or a list of integers and slices (with correspondingly sized new data) The kinds of patches now accepted are summarized below:
```
(10, 100)
(slice(2), [100, 101])
([1, 4], [6])
([0, slice(2, 4)], [100, 101])
([1, 4, slice(None)], [1, 2, 3, 4, 5])
([0, slice(2, 4), 2], [100, 101])
```
> Extend CDS patching to sub-elements in columns

- bokeh/server/server.py
issues: fixes #6319 
This avoids a ResourceWarning with the HTTP server's listening socket(s).
> Fix #6319: close HTTP server explicitly when closing Bokeh server

- bokeh/core/properties.py
- bokeh/core/tests/test_properties.py
Fixes issue #6316 associated with ``ScreenDistanceSpec`` and ``DataDistanceSpec`` attempting to set ``units`` directly on a container, triggering a validation error. I'm still looking for a small reproducible example that could be tested but this seems to be the safer approach regardless.
> Ensure DataSpec.to_serializable returns new dict

- bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
To be able to identify which renderer invoked the callback from within the JS
> Adds the renderer object to cb_data

- bokehjs/src/coffee/core/has_props.coffee
- bokehjs/src/coffee/core/properties.coffee
- bokehjs/src/coffee/core/signaling.ts
- bokehjs/src/coffee/core/util/string.ts
- bokehjs/src/coffee/core/view.coffee
- bokehjs/src/coffee/document.coffee
This is a side effect of work on layout. Changes in this PR:
fixes #6336
> Silence all change events during initialization of models

- bokehjs/src/coffee/models/layouts/box.coffee
I feel dirty writing code like this, but I don't see any other option, perhaps besides restoring old logic with invalidating all models every time `children` change (which isn't any better). Now I know why this code was there before. There are two proper solutions to this issue. One is fix document to attach itself to all new objects, which, to my surprise, doesn't work or at least doesn't work early enough. The other is move layout logic to views, but due to `LayoutCanvas` model and lack of `LayoutCanvasView`, it's pretty much impossible right now to do so.
fixes #6261
> Hack around unset document in Box's layout computations

- bokehjs/src/coffee/models/annotations/legend.coffee
This change makes the origin for legends in the left/right panel be based on the top left corners of the left/right side panels instead of the bottom left corner. This matches the behavior from 0.12.4.
> Fix regression in legend location

- bokeh/models/plots.py
Fix up webgl and x/y_mapper_type deprecation. Was missing adding the deprecated attrs as __deprecated_attributes__ so the property system would defer to the models getters/setters.
> Fix up webgl and x/y_mapper_type deprecation

- bokehjs/src/coffee/models/plots/gmap_plot_canvas.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
- bokehjs/test/models/plots/plot_canvas.coffee
issues: fixes #6328
This fixes issues with `pause` and `unpause`. These functions were being called in the `PlotCanvasView` initializer, but *not* in the subclass `GMapPlotView` initializer. This could result in calls to `request_render` too early.  Specifically wrt to gmaps, this could cause `_build_map` to be called before the plot was otherwise initialized and ready to render, which in turn results in a blank gmap. 
To fix pause/unpause for now, needed to change from simple boolean to a condition counter to keep track of "pause level", so that on pause/unpause pair nested in side another (via a function call, say) would be handled correctly. Additionally, put an explicit guard in `render` itself to prevent any renders during a pause regardless of how they were triggered. I don't think …
> fix promblems with render pause/unpause

- bokeh/sphinxext/bokeh_gallery.py
> gallery toctree path should not use os separator, always backslash

- bokeh/models/tools.py
- bokehjs/src/coffee/models/tools/inspectors/inspect_tool.coffee
- bokehjs/src/coffee/models/tools/toolbar_base.coffee
issues: fixes #6064
Until there is a better solution to consolidating multiple hover tools in toolbars, this feature at least allows users who have multiple hover tools the option of hiding some or all of the buttons in the toolbar.
> add a toggleable property to inspectors

- bokehjs/src/coffee/models/widgets/range_slider.coffee
fixes #6123
Not 100% about this solution but it seems like a "good-enough" solution for the immediate term. It makes things usable at all (and for probably most common use cases) until broader jq refactor can take place. 
This code:
```
from bokeh.io import curdoc
from bokeh.models import RangeSlider
slider = RangeSlider(start=0, end=10, range=(1,9), step=.1, title="Stuff")
def cb(attr, old, new):
print(slider.range)
slider.on_change('range', cb)
curdoc().add_root(slider)
```
Behaves as expected:
> Do not over-execute range slider render

- bokeh/core/property/bases.py
- bokeh/core/property/tests/test_bases.py
This PR adds handling of Pandas types explicitly, as well as adds back overall exception fallback in any case. 
Without this, `export_csv` example would work but show errors like
```
2017-06-06 20:36:45,200 error handling message Message 'PATCH-DOC' (revision 1): ValueError('The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().',)
```
With this, dicts of arrays, series, and indices are compared correctly (tests added)
ping @mattpap
> More explicit match cases

- bokehjs/src/coffee/models/tools/gestures/tap_tool.coffee
issues: fixes #6400
The loop was iterating over an object indexed by data source id's and passing the id as the data source to the callback. This PR correctly grabs the actual data source.
If there is any good test that is reasonable to add I'd appreciate suggestions.
> extract data source correctly on line selections

- bokehjs/src/coffee/core/util/object.ts
- bokehjs/test/core/selector.coffee
This PR fixes the merging of 2d selections. The merge function was moved into object.ts from hittest in [PR 6202](https://github.com/bokeh/bokeh/pull/6202). Before the move, the result of merge was created by `result = {}`. When it was moved to typescript, it became `result = Object.create(null)`. But `result = {}` creates an object whose prototype is Object.prototype, so in object.ts, it should be `result = Object.create(Object.prototype)`. We need the returned object to have Object methods, like `hasOwnProperty`. 
The test "Selector should merge 2d selections with append=true" fails before the change.  
```
1) Selector should merge 2d selections with append=true:
TypeError: obj1.hasOwnProperty is not a function
at Object.merge (build/js/tree/core/util/object.js:43:25)
at …
```
> Fix merging of 2d selections

- setup.py
This should be merged AFTER the new bkcharts is available in `defaults`
> bump required bkcharts version to 0.2

- bokeh/core/_templates/autoload_js.js
Without this `try/finally` if there is an exception in the the load callback then it is not deleted, and the next time output is attempted, the old callback is tried to run again, again resulting in an error. (i.e. permanently corrupting a notebook until a clear restart)
> protect against exceptions when running inline code

- bokehjs/src/coffee/models/widgets/data_table.coffee
- bokehjs/test/models/widgets/data_table.coffee
Restore workaround to properly trigger changes in source.data 
Fix typo in tests for data_table.setItem
The workaround used was restored from 260f5765b63060b60680f7f3c7e91df0a5ed637e using the new emit API.
> Restore workaround to properly trigger changes in source.data from data_tables

- scripts/build_upload.py
`--build-only` does not leave build artifacts in `conda-bld/noarch` for whatever reason
Will test with a `0.12.7dev2`
> revert conda build to --no-test

- bokeh/util/serialization.py
- bokeh/util/tests/test_serialization.py
The intent behind this PR is to send all datetime values to BokehJS "as-is". If a user wanted to perform timezone conversion, that could be done explicitly with a custom tick formatter. LAter perhaps we can add optional properties to specify an assumed timezone for the values, as well as a display timezome for automatic conversions when displaying.
> send all datetimes to BokehJS timezone-naive

- scripts/build_upload.py
issues: fixes #6464
This adds an option to upload binary data such as the examples zip file correctly to CDN. 
Tested locally by hand, however for good measure examples upload has also been moved last so that if it fails, nothing else is impacted. 
Would like to merge this before `0.12.7dev2`
> add option to upload binary files to CDN

- .travis.yml
- bokeh/command/subcommands/tests/test_png.py
- bokeh/command/subcommands/tests/test_svg.py
- bokeh/tests/test_io.py
- conda.recipe/meta.yaml
- conftest.py
- setup.cfg
- sphinx/source/docs/dev_guide/testing.rst
- tests/conftest.py
- tests/plugins/implicit_mark.py
issues: fixes #6441
Non-integration tests that require selenium can now be selected with `py.test -m selenium` This includes, e.g.some png and svg export unit tests. 
Additionally `py.test -m unit` will run all tests otherwise unmarked (i.e the basic python unit tests)
> add mark for tests needing selenium and support pytest --unmarked

- examples/app/spectrogram/audio.py
- examples/app/spectrogram/server_lifecycle.py
issues: fixes #5628
Produces this now, when `pyaudio` is not installed:
@philippjfr if you care interested in making the fake data better or more interesting, let me know.
> add mode for synthetic data if no pyaudio installed

- bokehjs/src/coffee/core/has_props.coffee
- bokehjs/src/coffee/core/properties.coffee
- bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
issues: fixes #6185
This removed the gorpy `propchange` signal in favor of calling `set_data` in response to standard property change events. If it's found we need an optimization we can be smarter about it (i.e. by splitting up `set_data` into different pieces, and triggering only what is necessary)
> trigger set_data normally off glyph property changes

- bokeh/util/future.py
This fixes five unit tests that were broken under Python 2.7.9 (but not under Python 2.7.10+). No new tests were added since it was necessary to change the code to pass existing tests.
List of previously broken tests:
* `test_property_on_change_good_partial_function`
* `test_property_on_change_good_partial_method`
* `test_event_on_change_good_partial_function`
* `test_event_on_change_bad_partial_function`
* `test_event_on_change_good_partial_method`
All tests broke with the same issue:
```
bokeh/util/callback_manager.py:35: in on_event
_check_callback(callback, ('event',), what='Event callback')
bokeh/util/callback_manager.py:12: in _check_callback
sig = signature(callback)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ …
```
> Fix signature() utility function for Python 2.7.9

- scripts/ci/test:docs
Maybe fixes doc builds for external contributors. cc @bryevdv.
> export GOOGLE_API_KEY in test:docs

- bokehjs/src/coffee/models/plots/plot_canvas.coffee
- bokehjs/test/size.ts
- sphinx/source/docs/user_guide/webgl.rst
Fix save tool when `output_backend= "webgl"`.
Fix webgl docs for the example without webgl.
> 6592 webgl save

- bokehjs/src/coffee/models/sources/cds_view.coffee
- bokehjs/test/models/sources/cds_view.coffee
This PR fixes streaming in the presence of CDSViews. The if statement is to guard against cases where the data source of a renderer is not a columnar data source and therefore doesn't have a `streaming` signal and when there is no data source.
One thing I considered was that for each streaming event, of the CDSView and GlyphRenderer, you would want the CDSView to respond first to update its indices before the GlyphRenderer responds with its set_data. Otherwise the first streaming event would not cause a re-render of the new data. This seems to be what happens (I checked with the following script that streams new_data on a button click), but I don't know if there is a way to guarantee that one slot is called before another one? 
```python
from bokeh.models …
```
> Fix streaming with filterable CDS

- bokeh/document.py
- bokeh/models/sources.py
- bokeh/models/tests/test_sources.py
Addresses issue 6577 by making the stream setter argument only accessible in a private method (_stream).
test__stream_good_data  tests the private method and 
test_stream_good_data tests the public method.
Tested on linux using 
py.test -m "unit and not selenium"
999 passed
> Issue6577_make stream setter accessible only in the private API

- sphinx/source/docs/user_guide/tools.rst
fixes issue #6651 : minor update to documentation to reflect expected values of `dimensions` attribute of `bokeh.models.CrosshairTool`.
> update documentation for `bokeh.models.CrosshairTool`

- bokehjs/src/coffee/models/sources/cds_view.coffee
- bokehjs/test/models/sources/cds_view.coffee
- examples/app/export_csv/main.py
This PR fixes the DataTable resize regression. It also updates the export_csv app, so that the range of the slider better matches the example data.
> Fix DataTable resize regression by computing indices when source data changes

- bokeh/util/session_id.py
- bokeh/util/tests/test_session_id.py
> Ensure provided and expected signature strings have same encoding

- bokehjs/src/coffee/models/tiles/mercator_tile_source.coffee
Removed the hard coded 0 and 30 for Zoom levels during resolution calculation, and used the preconfigured min_zoom and max_zoom options, which are defaulted to 0 and 30, but are configurable when defining the tile source.
> Removed hard-coded zoom levels on Mercator Tile calculations

- bokehjs/src/coffee/models/graphs/static_layout_provider.coffee
- bokehjs/test/models/graphs/static_layout_provider.coffee
Correctly handle single node graph by filling w/ NaNs instead of nulls
> Correctly handle single node graph

- bokeh/layouts.py
- bokeh/tests/test_layouts.py
I have moved the creation of the grid in the layout into a separate function which recursively calls itself which should allow for arbitrary lists.
At this point I haven't added any tests. I couldn't find any current tests of the layout function, and am not sure how to test correctness.
> Allow arbitrary nested lists in layout function

- bokehjs/src/coffee/core/util/color.coffee
- bokehjs/src/coffee/models/mappers/color_mapper.coffee
- bokehjs/test/core/util/color.coffee
- bokehjs/test/models/mappers/linear_color_mapper.coffee
- bokehjs/test/models/mappers/log_color_mapper.coffee
In https://github.com/bokeh/bokeh/issues/6755 I described an issue handling transparency for special colors (e.g. nan_color, low_color and high_color) when specifying the color as an RGBA tuple. It took me a very long time to work out that bitwise math in Javascript tops out at 31-bits, which means the previous approach to bit shifting the colors no longer worked and I had to use a bit of actual math to handle the alpha value correctly. Additionally the ``color2hex`` utility was not correctly converting the alpha value to a hex value.
I have also put together a notebook demonstrating the original issue and the new behavior with the fix: https://anaconda.org/philippjfr/bokeh_alpha/notebook
Let me know what tests you think I should add and whether you have any concerns with the approach I …
> Add support for special color transparency in ColorMapper

- bokeh/core/property/containers.py
- bokeh/models/sources.py
- bokeh/models/tests/test_sources.py
> Fix steaming for DataFrame-based ColumnDataSource

- bokeh/plotting/helpers.py
- bokeh/plotting/tests/test_helpers.py
Fixes #6731
Apart from fixing `False`, also fixes potential use of `None` as an argument value
> Fix False renderer args not being set

- bokeh/models/plots.py
- bokehjs/src/coffee/models/plots/plot.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
This PR adds a simple aspect ratio control tool.
This PR adds a two properties to the plot object.
`match_aspect` which indicates whether Bokeh should attempt the match the (width/height) of *data space* to the (width/height) in pixels of *screen space*.
`aspect_scale` which allows for further control of aspect control behavior by multiplying on top of the ratio calculated at `match_aspect`. This property allows the user to distort the axis at will. For example, with `aspect_scale= 2` a square in *data* units will be drawn as a rectangle with twice the *pixel* units in width than in height.
This fixes the bug shown in #6603.
Hello Bokeh team,
From my understanding the current behavior when plotting the data ranges is to use the bounds of the glyphs. The method proposed in this PR for …
> Basic aspect ratio control

- bokeh/core/_templates/autoload_js.js
- bokeh/core/_templates/autoload_nb_js.js
- bokeh/core/_templates/notebook_cell_observer.js
- bokeh/core/state.py
- bokeh/core/templates.py
- bokeh/core/tests/test_state.py
- bokeh/embed.py
- bokeh/io.py
- bokeh/tests/test_embed.py
- bokeh/tests/test_io.py
- bokeh/util/notebook.py
This reverts commit e45e24f8e32534d64a386f5d36357bb5f351814b, reversing
changes made to c3ee83210d75ea0dbbb5ab92fe69dc4756ec2e88.
Revert "add mechanism to install external notebook display hooks (#6799)"
This reverts commit 33c2356663e5747296ac5576af74d4a1dad1b0c2.
Revert "Add mime message for jupyter lab load mime renderer (#6797)"
This reverts commit 6120d89d99d69b6f1756be6eb216b1ba1441683a.
Revert "Merge pull request #6774 from bokeh/canavandl/nb_register_mime"
This reverts commit 2788ce89fce47527d980c8ccbb83010e462023b0, reversing
changes made to e244cc4603f0bf7b50a43f2e91ddc562b93b5e0e.
Fix revert conflicts
feature. You can …
> Revert JLab integration changes

- bokehjs/src/coffee/models/graphs/graph_hit_test_policy.coffee
- bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
Use setv to silent set data_source.inspected (not not trigger render)
> Use setv to silent set data_source.inspected (not not trigger render)

- bokeh/io.py
- bokeh/tests/test_io.py
This covers common cases where previously detected file names were unhelpful (e.g. `runpy.html`).
fixes #6560
> Use default action when detecting file name in jupyter

- bokeh/core/enums.py
- bokeh/models/widgets/tables.py
- bokehjs/src/coffee/models/widgets/tables/cell_formatters.coffee
- bokehjs/test/models/widgets/index.coffee
- bokehjs/test/models/widgets/tables/cell_formatters.coffee
- bokehjs/test/models/widgets/tables/data_table.coffee
- bokehjs/test/models/widgets/tables/index.coffee
- sphinx/source/docs/releases/0.12.8.rst
This PR fixes `DateFormatter` but in doing so updates it to use `strftime` formats instead of the JQ style formats. The previous special format names are still accepted, except `TICKS` which has been removed. 
Original example now shows:
> fix table DateFormatter using tz

- bokehjs/src/coffee/models/plots/plot_canvas.coffee
Checks for finite values of bounds before doing the calculation for `match_aspect `bounds.
When trying to plot a figure which contains a glyph without specified bounds. The default value given to these glyphs is Infinity. If you also specified the `match_aspect` for the figure, it would fail to draw the initial ranges since the computation done to to insure `match_aspect` would turn the `Infinity` values into `NaN`. This fixes the issue by checking that all values are finite before doing any calculation for the bounds. 
```
p = figure(match_aspect=True)
source = ColumnDataSource(data={'x': [], 'y': []})
p.circle(x='x', y='y', source=source)
p.circle(x=1, y=2)
```
Without the fix the ranges fail to set. However, with `match_aspect=False` the figure will set the ranges properly.
> Checks for finite values of bounds before doing the calculation for match_aspect bounds

- bokeh/core/has_props.py
- bokeh/server/session.py
- bokeh/settings.py
- bokeh/util/logconfig.py
- sphinx/source/docs/dev_guide/env_vars.rst
issues: closes #6888 
This adds a `trace` log level and uncomments any commented `debug` log calls, replacing them with uncommented `trace` instead.
@bokeh/dev any comments on whether there are any downsides to monkey patching `logging` ?
> add trace log level

- bokehjs/src/coffee/models/graphs/static_layout_provider.coffee
- bokehjs/test/models/graphs/static_layout_provider.coffee
- sphinx/source/docs/user_guide/examples/graph_static_paths.py
- sphinx/source/docs/user_guide/graph.rst
When plotting a graph using the GraphRenderer and StaticLayoutProvider there is no way to supply an explicit set of paths because StaticLayoutProvider draws straight line paths from the start and end points. This PR allows supplying explicit 'xs' and 'ys' to the ``MultiLine`` CDS, which the ``StaticLayoutProvider`` will use rather than computing the straight line paths. Since the ``StaticLayoutProvider`` already expects ``start`` and ``end`` columns I think it's fine and consistent if it also looks for xs and ys, although I'd be open to respecting names set for 'xs' and 'ys' on the MultiLine glyph. Still needs tests and documentation.
> Allow supplying explicit edge paths for graphs

- bokeh/sampledata/__init__.py
- bokeh/sampledata/airport_routes.py
Expose airport_routes data via bokeh.sampledata
Data need to be uploaded to S3 before merging.
> Expose airport_routes data via bokeh.sampledata

- sphinx/source/docs/user_guide/interaction/callbacks.rst
Attributes are accessible directly from `cb_obj`.
Use `cb_obj.x` instead.
> js code error in documentation

- bokehjs/src/coffee/core/hittest.coffee
- bokehjs/src/coffee/models/glyphs/segment.coffee
Horizontal/vertical segments have zero bbox area and hence
are almost impossible to coincide with a point for hittest search.
Hence RBush.indices() was never returning such segments.
We now instead search rbush with a square of size 4x4 instead of a
point to find such segments as well.
Ideally, the square size should be maximum of the the line_width,
but the current state is in itself a great improvement.
> Issue #6704: Fix hover hittest on horizontal/vertical segments

- sphinx/source/docs/user_guide/notebook.rst
There was no issue for this. Just noticed a typo in the docs.
> Fix typo in notebook.rst

- bokeh/__init__.py
- bokeh/tests/test_bokeh_init.py
- bokeh/util/version.py
- sphinx/source/docs/releases/0.12.10.rst
This PR removes ``bokeh.__version__`` which was computed on every import of Bokeh and could take hundred of milliseconds. 
Ref: https://github.com/dask/distributed/issues/1399#issuecomment-329834414
> stop computing unused and expensive bokeh.__base_version__

- bokeh/layouts.py
Doctext formatting change.
(I have not yet been able to run sphinx myself due to an error running sphinx/build)
> Correct gridplot doctext so that ncols parameter name is rendered

- sphinx/source/docs/user_guide/annotations.rst
Also, modify text to match surrounding style.
- (n/a) tests added / passed
- (n/a) release document entry (if new feature or API change)
> Remove out-of-date matplotlib reference from ColorBar user guide.

- bokeh/models/mappers.py
- bokeh/models/tests/test_mappers.py
Solution was to make `if` tests explicitly check for `None`, otherwise array errors about using `.any` or `.all` pop up when arrays are used. 
With this change, the following code:
```
import pandas as pd
from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource, FactorRange
from bokeh.transform import factor_cmap
from bokeh.palettes import Spectral6
output_file("test.html")
fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ['2015', '2016', '2017']
data = {'2015'   : [2, 1, 4, 3, 2, 4],
'2016'   : [5, 3, 3, 2, 4, 6],
'2017'   : [3, 2, 4, 4, 5, 3]}
df = pd.DataFrame(data, index=fruits)
fruits = df.index
years = df.columns # THIS FAILED BEFORE
x = [ (fruit, year) for fruit in fruits for year in …
```
> allow cat cmapper factors to be pd Index

- bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
- bokehjs/src/coffee/models/sources/cds_view.coffee
- bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
This PR fixes the rendering of glyphs that use a subset of data, through filtering with CDSView. It also fixes some bugs with the hover tool and filtered plots that were introduced with GraphRenderer work. 
The problem was at line 141 in bokehjs/src/coffee/models/renderers/glyph_renderer.coffee. I had mistakenly thought that `all_indices` was in subset space when it really is in full data space. `all_indices` contains the indices of the filtered data source (e.g. [1, 20, 45]) in the full data space. It needs to be converted to `indices` in subset space (i.e. [0, 1, 2]). This previously was working for the circle glyph, because `mask_data` using the spatial index would return the correct subset space `indices`. However, for glyphs that don't have `_mask_data`, `indices` was incorrectly in …
> fix rendering of filtered data sources for previously broken glyphs

- bokeh/embed/standalone.py
- sphinx/source/docs/installation.rst
- sphinx/source/docs/releases/0.12.7.rst
- sphinx/source/docs/user_guide/embed.rst
* add `-tables` resources in `embed.rst` and `installation.rst`
* add reference to `embed.rst` to the `components` docstring
* touch up the `0.12.7.rst` to highlight that these resources must be manually loaded in any scenario where Bokeh is not loading resources itself.
I couldn't build and check the docs yet (need a dev install) but wanted to push the PR anyway.
> Add "-tables" css and js includes to the docs (#6999)

- sphinx/source/docs/user_guide/server.rst
Docs were not updated to reflect changes made to session_context in #5901. The docs reference to users having access to `request.cookies ` (and other attributes) which was removed in v0.12.5. New wording reflects the current restrictions.
Issue related to this PR is #7031.
> update docs to reflect new behavior of session_context

- bokehjs/src/coffee/models/axes/categorical_axis.coffee
A small change applies formatting to the major ticks adjacent to to the axis:
However, not in the nested case, it does *not* apply formatting to the higher level:
@hiramf @hafen is this OK for now? Another change *can* produce this:
but it's not ideal &mdash; the only info available to the (one single) formatter is the local tick value, not what level it is for, or a complete compound category value. I think this is not ideal so I don't want to push it now. It might be better to have separate formatters for mid or top level ticks, or possibly there could be a way to pass more info to the formatter, so that a single formatter can intelligently switch on the category level. 
If this seems OK for the immediate issue I will figure out some tests and merge.
> call formatter for major categorical ticks

- examples/app/movies/README.md
- examples/app/movies/description.html
fixed URL typo("hhttp" -> "https") in examples app & also changed README URL to https.
- issues: None
- reso: completed 
- type: bug
- milestone: short-term
> fixed URL typo in examples app & changed README URL to https

- bokeh/command/subcommands/serve.py
- bokeh/command/subcommands/tests/test_serve.py
- bokeh/document/document.py
- bokeh/document/tests/test_document.py
- bokeh/server/application_context.py
- bokeh/server/tornado.py
This PR adds a detailed check in `Document.delete_modules` that saved modules only have the expected set of referrers. The method `delete_modules` is made responsible for clearing the internal list of modules so that they may be correctly reaped. Additionally some extra logging has been added to trace the session destruction codepath.
> ensure Document modules are properly disposed of

- bokehjs/src/coffee/models/tools/toolbar.coffee
This makes shared tools initialize properly, but this doesn't fix the overall mess that tool/toolbar initialization is. I will address the broader issue after PR #7008.
fixes #6921
> Properly maintain active tools when proxying toolbars

- bokehjs/src/coffee/models/glyphs/patches.coffee
issues: fixes #3601
I tested this with existing choropleth examples and it seems fine. 
@philippjfr I can't get HV to work at all right now, and there is no MRE in the issue, so someone else needs to confirm that it functions as desired with overlapping patches.
> sort the results of _mask_data so patch draw order is stable

- bokeh/server/session.py
- bokeh/server/tests/test_server.py
@havocp this is a trivial change, but I'd appreciate your input. I believe the test changes reflect your intent in the original issue, but please confirm if you can.
> ignore locked callbacks when a session is destroyed

- bokeh/core/properties.py
- bokeh/core/tests/test_properties.py
This PR makes `ScreenDistanceSpec` and `DataDistanceSpec` properly be `UnitsSpec` subclasses. Since there is only one valid unit value, in order to keep existing semantics identical, and not avoid a useless `_units` property that can only accept one value the descriptor machinery for each was specialized.
> fix distance spec hierarchy

- bokeh/core/properties.py
- bokeh/core/property_mixins.py
- bokeh/core/tests/test_properties.py
- bokeh/models/glyphs.py
@mattpap if you agree with this general approach, I will:
* add a real `FontSize` prop instead of `String`
* apply these scalar props other places to reduce code dupe (some annotations)
* add more tests
* general clean up
> add Scalar versions of property mixins

- bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
issues: fixes #6174
When computing the nearest point for determining where to position a tooltip, when the hit geometry is a span, only compute the distance along the transverse dimension.
This PR also:
* deletes a duplicative "color to hex" function in favor of one in utils
* factors out some common code
In general this is all too complicated and untested. A larger refactor should be considered, perhaps in conjunction with selection refactor work, or immediately after.
> compute 'nearest' to span only in one dimension

- bokehjs/src/coffee/models/glyphs/box.coffee
- bokehjs/src/coffee/models/glyphs/glyph.coffee
- bokehjs/src/coffee/models/glyphs/rect.coffee
- bokehjs/test/models/glyphs/rect.coffee
In the interest of remaining consistent with `rect` behaviour, and also re-using code, I have factored the rect-rect index hit testing up to glyph to also be used by `Box` subclasses. Will add test before merging.
> factor rect hit-testing against an index out to glyph view

- bokehjs/src/coffee/models/glyphs/rect.coffee
- bokehjs/test/models/glyphs/rect.coffee
@clairetang6 this is your suggested function only modified to always set `vpt_corner` to something. If you have suggestions for additional/better tests please let me know (or just add them). TBH I am still not 100% clear on `sx0` and `sy1` but digging into the details will have to be another day.
> compute rect dists more carefully

- sphinx/source/docs/releases/0.12.10.rst
probably a typo, `0.12.0` in document title should be `0.12.10`
- issues: fixes #7121
> documentation - fix version

- bokeh/embed/server.py
- bokeh/embed/tests/test_server.py
Handling of `model=None` was broken in the `embed.py` refactor for `0.12.10`. This PR restores the capability and adds a unit test to explicitly test this use case.  
With the change so far, this code functions as expected:
```
bokeh serve sliders.py --allow-websocket-origin=localhost:8080
```
```
from flask import Flask, render_template
from bokeh.client import pull_session
from bokeh.embed import server_session
import bokeh
print(bokeh.__version__)
app = Flask(__name__)
@app.route('/', methods=['GET'])
def bkapp_page():
session = pull_session(url="http://localhost:5006/sliders")
script = server_session(None, session.id, url='http://localhost:5006/sliders')
return render_template("embed.html", script=script, template="Flask")
if __name__ == '__main__':
app.run(port=8080)
```
However, if …
> handle model=None for server_session

- bokehjs/examples/hover/hover.ts
- bokehjs/examples/tap/tap.ts
- bokehjs/package.json
- tests/examples/test_examples.py
Contrary to my previous understanding, "^2.6.1" means that only first number (major version) can't change. Given that TypeScript introduces breaking changes in minor versions, I locked its version to 2.6.1 and will update when new compilers are available.
> Update TypeScript to 2.6.1 and fix examples

- bokehjs/src/coffee/document.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
- bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
- bokehjs/src/coffee/models/tools/actions/zoom_in_tool.coffee
- bokehjs/src/coffee/models/tools/actions/zoom_out_tool.coffee
- bokehjs/src/coffee/models/tools/gestures/pan_tool.coffee
- bokehjs/src/coffee/models/tools/gestures/wheel_pan_tool.coffee
- bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee
- bokehjs/test/core/ui_events.coffee
- bokehjs/test/document.coffee
- bokehjs/test/models/annotations/color_bar.coffee
- bokehjs/test/models/axes/axis.coffee
- bokehjs/test/models/graphs/graph_hit_test_policy.coffee
This PR adds support for "linked" LOD by making the document centrally responsible to note the start/end/duration of interactive periods. This simplifies the code at the point of usage and allows for some simple unit tests to be added. 
With this work, LOD start/end events are only triggered on the plot that originated the interactive period. 
Here is an example script that can be used:
```
from bokeh.plotting import figure, show, output_file
from bokeh.layouts import row
N = 4000
x = np.random.random(size=N) * 100
y = np.random.random(size=N) * 100
radii = np.random.random(size=N) * 1.5
colors = [
"#%02x%02x%02x" % (int(r), int(g), 150) for r, g in zip(50+2*x, 30+2*y)
]
p0 = figure()
p0.scatter(x, y, radius=radii,
fill_color=colors, fill_alpha=0.6,
line_color=None)
x = …
```
> note start/end of interactive periods on document

- bokehjs/src/coffee/models/widgets/abstract_slider.coffee
This was adapted from this [example](https://refreshless.com/nouislider/examples/#section-keyboard) in the nouislider documentation.
Tested this with the sliders example app and it works well, but I have yet to try this for sliders with multiple handles.
> Make slider handles updatable from arrow keys

- bokeh/document/events.py
- bokeh/document/tests/test_events.py
When calling CDS stream with DataFrames, the DataFrame would make it all the way to the `ColumnsStreamedEvent`, which presented it as-is for JSON encoding. This fails because DataFrames are not directly JSON serializable.
For compartmentalization and ease of testing, the issue is resolved by teaching `ColumnsStreamedEvent` how to convert DataFrames to the appropriate serializable dict itself. Other possible solutions not pursued at this time:
* ensure `ColumnsStreamedEvent` only ever receives a dict (higher level)
* teach the Bokeh JSON encoder how to handle DataFrames (lower level)
> Permit ColumnsStreamedEvent to accept DataFrames

- bokeh/models/layouts.py
- bokeh/models/tests/test_layouts.py
- bokehjs/src/coffee/models/layouts/layout_dom.coffee
In order for in place updates such as `.append` to properly trigger events, the property type must be `List` (so that `PropertyValueList` is used to wrap the value). This PR changes the type to `List`, but also adds an `accept` clause so that setting from tuples, etc. still functions.
> Change css_classes property type to List

- bokehjs/src/coffee/models/tools/toolbar.coffee
Missing import of logger.
https://github.com/bokeh/bokeh/edit/master/bokehjs/src/coffee/models/tools/toolbar.coffee#L35
Error is logged if event_type does not match and therefore a Reference error was raised because of the missing import.
> Missing import of logger in toolbar.coffee

- bokeh/core/_templates/doc_js.js
- bokeh/core/_templates/script_tag.html
- bokeh/core/json_encoder.py
- bokeh/embed/tests/test_standalone.py
- bokeh/embed/tests/test_util.py
- bokeh/embed/util.py
- bokehjs/src/coffee/core/util/string.ts
- bokehjs/src/coffee/embed.coffee
- examples/examples.yaml
- examples/integration/security/xss.py
This splits off docs JSON from javascript script into a HTML-safe encoded application/json script in standalone HTML output mode. Otherwise it uses HTML-safe encoded JavaScript string with JSON content. As long as one uses `script_for_render_items()` as the **only** way to generate bokeh script, then vulnerability described in #7039 is fixed. 
fixes #7039
> Encode JSON into application/json script for standalone HTML

- bokeh/core/_templates/autoload_nb_js.js
Screenshot shows bokeh now successfully loading in notebook in IE11:
I haven't yet run any other tests.
> Remove unsupported-by-IE11 template string (see #7212).

- bokehjs/src/coffee/core/util/canvas.coffee
(Depends on #7220) 
IE11 screenshot:
> Add support for IE 11 and Edge 14 to canvas image smoothing fixups; fixes #7213.

- bokeh/embed/util.py
> Double encode escapes (e.g. \n) in HTML-safe JSON strings

- sphinx/source/docs/user_guide/graph.rst
Fixes missing figure import on graph network example.
https://bokeh.pydata.org/en/latest/docs/user_guide/graph.html#edge-and-node-renderers
- [ X] issues: fixes #7240
> Missing figure import on graph network example

- bokeh/core/_templates/doc_js.js
- bokeh/core/_templates/doc_nb_js.js
- bokeh/core/_templates/try_run.js
- bokeh/core/templates.py
- bokeh/embed/notebook.py
- bokeh/embed/tests/test_notebook.py
- bokehjs/src/coffee/embed.coffee
Makes standalone notebook path non-deferred for now in order to restore notebook comms functionality. In the future probably just a "comms init" step can be non-deferred, and a subsequent "comms start" step can be deferred along with everything else.
> Separate standalone notebook embed path 

- bokehjs/src/coffee/models/tools/gestures/box_zoom_tool.coffee
- bokehjs/test/models/tools/gestures/box_zoom_tool.coffee
- bokehjs/test/models/tools/gestures/index.coffee
This PR fixes a regression in the BoxZoomTool when used with the ``match_aspect`` introduced in https://github.com/bokeh/bokeh/pull/7108 and adds unit tests to avoid future regressions.
> Fix BoxZoomTool match_aspect regression

- bokeh/models/tiles.py
- bokehjs/src/coffee/models/tiles/mercator_tile_source.coffee
- bokehjs/src/coffee/models/tiles/tile_renderer.coffee
- bokehjs/test/models/tiles/tile_renderer.coffee
- sphinx/source/docs/releases/0.12.14.rst
As discussed in https://github.com/bokeh/bokeh/issues/6655 and https://github.com/bokeh/bokeh/issues/5126, when using a map tile source the plot will snap to the nearest zoom level, which is not always desirable and often makes it very difficult to initialize the plot to a reasonable zoom range.
This PR adds an option called ``snap_to_zoom`` to the ``MercatorTileSource`` which disables this behavior and instead simply tries to maintain the appropriate aspect ratio. It does this by finding the supplied range which is closest to the next zoom level and then adjusts the other range by scaling it as a fraction of the range of the closest zoom level. In my testing this produces much better results overall, but I've left the option set to True by default to maintain backward compatibility.
Here …
> Added snap_to_zoom option for MercatorTileSource

- bokeh/tests/test_tile_providers.py
- bokeh/tile_providers.py
I took the opportunity to update the URLs to https in the attributions as well.
I haven't changed the URL to the stamen tiles. They seem to be available through https but the certificate is invalid which results in browser showing an error message.
> Use HTTPS to get tiles from CartoDB

- bokeh/embed/notebook.py
This PR proposes a small change that seems to fix the issue described in #7319 where bokeh themes fail to apply in the notebook environment. 
I've had this diff outstanding for a while in my local copy of bokeh and I have not yet noticed any issues in other contexts (e.g bokeh server). That said, here might be other implications/issues that I am currently unaware of so maybe this simple fix isn't sufficient.
> Fix for themes in notebooks

- tests/conftest.py
Recent versions of pytest fail with this error:
```
argparse.ArgumentError: argument --log-file: conflicting option string: --log-file
```
This PR changes the cusotm option added in `tests/conftest.py` to be `--examples-log-file` instead. A grep of the CI tests did not find any usage of the old `--log-file` argument (the default value is "examples.log" which is what seems to be being used).
> Resolve pytest --log-file conflict

- bokeh/models/plots.py
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
- bokehjs/src/coffee/models/ranges/data_range1d.ts
- bokehjs/test/models/ranges/data_range1d.coffee
The commit moves the aspect ratio adjust (for a single plot update) to after the unioned bounds are computed for the DataRange renderers. Previously the aspect correction happened on all the individual renderer bounds, before the call to update. This could result in incorrect aspect-corrected overall bounds in some situations.
Note: use of match_aspect with linked DataRange1d across multiple plots will probably yield undefined/undesirable behavior and should be considered unsupported.
#
> delay match_aspect adjustment

- bokehjs/src/coffee/models/widgets/tables/data_table.coffee
- bokehjs/test/models/widgets/tables/data_table.coffee
This problem was caused by applying the scroll computation in the case where there was an empty selection. In this instance, the scroll index was computed using `Math.min.apply(null, [])` which is `Infinity`, resulting in a scroll to the very end. The moves the logic for computing the index in to a method on the model (with the fix for empty selections) and places it under test.
> Fix errant scroll to end on DataTable with no selection

- bokehjs/src/coffee/models/glyphs/text.coffee
- sphinx/source/docs/releases/0.12.14.rst
This PR updates `draw_legend_for_index` render empty space in legends.  The previous implementation simply rendered the word "text" unconditionally which is not useful. Now text glyphs can added to legends in combination with other glyphs in order to be able to hide or mute them together:
issues: fixes #7337
> Fix broken generic text legend.

- bokeh/util/serialization.py
- bokeh/util/tests/test_serialization.py
The existing code called `total_seconds` on a TimeDelta, as well as explicitly added `microseconds` back in. However, this resulted in a doubling of the microsecond component, since `total_seconds` already includes this portion:
https://docs.python.org/2/library/datetime.html#datetime.timedelta.total_seconds
This was never discoverd because all tests of `convert_datetime_type` on datetime values only exercised "exact date" values.
> Correct datetime conversion when subsecond fractions are present

- bokehjs/src/coffee/models/renderers/graph_renderer.coffee
This PR fixes a regression when zooming on plots with a GraphRenderer. As described in #7370 zooming causes the nodes to snap to the origin. By connecting the ``GraphRenderer.set_data`` method to range change events just as was done for the ``GlyphRenderer`` in #7363 the issue is resolved.
> Connect GraphRenderer to range change events

- bokeh/util/tornado.py
This came up in some other work. It's probably long overdue I wanted to get it put in immediately.  An exception in a periodic callback now yields e.g.
```
2018-01-05 17:45:40,670 Error thrown from periodic callback:
2018-01-05 17:45:40,670 Traceback (most recent call last):
File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 828, in callback
result_list.append(f.result())
File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/concurrent.py", line 238, in result
raise_exc_info(self._exc_info)
File "<string>", line 4, in raise_exc_info
File "/Users/bryanv/anaconda/lib/python3.6/site-packages/tornado/gen.py", line 1069, in run
yielded = self.gen.send(value)
File "/Users/bryanv/work/bokeh/bokeh/server/session.py", line 51, in _needs_document_lock_wrapper …
```
> add traceback information to exception messages callbacks

- bokehjs/src/coffee/models/tools/toolbar.coffee
- bokehjs/src/coffee/models/tools/toolbar_box.coffee
- bokehjs/test/models/tools/toolbar_box.coffee
As I described in https://github.com/bokeh/bokeh/issues/7391 while implementing support for multi-gesture tools I did not handle the initialization of a ``ProxyToolbar`` causing it to raise errors when you attempt to create a layout plot with a multi-gesture tool.
> Handle multi-gesture tools on ProxyToolbar

- bokehjs/src/coffee/models/plots/plot_canvas.ts
- bokehjs/src/coffee/models/renderers/graph_renderer.ts
- bokehjs/src/coffee/models/tiles/tile_renderer.ts
As described in #7398, decaffeination introduced a usage of ``includes`` without importing it.
> Added missing includes import in tile_renderer.ts

- bokeh/io/notebook.py
- bokeh/io/tests/test_notebook.py
> allow push_notebook with empty events

- bokehjs/src/coffee/embed.ts
Simple fix for the regression described in #7439. Trying to open a notebook with embedded bokeh plots outside the notebook itself would cause it to fail to render the plots because an error occurred when trying to set up a Jupyter Comm. It now checks whether the Jupyter variable is defined.
> Fixed regression in notebook plot embedding

- bokehjs/src/less/widgets/widgets.less
I'm not sure why this was done, but seems unnecessary anymore and fixes the overlapping layout issue.
fixes #7443
> Don't set `float: left` on tabs' panels

- bokeh/core/properties.py
- bokeh/core/tests/test_properties.py
This adds a catch for `OSError` to `Date.transform` which is the proper way to catch the exception on some platforms/versions. 
Note that `test_validate_milliseconds` was verified to fail without the associated code change, and is passing with the code change (on windows)
> transform Date correctly on windows

- bokeh/plotting/helpers.py
- bokeh/plotting/tests/test_figure.py
- bokeh/plotting/tests/test_helpers.py
This fixes the case where passing both a legend and a DataFrame for `source` caused errors, by moving the processing of `source` up earlier (so that the legend handling code always sees only a CDS)
However, this did uncover an (unrelated) issue with DF sources and legends, namely that this case will not work as expected:
```
source = pd.DataFrame(data=dict(x=[1, 2, 3], y=[1, 2, 3], label=['a', 'b', 'c']))
square = p.square(x='x', y='y', legend='label', source=source)
circle = p.circle(x='x', y='y', legend='label', source=source)
```
The "combining" is contingent on renderers sharing a source, but in this case each renderer will have a new source, created from the DataFrame. This should be fixed, but later as part of a more general clean up. Mentioning here to document.
> handle legends better with data frame sources

- bokeh/models/tools.py
- bokehjs/src/coffee/models/tools/edit/box_edit_tool.ts
- bokehjs/src/coffee/models/tools/edit/point_draw_tool.ts
- bokehjs/src/coffee/models/tools/edit/poly_draw_tool.ts
- bokehjs/src/coffee/models/tools/edit/poly_edit_tool.ts
- bokehjs/src/coffee/models/tools/toolbar_box.ts
- sphinx/source/docs/user_guide/tools.rst
Fixes issue with PolyDrawTool not emitting event on completing a polygon/line with a double tap. Also renames remaining references to BoxDrawTool left over from a rename.
I'll leave this as a WIP until I've finished writing examples for higher level libraries, in case I find any further issues.
> Fixes for EditTools

- bokehjs/src/coffee/models/tools/edit/poly_edit_tool.ts
I fixed this for the PolyDraw tool in my previous PR but somehow missed the same thing on the PolyEdit tool.
> Ensured PolyEdit tool emits CDS data change event on vertex add

- bokeh/server/server.py
- bokeh/server/tests/test_callbacks.py
- bokeh/server/tests/test_server.py
- bokeh/server/tests/utils.py
- bokeh/server/tornado.py
> Tornado 5 Compatibility 

- bokehjs/src/coffee/polyfill.ts
The previous fix was incorrect on the type-level, because `Number.isInteger` is not a part of the standard library (es5 + es2015.collections) that we use. This isn't needed for the release.
addresses #7373, PR #7493
> Resolve compilation errors around Number.isInteger

- bokehjs/.gitignore
- bokehjs/gulpfile.js
- bokehjs/package.json
- bokehjs/prepare.js
For now this only notifies the user. It's not possible to run `npm install` and keep `gulp task_name` for running the build. This could be achieved in future by adding a layer above `gulp` or dropping `gulp` altogether (which I've been contemplating for some time).
fixes #7513
> Notify the user if package.json changed and `npm install` is needed

- bokeh/core/json_encoder.py
The most recent version of NumPy raises a FutureWarning during serialization because the np.issubdtype expects a scalar baseclass instead of a specific dtype. Replacing np.float with np.floating addresses this issue.
> Fixed FutureWarning in json serialization of floating values

- sphinx/source/docs/user_guide/bokehjs.rst
> Replace Range1d(start, end) with Range1d({start, end}) in documentation

- bokeh/io/notebook.py
Added port parameter to show_app method.  This allows the user the override the default behavior of embedded servers listening on random ports.  This is necessary to allow users to use embedded servers remotely when firewalls may restrict available ports.
> Added port parameter to show_app method.  

- bokeh/models/formatters.py
- bokehjs/src/coffee/models/formatters/func_tick_formatter.ts
- bokehjs/test/models/formatters/func_tick_formatter.coffee
Alternative to https://github.com/bokeh/bokeh/pull/7564.
> FuncTickFormatter: expose `index` and `ticks`

- bokehjs/src/coffee/embed.ts
- bokehjs/src/coffee/main.ts
- bokehjs/src/coffee/protocol/index.ts
This PR adds support for using ``push_notebook`` in JupyterLab when combined with https://github.com/bokeh/jupyterlab_bokeh/pull/20. The way it works is that it defines a ``Bokeh.embed.kernels`` registry which the JupyterLab extension registers kernels with on display. This allows the embed functions to register the Jupyter comm to send data from Python to JS.
I'd be happy to hear a different approach, and or make ``Bokeh.embed.kernels`` private to avoid cluttering the namespace. I've also made the ``Bokeh.embed.Receiver`` object public to allow other extensions (e.g. HoloViews) to register their own message handlers on platforms other than Jupyter.
@canavandl @bryevdv
> Add support for JupyterLab comms

- scripts/ci/install:test
The previous CI scripts would unconditionally re-install miniconda on top of an previous install, when a PR from an outside fork was made. With the latests miniconda installers this causes conda errors. This PR changes the CI scripts to only perform the base install a single time in all cases.
> don't repeat base install for external PRs

- docker-tools/.dockerignore
- docker-tools/Dockerfile-py2
- docker-tools/Dockerfile-py3
Follow on to updating `CONDA_REQS` on TravisCI, this PR updates docker files to match. Additionally adds a `.dockerignore` so that any local `.pyc` files are not copied to the image (causes issues with `pytest`)
> rev CONDA_REQS and ignore built python files for docker images

- bokeh/models/sources.py
- bokeh/models/tests/test_sources.py
Fixes two regressions in datetime streaming, the first applies to attempts to stream pandas Index or Series objects, which are currently not appropriately transformed. The second deals with a difference between server and notebook streaming. When streaming data on the server the data is transformed from datetime64 types to integers, which ends up being synced. Since JS->Python is not synced in the notebook this does not occur there. To avoid this problem we only transform the data during streaming if the column it is being streamed to has also been transformed.
The two added tests cover these two conditions, one where the data has not been transformed (emulating the notebook) and one where the data has been transformed (emulating bokeh server).
> Datetime stream fix

- .travis.yml
- scripts/ci/install:test
Rather than burden our already long build with a new job, this PR just makes one of the existing unit test jobs use Tornado 4.5.x
> have one unit test job use tornado 4.5

- examples/howto/server_embed/flask_embed.py
Added parameter io_loop in bk_worker() at examples/howto/server_embed/flask_embed.py for correct working with new version tornado.
> Fix io_loop paramenter in examples/howto/server_embed/flask_embed.py

- bokeh/command/subcommands/serve.py
- bokeh/command/subcommands/tests/test_serve.py
- bokeh/document/document.py
- bokeh/server/session.py
- bokeh/server/tests/test_server.py
- bokeh/server/tests/test_session.py
- bokeh/server/tornado.py
This PR adds a `destroy` method to Document, that removes several places where there might be circular references. However, this alone does not (yet) solve the problem, and a call to `gc.collect()` is required to fully release memory. A fuller solution down the road might be to implement a `destroy` protocol on all models so that they can be responsible for cleaning up any cycles.
> Address leaking memory

- bokeh/server/views/tests/test_ws.py
- bokeh/server/views/ws.py
- tests/examples/test_examples.py
This PR handles send errors (as might happen with an early disconnect) better across Tornado versions. Also cleans up/adds some docstrings and adds a test module for `ws.py`
> handle message send exceptions better

- bokeh/models/tools.py
- bokehjs/src/coffee/models/tools/edit/box_edit_tool.ts
- bokehjs/test/models/tools/edit/box_edit_tool.ts
- sphinx/source/docs/user_guide/tools.rst
This PR adds support to the ``BoxEditTool`` to draw boxes by doubletapping on the canvas, moving the mouse, and then doubletapping again to finish drawing. This makes it more consistent with the ``PolyDrawTool``, while retaining the old behavior to draw on shift+drag.
> Add support for doubletap drawing on BoxEditTool

- bokehjs/src/coffee/models/plots/plot_canvas.ts
This was broken when the main coordinate system was switched from view to screen. Apparently webgl expects view coordinates, contrary to canvas' screen coordinates.
fixes #7211
> Fix frame clipping with webgl backend

- bokeh/io/tests/test_export.py
- bokehjs/src/coffee/models/glyphs/webgl/markers.frag.ts
- bokehjs/src/coffee/models/glyphs/webgl/markers.ts
- bokehjs/src/coffee/models/plots/plot_canvas.ts
- examples/integration/glyphs/frame_clipping_multi_backend.py
I'm not sure why clipping depended on output backed, but that definitively can't work when `webgl` and `canvas` glyphs are mixed together. In fact this also resolves clipping issues with SVG (not surprisingly).
fixes #6867
fixes #6787
> Always clip frame in _paint_levels() despite output backend

- bokehjs/src/coffee/models/glyphs/webgl/base.ts
- examples/integration/glyphs/frame_clipping_multi_backend.py
- examples/integration/glyphs/log_scale_multi_backend.py
This doesn't actually fix the webgl backend, just allows it to reliably fall back to canvas rendering. I'm not sure if the current implementation considers non-linear scales as a possibility at all.
fixes #7087
> Make webgl renderer work with log scales

- bokeh/models/widgets/tables.py
Accidentally added mistaken deprecation codepath for `row_header`, instead of correct `row_headerS`.
> remove useless botched deprecation code

- bokeh/core/has_props.py
- bokeh/model.py
ensures pretty-printer is used on bokeh classes by default and simplifies logic in `.pretty()` to avoid the temporary class definition.
This has the additional benefit that the default IPython display of these objects will use your pretty-print methods. Was avoiding the default pretty-printer intentional, or a typo in the method name?
Another fix if avoiding the default pretty-printer is intentional is to register as `type_printers[cls]` for the current class, rather than `type_printers[HasProps]` only on the less specific base class.
closes #7729
> use IPython standard _repr_pretty_ method name

- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/coffee/api/typings.d.ts
- bokehjs/src/coffee/core/hittest.ts
- bokehjs/src/coffee/core/util/spatial.ts
- bokehjs/src/coffee/external/flatbush.d.ts
- bokehjs/src/coffee/models/glyphs/bezier.ts
- bokehjs/src/coffee/models/glyphs/box.ts
- bokehjs/src/coffee/models/glyphs/image_url.ts
- bokehjs/src/coffee/models/glyphs/multi_line.ts
- bokehjs/src/coffee/models/glyphs/patches.ts
- bokehjs/src/coffee/models/glyphs/quadratic.ts
- bokehjs/src/coffee/models/glyphs/segment.ts
- bokehjs/src/coffee/models/glyphs/xy_glyph.ts
- bokehjs/src/coffee/tsconfig.json
As suggested in https://github.com/bokeh/bokeh/issues/7582, this PR attempts to switch out RBush for flatbush to perform the spatial indexing. As flatbush is very new is no ``@types/flatbush`` package yet, so I haven't typed everything properly yet. Before proceeding with this I'd like to find a principled way to perform some benchmarks. So far I've only seen noticeable improvements for very large number of points.
> Switched from RBush to FlatBush

- bokeh/models/sources.py
- bokehjs/src/coffee/api/typings/models/sources.d.ts
- bokehjs/src/coffee/models/sources/columnar_data_source.ts
- sphinx/source/docs/releases/0.12.16.rst
@mattpap @clairetang6 would appreciate any comments from you both. All of the existing tests of `source.column_names` pass without modification.
> make CDS.column_names a read-only property

- bokehjs/src/coffee/models/plots/plot.ts
- bokehjs/src/coffee/models/plots/plot_canvas.ts
- bokehjs/src/coffee/models/tools/actions/reset_tool.ts
example:
```py
from bokeh.io import show
from bokeh.models import Button, CustomJS
p = figure(tools="reset,pan,wheel_zoom,lasso_select")
p.circle(list(range(10)), list(range(10)))
b = Button()
b.js_on_click(CustomJS(args=dict(p=p), code="""
p.reset.emit()
"""))
show(column(p, b))
```
> add reset signal to plots

- bokehjs/src/coffee/models/plots/plot_canvas.ts
~~The problem outlined in the issues is very general. Here I was able to get around it, but in the longer term, we will have to rethink document access in models and state management, especially related to models initialized in bokehjs.~~
fixes ~~#7497 (works around)~~
fixes #7476
> Clean up all rendering levels in PlotCanvasView.build_levels()

- bokeh/command/subcommands/png.py
- bokeh/command/subcommands/svg.py
- bokeh/io/export.py
- bokeh/io/tests/test_export.py
I'm marking this as "fixes". We should open new issue for adding support for chromedriver (and firefoxdriver). With this PR we will only need to change one place in the code instead of a dozen. This also adds `try-finally` blocks to make sure `terminate_webdriver()` is actually called if failure occurs.
fixes #7510
> Silence deprecation warning from selenium.webdriver.phantomjs

- bokehjs/src/lib/core/ui_events.ts
This needs to be verified on an actual mobile device.
fixes #7801
> Handle cases where TouchEvent.touches may be empty

- bokehjs/src/lib/safely.ts
Allow to hide, display, or relocate error box to be useful and valuable on complicated web pages.
Basic style do not support (and not aimed to do so) webpages with navbars, relative positioning 
and so on, this integration is delegated to webpage designer through `bokeh-error-box-into-flames` 
css class.
> All pull requests must have an associated issue in the issue tracker. If there
> DOM: add class to safely()'s error box

- .travis.yml
- scripts/ci/install:downstream
- scripts/ci/test:downstream
fixes: #7720 
For now at least this test does not fail, it only generates a report. Want to avoid a situation where one or other project is intentionally out out of sync (major revision) and then the test can't be made to pass at all in any way for some interval
> add downstream test report

- bokeh/models/tools.py
- bokehjs/src/lib/models/tools/edit/edit_tool.ts
- bokehjs/src/lib/models/tools/edit/point_draw_tool.ts
- bokehjs/src/lib/models/widgets/tables/data_table.ts
This fixes both issues that got lumped into #7745
The part missing for python updates was a self-assign to `.data`, so that the doc notification machinery is invoked. The part missing for the table updates was a more explicit change signal on `.data`. Not sure why it worked before, though. Data tables have required that signal for a long time AFAICT. 
@philippjfr are there other places that the "self-assign" should go, e.g. for other tools, so that python gets updates at the appropriate times?
@mattpap any comments welcome
We do need to document that Python side updates will only happen at the end of these edit operations and not continuously throughout.
> fix missing python and data table updates

- bokeh/io/showing.py
Updated docs to reflect that `notebook_url="*"` is not supportable, since Jupyter will not provide an API to determine the server location.
> update docs for showing apps in notebooks

- bokeh/models/axes.py
- bokehjs/src/lib/models/axes/axis.ts
- bokehjs/src/lib/models/plots/plot_canvas.ts
- bokehjs/src/lib/models/renderers/renderer.ts
- bokehjs/test/models/axes/axis.coffee
- bokehjs/test/models/renderers/index.coffee
- bokehjs/test/models/renderers/renderer.coffee
- examples/plotting/file/fixed_axis.py
This implements the plan outlined in #113 and produces output such as the following:
Including working with categorgical coordinates:
It's worth noting here that at least for now, axes labels are suppressed when a fixed location is provided. 
@mattpap I'd like to add some more docs and examples (and a few tests) but before going further I'd like your comments.
> support axes at fixed locations
