- bokehjs/src/coffee/models/widgets/multiselect.coffee
- bokehjs/src/coffee/models/widgets/selectbox.coffee
> Implement 'disabled' for 'Select' and 'MultiSelect' widgets

- bokeh/core/validation/errors.py
- bokeh/models/map_plots.py
- sphinx/source/docs/user_guide/geo.rst
Not super happy with this but it will do for now. Nothing is done with "extra" ranges but I don't think that's common enough to bother with.
> add init and validation check for map ranges

- bokehjs/src/coffee/models/widgets/tabs.coffee
> added render line to allow programatic change of tabs, fixes Issue #6502

- sphinx/source/docs/releases/0.12.11.rst
- sphinx/source/docs/user_guide/examples/extensions_ion_range_slider.coffee
> Make extensions_ion_range_slider work with CoffeeScript 2

- bokehjs/src/coffee/document.coffee
- bokehjs/src/coffee/embed.coffee
- bokehjs/src/coffee/models/canvas/canvas.coffee
This so far reduces initialization time of the 60 plot example from 37 to 22 seconds on my hardware. Further optimization is possible, but not as cheap as this. I may add some more if time permits. Otherwise I will look into this more after release.
addresses #6294
> Reduce (multi) plot initialization time

- sphinx/source/docs/user_guide/plotting.rst
Adding in additional Information regarding  CDS data structure used in multi_line() to clarify usage.
- [ X] issues: fixes #7198
> multi_line() Documentation Addition

- bokehjs/src/coffee/core/layout/side_panel.coffee
- bokehjs/src/coffee/models/layouts/layout_dom.coffee
- bokehjs/src/coffee/models/plots/plot.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
- bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
- bokehjs/src/coffee/models/tools/actions/zoom_in_tool.coffee
- bokehjs/src/coffee/models/tools/actions/zoom_out_tool.coffee
- bokehjs/src/coffee/models/tools/gestures/pan_tool.coffee
- bokehjs/src/coffee/models/tools/gestures/wheel_pan_tool.coffee
- bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.coffee
- bokehjs/test/core/layout/side_panel.coffee
- bokehjs/test/core/ui_events.coffee
fixes #4394
fixes #6676 
~~~fixes #6356~~~
> Allow to recompute layout when panels' dimensions change

- bokeh/application/handlers/directory.py
Added so that the required filename keyword is exposed to docs in https://bokeh.pydata.org/en/latest/docs/reference/application/handlers/directory.html#bokeh.application.handlers.directory.DirectoryHandler.__init__
> add kwargs documentation for DirectoryHandler

- bokehjs/src/coffee/models/tools/gestures/pan_tool.coffee
> Invert range_info.sdy after switch to screen coordinates

- bokehjs/src/coffee/models/widgets/slider.coffee
> Fix incorrect values of all-integers Sliders

- examples/app/spectrogram/waterfall.coffee
> Fix app/spectrogram example

- examples/plotting/file/brewer.py
Stacked area chart example - https://bokeh.pydata.org/en/latest/docs/gallery/brewer.html can be simplified in 2 parts.
- generation of dataframe
- `stacked` function
> REF: Simplify examples/plotting/file/brewer.py dataframe creation and stacked function

- bokehjs/src/coffee/core/layout/side_panel.coffee
- bokehjs/src/coffee/models/annotations/annotation.coffee
- bokehjs/src/coffee/models/axes/axis.coffee
- bokehjs/src/coffee/models/plots/plot_canvas.coffee
Performance is still worse than before, but that's expected. This should improve with further refinements to layout and rendering pipeline.
fixes #7255
> Don't cut corners and implement proper get_size() method

- bokeh/sphinxext/bokeh_options.py
fix formatting for new jinja2 version
> update for jinja exposed an issue with Options processing

- bokeh/resources.py
> Add proper error message when invalid BOKEH_LOG_LEVEL (#7276)

- sphinx/source/docs/user_guide/tools.rst
> changed example to include import statement

- sphinx/source/docs/user_guide/server.rst
Removed a broken link. No changes made to code.
> Removed a broken link from server.rst

- bokeh/io/export.py
Resolves [#7298](https://github.com/bokeh/bokeh/issues/7298).
> Remove dependency on PhantomJS when the default webdriver is not used

- bokeh/server/views/root_handler.py
> Sort app names

- sphinx/source/bokeh_theme/static/js/main.js
issues: fixes #7318
tests added / passed
> make docs version warning banner stick to the top always

- bokeh/models/tests/test_graphs.py
These tests are failing for me locally, which has been fairly annoying.
> replace strict fp equality with allclose

- bokehjs/src/coffee/models/layouts/box.ts
> Initialize Box's layout variables in initialize()

- bokeh/core/_templates/file.html
- bokehjs/src/coffee/core/dom.ts
- bokehjs/src/coffee/models/layouts/layout_dom.ts
- bokehjs/src/less/bokeh.less
- sphinx/source/docs/releases/0.12.13.rst
> Don't require CSS width/height for responsive sizing modes

- bokeh/io/export.py
- bokeh/util/dependencies.py
- [#7327 ] issues: fixes 
- [NA] tests added / passed - Can add, just need to know preferred test directory I should add to.
- [NA] release document entry (if new feature or API change)
> Sweet phantomjs dependency

- sphinx/source/docs/user_guide/server.rst
> Fix minor typos in bokeh server docs

- bokehjs/src/coffee/models/widgets/tables/cell_editors.coffee
cc @mattpap this seems to resolve the issue, do you have any additional comments?
> fix initialization order issue

- examples/examples.yaml
Followup on PR #7350.
fixes #7164
> Add integration/layout to examples.yaml

- bokehjs/src/coffee/models/ranges/factor_range.ts
- bokehjs/src/coffee/models/renderers/glyph_renderer.coffee
- bokehjs/test/models/ranges/factor_range.coffee
- sphinx/source/docs/releases/0.12.14.rst
> Support updates to factor range factors

- README.md
> fixed a broken link ('why anaconda')

- bokehjs/src/coffee/polyfill.ts
issues: fixes #7373
@mattpap I believe this is the required fix but please take a look (doing some cargo-cult TS learning)
> add polyfill for Number.isInteger

- bokehjs/src/coffee/core/has_props.ts
- bokehjs/src/coffee/core/view.ts
- bokehjs/src/coffee/models/annotations/legend.ts
- bokehjs/src/coffee/models/callbacks/customjs.ts
- bokehjs/src/coffee/models/filters/customjs_filter.ts
- bokehjs/src/coffee/models/formatters/basic_tick_formatter.ts
- bokehjs/src/coffee/models/plots/plot_canvas.ts
- bokehjs/src/coffee/models/tools/tool_proxy.ts
- bokehjs/src/coffee/models/tools/toolbar_base.ts
- bokehjs/src/coffee/models/tools/toolbar_box.ts
- bokehjs/src/coffee/models/transforms/customjs_transform.ts
> Drop {Model,View}.getters, use get/set syntax instead

- bokehjs/src/coffee/api/charts.ts
- bokehjs/src/coffee/api/plotting.ts
- bokehjs/src/coffee/core/enums.ts
- bokehjs/src/coffee/core/ui_events.ts
- bokehjs/src/coffee/core/util/color.ts
- bokehjs/src/coffee/models/glyphs/annular_wedge.ts
- bokehjs/src/coffee/models/plots/plot_canvas.ts
- bokehjs/src/coffee/models/renderers/glyph_renderer.ts
- bokehjs/src/coffee/models/sources/geojson_data_source.ts
- bokehjs/src/coffee/models/tiles/tile_renderer.ts
- bokehjs/src/coffee/models/tiles/tile_source.ts
- bokehjs/src/coffee/models/tools/toolbar_box.ts
- bokehjs/src/coffee/models/transforms/customjs_transform.ts
- bokehjs/src/coffee/models/widgets/abstract_slider.ts
- bokehjs/src/coffee/models/widgets/autocomplete_input.ts
- bokehjs/src/coffee/models/widgets/multiselect.ts
- bokehjs/src/coffee/models/widgets/selectbox.ts
- bokehjs/src/coffee/models/widgets/tables/data_table.ts
- bokehjs/src/coffee/models/widgets/tabs.ts
> Resolve TS2304 errors

- bokehjs/src/coffee/core/dom_view.ts
- bokehjs/src/coffee/models/annotations/tooltip.ts
- bokehjs/src/coffee/models/canvas/canvas.ts
- bokehjs/src/coffee/models/layouts/box.ts
- bokehjs/src/coffee/models/layouts/column.ts
- bokehjs/src/coffee/models/layouts/layout_dom.ts
- bokehjs/src/coffee/models/layouts/row.ts
- bokehjs/src/coffee/models/layouts/spacer.ts
- bokehjs/src/coffee/models/layouts/widget_box.ts
- bokehjs/src/coffee/models/plots/plot.ts
- bokehjs/src/coffee/models/plots/plot_canvas.ts
- bokehjs/src/coffee/models/tools/button_tool.ts
- bokehjs/src/coffee/models/tools/toolbar_box.ts
- bokehjs/src/coffee/models/widgets/date_picker.ts
- bokehjs/src/coffee/models/widgets/tables/cell_editors.ts
- bokehjs/src/coffee/models/widgets/tables/data_table.ts
- bokehjs/src/coffee/models/widgets/text_input.ts
- bokehjs/src/coffee/models/widgets/widget.ts
- sphinx/source/docs/releases/0.12.14.rst
> Allow to accumulate CSS classes from parent views

- bokehjs/package-lock.json
> Update package-lock.json after upgrading nouislider

- bokehjs/src/coffee/models/glyphs/annular_wedge.ts
- bokehjs/src/coffee/models/glyphs/circle.ts
- bokehjs/src/coffee/models/glyphs/multi_line.ts
> Clean up mapping code in models/glyphs

- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/coffee/models/widgets/abstract_slider.ts
- bokehjs/src/less/widgets/nouislider.less
- sphinx/source/docs/releases/0.12.14.rst
> Revert upgrade of nouislider to version 11.0

- bokehjs/package-lock.json
- scripts/deploy.py
> Update version number in package-lock.json

- bokehjs/src/coffee/models/renderers/glyph_renderer.ts
- examples/examples.yaml
- examples/integration/glyphs/selection_nonselection.py
> Fix regression in rendering (non)selection glyphs

- bokeh/util/dependencies.py
- bokeh/util/tests/test_dependencies.py
- setup.py
- sphinx/source/docs/releases/0.12.14.rst
- sphinx/source/docs/user_guide/export.rst
> document min PhantomJS version and error on bad versions

- sphinx/source/docs/releases/0.12.14.rst
- sphinx/source/docs/user_guide/embed.rst
> update user guide embed docs

- bokehjs/src/coffee/models/renderers/glyph_renderer.ts
@philippjfr @mattpap this seems to fix both the issues above, as well as keep the fix for #7083 but more testing appreciated.
My best guess is the the more general original code resulted in some kind of perpetual event ping-pong that made UI interactions difficult
> only trigger set_data from FactorRange changes

- bokehjs/src/coffee/models/plots/plot.ts
- bokehjs/src/coffee/models/renderers/glyph_renderer.ts
> Improve state management for implicit toolbar panel

- examples/plotting/file/elements.py
- accoding to https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#basic-tooltips
- plus tiny bit of code cleanup (pylint)
no tests needed, no new functionality, just example
no new feature or API chnge
> Add tooltip to elements example, fix #7500

- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/coffee/models/annotations/annotation.ts
- bokehjs/src/coffee/models/annotations/arrow.ts
- bokehjs/src/coffee/models/annotations/band.ts
- bokehjs/src/coffee/models/annotations/color_bar.ts
- bokehjs/src/coffee/models/annotations/label_set.ts
- bokehjs/src/coffee/models/annotations/text_annotation.ts
- bokehjs/src/coffee/models/annotations/whisker.ts
- bokehjs/src/coffee/models/axes/axis.ts
- bokehjs/src/coffee/models/glyphs/glyph.ts
- bokehjs/src/coffee/models/glyphs/quad.ts
- bokehjs/src/coffee/models/renderers/glyph_renderer.ts
- bokehjs/src/coffee/models/renderers/graph_renderer.ts
- bokehjs/src/coffee/models/renderers/renderer.ts
- bokehjs/src/coffee/models/tools/toolbar_box.ts
- bokehjs/src/coffee/models/widgets/tables/cell_editors.ts
- bokehjs/src/coffee/models/widgets/tables/cell_formatters.ts
> Upgrade TypeScript to version 2.7.1

- bokehjs/gulp/tasks/scripts.ts
- bokehjs/gulp/tasks/test.ts
- bokehjs/src/coffee/tsconfig.json
This is a further simplification of our build. This also makes bokehjs development with vscode finally possible.
addresses #6481
> Specify compilation inputs in tsconfig.json

- conda.recipe/meta.yaml
> Remove pytest-catchlog from test dependencies

- examples/models/file/iris_splom.py
> Add axis names to Scatterplot matrix

- bokeh/command/subcommands/png.py
- bokeh/command/subcommands/svg.py
- bokeh/io/export.py
- bokeh/io/tests/test_export.py
> Clean up tmp files and processes used by bokeh.io.export

- bokehjs/src/coffee/models/plots/plot.ts
> Configure side renderers' panels before setting up a toolbar

- bokeh/core/property/containers.py
- bokeh/core/property/tests/test_containers.py
> Stream as ndarray if any of old or new is an ndarray

- bokeh/models/callbacks.py
- bokeh/models/filters.py
- bokeh/models/formatters.py
- bokeh/models/transforms.py
- sphinx/source/docs/user_guide/interaction/callbacks.rst
> update docs to install flexx from conda-forge

- bokehjs/src/coffee/models/sources/column_data_source.ts
> Implement rollover correctly in non-typed array case

- _setup_support.py
- bokehjs/gulp/tasks/scripts.ts
- scripts/ci/install:codebase
- scripts/ci/test:codebase
> Fail travis ci tests when TS errors are present

- bokeh/io/export.py
> Fix WebDriverException when using export_png

- bokeh/application/tests/test_application.py
- bokeh/core/validation/check.py
- bokeh/document/document.py
- bokeh/document/tests/test_document.py
- bokeh/events.py
- bokeh/model.py
> fix bad logger name configs

- sphinx/source/docs/user_guide/embed.rst
> DOC: BUG: fix typo in user guide docs on embed

- bokehjs/src/coffee/core/util/formatters.d.ts
- bokehjs/src/coffee/models/axes/categorical_axis.ts
- bokehjs/src/coffee/models/formatters/basic_tick_formatter.ts
- bokehjs/src/coffee/models/formatters/categorical_tick_formatter.ts
- bokehjs/src/coffee/models/formatters/datetime_tick_formatter.ts
- bokehjs/src/coffee/models/formatters/func_tick_formatter.ts
- bokehjs/src/coffee/models/formatters/log_tick_formatter.ts
- bokehjs/src/coffee/models/formatters/mercator_tick_formatter.ts
- bokehjs/src/coffee/models/formatters/numeral_tick_formatter.ts
- bokehjs/src/coffee/models/formatters/printf_tick_formatter.ts
- bokehjs/src/coffee/models/formatters/tick_formatter.ts
> Fix type errors in models/formatters

- bokehjs/gulpfile.js
- bokehjs/package.json
- scripts/ci/install:build
- scripts/ci/install:test
> Add node and npm version requirement specification

- bokehjs/src/coffee/core/build_views.ts
- bokehjs/src/coffee/models/tools/tool_proxy.ts
- bokehjs/src/coffee/models/tools/toolbar.ts
- bokehjs/src/coffee/models/tools/toolbar_base.ts
- bokehjs/src/coffee/models/tools/toolbar_box.ts
> Fix type errors in models/tools/toolbar*

- bokehjs/src/coffee/models/glyphs/webgl/base.ts
- bokehjs/src/coffee/models/glyphs/webgl/index.ts
- bokehjs/src/coffee/models/glyphs/webgl/line.ts
- bokehjs/src/coffee/models/glyphs/webgl/markers.frag.ts
- bokehjs/src/coffee/models/glyphs/webgl/markers.ts
- bokehjs/src/coffee/models/glyphs/webgl/markers.vert.ts
- bokehjs/src/coffee/models/plots/plot_canvas.ts
> Fix type errors in models/glyphs/webgl

- bokehjs/src/coffee/models/widgets/abstract_slider.ts
Small bug fix.  This fix could potentially hid some deeper problem; I don't have a very complete understanding of the javascript code.
> Bug fix: slider keyboard navigation

- bokehjs/src/coffee/models/widgets/multiselect.ts
- bokehjs/test/models/widgets/index.coffee
- bokehjs/test/models/widgets/multiselect.coffee
> render initial values for multi selects

- bokehjs/src/coffee/models/glyphs/image.ts
- bokehjs/src/coffee/models/glyphs/image_rgba.ts
- examples/integration/glyphs/image_non_binary_arrays.py
> Restore code handling empty array shape tuples

- bokehjs/src/coffee/core/dom.ts
- bokehjs/src/coffee/models/layouts/layout_dom.ts
> Subtract padding when calculating dims for responsive modes

- bokeh/server/tornado.py
> Propagate settings from Bokeh Server to TornadoApplication

- bokehjs/src/coffee/models/plots/plot_canvas.ts
- examples/examples.yaml
- examples/integration/webgl/multiple_webgl_plots.py
I added a test, but this will fully make sense when we move away from phantomjs.
fixes #7681
> Fix initialization of multiple webgl plots

- README.md
Reworded several sentences and paragraphs for clarity and concision. Corrected several spelling and grammatical errors. All original information was maintained.
> Update README.md for clarity and concision

- bokehjs/src/coffee/models/plots/gmap_plot_canvas.ts
> Fix regression in GMapPlotCanvas' initialization code

- bokeh/models/tools.py
- bokehjs/src/coffee/models/plots/plot_canvas.ts
- bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.ts
> Add maintain_focus parameter to WheelZoomTool

- examples/howto/events_app.py
- examples/howto/js_events.py
> Fix CSS in examples/howto/{events_app,js_events}

- bokeh/application/application.py
- bokeh/document/document.py
- bokeh/document/locking.py
- bokeh/document/tests/test_document.py
- bokeh/document/tests/test_locking.py
- bokeh/server/application_context.py
- bokeh/server/callbacks.py
- bokeh/server/tests/test_callbacks.py
- bokeh/server/tests/test_server.py
- bokeh/tests/test_client_server.py
- bokeh/util/tornado.py
- sphinx/source/docs/releases/0.12.15.rst
- tests/examples/test_examples.py
> Make adding callbacks thread-safe

- bokeh/io/notebook.py
- bokeh/io/showing.py
- bokeh/io/tests/test_showing.py
> bokeh server support for running in JupyterHub. (#7685)

- bokeh/palettes.py
> Fixed typos in palettes.py

- sphinx/source/docs/releases/0.12.15.rst
- sphinx/source/docs/user_guide/examples/plotting_hex_tile_basic.py
- sphinx/source/docs/user_guide/examples/plotting_hex_tile_binning.py
- sphinx/source/docs/user_guide/plotting.rst
> release docs for 0.12.15

- conda.recipe/meta.yaml
- scripts/ci/install:deploy
- scripts/deps.py
- setup.py
ref: https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
> Markdown description for PyPI

- bokehjs/src/coffee/models/glyphs/glyph.ts
- examples/integration/glyphs/categorical_multi_glyphs.py
> process categorical coords properly for multi-glyphs

- .gitignore
- bokeh/core/enums.py
- bokeh/core/tests/test_enums.py
- bokeh/models/axes.py
- bokehjs/src/coffee/core/enums.ts
- bokehjs/src/coffee/models/axes/axis.ts
- bokehjs/src/coffee/models/axes/categorical_axis.ts
- examples/integration/axes/cat_labels_rotate.py
> add support for rotating group and subgroup categorical tick labels

- conda.recipe/meta.yaml
- scripts/ci/test:unit
> don't use --rerun

- bokehjs/src/coffee/models/widgets/tables/cell_editors.ts
@mattpap If there are improvements (better return typings, or tests) let me know or feel free to add them to this branch
> add missing return to cell editor view validate()

- bokeh/server/views/ws.py
> lower bad pong messages to trace

- bokeh/io/showing.py
- bokeh/io/tests/test_showing.py
> better error message if show arg is bad

- bokeh/models/tools.py
- bokehjs/src/coffee/models/tools/gestures/wheel_zoom_tool.ts
- examples/models/file/dateaxis.py
> add option to disable wheel zoom on axes

- sphinx/source/bokeh_theme/static/js/main.js
> fix error with link highlighting and external links

- bokehjs/src/coffee/models/glyphs/hex_tile.ts
> Replace RBush with SpatialIndex in glyphs/hex_tile

- bokeh/io/export.py
> Fix "bad file descriptor" error on travis ci

- conda.recipe/meta.yaml
- scripts/ci/test:unit
> Revert "don't use --rerun"

- bokeh/client/session.py
- bokeh/client/tests/test_session.py
- bokeh/embed/server.py
- examples/embed/server_session/README.md
- examples/embed/server_session/bokeh_app.py
- examples/embed/server_session/serve.py
- sphinx/source/docs/user_guide/embed.rst
- sphinx/source/docs/user_guide/server.rst
> make ClientSession a context manager

- tests/plugins/jupyter_notebook.py
AFAIK we aren't currently using this fixture, but we should start putting notebooks back under test soon. For now tested this code by hand.
> restore old custom.js contents if it exists

- bokeh/io/export.py
- bokeh/io/tests/test_export.py
> Don't reopen temp files to avoid platform specific issues

- tests/examples/examples_report_plugin.py
- tests/plugins/upload_to_s3.py
> Don't report multiple S3 upload errors for PRs submitted from forks

- examples/plotting/file/hex_tile.py
When I was playing with this example I found myself wanting to pan after zooming in.
I thought this might be a sane default to add.  Granted others could add that in later but I thought it would be nice to have right off the bat.
> added 'pan' to the hexbin example

- bokehjs/src/coffee/core/selection_manager.ts
- bokehjs/src/coffee/models/renderers/glyph_renderer.ts
- bokehjs/src/coffee/models/sources/data_source.ts
- bokehjs/src/coffee/models/sources/remote_data_source.ts
> Type core/selection_manager and handle null hit test result

- bokehjs/src/coffee/core/properties.ts
- bokehjs/test/core/properties.coffee
- examples/integration/widgets/tabs_with_multiselect.py
> Make detection of a spec more robust

- bokehjs/src/lib/models/plots/plot_canvas.ts
> Add missing break statements to PlotCanvas.save()

- .bettercodehub.yml
- bokeh/io/export.py
- bokehjs/src/lib/base.ts
- bokehjs/src/lib/models/glyphs/webgl/base.ts
- bokehjs/test/unit.coffee
- scripts/deploy.py
- sphinx/source/docs/user_guide/bokehjs.rst
- sphinx/source/docs/user_guide/extensions.rst
> Finalize rename bokehjs/src/{coffee->lib}

- bokeh/command/bootstrap.py
> Add an epilog to 'bokeh --help` regarding subcommands' help

- bokeh/sphinxext/bokeh_plot.py
Add 'bokeh_plot_use_relative_paths' sphinx config option which places
relative path strings in the generated html to render bokeh plots served
statically.
Default is false which leaves the paths unchanged as they currently are.
-  partially addresses #5955
> Add relative path option and handling to sphinx ext.

- bokeh/models/callbacks.py
- bokeh/models/filters.py
- bokeh/models/formatters.py
- bokeh/models/tests/test_formatters.py
- bokeh/models/tests/test_transforms.py
- bokeh/models/transforms.py
- conda.recipe/meta.yaml
- examples/plotting/file/python_callback.py
- sphinx/source/docs/user_guide/data.rst
- sphinx/source/docs/user_guide/interaction/callbacks.rst
This will have to wait for @almarklein to publish a conda package for `pscript`.
fixes #7576
> Replace flexx.pyscript with pscript

- examples/app/surface3d/main.py
- examples/app/surface3d/surface3d.coffee
- examples/app/surface3d/surface3d.py
- sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py
> remove spurious surface3d color property

- bokeh/models/sources.py
- bokeh/tests/test_objects.py
- bokehjs/src/lib/core/selection_manager.ts
- bokehjs/src/lib/models/selections/interaction_policy.ts
- bokehjs/src/lib/models/sources/columnar_data_source.ts
- bokehjs/src/lib/models/tools/gestures/select_tool.ts
- bokehjs/src/lib/models/tools/gestures/tap_tool.ts
- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
- bokehjs/src/lib/models/tools/util.ts
- bokehjs/test/core/selection_manager.coffee
> Revert "Set a data source's inspected taking multiple renderers into account"

- bokehjs/package-lock.json
- bokehjs/package.json
Other PRs will need to rebase/merge master after this. 
cc @mattpap
> Update for npm 6

- bokehjs/src/lib/models/widgets/abstract_slider.ts
> use internal slider value for keypress action

- sphinx/source/docs/user_guide/embed.rst
A missing "<" is added to an example in embed.rst.
> Minor fix in docs

- sphinx/source/docs/user_guide/quickstart.rst
> Proofread Quickstart

- sphinx/source/docs/user_guide/examples/extensions_ion_range_slider.coffee
> Fixed name collision in ion_range_slider example

- bokeh/models/formatters.py
- bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts
> use full year in default month format

- bokeh/models/tools.py
- bokehjs/src/lib/core/menus.ts
- bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
- bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
- bokehjs/src/lib/models/widgets/autocomplete_input.ts
- bokehjs/src/lib/models/widgets/dropdown.ts
> Add support for center origin to box select/zoom tools

- bokeh/embed/standalone.py
- bokeh/embed/tests/test_standalone.py
> use whole doc for saving

- bokeh/models/widgets/buttons.py
> update Dropdown.default_value docs

- bokehjs/package-lock.json
- bokehjs/package.json
@mattpap npm was reporting several vulnerabilities, some "high" or "ciritical". All of them were in `devDependencies` as far as I could tell, but I'd still rather be visibly in front of these things. I made the changes it suggested, things seem to build fine, and tests pass. Do you have any comments?
partial for #7880
> resolve reported npm issues

- bokeh/util/dependencies.py
> Fix detect_phantomjs() when shutil.which() returns None

- bokeh/io/export.py
- bokeh/io/tests/test_export.py
> correctly export unicode content with unminified resources

- sphinx/source/docs/releases/0.12.16.rst
Does it makes sense to change Apr to May for 0.12.16 release?  Because the final version was released on 14 of May.
And should I create an issue for such minor change?
> Fix release month for 0.12.16 in docs

- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/lib/api/plotting.ts
- bokehjs/src/lib/core/build_views.ts
- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/core/types.ts
- bokehjs/src/lib/core/util/object.ts
- bokehjs/src/lib/core/util/templating.ts
- bokehjs/src/lib/core/util/types.ts
- bokehjs/src/lib/document.ts
- bokehjs/src/lib/models/layouts/box.ts
- bokehjs/src/lib/models/layouts/spacer.ts
- bokehjs/src/lib/models/layouts/widget_box.ts
- bokehjs/src/lib/models/plots/plot.ts
- bokehjs/src/lib/models/plots/plot_canvas.ts
- bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
- bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
- bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
- bokehjs/src/lib/models/tools/gestures/select_tool.ts
- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
- bokehjs/src/lib/models/tools/util.ts
- bokehjs/src/lib/models/widgets/markup.ts
- bokehjs/src/lib/models/widgets/tables/cell_editors.ts
- bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
- bokehjs/src/lib/safely.ts
- bokehjs/test/core/util/object.ts
> Remove unnecessary usage of any type from inspectors/hover_tool

- scripts/ci/install
> Pin pandas to version < 0.23

- sphinx/source/docs/user_guide/data.rst
Do this because it totally tripped me up when I used the example structure as a template to iterate from.
I know the Pull Request template requested an issue to be made first, but it seemed like overkill in this case.  I will go do so upon request though.
Thanks for the great tool!
> Correct off-by-one error in example in documentation.

- scripts/build_upload.py
> parameterize RS urls

- scripts/ci/deploy
> Don't use known_hosts from secrets 

- bokehjs/src/lib/models/widgets/multiselect.ts
> Make MultiSelect unselect previously selected items

- sphinx/source/docs/dev_guide/bokehjs.rst
- sphinx/source/docs/dev_guide/setup.rst
- sphinx/source/docs/user_guide/data.rst
- sphinx/source/docs/user_guide/styling.rst
> Update docs regarding the implementation language of bokehjs

- sphinx/source/docs/user_guide/notebook.rst
> Add link to Bokeh tutorial notebooks

- examples/howto/server_embed/flask_gunicorn_embed.py
> get gunicorn example working again (py3 only)

- bokeh/util/callback_manager.py
- bokeh/util/tests/test_callback_manager.py
> ensure on_event works with unicode event names

- bokeh/model.py
- bokeh/sphinxext/bokeh_plot.py
@mattpap if you think this (or something like it) should be made public please let me know and I will add tests and docs. Otherwise I think this is just a stopgap measure until something more comprehensive can be undertaken.
> add a private _clear_extensions method that the docs can use for now

- bokehjs/make/index.js
> Run `npm install` automatically if package.json changed

- bokeh/models/glyphs.py
> Typo fixed in image w parameter (height instead of width)

- MAINTAINERS
@bryevdv has asked me to make regular dev builds
> Add new maintainer to the list

- bokehjs/src/lib/models/transforms/jitter.ts
- bokehjs/test/models/transforms/jitter.coffee
> cache jitter for identical input lengths

- bokeh/core/properties.py
- bokeh/core/property/bases.py
- bokeh/core/property/containers.py
- bokeh/core/property/descriptors.py
- bokeh/core/property/tests/test_bases.py
- bokeh/core/tests/test_properties.py
- bokeh/util/serialization.py
Will add tests after it is determined that this is of reasonable benefit.
> don't generate detail validation stings for purely internal checks

- bokehjs/src/lib/models/renderers/glyph_renderer.ts
- bokehjs/src/lib/models/widgets/tables/data_table.ts
These issues actually seem to be left over issues from the selection refactor. The first commit here fixes both issues but I need to do more testing to see if anything else is broken.
> fix up selection handling

- bokehjs/src/lib/models/layouts/layout_dom.ts
ref: #7978 
Not closing the linked issue with this since it is a partial bandaid, at best.
> temp partial fix allowing scale_both to work in some cases

- sphinx/source/docs/user_guide/server.rst
> Updated docs for two-way Jupyter communication

- bokeh/plotting/helpers.py
- bokeh/plotting/tests/test_helpers.py
Access underlying `np.ndarray` when passing `pd.Series`. Also added tests, and made the pandas dependency optional (this is good-form, right?)
> Fixes #7401: set range with pandas Series

- bokehjs/src/lib/models/canvas/canvas.ts
- bokehjs/src/lib/models/layouts/layout_dom.ts
- examples/plotting/file/custom_layout.py
> Improve computing of available space for responsive layouts

- examples/app/dash/README.md
Added short usage instructions as per @bryevdv (#8011 comment: https://github.com/bokeh/bokeh/pull/8011#issuecomment-399509585)
> Added short usage instructions for examples/app/dash

- bokeh/core/validation/errors.py
- bokeh/core/validation/warnings.py
- bokeh/models/ranges.py
- bokeh/models/tests/test_ranges.py
> raise validation error on duplicate factor range factors

- bokehjs/src/lib/models/tickers/log_ticker.ts
- bokehjs/test/models/tickers/log_ticker.ts
> move log tick filtering to the very end

- bokeh/util/serialization.py
- bokeh/util/tests/test_serialization.py
> handle pd.NaT

- bokeh/io/tests/test_export.py
> add fixture to re-use webdriver in export tests

- bokeh/server/contexts.py
- bokeh/server/tests/test_contexts.py
- bokeh/server/tornado.py
- sphinx/source/docs/reference/server/application_context.rst
- sphinx/source/docs/reference/server/contexts.rst
- sphinx/source/docs/releases/1.0.0.rst
> fix ServerContext.sessions bug

- bokeh/application/handlers/code.py
- bokeh/application/handlers/code_runner.py
- bokeh/application/handlers/notebook.py
- bokeh/application/handlers/tests/test_code_runner.py
> allow recovery from transient script errors

- bokehjs/src/lib/models/widgets/tables/data_table.ts
... to allow selectable be a checkbox
Fixes #8050
> Addresses #8050 Change type of the selectable property of DataTable

- bokeh/document/document.py
- bokeh/document/tests/test_document.py
- bokeh/models/plots.py
- bokeh/models/selections.py
- bokeh/models/tests/test_plots.py
- bokeh/server/tests/test_callbacks.py
- bokeh/util/tornado.py
- examples/models/file/transform_jitter.py
- examples/models/file/transform_jitter_coffee.py
- examples/plotting/file/elements.py
Removes all deprecations for upcoming 1.0 release.
> remove all deprecations

- bokeh/models/widgets/tables.py
- bokehjs/src/lib/models/widgets/tables/data_table.ts
This is not an especially important feature in and of itself, but I plan to use this issue to figure out how to ad back some selenium tests on Travis.
> add header_row property to support hiding table headers

- bokehjs/src/lib/models/markers/marker.ts
- scripts/ci/install
- scripts/ci/install:unit
> always use zero angle for marker legends

- sphinx/source/docs/user_guide/annotations.rst
- sphinx/source/docs/user_guide/bokehjs.rst
- sphinx/source/docs/user_guide/layout.rst
Cleanup backticks in .rst docs
> DOC: clean backticks in .rst docs #8097

- _setup_support.py
- bokeh/_testing/util/examples.py
- bokeh/core/enums.py
- bokeh/embed/util.py
- bokeh/models/filters.py
- bokeh/models/formatters.py
- bokeh/models/tools.py
- bokeh/models/transforms.py
- bokeh/plotting/helpers.py
- bokeh/sampledata/autompg2.py
- bokeh/sampledata/us_holidays.py
- bokeh/tests/test_palettes.py
- bokeh/util/compiler.py
- bokeh/util/string.py
- examples/app/fourier_animated.py
Use generators inplace of lists
> REF: Use generators inplace of lists #8092

- bokeh/core/validation/errors.py
- bokeh/models/widgets/sliders.py
- bokeh/models/widgets/tests/test_slider.py
> Fix Karel/7788 rangeslider minmax

- bokeh/protocol/receiver.py
> Replace use of return_future with gen.coroutine

- bokeh/embed/server.py
- sphinx/source/docs/releases/1.0.0.rst
> remove non-functional arguments parameter

- examples/app/ohlc/main.py
Removed BUFSIZE variable, which is not being used in this script.
issues: none
type: bug
reso: completed
tag: examples
milestone: unmilestoned
> issues: none type: bug tag: examples Updated main.py

- bokeh/document/tests/test_document.py
> account for get_referrers change in python 3.7

- sphinx/source/docs/installation.rst
- sphinx/source/docs/user_guide/export.rst
This PR does the following:
- Updates installation docs to add missing dependencies
- Improves doc on Exporting Plots. Additional dependencies are required for all export functions not just export_png.
> Improve docs for export functions

- bokeh/core/properties.py
- bokeh/model.py
Code was erroneously checking for `str`, changing to add `unicode_literals` exposed the error.
> properly use string_types for Instance properties and js_on_event

- sphinx/source/docs/user_guide/examples/plotting_hex_tile_basic.py
> typo for plotting_hex_tile_basic.py by ppplinday

- bokeh/models/ranges.py
- sphinx/source/docs/user_guide/plotting.rst
> slight range docs improvements

- bokeh/client/connection.py
- bokeh/client/session.py
- bokeh/client/tests/test_connection.py
- bokeh/client/tests/test_session.py
> allow pull_session to accept HTTP args

- .appveyor.yml
- scripts/ci/appveyor/build.ps1
- scripts/ci/appveyor/install.ps1
- scripts/ci/appveyor/test.ps1
> Ci windows appveyor

- bokehjs/src/lib/models/annotations/legend.ts
- bokehjs/src/lib/models/annotations/legend_item.ts
Re: testing, there is not any good current way. This needs an integration/selenium test since it involves executing an interaction to make an update to legend state. It's not merely enough to inspect the state however, the test needs to confirm the render (that was the actual issue to fix). That will require "image-diff" integration tests, which we do not have yet. I will add an issue to add those, and start a list linking back to specific issues like this that need one. 
Test script:
```
from bokeh.io import curdoc
from bokeh.models import Button
x = [1,2,3,4,5, 10]
y = [5,6,2,3,4,10]
p = figure()
r = p.line(x, y, legend="foo")
def cb():
p.circle(x, y, legend="foo")
r.glyph.line_dash = "dotted"
r.glyph.line_color = …
```
> add plumbing to make legends update changes

- bokeh/util/dependencies.py
Resolves #8263 by adding text to exception message
> Adding mention of BOKEH_PHANTOMJS_PATH to RuntimeError exception message

- bokehjs/src/lib/models/glyphs/image_url.ts
- examples/models/file/image_url.py
> let image_url compute bounds

- bokeh/command/subcommands/serve.py
- bokeh/command/subcommands/tests/test_serve.py
> Adding autoreload based on tornado

- bokehjs/src/lib/models/tools/gestures/select_tool.ts
> request a render after clearing selection

- examples/app/gapminder/main.py
#8319 :
> gapminder: has pandas deprecation issues
> Pandas warning removed in Gapminder example

- examples/app/selection_histogram.py
#8319
> selection_histogram: needs update for selection changes
> Correction selection histogram example

- examples/app/population.py
#8319
> populatation: legend position bad
> population example legend position -> "bottom_right"

- bokeh/core/templates.py
> Compat: Get correct env when freezing with cx_Freeze

- examples/embed/embed_multiple.py
#8319 
> embed_multiple: better arrangement
> embed_multiple: better arrangement

- bokehjs/src/lib/models/glyphs/box.ts
> correct spatial index MBB for box glyphs

- sphinx/source/docs/dev_guide/bokehjs.rst
> Chaco link is a 404 - changed to git repo URL 

- bokehjs/src/lib/models/annotations/toolbar_panel.ts
- bokehjs/src/lib/models/tools/toolbar_base.ts
- bokehjs/test/models/tools/toolbar_base.coffee
- tests/integration/tools/test_toolbar_autohide.py
```python
from bokeh.plotting import figure, show, output_file
output_file("test0.html")
p = figure(plot_width=300, plot_height=300)
p.scatter([1, 2, 3], [1, 2, 3])
p.toolbar.autohide = True
show(p)
```
> Fixing autohide pan and wheel stutter

- bokeh/io/webdriver.py
> Always kill phantomjs at process exit

- bokeh/models/annotations.py
- bokeh/models/tools.py
> Fix typo and grammar mistakes

- bokeh/core/property/bases.py
- scripts/deploy.py
> Fix failing codebase tests

- bokeh/io/export.py
> fixed typo in io.export.create_webdriver docs

- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
> Omit colon in hover tooltips if label is empty

- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/lib/core/dom.ts
- bokehjs/src/lib/core/layout/side_panel.ts
- bokehjs/src/lib/external/ie.d.ts
- bokehjs/src/lib/models/layouts/layout_dom.ts
- bokehjs/src/lib/models/plots/plot_canvas.ts
- bokehjs/src/lib/models/widgets/date_picker.ts
> Upgrade TypeScript to version 3.1

- bokeh/embed/standalone.py
- bokeh/embed/tests/test_standalone.py
> Maintain dict type in components()

- bokehjs/package.json
- bokehjs/test/index.coffee
- conda.recipe/meta.yaml
> Allow newer versions of nodejs

- examples/howto/Hover callback.ipynb
sr.data_source -> cr.data_source
> fix a typo

- bokehjs/src/less/tooltips.less
> set tootip text color explicitly

- bokeh/models/sources.py
- bokeh/models/tests/test_sources.py
> Transform Pandas Columns CategoricalIndex in list

- bokehjs/make/compiler.ts
- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/lib/models/axes/categorical_axis.ts
- bokehjs/src/lib/tsconfig.json
> Upgrade to TypeScript 3.2

- bokehjs/src/lib/models/annotations/arrow.ts
This is a proposed fix to allow updating arrow annotations. However it is somewhat inelegant so I am also open to adjusting this if there is a better solution.
> fix for arrow annotation updating on property change

- LICENSE.txt
- bokeh/tests/test___init__.py
- bokehjs/package-lock.json
- bokehjs/package.json
- tests/codebase/test_js_license_set.py
> monitor JS package license usage

- bokeh/core/validation/errors.py
- bokeh/models/renderers.py
Extended BAD_COLUMN_NAME error to include suggestions and 
show key that caused error.
> Extended BAD_COLUMN_NAME error 

- bokeh/models/__init__.py
- scripts/ci/install.downstream
- scripts/ci/test.downstream
Just seeing if I can get this working at first.
> Attempt to enable downstream tests for holoviews

- bokeh/core/_templates/macros.html
- bokeh/embed/tests/test_standalone.py
> Add figure's plot id in DOM structure as well

- bokeh/document/document.py
- bokeh/document/tests/test_document.py
- bokeh/document/util.py
- bokeh/embed/server.py
- bokeh/embed/tests/test_standalone.py
- bokeh/embed/tests/test_util.py
- bokeh/embed/util.py
- bokeh/events.py
- bokeh/io/notebook.py
- bokeh/io/tests/test_notebook.py
- bokeh/model.py
- bokeh/tests/test_events.py
- bokeh/tests/test_objects.py
- bokeh/util/callback_manager.py
- bokehjs/package-lock.json
cc @mattpap this PR also fixes up the BokehJS package lock file
> Property getter for Model.id

- sphinx/source/docs/releases/1.0.1.rst
- sphinx/source/docs/releases/1.0.2.rst
- sphinx/source/docs/releases/1.0.3.rst
> release notes

- bokeh/command/tests/test_util.py
- bokeh/command/util.py
> better error message for nonexistent bokeh serve targets

- bokehjs/prepare.js
I realize this is marked `good first issue` but I want to clear down the tracker, also FWIW I think good first issues should have *slightly* more teeth
> remove warning message aboug gulp

- bokeh/settings.py
- sphinx/source/docs/dev_guide/env_vars.rst
Fixes #8534 (ongoing)
Follow-up with the ToDos still left from #8537
> Fix-up BOKEH_DEV docs (follow-up)

- bokeh/core/validation/warnings.py
- bokeh/models/widgets/sliders.py
> Add documentation on callback policy for slider

- bokeh/events.py
- bokeh/model.py
- bokeh/models/__init__.py
cc @HuntJSparra Just FYI I overlooked some things in earlier reviews.
> add Model, Event, and populate bokeh.models __all__

- bokeh/models/tools.py
Correct three minor typos in` tools.py` comments.
> Correct three minor typos

- bokeh/application/handlers/code_runner.py
- bokeh/application/handlers/notebook.py
- bokeh/application/handlers/tests/test_notebook.py
> Unicode fix when serving notebooks on Python 2

- bokeh/util/tests/test_compiler.py
- bokehjs/src/lib/models/axes/axis.ts
- bokehjs/test/models/axes/axis.ts
> force zero padding for fixed axes

- bokeh/sampledata/commits.py
> adapt to pandas changes

- bokeh/_testing/plugins/bokeh_server.py
- bokeh/_testing/plugins/examples_report.py
- bokeh/_testing/plugins/jupyter_notebook.py
- bokeh/_testing/plugins/log_file.py
- tests/test_examples.py
> Fix pytest's deprecations in examples' tests

- .travis.yml
- bokeh/util/tests/test_compiler.py
- bokehjs/src/compiler/compile.ts
- scripts/ci/install.test
- scripts/ci/install.unit
> Make custom extensions compiler work on Windows

- bokeh/_testing/plugins/examples_report.py
- tests/test_examples.py
After PR #8619 examples' report and images aren't uploaded anymore.
> Fix examples' tests after PR #8619

- bokeh/models/widgets/sliders.py
- bokeh/models/widgets/tests/test_slider.py
> Daterangeslider value as date

- bokeh/application/handlers/document_lifecycle.py
- bokeh/application/handlers/notebook.py
- bokeh/core/property/color.py
- bokeh/core/property/container.py
- bokeh/document/document.py
- bokeh/embed/standalone.py
- bokeh/embed/util.py
- bokeh/plotting/helpers.py
- bokeh/server/tests/utils.py
- bokeh/tests/test_tile_providers.py
- bokeh/util/future.py
- conda.recipe/meta.yaml
- setup.cfg
> resolve various deprectations

- bokeh/_testing/plugins/examples_report.py
- bokeh/_testing/util/examples.py
- tests/test_examples.py
> Make examples' tests work on Windows

- sphinx/source/docs/user_guide/examples/extensions_example_latex.py
- sphinx/source/docs/user_guide/examples/extensions_example_ticking.py
- sphinx/source/docs/user_guide/examples/extensions_example_tool.py
- sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py
It's a work in progress.
It's the first time I code ith typeScript so any advice is welcome
> Transform coffee script in custom extension examples in TypeScript

- examples/integration/layout/grid_axis_alignment_no_toolbar.py
> Fix grid_axis_alignment_no_toolbar on 32-bit platforms

- bokeh/models/widgets/sliders.py
These tests were failing for me locally, only working on travis due to a timezone coincidence.
> assume UTC in value_as_date

- bokehjs/src/lib/core/dom.ts
- bokehjs/src/lib/models/annotations/box_annotation.ts
- bokehjs/src/lib/models/annotations/label.ts
- bokehjs/src/lib/models/annotations/label_set.ts
- bokehjs/src/lib/models/annotations/span.ts
- bokehjs/src/lib/models/annotations/text_annotation.ts
- bokehjs/src/lib/models/annotations/title.ts
- bokehjs/src/lib/models/annotations/toolbar_panel.ts
- bokehjs/src/lib/models/annotations/tooltip.ts
- bokehjs/src/lib/models/widgets/autocomplete_input.ts
- bokehjs/src/lib/models/widgets/dropdown.ts
> Use visibility: hidden on hidden tabs

- bokeh/layouts.py
> restore Spacer transitive import in bokeh.layouts

- .travis.yml
- bokeh/_testing/util/examples.py
- bokeh/_testing/util/s3.py
- scripts/ci/build
- scripts/ci/install.test
Migrate CI test artifact storage to ci.bokeh.org
> use ci.bokeh.org for artifact storage

- bokeh/_testing/util/examples.py
- bokeh/application/handlers/notebook.py
- scripts/ci/build
- scripts/ci/install.test
> open bokeh serve notebooks with utf8

- bokeh/core/_templates/autoload_js.js
- bokehjs/src/lib/embed/dom.ts
- bokehjs/src/lib/embed/index.ts
I tested this manually in Jupyter notebook and lab.
fixes #8681
> Make autoload_js load CSS before JavaScript

- bokehjs/src/lib/models/layouts/layout_dom.ts
This fixes the problem universally (not only in jupyter). This doesn't affect performance (computing `offsetParent` is cheap, compared to other DOM APIs).
fixes #8655
> Observe changes to offset parent and relayout

- bokehjs/examples/tsconfig.json
- bokehjs/make/paths.ts
- bokehjs/make/tasks/scripts.ts
- bokehjs/make/tasks/test.ts
- bokehjs/package.json
- bokehjs/src/compiler/compile.ts
- bokehjs/test/tsconfig.json
> Rename bokehjs/build/js/{tree->lib} to match src/

- bokehjs/src/lib/models/plots/plot_canvas.ts
> Lazily value import UIEvents in PlotView

- bokeh/models/sources.py
- bokehjs/src/lib/models/sources/ajax_data_source.ts
- bokehjs/src/lib/models/sources/index.ts
- bokehjs/src/lib/models/sources/remote_data_source.ts
- bokehjs/src/lib/models/sources/server_sent_data_source.ts
- bokehjs/src/lib/models/sources/web_data_source.ts
- examples/howto/server_sent_events_source.py
> add support for server-sent events

- bokehjs/package-lock.json
Fixes: #8708
Not sure if this is all that needs to be done, but this is what updated after running `npm audit fix`
> After running npm audit fix

- bokeh/server/server.py
- bokeh/tests/test_client_server.py
> yield close_all_connections

- bokehjs/src/less/menu.less
- bokehjs/src/less/mixins.less
- bokehjs/src/less/tooltips.less
> Use correct z-index in bk-tooltip

- bokeh/core/_templates/autoload_js.js
> Run inline js in individual functions in autoload_js

- bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
> Make GMapPlotCanvas work in strict mode

- bokeh/command/subcommands/serve.py
- bokeh/command/subcommands/tests/test_serve.py
> Note for windows user for server --dev

- bokeh/models/layouts.py
- bokehjs/src/less/tabs.less
- bokehjs/src/lib/core/util/array.ts
- bokehjs/src/lib/models/layouts/layout_dom.ts
- bokehjs/src/lib/models/layouts/tabs.ts
- examples/models/file/glyphs.py
> Add support for closable tabs

- bokeh/embed/server.py
- bokeh/io/notebook.py
> Corrected spelling mistakes

- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/lib/api/charts.ts
- bokehjs/src/lib/api/index.ts
- bokehjs/src/lib/core/util/templating.ts
- bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts
- bokehjs/src/lib/models/formatters/printf_tick_formatter.ts
- bokehjs/src/lib/models/widgets/date_picker.ts
> Don't expose external libraries in the public API

- bokeh/embed/bundle.py
- bokeh/embed/elements.py
- bokeh/embed/standalone.py
- bokeh/io/notebook.py
- bokeh/server/views/autoload_js_handler.py
- bokeh/util/compiler.py
- bokeh/util/tests/test_compiler.py
This is a crude but working change. In the long term this should be handled by resources (or resource bundles, yet to be implemented), but that's quite some work given the current state of affairs.
addresses #8747
> Selectively bundle custom models if possible

- bokeh/util/compiler.py
- bokehjs/make/prelude.ts
- sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py
> Allow to resolve both core/layout and core/layout/index

- MAINTAINERS
Adding myself and updating @bryevdv's email
> Update MAINTAINERS list

- bokehjs/src/lib/models/tools/tool_proxy.ts
> Proxy InspectTool.toggleable property

- bokehjs/src/lib/models/layouts/layout_dom.ts
- bokehjs/src/lib/models/widgets/button_group.ts
- bokehjs/src/lib/models/widgets/checkbox_button_group.ts
- bokehjs/src/lib/models/widgets/checkbox_group.ts
- bokehjs/src/lib/models/widgets/control.ts
- bokehjs/src/lib/models/widgets/input_group.ts
- bokehjs/src/lib/models/widgets/radio_button_group.ts
- bokehjs/src/lib/models/widgets/radio_group.ts
> Handle disabled property in control widgets

- bokehjs/examples/legends/legends.ts
- bokehjs/src/lib/api/plotting.ts
> Better handling of default legend in bokehjs' Figure

- bokehjs/src/lib/core/dom.ts
- bokehjs/src/lib/core/layout/grid.ts
- bokehjs/src/lib/core/layout/layoutable.ts
- bokehjs/src/lib/core/layout/types.ts
- bokehjs/src/lib/models/annotations/annotation.ts
- bokehjs/src/lib/models/axes/axis.ts
- bokehjs/src/lib/models/layouts/layout_dom.ts
- bokehjs/src/lib/models/plots/plot_canvas.ts
> Make layout respect visible property

- bokehjs/src/lib/core/util/spatial.ts
> Normalize rects in spatial index to allow inverted ranges

- README.md
- sphinx/source/docs/contact.rst
- sphinx/source/docs/contribute.rst
- sphinx/source/docs/team.rst
- sphinx/source/index.rst
cc @lisamartin72 please check this is the correct link
> update NF donation link

- bokehjs/src/lib/models/layouts/tabs.ts
> Update tabs header when layout recomputes

- bokeh/application/handlers/directory.py
- bokeh/application/handlers/tests/test_directory.py
Ensures that ``DirectoryHandler`` supports notebook files as advertised.
> Fix handling of main.ipynb in DirectoryHandler

- tests/codebase/test_python_execution_with_OO.py
> Make test_python_execution_with_OO work on Windows

- bokeh/io/export.py
- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/lib/polyfill.ts
> Make bokehjs work with phantomjs again

- bokeh/models/widgets/markups.py
> Warn about layout and asynchronous HTML content

- bokehjs/src/lib/models/layouts/layout_dom.ts
> Invalidate render when LayoutDOM.css_classes changes

- bokeh/models/graphs.py
- bokeh/models/tests/test_graphs.py
> accept list/tuple graph attributes

- bokehjs/make/tasks/scripts.ts
- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/lib/bokeh.ts
There is a WIP webpack bundling [example](https://github.com/bokeh/bokehjs-examples/tree/master/webpack-example) to test this.
fixes #8596
> Unify API of npm package and browser bundle

- bokeh/models/widgets/icons.py
- bokehjs/src/lib/models/widgets/abstract_button.ts
- bokehjs/src/lib/models/widgets/abstract_icon.ts
- examples/app/surface3d/surface3d.ts
- examples/custom/font-awesome/fontawesome.less
- examples/custom/font-awesome/fontawesome_icon.ts
- tests/baselines/examples/custom/font-awesome/font-awesome
> Fix app/surface3d and custom/font-awesome examples

- bokehjs/src/lib/core/ui_events.ts
- bokehjs/test/core/ui_events.ts
> Pan the webpage on touch pan events when no tools are selected

- bokeh/io/export.py
- bokeh/models/map_plots.py
- bokeh/models/tools.py
- sphinx/source/docs/dev_guide/setup.rst
- sphinx/source/docs/user_guide/export.rst
- sphinx/source/docs/user_guide/geo.rst
> Close small docs issues

- bokeh/resources.py
> silence warning about root_url trailing slash

- bokehjs/src/lib/models/widgets/abstract_slider.ts
> hook up slider bar color handling

- tests/integration/widgets/test_range_slider.py
- tests/integration/widgets/test_slider.py
- tests/integration/widgets/test_spinner.py
Could use more but it's a start
> selenium tests for sliders

- bokeh/io/export.py
This PR is a first attempt to allow for configurable timeouts when exporting figures.
> Allow export timeouts to be configurable.

- sphinx/source/docs/user_guide/examples/geo_tile_source.py
Update documentation on using tile providers with the `get_provider()` method.
> Fixes #8867

- bokehjs/package-lock.json
- bokehjs/package.json
> Fix security vulnerabilities reported by npm audit

- scripts/build_upload.py
> Upload releases to anaconda dev and main label

- requirements.txt
`requirements.txt` file updated
> Reference link updated

- bokehjs/src/lib/models/widgets/abstract_slider.ts
- tests/integration/widgets/test_slider.py
> Ensure change in Slider widget title updates view

- .travis.yml
> Use Python 3.7 in examples' tests on Travis CI

- bokehjs/src/lib/client/connection.ts
- bokehjs/src/lib/client/session.ts
- bokehjs/src/lib/core/logging.ts
- bokehjs/src/lib/core/types.ts
- bokehjs/src/lib/core/util/array.ts
- bokehjs/src/lib/core/util/arrayable.ts
- bokehjs/src/lib/core/util/templating.ts
- bokehjs/src/lib/core/util/types.ts
- bokehjs/src/lib/es.d.ts
- bokehjs/src/lib/models/axes/axis.ts
- bokehjs/src/lib/models/mappers/categorical_mapper.ts
- bokehjs/src/lib/models/sources/column_data_source.ts
- bokehjs/src/lib/models/sources/columnar_data_source.ts
- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
- bokehjs/src/lib/protocol/message.ts
- bokehjs/test/client/connection.ts
A couple hundred more to go in future PRs.
> Replace some instances of any type

- sphinx/source/docs/user_guide/quickstart.rst
> Docs: Fix typo

- .travis.yml
> trim test matrix

- bokeh/models/callbacks.py
- bokeh/models/filters.py
- bokeh/models/formatters.py
- bokeh/models/transforms.py
- bokehjs/src/lib/models/callbacks/customjs.ts
- bokehjs/src/lib/models/filters/customjs_filter.ts
- bokehjs/src/lib/models/formatters/func_tick_formatter.ts
- bokehjs/src/lib/models/transforms/customjs_transform.ts
- bokehjs/test/models/callbacks/customjs.ts
- bokehjs/test/models/filters/customjs_filter.ts
- bokehjs/test/models/formatters/func_tick_formatter.ts
- bokehjs/test/models/transforms/customjs_transform.ts
- sphinx/source/docs/releases/2.0.0.rst
> use 'use strict' unconditionally

- classifiers.txt
- setup.py
This PR updates the PyPI classifiers, also sets a `python_requires` value. 
@bokeh/core I also removed the "author" info pointing at Anaconda, and in its place added myself as "maintainer" If there is something else preferred (e.g. creating another new bokeh.org email account)  please open an issue to discuss
> update classifiers and setup.py

- sphinx/source/docs/user_guide/categorical.rst
- sphinx/source/docs/user_guide/tools.rst
> Documentation: fix typo and duplicate description

- bokeh/models/annotations.py
- bokeh/models/arrow_heads.py
- bokeh/models/axes.py
- bokeh/models/glyphs.py
- bokeh/models/plots.py
- bokeh/models/tests/test_annotations.py
- bokeh/models/tests/utils/property_utils.py
- bokeh/sphinxext/bokeh_plot.py
- bokeh/themes/_caliber.py
@mattpap I want to keep looking for more places, but are you aware of any others besides these offhand that could be updated?
> Use scalar props where applicable

- bokeh/_testing/util/selenium.py
- bokehjs/src/lib/models/widgets/abstract_slider.ts
- bokehjs/src/lib/models/widgets/date_range_slider.ts
- bokehjs/src/lib/models/widgets/date_slider.ts
- bokehjs/src/lib/models/widgets/range_slider.ts
- bokehjs/src/lib/models/widgets/slider.ts
- tests/integration/widgets/test_range_slider.py
- tests/integration/widgets/test_slider.py
> Fix keyboard events on range sliders

- bokeh/command/subcommands/serve.py
- bokeh/command/subcommands/tests/test_serve.py
> make docs for --dev arg placement clearer

- bokeh/core/enums.py
- bokeh/core/tests/test_enums.py
> fix enum doc issues

- bokehjs/src/lib/models/glyphs/box.ts
- bokehjs/src/lib/models/glyphs/quad.ts
I am unsure of the kinds of tests I should include here. I'm thinking a [screenshot integration test](https://bokeh.pydata.org/en/latest/docs/dev_guide/testing.html#id1)? I haven't written it yet but I wanted to post this PR first so I don't get too far in the wrong direction.
> implement hover anchor for quad glyphs

- sphinx/source/docs/user_guide/examples/geo_geojson_source.py
> Geojson docs

- README.md
> fixed analysis

- scripts/build_upload.py
- scripts/ci/build
- scripts/ci/install.test
> upload to s3 CDN in parallel

- scripts/ci/install.downstream
- scripts/ci/test.downstream
@bryevdv asked me to add downstream tests for Pandas-Bokeh.
> Add Pandas-Bokeh to downstream tests

- scripts/deps.py
> specify yaml loader in deps.py

- .gitignore
- bokeh/palettes.py
- bokeh/sphinxext/bokehjs_content.py
- conda.recipe/meta.yaml
- scripts/ci/test.codebase
- setup.cfg
Type type check bokeh issue `mypy bokeh`.
fixes #9057
> Add support for mypy

- bokeh/core/property/color.py
- scripts/ci/install
update: Also fixed a problem with the pyyaml fix PR. Necessary version is not available on conda for python 3.5
> User raw string for color regex

- bokeh/util/paths.py
- setup.cfg
> Add static types to bokeh.util.paths

- bokeh/embed/wrappers.py
- setup.cfg
Add type annotations to `bokeh.embed.wrappers`.
> Add types for bokeh.embed.wrappers.

- scripts/deps.py
- sphinx/source/docs/dev_guide/setup.rst
Fixes documentation and conda packages for windows dev setup.
> Small fix for windows dev guide and dev env setup

- bokehjs/src/lib/models/widgets/date_picker.ts
@mattpap I want to take this opportunity to add selenium tests for datepicker, since there are none. BUt I am tired, so that will be later this weekend. But if you have any comments on the implementation please let me know.  
I guess it's possible we could try to fix this with a [pikaday formatter](https://stackoverflow.com/questions/36372809/pikaday-date-formatting-without-moment-js), but there is an issue to add a user hook for formatting so this would better leave the door open for that.
> update datepicker properly

- bokeh/util/options.py
- setup.cfg
> Add static types to bokeh.util.options

- sphinx/source/docs/user_guide/server.rst
This PR adds much-needed user guide discussion around security related options for the Bokeh server, e.g. allowed websocket origins and signed session ids. The section on `supervisord` was also removed as it is complicated an uncertain that it still applies.
> add docs for bokeh server security options

- bokehjs/src/lib/core/hittest.ts
- bokehjs/src/lib/models/glyphs/harea.ts
- bokehjs/src/lib/models/glyphs/patch.ts
- bokehjs/src/lib/models/glyphs/varea.ts
- bokehjs/src/lib/models/glyphs/xy_glyph.ts
- bokehjs/src/lib/models/renderers/glyph_renderer.ts
> Add hover support to area glyphs

- bokehjs/src/lib/models/glyphs/hbar.ts
- bokehjs/src/lib/models/glyphs/vbar.ts
> make vbar/hbar specs compatible with python

- bokehjs/src/lib/client/connection.ts
---
Because of the heavy use of promises, we still need to accumulate messages and handle them when the session is ready. Another reason to accumulate them is that there are kinds of messages other than PATCH - e.g. we don't want to miss any errors.
> Store msgs and handle them when session is created

- bokeh/server/views/autoload_js_handler.py
> fix double slash in autoload.js

- bokehjs/src/lib/models/tools/toolbar.ts
- bokehjs/src/lib/models/tools/toolbar_base.ts
- bokehjs/src/lib/models/tools/toolbar_box.ts
> Purge dead references on tools change

- docker-tools/Dockerfile-from-conda
- docker-tools/Dockerfile-from-source
- docker-tools/Dockerfile-from-travis
I've updated the Dockerfile for the three styles of containers we have.  Opened a related issue for autobuilding/testing here: https://github.com/bokeh/bokeh/issues/9094
> Update docker to work with new conda and bokeh

- README.md
> docs: Update Documentation urls in README

- scripts/ci/test.downstream
> Update dask test location

- .travis.yml
- conda.recipe/meta.yaml
- scripts/build_upload.py
This PR adds an upload to `cdn-backup.org` and also removes all code for the RackSpace upload.
> upload files to backup CDN on release

- bokeh/.coveragerc
- bokeh/_testing/plugins/ipython.py
- bokeh/application/handlers/tests/test_notebook.py
- bokeh/command/subcommands/tests/test_info.py
- bokeh/io/tests/test_showing.py
- conftest.py
> exclude ipython tests on minimal build

- bokeh/io/tests/test_export.py
- bokehjs/package.json
- bokehjs/src/lib/polyfill.ts
- sphinx/source/docs/releases/1.3.1.rst
> Polyfill ES2015 Set

- bokeh/sphinxext/bokeh_plot.py
- bokeh/sphinxext/collapsible_code_block.py
> Changes faulty type declaration in docstrings

- bokeh/io/export.py
- bokehjs/make/paths.ts
- bokehjs/make/tasks/scripts.ts
- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/compiler/compile.ts
- bokehjs/src/compiler/linker.ts
- bokehjs/src/compiler/sys.ts
- bokehjs/src/compiler/transforms.ts
- bokehjs/src/lib/index.ts
- bokehjs/src/lib/legacy.ts
- bokehjs/src/lib/polyfill.ts
- bokehjs/src/lib/tsconfig.json
- bokehjs/test/size.ts
> Generate ES6 (ES2015) compatible bundles

- bokeh/application/tests/test_application.py
- bokeh/command/tests/test_util.py
- bokeh/core/property/tests/test_descriptors.py
- bokeh/core/property/tests/test_validation.py
- bokeh/core/tests/test_has_props.py
- bokeh/embed/tests/test_util.py
- bokeh/plotting/tests/test_helpers.py
- bokeh/server/tests/test_contexts.py
- bokeh/server/tests/test_server.py
- bokeh/tests/test_model.py
- bokeh/util/tests/test_dependencies.py
- conda.recipe/meta.yaml
I also pulled in a fix to an annoying server test failure from the `async` branch.
fixes #9175
> Make bokeh's tests work with pytest >= 5

- examples/app/clustering/README.md
> Fix broken link to examples/app

- bokeh/events.py
- bokehjs/src/lib/core/bokeh_events.ts
- bokehjs/src/lib/core/ui_events.ts
- bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
- bokehjs/src/lib/models/tools/edit/freehand_draw_tool.ts
- bokehjs/src/lib/models/tools/edit/point_draw_tool.ts
- bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts
- bokehjs/src/lib/models/tools/edit/poly_edit_tool.ts
- bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
- bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
- bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
- bokehjs/src/lib/models/tools/gestures/pan_tool.ts
- bokehjs/src/lib/models/tools/gestures/range_tool.ts
- bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
- bokehjs/src/lib/models/tools/tool.ts
- bokehjs/test/core/ui_events.ts
- bokehjs/test/models/tools/edit/box_edit_tool.ts
- bokehjs/test/models/tools/edit/freehand_draw_tool.ts
- bokehjs/test/models/tools/edit/point_draw_tool.ts
- bokehjs/test/models/tools/edit/poly_draw_tool.ts
- bokehjs/test/models/tools/edit/poly_edit_tool.ts
- bokehjs/test/models/tools/edit/utils.ts
- examples/custom/custom_tool.py
- examples/custom/parallel_plot/parallel_selection_tool.ts
- sphinx/source/docs/user_guide/examples/extensions_example_tool.py
> Finalize support for rotate events

- bokeh/server/protocol_handler.py
> Print full stacktrace to console when an error occurs

- sphinx/source/docs/user_guide/server.rst
> [DOC] Tpyos

- bokeh/command/subcommands/serve.py
- bokeh/command/subcommands/tests/apps/apply_theme.py
- bokeh/command/subcommands/tests/apps/line_on_off.py
- bokeh/command/subcommands/tests/test_serve.py
> Adding the ability to parse globs in quotes in serve

- LICENSE.txt
> Update current year

- bokeh/models/selections.py
- sphinx/source/docs/user_guide/tools.rst
> clarify selection usage

- bokeh/models/sources.py
> Updates doc string for AjaxDataSource to include note on FactorRange

- bokehjs/src/lib/models/tools/gestures/range_tool.ts
- bokehjs/test/models/tools/gestures/range_tool.ts
Edits as suggested by @bryevdv on issue #9267 . Thanks for the support getting the bug fixed!
> Fix range_tool selection bug

- .gitignore
- bokehjs/make/tasks/test.ts
- bokehjs/package-lock.json
- bokehjs/package.json
- tests/test_bokehjs.py
> 9271: replace deprecated package istanbul with nyc

- bokeh/util/dependencies.py
Same as, but targeting https://github.com/bokeh/bokeh/pull/9273 as proposed by @mattpap 
For details, see issue #9272
issues: fixes #9272
tests added / passed
release document entry (if new feature or API change)
> Use Exception Chaining if import_required failed

- examples/app/README.md
- sphinx/source/docs/user_guide.rst
- sphinx/source/docs/user_guide/server.rst
- sphinx/source/docs/user_guide/styling.rst
> Fixes of user-guide documentation and app example typos

- .github/CONTRIBUTING.md
- README.md
- _setup_support.py
- bokeh/embed/util.py
- sphinx/source/docs/user_guide/tools.rst
Developer builds were removed from the docs in #9106
> Fix broken docs links

- bokeh/_testing/util/selenium.py
- bokehjs/src/lib/models/widgets/tables/data_table.ts
- tests/integration/widgets/tables/test_sortable.py
I think I'd like to add some integration tests around table sorting but lets make sure the existing ones pass with this change
> respect global table.sortable flag

- bokeh/themes/theme.py
> Document plotting API effect on themes

- examples/howto/server_embed/flask_embed.py
- examples/howto/server_embed/flask_gunicorn_embed.py
- examples/howto/server_embed/notebook_embed.ipynb
- examples/howto/server_embed/standalone_embed.py
- examples/howto/server_embed/tornado_embed.py
> use better function name for apps

- bokeh/models/plots.py
- bokeh/models/tests/test_plots.py
- examples/app/population.py
- examples/integration/layout/grid_axis_alignment.py
- examples/integration/layout/grid_axis_alignment_nested.py
- examples/integration/layout/grid_axis_alignment_no_toolbar.py
- examples/plotting/file/categorical_scatter_jitter.py
- examples/plotting/file/hatch_grid_band.py
- examples/plotting/file/jitter.py
- examples/plotting/file/ridgeplot.py
- examples/plotting/file/stacked_area.py
cc @bokeh/dev for any comments. Seems like it should be uncontroversial so I will plan to merge tomorrow without comment.
> generalize splattable lists

- bokehjs/src/lib/models/plots/plot.ts
- tests/integration/models/test_plot.py
@mattpap I don't think this is elegant, but it is expedient and self-contained and establishes a test.
> ensure inner dims event on dynamic added plot

- bokeh/models/layouts.py
- sphinx/source/docs/reference/models/widgets.panels.rst
> Fix panels doc

- sphinx/source/bokeh_theme/ga.html
- sphinx/source/bokeh_theme/layout.html
After this is merged, will cut a dev build to check in actual deployment
> upate to use new gtag.js for GA

- bokehjs/src/lib/embed/notebook.ts
- sphinx/source/docs/user_guide/notebook.rst
For now I just updated jupyterlab_bokeh -> jupyter_lab. Better documentation is needed, but I will leave this for another PR.
> Update references to jupyter_bokeh extension

- conda.recipe/meta.yaml
- tests/integration/widgets/tables/test_copy_paste.py
- tests/integration/widgets/test_autocomplete_input.py
- tests/integration/widgets/test_password_input.py
- tests/integration/widgets/test_text_input.py
This would be a bandaid, but seeing how it looks.
> add test retry for flaky tests

- bokeh/models/plots.py
- bokeh/models/tests/test_plots.py
> Support accessing list-like attributes on splattable lists

- bokehjs/src/lib/models/layouts/layout_dom.ts
> Connect background change of layoutDOMView to invalidate_render()

- bokeh/embed/elements.py
- bokeh/embed/notebook.py
- bokeh/embed/standalone.py
- bokeh/util/browser.py
- bokeh/util/dependencies.py
- bokeh/util/logconfig.py
- bokeh/util/string.py
- bokeh/util/terminal.py
- bokeh/util/version.py
- examples/plotting/file/vector.py
- setup.cfg
Given that `landing-2.0` branch is being rebased, this merges together PRs:
- https://github.com/bokeh/bokeh/pull/9079
- https://github.com/bokeh/bokeh/pull/9077
- https://github.com/bokeh/bokeh/pull/9072
- https://github.com/bokeh/bokeh/pull/9071
to speed up development and unify changes introduced there when they intersect.
addresses #9064 
fixes #9070
> Add more static type declarations to bokeh

- bokeh/settings.py
- bokeh/sphinxext/_templates/settings_detail.rst
- sphinx/source/bokeh/static/custom.css
- sphinx/source/docs/gallery.rst
- sphinx/source/docs/releases/1.4.0.rst
- sphinx/source/docs/user_guide.rst
- sphinx/source/docs/user_guide/bokehjs.rst
- sphinx/source/docs/user_guide/cli.rst
- sphinx/source/docs/user_guide/compat.rst
- sphinx/source/docs/user_guide/data.rst
- sphinx/source/docs/user_guide/embed.rst
- sphinx/source/docs/user_guide/interaction.rst
- sphinx/source/docs/user_guide/layout.rst
- sphinx/source/docs/user_guide/plotting.rst
- sphinx/source/docs/user_guide/quickstart.rst
- sphinx/source/docs/user_guide/webgl.rst
OK would like to have done more, but just out of time.
> 1.4.0 misc docs

- _setup_support.py
- bokeh/embed/bundle.py
- bokeh/resources.py
- bokeh/server/.gitignore
- bokehjs/make/paths.ts
- bokehjs/make/tasks/styles.ts
- bokehjs/test/size.ts
This is a followup on PR #8989 that modularized bokeh's CSS.
> Finalize removal of bokeh's CSS resources

- bokeh/util/sampledata.py
- setup.cfg
In addition, fixes a `RuntimeError` message within the method `external_path`.
> Add static types to bokeh.util.sampledata

- bokehjs/src/lib/models/expressions/stack.ts
> Check for empty object

- bokehjs/src/lib/models/widgets/spinner.ts
- tests/integration/widgets/test_spinner.py
- [] tests added / passed
Verification on:
https://github.com/bokeh/bokeh/issues/8786
> Spinner improvements to handle bounds and steps

- bokehjs/src/lib/core/dom.ts
- bokehjs/src/lib/models/annotations/box_annotation.ts
- bokehjs/src/lib/models/annotations/span.ts
- bokehjs/src/lib/models/annotations/text_annotation.ts
- bokehjs/src/lib/models/annotations/toolbar_panel.ts
- bokehjs/src/lib/models/annotations/tooltip.ts
- bokehjs/src/lib/models/canvas/canvas.ts
- bokehjs/src/lib/models/canvas/cartesian_frame.ts
- bokehjs/src/lib/models/glyphs/circle.ts
- bokehjs/src/lib/models/glyphs/glyph.ts
- bokehjs/src/lib/models/glyphs/webgl/base.ts
- bokehjs/src/lib/models/grids/grid.ts
- bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
- bokehjs/src/lib/models/plots/plot_canvas.ts
- bokehjs/src/lib/models/tiles/tile_renderer.ts
- bokehjs/src/lib/polyfill.ts
- bokehjs/src/lib/styles/canvas.ts
- bokehjs/test/models/plots/plot.ts
This was extracted from PR #8931, to simplify work on that PR.
addresses #3821
> Detach canvas and webgl from plots

- _setup_support.py
- bokehjs/LICENSE
- docker-tools/Dockerfile-from-source
- docker-tools/npm-install.sh
- scripts/ci/appveyor/build.ps1
- scripts/ci/install.build
- scripts/ci/install.codebase
- scripts/ci/install.deploy
- scripts/ci/install.examples
- scripts/ci/install.js
- scripts/ci/install.unit
- sphinx/source/docs/dev_guide/setup.rst
> Use `npm ci` instead of `npm install --no-save`

- scripts/ci/install
> remove old conda free channel

- conda.recipe/meta.yaml
> update conda recipe

- bokeh/models/layouts.py
- sphinx/source/docs/releases/2.0.0.rst
> deprecate WidgetBox

- bokeh/embed/standalone.py
- bokeh/sphinxext/theme.py
- bokeh/util/deprecation.py
- setup.cfg
This is not yet a strict config, as some options related to implicit any type and imports aren't enabled. Those will be enabled in future PRs, when more of bokeh, especially core, will be typed, and conda stub packages will be available for bokeh's dependencies (e.g. numpy-stubs).
addresses #9064
> Use explicit and stricter mypy config

- bokeh/models/graphs.py
- bokeh/models/layouts.py
- bokeh/plotting/__init__.py
- bokeh/plotting/graph.py
- examples/models/file/graphs.py
- sphinx/source/docs/reference/plotting.rst
- sphinx/source/docs/releases/2.0.0.rst
- sphinx/source/docs/user_guide/examples/graph_interaction.py
- sphinx/source/docs/user_guide/examples/graph_networkx.py
- sphinx/source/docs/user_guide/examples/graph_node_and_edge_attributes.py
- sphinx/source/docs/user_guide/graph.rst
- tests/unit/bokeh/models/test_graphs.py
- tests/unit/bokeh/models/test_layouts__models.py
- tests/unit/bokeh/plotting/test_graph.py
> Move from_networkx to  bokeh.plotting

- examples/howto/server_embed/flask_embed.py
- examples/howto/server_embed/flask_gunicorn_embed.py
- examples/howto/server_embed/notebook_embed.ipynb
- examples/howto/server_embed/standalone_embed.py
- examples/howto/server_embed/tornado_embed.py
> update server embed exaples

- bokeh/util/compiler.py
- conda.recipe/meta.yaml
> Update minimum version of nodejs

- examples/plotting/file/image.py
- sphinx/source/docs/user_guide/examples/plotting_image.py
- sphinx/source/docs/user_guide/examples/plotting_image_rgba.py
- sphinx/source/docs/user_guide/plotting.rst
- sphinx/source/docs/user_guide/styling.rst
- sphinx/source/docs/user_guide/tools.rst
- tests/baselines/sphinx/source/docs/user_guide/examples/plotting_image_rgba
> document render level for images

- bokehjs/test/client/connection.ts
- bokehjs/test/client/with_server.ts
> Rewrite bokehjs' connection tests using async/await

- bokeh/server/auth_provider.py
- bokeh/server/views/ws.py
> fixes #9446

- bokeh/embed/server.py
- bokeh/server/tornado.py
> no f-strings for docstrings

- scripts/ci/install.build
Not 100% sure this will work, will have to get someone to test on an outside PR
> use main env for build

- bokeh/models/tools.py
corrected icon name for HoverTool
crosshair_icon --> hover_icon
> fix hover icon

- sphinx/source/docs/user_guide/examples/styling_visible_annotation_with_interaction.py
- tests/integration/widgets/tables/test_cell_editors.py
- tests/unit/bokeh/util/test_compiler.py
Fixed few spelling mistakes while going through code.
> 9463 spell mistakes 2019 nov

- bokeh/_sri.json
- bokeh/resources.py
- bokeh/sphinxext/bokeh_releases.py
- tests/unit/bokeh/test_resources.py
This is a fist step of steps towards #8397. Rebased version of PR #9465.
> Expose SRI hashes

- sphinx/source/bokeh/docs-navbar.html
- sphinx/source/docs/user_guide/quickstart.rst
> update twitter username

- bokeh/plotting/helpers.py
- tests/unit/bokeh/plotting/test_helpers.py
> split override/trait defaults, add tests

- sphinx/source/docs/user_guide/annotations.rst
> Fix simple typo: ther -> the

- sphinx/source/docs/user_guide/categorical.rst
- sphinx/source/docs/user_guide/concepts.rst
Fixes #9525 with some other minor grammatical corrections.
> Fix User Guide documentation errors.

- bokeh/plotting/helpers.py
> Add angle brackets to fakesource in order to be ignored by coverage

- .lgtm.yml
- _setup_support.py
- bokeh/_testing/plugins/file_server.py
- bokeh/command/subcommands/secret.py
- bokeh/command/subcommands/svg.py
- bokeh/core/property/either.py
- bokeh/core/property/wrappers.py
- bokeh/embed/bundle.py
- bokeh/embed/util.py
- bokeh/io/export.py
- bokeh/io/util.py
- bokeh/model.py
- bokeh/plotting/helpers.py
- bokeh/settings.py
- bokeh/sphinxext/bokehjs_content.py
- bokeh/sphinxext/example_handler.py
- bokeh/themes/theme.py
- examples/app/spectrogram/audio.py
- examples/embed/embed_themed.py
- examples/howto/server_auth/auth.py
- examples/models/file/gauges.py
- examples/webgl/line_compare.py
- scripts/deploy.py
- scripts/issues.py
- sphinx/docserver.py
- sphinx/source/bokeh/scripts.html
Just going through and fixing up many small easy issues pointed out by LGTM
> Misc fixes

- .github/workflows/bokeh-ci.yml
- bokeh/_testing/util/selenium.py
- bokehjs/src/lib/testing.ts
- tests/integration/models/test_datarange1d.py
- tests/integration/tools/test_box_edit_tool.py
- tests/integration/tools/test_box_zoom_tool.py
- tests/integration/tools/test_freehand_draw_tool.py
- tests/integration/tools/test_pan_tool.py
- tests/integration/tools/test_point_draw_tool.py
- tests/integration/tools/test_poly_draw_tool.py
- tests/integration/tools/test_poly_edit_tool.py
- tests/integration/tools/test_range_tool.py
- tests/integration/tools/test_reset_tool.py
- tests/integration/tools/test_wheel_zoom_tool.py
- tests/integration/tools/test_zoom_in_tool.py
- tests/integration/tools/test_zoom_out_tool.py
- tests/integration/widgets/tables/test_copy_paste.py
- tests/integration/widgets/test_range_slider.py
- tests/integration/widgets/test_slider.py
> flaky selenium tests

- .lgtm.yml
- bokeh/_testing/util/filesystem.py
- bokeh/application/handlers/code_runner.py
- bokeh/core/has_props.py
- bokeh/core/query.py
- bokeh/document/document.py
- bokeh/document/locking.py
- bokeh/layouts.py
- bokeh/models/sources.py
- bokeh/server/session.py
- bokeh/settings.py
- bokeh/sphinxext/bokeh_model.py
- bokeh/sphinxext/bokeh_options.py
- bokeh/sphinxext/bokeh_palette_group.py
- bokeh/sphinxext/bokeh_plot.py
- bokeh/sphinxext/bokeh_releases.py
- bokeh/sphinxext/bokeh_settings.py
- bokeh/sphinxext/example_handler.py
- bokeh/sphinxext/util.py
- bokeh/util/deprecation.py
- bokehjs/src/lib/core/ui_events.ts
- scripts/build_upload.py
- tests/unit/bokeh/document/test_locking.py
> More misc repo work

- bokehjs/src/lib/api/plotting.ts
This continues #9153. Still sorting out bugs, I'll probably need help with TS usage.
> New attempt to update bokehjs from pop_colors_and_alpha to _pop_visuals

- .github/workflows/bokeh-ci.yml
- sphinx/source/docs/user_guide/concepts.rst
- sphinx/source/docs/user_guide/data.rst
- sphinx/source/docs/user_guide/layout.rst
- sphinx/source/docs/user_guide/plotting.rst
- sphinx/source/docs/user_guide/quickstart.rst
fixes #9555.
docs changes only.
> fixes typos and makes minor text improvements

- bokeh/core/validation/errors.py
- bokeh/models/glyphs.py
- bokeh/models/renderers.py
- tests/unit/bokeh/models/test_renderers.py
> warn for CDSView filters and connected glyphs

- bokeh/io/notebook.py
- tests/unit/bokeh/io/test_notebook__io.py
Just starting. Marking for #9146 but would like to do a wider review to change things to kwarg-only wherever appropriate.
> Review for kwarg-only

- sphinx/source/docs/dev_guide.rst
- sphinx/source/docs/dev_guide/setup.rst
- sphinx/source/docs/dev_guide/testing.rst
> Update developer documentation

- bokehjs/make/tasks/test.ts
- bokehjs/make/toposort.d.ts
- bokehjs/package-lock.json
- bokehjs/package.json
> Detect chromium/chrome executable path

- .github/workflows/bokeh-ci.yml
> No need to start headless chrome anymore

- bokehjs/src/lib/core/logging.ts
- bokehjs/src/lib/models/glyphs/glyph.ts
- bokehjs/src/lib/models/glyphs/xy_glyph.ts
- bokehjs/test/unit/models/glyphs/glyph.ts
- bokehjs/test/unit/models/glyphs/index.ts
- bokehjs/test/unit/models/sources/column_data_source.ts
Simple improvement in an effort to submit smaller pieces of work as PRs.
> Make Glyph._hit_* methods statically typed

- bokehjs/src/lib/api/plotting.ts
- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/core/util/callback.ts
- bokehjs/src/lib/core/view.ts
- bokehjs/src/lib/embed/index.ts
- bokehjs/src/lib/embed/server.ts
- bokehjs/src/lib/embed/standalone.ts
- bokehjs/src/lib/model.ts
- bokehjs/src/lib/models/layouts/layout_dom.ts
- examples/embed/json_item.py
- sphinx/source/docs/user_guide/embed.rst
> Return a promise with views from embed_item{s}()

- bokehjs/src/lib/models/widgets/abstract_slider.ts
> Ensure that all AbstractSlider properties are connected to signals

- examples/app/clustering/README.md
- examples/app/crossfilter/README.md
- examples/app/dash/README.md
- examples/app/export_csv/README.md
- examples/app/faces/README.md
- examples/app/gapminder/README.md
- examples/app/movies/README.md
- examples/app/ohlc/README.md
- examples/app/simple_hdf5/README.md
- examples/app/spectrogram/README.md
- examples/app/stocks/README.md
- examples/app/surface3d/README.md
- examples/app/weather/README.md
> uniform READMEs for app directory examples

- bokeh/server/tornado.py
> Fix a typo in bokeh/server/tornado.py

- bokehjs/src/lib/client/connection.ts
- bokehjs/src/lib/client/session.ts
> Write promise API calls into async/await

- bokehjs/src/lib/client/connection.ts
> Discard PATCH-DOC messages received before we have a document

- bokehjs/make/main.ts
- bokehjs/make/task.ts
- bokehjs/make/tasks/test.ts
> Various bokehjs testing fixes

- bokeh/document/document.py
- bokeh/model.py
- tests/unit/bokeh/document/test_document.py
- tests/unit/bokeh/test_model.py
> Add support for class types in set_select

- bokeh/models/scales.py
- bokehjs/src/lib/models/canvas/cartesian_frame.ts
- bokehjs/src/lib/models/scales/categorical_scale.ts
- bokehjs/src/lib/models/scales/continuous_scale.ts
- bokehjs/src/lib/models/scales/index.ts
- bokehjs/src/lib/models/scales/linear_scale.ts
- bokehjs/src/lib/models/scales/log_scale.ts
- bokehjs/src/lib/models/scales/scale.ts
- bokehjs/test/unit/models/annotations/color_bar.ts
- bokehjs/test/unit/models/scales/linear_scale.ts
pre-work for #6517 
flying blind on JS tests as `node make test` won't run for me locally again, whether I start chrome headless myself or not.
> Clarify Scales hierarchy

- bokeh/server/contexts.py
- bokeh/server/session.py
- tests/unit/bokeh/server/test_contexts.py
> Allow using async callbacks in `add_next_tick_callback` and the like

- bokeh/io/webdriver.py
- tests/unit/bokeh/io/test_webdriver.py
fixes #9650
fixes https://github.com/bokeh/bokeh/pull/9331#discussion_r378211511
> Lazy initialize and eagerly terminate web drivers

- examples/plotting/file/texas.py
> removed superfluous parenthesis from tooltip

- bokeh/io/export.py
- bokeh/io/webdriver.py
> Make io.export work with devicePixelRatio != 1

- bokeh/io/export.py
- bokeh/io/webdriver.py
- tests/codebase/test_no_selenium_common.py
> do not require selenium for any common imports

- .github/ISSUE_TEMPLATE/config.yml
Fixes https://github.com/bokeh/bokeh/issues/9690
> Replace blank issue link with discourse link

- bokeh/_testing/plugins/selenium.py
- tests/integration/models/test_plot.py
- tests/integration/models/test_sources.py
- tests/integration/tools/test_box_edit_tool.py
- tests/integration/tools/test_point_draw_tool.py
- tests/integration/tools/test_poly_draw_tool.py
- tests/integration/tools/test_poly_edit_tool.py
- tests/integration/widgets/tables/test_source_updates.py
- tests/integration/widgets/test_autocomplete_input.py
- tests/integration/widgets/test_button.py
- tests/integration/widgets/test_checkbox_button_group.py
- tests/integration/widgets/test_checkbox_group.py
- tests/integration/widgets/test_color_picker.py
- tests/integration/widgets/test_datepicker.py
- tests/integration/widgets/test_dropdown.py
- tests/integration/widgets/test_password_input.py
- tests/integration/widgets/test_radio_button_group.py
- tests/integration/widgets/test_radio_group.py
- tests/integration/widgets/test_range_slider.py
- tests/integration/widgets/test_select.py
- tests/integration/widgets/test_slider.py
- tests/integration/widgets/test_spinner.py
- tests/integration/widgets/test_text_input.py
- tests/integration/widgets/test_textarea_input.py
- tests/integration/widgets/test_toggle.py
- tests/unit/bokeh/server/test_server__server.py
- tests/unit/bokeh/test_client_server.py
- tests/unit/bokeh/test_resources.py
I marked as flaky all common offenders from recent PRs.
> Try to improve passability of tests

- bokeh/embed/util.py
- bokehjs/src/lib/embed/dom.ts
- bokehjs/src/lib/embed/index.ts
- bokehjs/src/lib/embed/json.ts
- bokehjs/src/lib/embed/server.ts
- bokehjs/src/lib/embed/standalone.ts
Builds on https://github.com/bokeh/bokeh/pull/9536
> Ensure templating does not break when HTTP and Websocket requests arrive on different processes

- bokeh/models/widgets/inputs.py
- bokehjs/src/lib/models/widgets/spinner.ts
- tests/integration/widgets/test_spinner.py
> [Spinner] ensure step can be set until 1e-16

- bokeh/models/map_plots.py
- bokeh/plotting/gmap.py
- sphinx/source/docs/user_guide/geo.rst
This Pull Request is regarding Issue #9521, I have added some Docstring changes to 'gmap' and 'GMapPlot' in their respective files, which can serve as an alert message before storing the Google API Key in notebook. I have also made a few changes in 'geo.rst' file for the same message to be given the User_guide Documentation. Though the key is not encrypted yet (as suggested), I am working on it and submit a pr for the same soon.
tested on local virtual env.
> added some docstring changes for gmap function

- MANIFEST.in
- bokeh/resources.py
- bokehjs/make/paths.ts
- bokehjs/make/tasks/scripts.ts
- bokehjs/test/codebase/size.ts
> differentiate legacy files by filename

- bokehjs/make/tasks/lint.ts
- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/compiler/transforms.ts
- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/core/properties.ts
- bokehjs/src/lib/core/signaling.ts
- bokehjs/src/lib/core/view.ts
- bokehjs/src/lib/index.ts
- bokehjs/src/lib/models/glyphs/circle.ts
- bokehjs/src/lib/models/glyphs/glyph.ts
- bokehjs/src/lib/models/glyphs/line.ts
- bokehjs/src/lib/models/glyphs/webgl/markers.ts
- bokehjs/src/lib/models/markers/marker.ts
- bokehjs/src/lib/models/renderers/glyph_renderer.ts
- bokehjs/src/lib/tsconfig.json
This will get finalized when 3.8-final is released, which should be tomorrow. Tentatively adding to 2.0 milestone. If TypeScript's release is delayed, then I will move it to `next`.
> Upgrade to TypeScript 3.8

- bokehjs/src/lib/models/glyphs/image_url.ts
Rotation of image about center when using angle and anchor [combined] in image_url.
> fix issue #9703

- bokehjs/src/lib/models/annotations/arrow.ts
> Fix arrow clipping in plots in complex layouts

- bokeh/models/tools.py
- bokeh/plotting/_tools.py
- bokehjs/src/lib/api/plotting.ts
- bokehjs/src/lib/models/tools/actions/help_tool.ts
- bokehjs/src/lib/models/tools/actions/redo_tool.ts
- bokehjs/src/lib/models/tools/actions/reset_tool.ts
- bokehjs/src/lib/models/tools/actions/save_tool.ts
- bokehjs/src/lib/models/tools/actions/undo_tool.ts
- bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts
- bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts
- bokehjs/src/lib/models/tools/gestures/box_select_tool.ts
- bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts
- bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
- bokehjs/src/lib/models/tools/gestures/pan_tool.ts
- bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts
- bokehjs/src/lib/models/tools/gestures/tap_tool.ts
- bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts
- bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
- bokehjs/src/lib/models/tools/inspectors/crosshair_tool.ts
- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
- bokehjs/src/lib/models/tools/tool.ts
- tests/unit/bokeh/models/test_tools.py
- tests/unit/bokeh/test_model.py
> Add support for Tool.from_string()

- bokehjs/src/lib/core/bokeh_events.ts
- bokehjs/src/lib/core/geometry.ts
- bokehjs/src/lib/models/tools/gestures/select_tool.ts
> Properly statically type SelectionGeometry.geometry

- bokehjs/src/lib/models/ranges/data_range1d.ts
> Fix for issue 9724, v2

- bokeh/core/_templates/autoload_js.js
- bokeh/embed/bundle.py
- bokeh/embed/standalone.py
- bokeh/resources.py
- tests/unit/bokeh/test_resources.py
> Fix syntax error in autoload js in notebook

- setup.py
- tests/codebase/__init__.py
- tests/codebase/test_flake8.py
- tests/codebase/test_isort.py
> Use `git ls-files` to collect test files

- bokehjs/src/lib/core/util/serialization.ts
- bokehjs/src/lib/document/document.ts
- bokehjs/src/lib/protocol/message.ts
- bokehjs/src/lib/protocol/receiver.ts
- bokehjs/test/unit/core/util/serialization.ts
- bokehjs/test/unit/protocol/message.ts
- bokehjs/test/unit/protocol/receiver.ts
Just a clean up to get to proper work on improving handling of binary data.
addresses #9518
> Clean up type situation around buffer handling

- bokehjs/src/lib/models/glyphs/segment.ts
> Fix hover hit on vertical and horizontal segments

- bokeh/document/events.py
- bokehjs/src/lib/document/document.ts
- bokehjs/src/lib/document/events.ts
This for example allows to send binary content from jupyter widgets (https://github.com/bokeh/ipywidgets_bokeh/pull/5).
> Allow to send binary buffers by MessageSent

- sphinx/source/docs/releases/2.0.0.rst
> Update placeholder date in 2.0 release notes

- examples/howto/server_embed/django_embed/README.md
> Update bokeh_embed/django README.md

- bokehjs/src/lib/api/plotting.ts
- bokehjs/src/lib/client/session.ts
- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/core/properties.ts
- bokehjs/src/lib/core/property_mixins.ts
- bokehjs/src/lib/core/types.ts
- bokehjs/src/lib/core/util/color.ts
- bokehjs/src/lib/core/util/types.ts
- bokehjs/src/lib/core/visuals.ts
- bokehjs/src/lib/document/document.ts
- bokehjs/src/lib/document/events.ts
- bokehjs/src/lib/models/glyphs/circle.ts
- bokehjs/src/lib/models/plots/plot.ts
- bokehjs/src/lib/models/sources/column_data_source.ts
- bokehjs/test/framework.ts
- bokehjs/test/unit/core/has_props.ts
- bokehjs/test/unit/core/properties.ts
- bokehjs/test/unit/defaults.ts
- bokehjs/test/unit/document/document.ts
This is the first step (out of many) to bring soundness to the design of bokeh and bokehjs in particular. Given that those will be deeply incompatible changes, all will be submitted against `future` branch and marked accordingly. I will explain my plan towards bokeh 3.0 in a dedicated issue in the near future.
addresses #9518
> Clean separation between models' and properties' responsibilities

- bokeh/core/has_props.py
- bokeh/plotting/_tools.py
- setup.cfg
- tests/unit/bokeh/plotting/test__tools.py
> Don't warn of different variants of the same type of tool

- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/core/util/data_structures.ts
- bokehjs/src/lib/document/document.ts
- bokehjs/src/lib/document/events.ts
- bokehjs/src/lib/model.ts
- bokehjs/test/unit/document/document.ts
- bokehjs/test/unit/document/events.ts
> Use Map<K, V> or Set<V> instead of {[key: string]: V}

- bokehjs/src/lib/models/widgets/date_picker.ts
> Update current DatePicker value in UI

- bokeh/core/validation/errors.py
> Fix typo in validation error output for FactorRange and CDSView filters

- bokeh/_testing/util/selenium.py
- bokeh/_version.py
- bokeh/util/token.py
> Refactored unused vars to _

- bokehjs/src/lib/models/filters/filter.ts
- bokehjs/src/lib/models/filters/index_filter.ts
> change array.length issue in filters

- bokehjs/make/tasks/test.ts
- bokehjs/src/lib/core/util/throttle.ts
- bokehjs/src/lib/models/plots/plot_canvas.ts
- bokehjs/src/lib/models/ranges/factor_range.ts
- bokehjs/test/baselines/Bug__in_issue_#9879__disallows_to_change_FactorRange_to_a_lower_dimension_with_a_different_number_of_factors
- bokehjs/test/devtools/devtools.ts
- bokehjs/test/integration/index.ts
- bokehjs/test/unit/models/axes/axis.ts
- bokehjs/test/unit/models/callbacks/customjs.ts
- bokehjs/test/unit/models/filters/customjs_filter.ts
- bokehjs/test/unit/models/glyphs/multi_polygons.ts
- bokehjs/test/unit/models/glyphs/patches.ts
- bokehjs/test/unit/models/sources/column_data_source.ts
- bokehjs/test/unit/models/tools/inspectors/customjs_hover.ts
- bokehjs/test/unit/models/transforms/customjs_transform.ts
- bokehjs/test/unit/protocol/receiver.ts
Also fixes a bunch of issues with tests' runner and tests.
fixes #9879
> Properly reset state in FactorRange._init()

- bokehjs/make/tasks/test.ts
> Fix unreliable headless chrome on macos

- bokeh/tile_providers.py
- tests/unit/bokeh/test_tile_providers.py
As discussed in https://discourse.bokeh.org/t/stamen-maps-with-ssl/5107, these are the changes to use the Stamen SSL links
> Update Stamen urls for SSL links

- .github/workflows/bokeh-ci.yml
> FIx CI Miniconda download

- bokehjs/test/baselines/Bug__in_issue_#9877__disallows_BoxAnnotation_to_respect_fill_color_==_null_in_CSS_mode
- bokehjs/test/baselines/Bug__in_issue_#9877__disallows_BoxAnnotation_to_respect_fill_color_==_null_in_canvas_mode
- bokehjs/test/baselines/Bug__in_issue_#9877__disallows_BoxAnnotation_to_respect_line_color_==_null_in_CSS_mode
- bokehjs/test/baselines/Bug__in_issue_#9877__disallows_BoxAnnotation_to_respect_line_color_==_null_in_canvas_mode
- bokehjs/test/integration/index.ts
> Add a test for issue #9877

- bokehjs/eslint.json
- bokehjs/src/lib/models/formatters/basic_tick_formatter.ts
- bokehjs/src/lib/models/glyphs/annular_wedge.ts
- bokehjs/src/lib/models/glyphs/annulus.ts
- bokehjs/src/lib/models/glyphs/circle.ts
- bokehjs/src/lib/models/glyphs/ellipse_oval.ts
- bokehjs/src/lib/models/glyphs/quadratic.ts
- bokehjs/src/lib/models/glyphs/segment.ts
- bokehjs/src/lib/models/glyphs/webgl/line.ts
- bokehjs/src/lib/models/glyphs/wedge.ts
- bokehjs/src/lib/models/ranges/data_range1d.ts
- bokehjs/src/lib/models/scales/log_scale.ts
- bokehjs/src/lib/models/tickers/adaptive_ticker.ts
- bokehjs/src/lib/models/tickers/log_ticker.ts
- bokehjs/src/lib/models/tiles/mercator_tile_source.ts
- bokehjs/src/lib/models/tiles/tile_source.ts
- bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
- bokehjs/test/unit/models/tiles/tile_renderer.ts
Results in much more readable code.
> Prefer ** operator in bokehjs codebase

- sphinx/source/docs/releases/2.0.0.rst
- sphinx/source/docs/releases/2.0.1.rst
> Add missing release notes

- bokehjs/src/lib/models/plots/plot.ts
- bokehjs/src/lib/models/plots/plot_canvas.ts
- bokehjs/test/unit/models/plots/plot.ts
> Rebuild renderer views after add_layout

- conda.recipe/meta.yaml
- examples/.isort.cfg
- examples/howto/ipywidgets/README.md
- examples/howto/ipywidgets/ipyleaflet_tiles.py
- examples/howto/ipywidgets/ipyvolume_camera.py
- sphinx/source/docs/user_guide/jupyter.rst
- tests/unit/bokeh/server/test_server__server.py
Depends on https://github.com/bokeh/ipywidgets_bokeh/pull/6.
fixes #9772
> Add ipywidgets integration examples

- bokehjs/src/lib/models/glyphs/text.ts
> Fix Text glyph's point hit testing for null data points

- bokeh/transform.py
"For ``start_angle``" -> "For ``end_angle``"
> Fix `cumsum()` docstring

- .github/workflows/bokeh-ci.yml
> Use system installed google chrome in CI

- bokeh/models/ranges.py
> Fixed `FactorRange`'s `start` property help string

- README.md
- sphinx/source/docs/dev_guide.rst
> Add notes about CoC to README and dev-guide

- bokeh/models/layouts.py
I have made the requested changes. Please let me know if I have to add something else
> Updated documentation for Margin Attribute

- bokeh/document/document.py
> Changed Warning

- bokehjs/src/lib/core/dom.ts
- bokehjs/src/lib/models/widgets/abstract_button.ts
- bokehjs/src/lib/models/widgets/abstract_slider.ts
- bokehjs/src/lib/models/widgets/button_group.ts
- bokehjs/src/lib/models/widgets/checkbox_group.ts
- bokehjs/src/lib/models/widgets/color_picker.ts
- bokehjs/src/lib/models/widgets/control.ts
- bokehjs/src/lib/models/widgets/date_picker.ts
- bokehjs/src/lib/models/widgets/input_group.ts
- bokehjs/src/lib/models/widgets/input_widget.ts
- bokehjs/src/lib/models/widgets/radio_group.ts
- sphinx/source/docs/user_guide/examples/extensions_ion_range_slider.ts
> Handle 'disabled' property across all widgets

- examples/models/README.md
Added ':' before execution command for better view.
issue fixed-none
> Added ':' before execution command

- bokeh/server/views/auth_request_handler.py
- bokeh/server/views/metadata_handler.py
- bokeh/server/views/root_handler.py
- bokeh/server/views/session_handler.py
- sphinx/source/docs/reference/server/views.rst
- sphinx/source/docs/releases/3.0.0.rst
I have renamed the `auth_mixin` file and made the hierarchy changes accordingly.
> Update Auth Request Handler hierarchy

- bokeh/core/_templates/js_resources.html
- bokeh/sphinxext/_templates/bokehjs_html_template.html
- bokeh/sphinxext/bokehjs_content.py
First time contributor, Season of Docs hopeful 👋
- I referenced js_resources.html for the code changes
- Fixed a small typo in js_resources.html 
Do we need to write tests for doc changes?
> Include SRI hashes for BokehJS in user guide section

- sphinx/source/docs/user_guide/examples/layout_sizing_mode_multiple.py
- tests/baselines/sphinx/source/docs/user_guide/examples/layout_sizing_mode_multiple
The lorem-ipsum in multiple layouts has been replaced by more meaningful text.
> lorem-ipsum-change

- bokeh/models/annotations.py
> Link reference guide entries to user guide

- .github/workflows/bokeh-ci.yml
- conda.recipe/meta.yaml
> install channels from conda-forge

- bokehjs/src/lib/models/tools/edit/line_edit_tool.ts
> addresses bug described in #10040

- bokehjs/src/lib/models/widgets/date_picker.ts
- bokehjs/src/lib/models/widgets/tables/data_table.ts
> Destroy slickgrid and flatpickr on widget removal

- bokehjs/src/lib/models/widgets/selectbox.ts
- tests/integration/widgets/test_select.py
> Don't re-renderer Select widget when value changes

- bokehjs/src/less/menus.less
- bokehjs/src/lib/models/tools/button_tool.ts
- bokehjs/src/lib/models/tools/tool_proxy.ts
Additionally makes some stylistic improvements.
> Make menus usable with tool proxies

- sphinx/docserver.py
> Fix `cd sphinx; make serve`

- sphinx/source/bokeh/static/custom.css
> Prevent header from hiding anchors in the documentation

- bokeh/core/validation/errors.py
- bokeh/models/layouts.py
- tests/unit/bokeh/test_layouts.py
> Issue a validation error on repeated layout children

- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/core/view.ts
- bokehjs/src/lib/models/tools/on_off_button.ts
- bokehjs/src/lib/models/tools/tool_proxy.ts
- bokehjs/src/lib/models/tools/toolbar.ts
- bokehjs/src/lib/models/tools/toolbar_box.ts
> React to changes to Toolbar.active_* properties

- bokeh/models/selections.py
> Fix a typo in docs

- bokehjs/src/lib/core/has_props.ts
> Restore and deprecate HasProps.serializable_attributes()

- bokehjs/src/lib/embed/notebook.ts
- bokehjs/src/lib/external/colab.d.ts
Totally untested so far but following the APIs provided by Colab. Trying to figure out how to try this out on Colab now.
> Support push_notebook in Google Colab

- .github/workflows/bokeh-ci.yml
- bokeh/resources.py
- bokeh/sphinxext/bokeh_releases.py
- sphinx/source/bokeh/static/custom.css
- sphinx/source/docs/dev_guide/setup.rst
- sphinx/source/docs/dev_guide/testing.rst
- sphinx/source/docs/releases/2.1.0.rst
- sphinx/source/index.rst
- tests/unit/bokeh/io/test_util__io.py
- tests/unit/bokeh/io/test_webdriver.py
Release-ready updates for 2.1 (release notes) plus some docs fixes, improvements, and changes. Also this small issue:
Also had to revert #10104 due to some unintended render issues it caused.
> 2.1 updates

- bokehjs/src/lib/embed/notebook.ts
- bokehjs/src/lib/external/colab.d.ts
Made a stupid typo in registering the Google Colab comm target.
> Fixed typo when registering Google Colab comms

- examples/app/weather/README.md
issues: fixes #10142
type:bug
after the comment from bryevdv to rempve comma between install commands.
> #10142_Weather_example_scipy

- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/core/util/pretty.ts
- bokehjs/src/lib/core/util/types.ts
- bokehjs/test/integration/regressions.ts
- bokehjs/test/unit/core/has_props.ts
- bokehjs/test/unit/core/util/types.ts
- examples/howto/events_app.py
> Fix serialization of typed arrays

- bokehjs/src/compiler/compiler.ts
> Relativize imports of auto-generated modules

- bokehjs/src/lib/api/plotting.ts
This PR is the implementation of the harea and varea function for bokehjs
> bokehjs: harea and varea implemented

- bokeh/models/layouts.py
Change Minimal to Maximal for max_width and max_height in bokeh/models/layouts.py.
> Fix typo in docs.

- bokehjs/src/lib/core/layout/border.ts
- bokehjs/src/lib/models/plots/plot_canvas.ts
Extracted from PR #9964, to simplify that PR.
> PlotLayout -> core.layout.BorderLayout

- bokeh/models/tools.py
- bokehjs/src/lib/core/util/projections.ts
- bokehjs/src/lib/models/formatters/mercator_tick_formatter.ts
- bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
- bokehjs/src/lib/models/tickers/mercator_ticker.ts
- bokehjs/src/lib/models/tiles/tile_utils.ts
- bokehjs/test/unit/core/util/projections.ts
- bokehjs/test/unit/models/formatters/mercator_tick_formatter.ts
- examples/plotting/file/customjs_hover.py
> Allow NaN/Infinity in projections

- bokeh/models/annotations.py
- bokehjs/src/compiler/compiler.ts
- bokehjs/src/lib/core/property_mixins.ts
- bokehjs/test/unit/core/visuals.ts
- sphinx/source/docs/releases/2.1.1.rst
This is a forward merge of changes on `branch-2.1` for the `2.1.1` release. 
As a side note @mattpap @bokeh/core we really will need to eventually develop some automation (or manual process) and tagging to help keep track of: 
* backports to previous minor release branches
* forward ports from patch release milestones to the current development branch
> Forward merge from 2.1.1

- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
This doesn't improve that much, but is an obvious low changing fruit.
addresses #10234
> Update tooltips in bulk instead of individually

- sphinx/make.bat
Fixes:
* broken `make clean` 
* output to wrong build dir
> Fix windows docs build issues

- .github/workflows/bokehjs-ci.yml
- bokehjs/src/lib/embed/notebook.ts
- bokehjs/src/lib/models/tickers/mercator_ticker.ts
- bokehjs/test/unit/core/util/projections.ts
> Restore linting of bokehjs' codebase

- bokehjs/src/lib/models/canvas/canvas.ts
- bokehjs/test/devtools/devtools.ts
- bokehjs/test/framework.ts
- bokehjs/test/globals.d.ts
- bokehjs/test/unit/models/canvas/canvas.ts
- bokehjs/test/unit/models/canvas/index.ts
> Fix CanvasView.save() to configure device pixel ratio correctly

- bokeh/client/connection.py
- bokeh/client/session.py
- bokeh/client/states.py
- tests/unit/bokeh/test_client_server.py
> Revert "ClientSession: Add different error messages (Close #3653)"

- bokeh/client/connection.py
- bokeh/client/session.py
- bokeh/client/states.py
- tests/unit/bokeh/test_client_server.py
Updated pull request to different branch for PR #10243.
*  issues: fixes #3653
> Descriptive error

- bokeh/models/widgets/inputs.py
> fix Select.options type

- bokehjs/src/compiler/prelude.ts
> Unclobber global.Bokeh to avoid initialization failure

- bokeh/models/annotations.py
- bokehjs/src/lib/core/dom.ts
- bokehjs/src/lib/core/util/eq.ts
- bokehjs/src/lib/core/util/templating.ts
- bokehjs/src/lib/models/annotations/tooltip.ts
- bokehjs/src/lib/models/callbacks/open_url.ts
- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
- bokehjs/test/unit/core/util/eq.ts
- bokehjs/test/unit/core/util/templating.ts
- examples/models/file/popup.ts
- sphinx/source/docs/releases/2.2.0.rst
This improves various aspects of generating HTML tooltip content by hover tool. 
fixes #10234
> Improve performance of hover tool and tooltips

- bokehjs/src/lib/core/util/array.ts
- bokehjs/src/lib/models/sources/cds_view.ts
This improves performance in general and establishes a baseline for my ongoing and future work on indexing and selections.
> Improve performance of selections

- sphinx/source/docs/dev_guide/setup.rst
> Docs change anaconda install source

- bokeh/io/export.py
- bokehjs/src/lib/core/util/svg.ts
- bokehjs/src/lib/models/canvas/canvas.ts
- bokehjs/test/unit/models/canvas/canvas.ts
- tests/unit/bokeh/io/test_export.py
> Use APIs to collect serialized SVG canvas contents

- .github/CONTRIBUTING.md
and add a link to [BEP-1](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management) so people know what to expect after creating an issue or pull request.
> Change PR target branch recommendation

- bokehjs/src/lib/models/annotations/toolbar_panel.ts
> Avoid excessive rendering of toolbar panels

- bokeh/embed/standalone.py
- tests/unit/bokeh/embed/test_standalone.py
I don't think the tests are amazing but they are serviceable.
> autoload only uses necessary bundles

- bokehjs/src/lib/models/glyphs/harea.ts
- bokehjs/src/lib/models/glyphs/line.ts
- bokehjs/src/lib/models/glyphs/patch.ts
- bokehjs/src/lib/models/glyphs/varea.ts
- bokehjs/src/lib/models/selections/selection.ts
- bokehjs/src/lib/models/sources/cds_view.ts
Fixes line selection broken on `branch-2.2`
> fix bug with selection.get_view

- bokeh/sampledata/us_counties.py
- bokeh/sampledata/us_states.py
> Use ElementTree instead of deprecated cElementTree.

- sphinx/source/docs/user_guide/server.rst
This took me and a client of ours several days to figure out.
> Add note about nginx large_client_header_buffers to docs

- bokeh/server/views/app_index.html
- sphinx/source/docs/releases/1.3.0.rst
> update blog links

- bokeh/core/property_mixins.py
"http://www.w3schools.com/cssref/css_colornames.asp" was not working and I replaced with "https://www.w3schools.com/colors/colors_names.asp"
> Update `_color_help` url for css colors 

- bokehjs/src/lib/models/annotations/arrow.ts
- bokehjs/src/lib/models/annotations/band.ts
- bokehjs/src/lib/models/annotations/box_annotation.ts
- bokehjs/src/lib/models/annotations/label.ts
- bokehjs/src/lib/models/annotations/label_set.ts
- bokehjs/src/lib/models/annotations/slope.ts
- bokehjs/src/lib/models/annotations/span.ts
- bokehjs/src/lib/models/annotations/whisker.ts
- bokehjs/src/lib/models/axes/axis.ts
- bokehjs/src/lib/models/glyphs/glyph.ts
- bokehjs/src/lib/models/glyphs/hex_tile.ts
- bokehjs/src/lib/models/glyphs/multi_polygons.ts
- bokehjs/src/lib/models/glyphs/webgl/base.ts
- bokehjs/src/lib/models/grids/grid.ts
- bokehjs/src/lib/models/renderers/data_renderer.ts
- bokehjs/src/lib/models/renderers/renderer.ts
- bokehjs/src/lib/models/tiles/tile_renderer.ts
- bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
- bokehjs/src/lib/models/tools/edit/edit_tool.ts
- bokehjs/src/lib/models/tools/gestures/tap_tool.ts
- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
- examples/custom/latex_extension_base/latex_label/latex_label.ts
- examples/custom/latex_extension_full/latex_label/latex_label.ts
- examples/models/file/latex_extension.py
- sphinx/source/docs/user_guide/examples/extensions_example_latex.py
- tests/unit/bokeh/embed/latex_label/latex_label.ts
> rename renderer.scope -> .coordinates

- bokehjs/src/lib/models/transforms/interpolator.ts
- bokehjs/src/lib/models/transforms/step_interpolator.ts
- bokehjs/test/unit/models/transforms/index.ts
- bokehjs/test/unit/models/transforms/interpolator.ts
> Don't use for-in loop in Interpolator.sort()

- bokeh/_testing/util/selenium.py
- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/lib/models/widgets/tables/data_cube.ts
- bokehjs/src/lib/models/widgets/tables/data_table.ts
- bokehjs/test/codebase/size.ts
> Upgrade to SlickGrid 2.4.27

- bokehjs/package.json
- bokehjs/src/compiler/linker.ts
- bokehjs/src/lib/core/util/eq.ts
- bokehjs/src/lib/polyfill.ts
- bokehjs/test/codebase/size.ts
> Fix bokehjs' legacy bundles

- bokeh/io/webdriver.py
> Figure out actual binary executable firefox path

- bokehjs/src/lib/models/widgets/tables/data_table.ts
- bokehjs/test/unit/models/widgets/tables/data_table.ts
> Improve DataTable's sorting capability

- bokeh/models/widgets/inputs.py
- bokehjs/src/less/widgets/inputs.less
- bokehjs/src/lib/models/widgets/numeric_input.ts
- bokehjs/src/lib/models/widgets/spinner.ts
- tests/integration/widgets/test_numeric_input.py
> numeric input and spinner fixes

- bokeh/embed/standalone.py
- ci/environment-test-3.6.yml
- ci/environment-test-3.7.yml
- ci/environment-test-3.8.yml
- environment.yml
- tests/unit/bokeh/embed/test_standalone.py
issue: fixes #10361
Reverts bokeh/bokeh#10292
> Revert "autoload only uses necessary bundles"

- bokehjs/src/lib/core/util/bbox.ts
- bokehjs/src/lib/models/annotations/tooltip.ts
> Relativize layout's bbox in tooltip's side computations

- bokehjs/src/lib/models/sources/cds_view.ts
> Properly clone Selection in CDSView.convert_selection*()

- bokeh/model.py
> Update js_event_callbacks so that change events trigger

- bokehjs/src/lib/models/widgets/abstract_slider.ts
> Don't duplicate key action in sliders

- bokehjs/src/lib/core/util/templating.ts
- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
> Distinguish raw strings from HTML in replace_placeholders()

- bokeh/core/has_props.py
- bokeh/document/document.py
- bokeh/document/util.py
- bokehjs/src/lib/models/widgets/button.ts
This is a proof of concept. I think this change is promising, but it only fixes one side of the problem. The other is bokehjs sending too many objects and attributes.
fixes #10394
> Don't reinitialize existing instances

- sphinx/source/docs/user_guide/examples/interaction_open_url.py
> Update color link

- bokehjs/src/less/widgets/choices.less
- bokehjs/src/lib/models/widgets/multichoice.ts
> Fix updating of MultiChoice widget

- bokeh/server/views/autoload_js_handler.py
> Provide empty (not None) docs_json in AutoloadJsHandler

- bokeh/resources.py
- tests/unit/bokeh/test_resources.py
> Respect legacy=True in file/inline resources

- bokeh/model.py
- tests/unit/bokeh/test_model.py
> Fix Model.js_on_event() and add tests

- bokeh/server/django/consumers.py
Tentatively ready, but a test would be useful.
fixes #10434
> Fix a regression in django's autoload_js

- bokeh/client/connection.py
- bokeh/server/tornado.py
- bokeh/util/tornado.py
- tests/unit/bokeh/client/test_connection.py
- tests/unit/bokeh/server/test_tornado__server.py
Will add windows-only test from a windows machine later tonight
> Fixup event loop on windows in both client and server

- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
> Fix multiline inspection and reduce any type usage

- bokehjs/src/lib/models/formatters/tick_formatter.ts
- bokehjs/src/lib/models/widgets/abstract_slider.ts
- bokehjs/src/lib/models/widgets/date_range_slider.ts
- bokehjs/src/lib/models/widgets/date_slider.ts
- bokehjs/src/lib/models/widgets/range_slider.ts
- bokehjs/src/lib/models/widgets/slider.ts
- bokehjs/test/unit/models/widgets/slider.ts
> Make all sliders properly implement format property

- sphinx/source/bokeh/footer.html
> Add CoC information in documentation site

- sphinx/source/bokeh/footer.html
> Added link to the community page in the footer

- bokeh/io/webdriver.py
> added extra_options for create_chromium_webdriver

- sphinx/source/conf.py
> Add check for GOOGLE_API_KEY in conf.py

- ci/environment-test-3.6.yml
- ci/environment-test-3.7.yml
- ci/environment-test-3.8.yml
> pin pytest-asyncio 0.12

- sphinx/source/docs/dev_guide/testing.rst
Removed outdated CI instructions as mentioned in issue #10522
> removed outdated CI instructions

- sphinx/source/docs/dev_guide/documentation.rst
As part of Google's Season of Docs, this pull request adds style guidelines to the documentation section of the Developers Guide and refactors the document. As discussed with @bryevdv, @hyles-lineata, and @pavithraes.
> Add style guidlines and refactor

- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/core/properties.ts
- bokehjs/src/lib/core/util/serialization.ts
- bokehjs/src/lib/models/renderers/graph_renderer.ts
- bokehjs/src/lib/models/sources/ajax_data_source.ts
- bokehjs/test/defaults/index.ts
- bokehjs/test/framework.ts
- bokehjs/test/unit/models/renderers/graph_renderer.ts
- bokehjs/test/unit/models/renderers/index.ts
> Mark synthetic {x,y,xs,ys} expressions as internal

- bokehjs/src/lib/core/util/data_structures.ts
- bokehjs/src/lib/models/annotations/legend.ts
- bokehjs/src/lib/models/graphs/static_layout_provider.ts
- bokehjs/src/lib/models/plots/plot_canvas.ts
- bokehjs/src/lib/models/plots/range_manager.ts
- bokehjs/src/lib/models/renderers/graph_renderer.ts
- bokehjs/src/lib/models/renderers/renderer.ts
- bokehjs/src/lib/models/tools/edit/box_edit_tool.ts
- bokehjs/src/lib/models/tools/edit/edit_tool.ts
- bokehjs/src/lib/models/tools/gestures/tap_tool.ts
- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
- bokehjs/test/unit/models/plots/plot.ts
> Allow to resolve child renderers of composite renderers

- ci/environment-test-3.6.yml
- ci/environment-test-3.7.yml
- ci/environment-test-3.8.yml
- environment.yml
Cherry picked from PR #10550, because it will be awhile until 3.9 is available in conda.
> Pin pytest 6.0*

- sphinx/source/docs/user_guide/annotations.rst
- Edited the annotations doc to make it adhere to the documentation guidelines as in #10539 . Fixed few typos
> Annotation docs edits

- bokeh/server/django/consumers.py
> Fix periodic callback not stopping in Django

- bokeh/models/tools.py
Made changes to bokeh/models/tools.py line 900 as per the requirements of [issue #10581 ](https://github.com/bokeh/bokeh/issues/10581) to update CustemJSHover example. 
- [✓] issues: fixes #10581
> Issue 10581 custom js hover example

- sphinx/source/docs/user_guide/layout.rst
Finished editing layout.rst for task #10539.
Please let me know if you would like me to make any changes to the text.
> #10539 layout.rst

- sphinx/source/docs/user_guide/bokehjs.rst
Finished editing bokehjs.rst for task #10539.
Please let me know if you would like me to make any changes to the text.
> 10539 bokehjs.rst doc edit

- examples/app/README.md
- sphinx/source/docs/gallery.rst
> Minor typo in gallery docum. (repeated word)

- bokehjs/src/lib/api/plotting.ts
- bokehjs/src/lib/core/dom.ts
> Await for DOMContentLoaded in show()

- ci/environment-release-build.yml
Env works on OSX will just have to merge and try on linux
> don't use conda-forge for release buidl env

- bokehjs/package-lock.json
- bokehjs/package.json
- release/config.py
> use proper JS version

- sphinx/source/docs/user_guide/webgl.rst
> align webgl.rst with style guide, task #10539

- sphinx/source/docs/user_guide/geo.rst
Editing geo.rst for issue #10539.
First time contributor so let me know if anything is wrong or off. Eager to learn and to help.
> #10539 geo.rst doc edit

- sphinx/source/docs/user_guide/export.rst
Finished editing export.rst for task #10539.
Please let me know if you would like me to make any changes to the text.
> 10539 export.rst doc edit

- bokeh/server/contexts.py
This is a very simple PR, fixing issue #10536.
> Fix `super` call in "contexts.py"

- sphinx/source/docs/dev_guide/server.rst
Still needs a work to be more useful an up to date but at least flat-out wrong information is now gone.
> remove out of date info

- bokeh/palettes.py
Sphinx is suddenly puking on bokeh.palettes (new version?) when attempting dev build. In any case this PR:
* removes inline code-quotes from exception list in docstring (is overkill anyway)
* updates for f-string and dquotes
Will try dev build again after this is merged
> Fix new sphinx issue with bokeh.palettes

- examples/custom/latex_extension_base/latex_extension_base.py
- examples/custom/latex_extension_base/latex_label/latex_label.ts
- examples/custom/latex_extension_full/latex_extension_full.py
- examples/custom/latex_extension_full/latex_label/latex_label.ts
>  Fix custom/latex_extension_* examples

- bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
- bokehjs/test/unit/models/tools/inspectors/hover_tool.ts
> Modifying a HoverTool tooltip leads to errors if the new tooltip list is bigger.

- bokehjs/src/lib/core/serializer.ts
- bokehjs/test/unit/core/serializer.ts
> Allow serialization of circular objects

- .lgtm.yml
- bokehjs/package-lock.json
- bokehjs/package.json
- bokehjs/src/compiler/build.ts
- bokehjs/src/lib/core/property_mixins.ts
To make sure there are no major regressions. 4.1 final will be released in a few days.
> Upgrade to TypeScript 4.1 RC

- bokeh/util/callback_manager.py
> Add docstring to `on_event`

- bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
- bokehjs/test/unit/models/widgets/tables/cell_formatters.ts
> Fix scientific format for 0

- bokehjs/src/lib/models/widgets/tables/cell_formatters.ts
- bokehjs/test/unit/models/widgets/tables/cell_formatters.ts
This PR is a follow up of PR https://github.com/bokeh/bokeh/pull/10687 and should close https://github.com/bokeh/bokeh/issues/10697.
> Follow up of #10687

- .github/workflows/bokeh-ci.yml
- bokehjs/make/tasks/test.ts
> Use bokehjs' test framework to start chrome in examples' tests

- bokeh/models/tools.py
- bokehjs/src/lib/models/tools/gestures/tap_tool.ts
- bokehjs/test/unit/models/tools/gestures/tap_tool.ts
> Allow to configure TapTool with a gesture (tap or doubletap)

- .github/workflows/bokeh-ci.yml
- ci/build_bokehjs.sh
- ci/build_conda_pacakge.sh
- ci/environment-build.yml
- ci/environment-release-build.yml
- ci/environment-test-3.6.yml
> exit build steps on error

- bokehjs/src/compiler/build.ts
- bokehjs/src/compiler/prelude.ts
- examples/custom/latex_extension_full/latex_label/LICENSE.txt
- examples/custom/latex_extension_full/latex_label/bokeh.ext.json
> Add support for user supplied licenses to extensions

- bokeh/models/ranges.py
- bokeh/models/tools.py
> Fix `renderers` properties' types across bokeh

- bokeh/tile_providers.py
Updates Stamen docstring URLs to add SSL, matches https://github.com/bokeh/bokeh/commit/c42199633e2a1a6a515afb1dfeaa1e2ccb0d7c34
issues: fixes #10744
> Update Stamen doc urls for SSL Links

- bokeh/core/_templates/js_resources.html
> Only use SRI hashes in template when available

- bokeh/core/has_props.py
- bokeh/core/property/descriptors.py
- bokeh/document/document.py
- bokeh/model.py
- bokeh/models/expressions.py
- bokehjs/src/lib/base.ts
- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/core/types.ts
- bokehjs/src/lib/core/util/object.ts
- bokehjs/src/lib/core/vectorization.ts
- bokehjs/src/lib/document/defs.ts
- bokehjs/src/lib/document/document.ts
- bokehjs/src/lib/models/expressions/customjs_expr.ts
- bokehjs/src/lib/models/expressions/index.ts
- bokehjs/src/lib/models/renderers/glyph_renderer.ts
- bokehjs/src/lib/models/renderers/graph_renderer.ts
- examples/plotting/file/customjs_expr.py
- examples/plotting/file/data_models.py
Early preview.
See `plotting/file/data_models` example. For dynamic update, use e.g.:
```ts
Bokeh.index[1003].model.tags[0].freq = 10
```
in JS console.
fixes #3674
> Preliminary support for data models

- bokehjs/src/lib/core/util/bitset.ts
- bokehjs/test/unit/core/util/bitset.ts
- sphinx/source/docs/user_guide/examples/interaction_callbacks_for_range_update.py
> Improve BitSet.select() and fix a CustomJS example

- examples/plotting/file/boxplot.py
- [N/A] release document entry (if new feature or API change)
> 20201216.1718 resolve feature 10783. tested and working.

- bokeh/models/annotations.py
- sphinx/source/docs/includes/colors.txt
- sphinx/source/docs/includes/hatch_props.txt
- sphinx/source/docs/user_guide/styling.rst
This pull request updates styling.rst according to the style guidelines (#10539).
> Update styling.rst according to style guidelines

- bokeh/sphinxext/bokeh_enum.py
- bokeh/sphinxext/bokeh_github.py
- bokeh/sphinxext/bokeh_model.py
- bokeh/sphinxext/bokeh_palette.py
- bokeh/sphinxext/bokeh_sitemap.py
- bokeh/sphinxext/bokehjs_content.py
- bokeh/sphinxext/example_handler.py
- ci/environment-test-3.6.yml
- ci/environment-test-3.7.yml
- ci/environment-test-3.8.yml
- ci/environment-test-3.9.yml
- release/action.py
- release/config.py
- release/credentials.py
- release/logger.py
- release/pipeline.py
- release/remote.py
- release/system.py
- release/ui.py
> remove explicit defaults channel from ci env files

- sphinx/source/docs/user_guide/categorical.rst
- sphinx/source/docs/user_guide/compat.rst
- sphinx/source/docs/user_guide/extensions.rst
- sphinx/source/docs/user_guide/extensions_gallery/latex.rst
- sphinx/source/docs/user_guide/extensions_gallery/ticking.rst
- sphinx/source/docs/user_guide/extensions_gallery/tool.rst
- sphinx/source/docs/user_guide/extensions_gallery/widget.rst
- sphinx/source/docs/user_guide/extensions_gallery/wrapping.rst
- sphinx/source/docs/user_guide/interaction.rst
- sphinx/source/docs/user_guide/jupyter.rst
- sphinx/source/docs/user_guide/plotting.rst
- sphinx/source/docs/user_guide/styling.rst
This pull request fixes some minor typos and inconsistencies in various elements of the user guide that have been worked on in connection with #10539.
> Fix minor typos and inconsistencies

- sphinx/source/docs/dev_guide/documentation.rst
- sphinx/source/docs/user_guide/cli.rst
- sphinx/source/docs/user_guide/concepts.rst
This pull request updates concepts.rst an cli.rst as described in #10539. The changes to concepts.rst an cli.rst are mostly the changes made by @Konntroll in #10648. 
This pull request also updates documentation.rst in the dev docs to add a link to concept.rst's glossary (and also fixes some minor issues with incorrectly named labels in documentation.rst).
> Update concepts.rst and cli.rst

- bokehjs/make/tasks/scripts.ts
> Don't use explicit module names in styles/**/*.d.ts

- bokeh/models/sources.py
In line 105, error was thrown :
BokehUserWarning: ColumnDataSource's columns must be of the same length. 
changed np.ndarray to np.array
> Incorrect Example updated

- bokehjs/src/lib/models/annotations/poly_annotation.ts
- bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts
Regression test would be useful, though I think I will deal with those in-place updates in the first place (in near future).
fixes #10852
> Work around in-place updates in LassoSelectTool

- bokeh/client/connection.py
- bokeh/client/session.py
- bokeh/client/states.py
- tests/unit/bokeh/client/test_states.py
- tests/unit/bokeh/test_client_server.py
Small fix, I had almost all ready just from invesgation. Chose default to match existing server/browser value. Also fixed a bug that only happens a disconnect state transition.
> explose client side max message size

- sphinx/source/docs/releases.rst
> remote toctree from releases.rst

- bokeh/_testing/util/selenium.py
- bokeh/models/map_plots.py
- bokehjs/src/lib/models/plots/gmap_plot.ts
- bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
> Update and make configurable gmaps' API version

- bokeh/io/__init__.py
- tests/unit/bokeh/io/test___init___io.py
> add missing export_svg to bokeh.io top level

- bokeh/models/renderers.py
- bokehjs/src/lib/models/renderers/glyph_renderer.ts
> Allow None/null in GlyphRenderer.{non}selection_glyph

- bokeh/colors/hsl.py
- bokeh/colors/rgb.py
- bokeh/core/property/color.py
- bokeh/core/property/dataspec.py
- sphinx/source/docs/first_steps/first_steps_2.rst
- sphinx/source/docs/first_steps/first_steps_4.rst
- sphinx/source/docs/includes/colors.txt
- sphinx/source/docs/user_guide/examples/styling_specifying_colors.py
- sphinx/source/docs/user_guide/examples/styling_specifying_colors_properties.py
- sphinx/source/docs/user_guide/styling.rst
This pull request is a work in progress and will be used to collect commits to update various aspects related to colors in the docs. This pull request fixes #10895.
> Document new types of color types and color arrays

- bokeh/util/compiler.py
- conda.recipe/meta.yaml
- environment.yml
- setup.py
fixes https://github.com/holoviz/panel/issues/1993
> Bump minimum nodejs version to 14+

- bokeh/core/_templates/autoload_js.js
- sphinx/source/docs/user_guide/examples/extensions_example_widget.py
> Fix user_guide/extensions_example_widget.py

- sphinx/source/docs/releases/2.3.0.rst
> add 2.3 release notes

- .github/workflows/bokeh-ci.yml
- bokeh/core/property/bases.py
- bokeh/models/widgets/inputs.py
- bokeh/plotting/_plot.py
- tests/unit/bokeh/core/test_has_props.py
> Fix dask related regressions

- bokehjs/src/lib/models/renderers/glyph_renderer.ts
- bokehjs/test/unit/regressions.ts
> Don't render a legend if there's no data

- release/deploy.py
I'm landing this on `branch-2.3` on the assumption that there is at least a reasonable chance of a `2.3.1` happening at some point.  I will cherry-pick it to `branch-2.4` as soon as it is merged.
> fix broken cloudfront invalidation

- bokeh/server/views/app_index.html
- sphinx/source/bokeh/footer.html
Update footer links from "Citation" to "Branding".
> Update footer link to branding

- bokeh/core/has_props.py
- bokeh/core/property/descriptor_factory.py
- bokeh/model.py
- sphinx/source/docs/dev_guide/models.rst
- sphinx/source/docs/user_guide/examples/extensions_example_wrapping.py
- tests/unit/bokeh/core/property/test_dataspec.py
- tests/unit/bokeh/core/property/test_descriptor_factory.py
- tests/unit/bokeh/core/property/test_include.py
- tests/unit/bokeh/core/property/test_instance.py
- tests/unit/bokeh/test_objects.py
This is just WIP for preview. I will rebase on `branch-2.4` when it is made. 
There is indeed *lot* of cruft and/or unnecessary code around properties that can be jettisoned or cleaned up.
> Streamline / Cleanup Properties System

- sphinx/source/docs/first_steps/installation.rst
Add information about the [Bokeh channel on Anaconda](https://anaconda.org/bokeh/bokeh) to the installation details.
> Add information about Bokeh channel for installation

- bokeh/models/widgets/inputs.py
Add a note to the docstring of bokeh.models.widgets.inputs.FileInput regarding the upstream issue with Chrome/Big Sur discussed in bokeh.models.widgets.inputs.FileInput
cc @jeffreymonaco, @bryevdv
> Add note re. Chrome/MacOS bug

- bokeh/core/_templates/autoload_js.js
- bokeh/core/_templates/js_resources.html
- bokeh/sphinxext/_templates/bokehjs_html_template.html
- tests/unit/bokeh/embed/test_standalone.py
- tests/unit/bokeh/test_resources.py
> remove SRI hashes from Bokeh output

- bokehjs/src/lib/models/tools/edit/freehand_draw_tool.ts
> register "freehand_draw" as alias

- bokeh/models/tools.py
> register "freehand_draw" as an alias in python

- examples/app/spectrogram/audio.py
- examples/app/spectrogram/waterfall.py
- examples/app/spectrogram/waterfall.ts
> Fix examples/app/spectrogram

- bokehjs/src/lib/models/renderers/glyph_renderer.ts
- bokehjs/test/unit/regressions.ts
> Clean up after PR #10939

- sphinx/source/docs/first_steps/first_steps_1.rst
Another minor update to First Steps one, clarifying/correcting some wording.
> Clarify explanation in First Steps 1

- bokehjs/src/lib/models/formatters/func_tick_formatter.ts
- bokehjs/test/unit/models/formatters/func_tick_formatter.ts
> Make sure FuncTickFormatter always produces string labels

- sphinx/source/docs/user_guide/annotations.rst
- sphinx/source/docs/user_guide/examples/plotting_polygon_annotation.py
Add a short explanation and an example for PolyAnnotation to user guide.
> Add PolyAnnotation to user guide

- bokehjs/test/devtools/devtools.ts
Shaves 10s off integration tests. More improvements will follow in future PRs.
> Improve speed by comparing whole buffers first

- bokeh/models/tools.py
- bokehjs/src/lib/models/tools/edit/edit_tool.ts
> Make EditTool.custom_icon nullable

- sphinx/source/docs/user_guide/extensions.rst
> add note about extension defaults

- bokehjs/src/lib/core/util/bbox.ts
- bokehjs/src/lib/models/annotations/box_annotation.ts
- bokehjs/test/unit/core/util/bbox.ts
> Don't allow invalid bboxes in BoxAnnotation

- bokehjs/src/lib/models/tiles/tile_renderer.ts
> Fix snap_back for tile renderer

- bokehjs/src/lib/core/util/color.ts
- bokehjs/src/lib/models/widgets/color_picker.ts
> Use #rrggbb for input[type=color].value

- bokeh/colors/hsl.py
- bokeh/models/annotations.py
- bokeh/models/tools.py
- bokehjs/src/lib/core/util/bbox.ts
- bokehjs/src/lib/core/util/color.ts
- bokehjs/src/lib/models/annotations/box_annotation.ts
- bokehjs/src/lib/models/formatters/func_tick_formatter.ts
- bokehjs/src/lib/models/renderers/glyph_renderer.ts
- bokehjs/src/lib/models/tiles/tile_renderer.ts
- bokehjs/src/lib/models/tools/edit/edit_tool.ts
- bokehjs/src/lib/models/tools/edit/freehand_draw_tool.ts
- bokehjs/src/lib/models/widgets/color_picker.ts
- bokehjs/test/unit/core/util/bbox.ts
- bokehjs/test/unit/models/formatters/func_tick_formatter.ts
- bokehjs/test/unit/regressions.ts
- examples/app/spectrogram/audio.py
- examples/app/spectrogram/waterfall.py
- examples/app/spectrogram/waterfall.ts
- sphinx/source/docs/dev_guide/documentation.rst
- sphinx/source/docs/first_steps/first_steps_1.rst
- sphinx/source/docs/releases/2.3.0.rst
- sphinx/source/docs/releases/2.3.1.rst
- sphinx/source/docs/user_guide/annotations.rst
- sphinx/source/docs/user_guide/bokehjs.rst
- sphinx/source/docs/user_guide/examples/plotting_polygon_annotation.py
- sphinx/source/docs/user_guide/extensions.rst
> [NO SQUASH] Forward ports to branch-2.4

- bokeh/core/_templates/autoload_nb_js.js
- bokeh/core/_templates/autoload_request_tag.html
- tests/unit/bokeh/core/test_templates.py
Fixes regressions introduced in PR #10930 (on `branch-2.4`). This was revealed when working on https://github.com/lightkurve/lightkurve/issues/990.
> Fix regressions after PR #10930

- bokehjs/src/lib/document/document.ts
- bokehjs/test/codebase/size.ts
- bokehjs/test/unit/document/document.ts
> Serialize definitions of only newly created objects

- bokehjs/src/lib/api/gridplot.ts
- bokehjs/src/lib/api/linalg.ts
- bokehjs/src/lib/api/plotting.ts
- bokehjs/src/lib/core/properties.ts
- bokehjs/src/lib/core/util/object.ts
- bokehjs/src/lib/core/util/pretty.ts
- bokehjs/src/lib/models/plots/plot.ts
- bokehjs/test/unit/core/util/pretty.ts
- bokehjs/test/unit/regressions.ts
fixes #11016
fixes #11035
fixes #11037
fixes #11038
> Update bokehjs' plotting API to match bokeh

- examples/app/clustering/main.py
- examples/plotting/file/vector.py
- examples/webgl/clustering.py
> Remove deprecated np.int alias for int builtin

- bokeh/core/has_props.py
- bokehjs/src/lib/base.ts
- bokehjs/src/lib/document/defs.ts
- bokehjs/src/lib/document/document.ts
- examples/plotting/file/data_models.py
- tests/unit/bokeh/document/test_document.py
> Add support for per-Document model resolvers

- bokeh/core/has_props.py
- bokehjs/src/lib/base.ts
- bokehjs/src/lib/core/layout/grid.ts
- bokehjs/src/lib/document/defs.ts
- bokehjs/src/lib/document/document.ts
- bokehjs/src/lib/models/layouts/layout_dom.ts
- tests/unit/bokeh/document/test_document.py
> [NO SQUASH] more ports from branch-2.3

- bokeh/core/property/visual.py
- sphinx/source/docs/releases/2.4.0.rst
- tests/unit/bokeh/core/property/test_visual.py
> Add support for data URLs and pathlib to Image property

- sphinx/source/_static/custom.css
- sphinx/source/_templates/footer.html
Fix HTML and CSS for footer with pydata theme.
> Fix footer

- bokehjs/src/lib/core/util/serialization.ts
- bokehjs/test/unit/core/serializer.ts
- bokehjs/test/unit/core/util/serialization.ts
> Lazily serialize base64 encoded ndarrays

- bokehjs/test/unit/models/formatters/log_tick_formatter.ts
> Correct class name in describe()

- bokeh/layouts.py
- bokeh/plotting/figure.py
- bokeh/plotting/gmap.py
- bokehjs/src/lib/api/gridplot.ts
- examples/app/ohlc/main.py
- examples/models/file/toolbars2.py
- examples/plotting/file/color_data_map.py
- examples/plotting/file/glyphs.py
- examples/plotting/file/histogram.py
- examples/plotting/file/legend.py
- examples/plotting/file/rect.py
- examples/plotting/file/stocks.py
- examples/plotting/file/vector.py
- sphinx/source/docs/releases/2.4.0.rst
- sphinx/source/docs/user_guide/bokehjs.rst
- sphinx/source/docs/user_guide/examples/layout_grid.py
- sphinx/source/docs/user_guide/examples/layout_grid_convenient.py
- sphinx/source/docs/user_guide/layout.rst
- tests/integration/models/test_plot.py
- tests/integration/tools/test_pan_tool.py
- tests/integration/tools/test_reset_tool.py
- tests/integration/tools/test_wheel_zoom_tool.py
- tests/integration/tools/test_zoom_in_tool.py
- tests/integration/tools/test_zoom_out_tool.py
- tests/unit/bokeh/plotting/test_figure.py
> Replace {plot_->}{width,height} in gridplot()

- _setup_support.py
- release/build.py
- release/deploy.py
- release/stages.py
- setup.py
Will have to merge, and cut a dev build to test. 
Targeting 2.4 because this would be strange to add on a point release.
> support for publishing wheels

- bokeh/models/tools.py
- bokeh/plotting/_tools.py
- bokeh/plotting/figure.py
- bokeh/plotting/gmap.py
- bokehjs/src/lib/models/tools/toolbar.ts
> Unify {Figure,Toolbar}.active_* properties

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
> Link to Code of Conduct in issue and feature request templates

- bokehjs/src/lib/models/callbacks/open_url.ts
- bokehjs/test/integration/regressions.ts
- bokehjs/test/unit/models/callbacks/openurl.ts
This fixes the issues. @mattpap any thoughts on testing? I briefly looked at using `sinon.spy` but some additional refactoring would be needed to make that work
> Fix OpenURL escaping

- bokehjs/package-lock.json
- bokehjs/package.json
> Upgrade TypeScript to 4.3-rc

- sphinx/source/docs/dev_guide/setup.rst
Added init conda command into this dev_guide
> Added conda init command in Getting Set Up

- bokeh/embed/standalone.py
- tests/unit/bokeh/embed/test_standalone.py
This should change to a dataclass but that should happen at 3.0
> Add version to json_items output

- bokeh/embed/bundle.py
- bokeh/embed/standalone.py
- bokeh/plotting/figure.py
- bokeh/plotting/glyph_api.py
- ci/environment-test-3.7.yml
- ci/environment-test-3.8.yml
- ci/environment-test-3.9.yml
- environment.yml
- pyproject.toml
- tests/unit/bokeh/embed/test_standalone.py
- typings/bs4.pyi
> Statically type the return of `json_item()`

- bokehjs/package-lock.json
> Refresh `bokehjs/package-lock.json`

- bokehjs/src/lib/models/scales/linear_interpolation_scale.ts
- bokehjs/test/unit/models/scales/linear_interpolation_scale.ts
fixes https://github.com/holoviz/holoviews/issues/4978
> Handle corner cases in LinearLinterpolationScale.v_compute()

- bokeh/server/views/app_index.html
> app_index.html missing quotes in href attribute

- bokeh/_testing/plugins/file_server.py
- examples/embed/arguments/flask_server.py
- examples/howto/server_auth/auth.py
- tests/integration/widgets/test_range_slider.py
- fixes #11392
- ignores some LGTM issues that were determined to not be an issue
- minor change to redirects in auth example
- change to `open` mode as requested in #11392
> 11392 address lgtm issues

- tests/unit/bokeh/server/test_server__server.py
> Increase session_token_expiration

- bokehjs/src/lib/core/layout/grid.ts
- bokehjs/src/lib/core/layout/layoutable.ts
- bokehjs/src/lib/models/annotations/color_bar.ts
- bokehjs/src/lib/models/layouts/layout_dom.ts
- fixes #11344
- fixes #11188
- fixes #11161 
- fixes #11083
- fixes #11057
- fixes #10851
> Revert layout to pre PR #10779 state

- sphinx/source/docs/user_guide/categorical.rst
- sphinx/source/docs/user_guide/data.rst
- sphinx/source/docs/user_guide/examples/categorical_scatter_jitter.py
- sphinx/source/docs/user_guide/plotting.rst
- sphinx/source/docs/user_guide/styling.rst
- sphinx/source/rst_epilog.txt
There is still lots of improvements that can be made to this chapter, but this PR fixes two of the most bothersome things for me for a long time:
* Lack of any introductory discussion *at all*.
* Oddball "categorical offsets" section. (Now all top-level sections relate to data/plot types)
cc @tcmetzger please make any edits you see fit.
> Add intro for categorical chapter

- bokehjs/src/lib/api/gridplot.ts
- bokehjs/src/lib/models/axes/axis.ts
- bokehjs/src/lib/models/glyphs/step.ts
- bokehjs/src/lib/models/transforms/jitter.ts
- bokehjs/src/lib/models/transforms/range_transform.ts
- bokehjs/test/unit/models/transforms/jitter.ts
> Change jitter caching to only cache offsets instead of values

- bokeh/sampledata/commits.py
> Fix pandas future warning

- bokehjs/package-lock.json
- examples/plotting/file/sprint.py
Updated CustomJS to reflect current ColumnDataSource structure; some cosmetic changes.
> Sprinters example: updated CustomJS; some PEP8 cleanup

- bokeh/io/export.py
- tests/unit/bokeh/io/test_export.py
> Restore and robustify bokeh's SVG unit tests

- release/stages.py
> check base branch on deploy

- bokeh/themes/theme.py
> revert kwarg-only Theme args

- bokehjs/test/unit/models/callbacks/openurl.ts
> Stub `OpenURL.navigate()` in unit tests to avoid popups

- _setup_support.py
- bokeh/embed/bundle.py
- bokeh/embed/standalone.py
- bokeh/resources.py
- bokehjs/make/paths.ts
- bokehjs/make/tasks/scripts.ts
- bokehjs/src/compiler/linker.ts
- bokehjs/src/lib/bokeh.ts
- bokehjs/src/lib/core/util/modules.ts
- bokehjs/src/lib/models/canvas/canvas.ts
- bokehjs/src/lib/models/glyphs/circle.ts
- bokehjs/src/lib/models/glyphs/glyph.ts
- bokehjs/src/lib/models/glyphs/line.ts
- bokehjs/src/lib/models/glyphs/rect.ts
- bokehjs/src/lib/models/glyphs/scatter.ts
- bokehjs/src/lib/models/glyphs/webgl/index.ts
- bokehjs/src/lib/models/glyphs/webgl/main.ts
- bokehjs/src/lib/models/glyphs/webgl/rect.ts
- bokehjs/test/codebase/size.ts
- bokehjs/test/devtools/test.html
- release/remote.py
- sphinx/source/docs/first_steps/installation.rst
- sphinx/source/docs/user_guide/embed.rst
- tests/unit/bokeh/embed/test_bundle.py
- tests/unit/bokeh/embed/test_standalone.py
- tests/unit/bokeh/test_resources.py
> Restore `bokeh-gl(.min).js` bundle

- .github/workflows/bokeh-ci.yml
- bokeh/_version.py
- setup.cfg
- tests/unit/bokeh/test_resources.py
- tests/unit/bokeh/util/test_version.py
See if fetching full history resolves
> fetch full repo history for build job

- bokeh/tile_providers.py
- sphinx/source/docs/releases/2.4.0.rst
- tests/unit/bokeh/test_tile_providers.py
> Remove WIKIMEDIA tile provider

- bokeh/core/property/either.py
- tests/unit/bokeh/core/property/test_container.py
- tests/unit/bokeh/core/property/test_either.py
- tests/unit/bokeh/core/property/test_nullable.py
> Handle container wrapping better

- .github/workflows/bokeh-ci.yml
- ci/environment-test-downstream.yml
- ci/install_downstream_packages.sh
- ci/run_downstream_tests.sh
cc @jrbourbeau please confirm this satisfies the need on the Dask side
> streamline ci install for downstream

- bokeh/sampledata/perceptions.py
- bokeh/sphinxext/_templates/example_metadata.rst
- bokeh/sphinxext/bokeh_example_metadata.py
- bokeh/sphinxext/templates.py
- examples/plotting/file/bar_colormapped.py
- examples/plotting/file/hexbin.py
- examples/plotting/file/iris.py
- examples/plotting/file/pie.py
- examples/plotting/file/ridgeplot.py
- sphinx/source/conf.py
- sphinx/source/docs/user_guide/plotting.rst
Adding ReST docstrings to examples in gallery.
> Example metadata for gallery examples

- tests/unit/bokeh/models/test_plots.py
Fixing typo in unit-tests and errors.py
> Fixing typo error 2

- bokeh/command/subcommands/serve.py
> Print URL with protocol inferred from config

- bokeh/models/plots.py
- bokeh/plotting/figure.py
- bokeh/plotting/gmap.py
- tests/unit/bokeh/models/test_plots.py
> Always convert `str` to `Title` in `Plot.title`

- bokeh/_testing/util/env.py
- tests/unit/bokeh/_testing/util/test_env.py
- tests/unit/bokeh/command/subcommands/test_serve.py
- tests/unit/bokeh/embed/test_bundle.py
- tests/unit/bokeh/server/test_tornado__server.py
- tests/unit/bokeh/test_client_server.py
- tests/unit/bokeh/test_settings.py
- tests/unit/bokeh/util/test_browser.py
- tests/unit/bokeh/util/test_serialization.py
- tests/unit/bokeh/util/test_token.py
> Handle env vars in tests more carefully

- bokeh/core/_templates/autoload_request_tag.html
> Wrap autoload script's contents in a closure

- examples/app/surface3d/surface3d.py
> Define properties correctly in surface3d example

- bokeh/_testing/util/project.py
> Replace unix separators instead of os.sep

- .github/workflows/bokeh-ci.yml
- bokeh/util/terminal.py
- release/ui.py
- tests/test_examples.py
> Resolve typing platform specific issues

- bokehjs/src/lib/core/util/pretty.ts
- bokehjs/test/unit/core/util/pretty.ts
Trying to address `lgtm [js/incomplete-sanitization]` and related issue from codeql. The code is actually wrong, but for a different reason. Let's if they still complain. I also made the output to not over escape quotes, for readability.
> Fix and improve output from Printer.string()

- bokehjs/src/compiler/build.ts
- tests/unit/bokeh/test_ext.py
> Use the new scoped bokehjs package in `bokeh init`

- bokeh/embed/standalone.py
- sphinx/source/docs/user_guide/embed.rst
- sphinx/source/docs/user_guide/interaction/widgets.rst
- sphinx/source/docs/user_guide/styling.rst
- sphinx/source/rst_epilog.txt
This PR updates the user and reference guide to be more precise about the new mathjax bundle.
> Add information about mathjax bundle

- bokeh/models/annotations/html/labels.py
- bokeh/models/annotations/labels.py
- bokehjs/src/lib/models/annotations/html/label_set.ts
- bokehjs/src/lib/models/annotations/label_set.ts
- bokehjs/src/lib/models/glyphs/text.ts
- bokehjs/test/integration/annotations/label_set.ts
> Handle `NaN`/`null` in `LabelSet` correctly

- bokeh/server/views/app_index.html
- sphinx/source/_templates/footer.html
> update footer links

- sphinx/source/docs/first_steps/examples/first_steps_4_grid_lines.py
- sphinx/source/docs/first_steps/examples/first_steps_4_resize_plot.py
- sphinx/source/docs/first_steps/first_steps_4.rst
Changed some typographical errors in some Python files and changed the word "some things" to more specific wordings for a more specific and better tone of communication.
> Fixed some typos and changed wording for better tone

- bokehjs/package-lock.json
- bokehjs/package.json
> Upgrade SlickGrid to version 2.4.41(01)

- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/models/expressions/expression.ts
- bokehjs/src/lib/models/expressions/stack.ts
> Don't depend on signaling order when initializing data

- examples/models/file/basic_plot.py
PyData Global sprint: thanks for the help.
Bryan V's text amend suggestion included. 
Tests seemed to pass after I had eliminated the trailing whitespace :).
> 11765 basic plot example metadata

- bokehjs/src/lib/models/renderers/graph_renderer.ts
addresses #11800 (will be fully fixed by PR #11469)
> Don't unnecessarily update node/edge renderers in graphs

- bokehjs/src/lib/document/document.ts
- bokehjs/test/unit/regressions.ts
> Work around issues with initialization-time change discovery

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/ISSUE_TEMPLATE/task.md
- sphinx/source/docs/dev_guide/creating_issues.rst
As a follow-up to PR #11795 (issue #11791), this PR updates the docs to reflect the new forms for bug reports and feature requests.
> Update docs for new issue forms

- examples/models/file/calendars.py
> metadata for examples/models/file/calendars.py added

- bokeh/document/document.py
- tests/unit/bokeh/document/test_document.py
> Provide complete model context for deserialization of instances

- .github/workflows/bokeh-ci.yml
- .github/workflows/composite/test-setup/action.yml
- ci/unpack_artifacts.sh
GitHub added support for [Composite Actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) which should allow us to reduce the enormous duplication in our test action yaml file.
> simplify CI jobs with composite action

- ci/environment-test-3.10.yml
- ci/environment-test-3.7.yml
- ci/environment-test-3.8.yml
- ci/environment-test-3.9.yml
- environment.yml
> Pin to django 3.x

- bokehjs/src/lib/api/glyph_api.ts
- bokehjs/src/lib/core/util/image.ts
- bokehjs/src/lib/models/glyphs/image_url.ts
- bokehjs/test/integration/glyphs/markers.ts
- bokehjs/test/unit/regressions.ts
> Allow to render data URL images in one iteration

- examples/app/clustering/main.py
- examples/app/crossfilter/main.py
- examples/app/dash/main.py
- examples/app/export_csv/main.py
- examples/app/faces/README.md
- examples/app/faces/main.py
- examples/app/gapminder/main.py
- examples/app/image_blur.py
- examples/app/line_on_off.py
- examples/app/movies/main.py
- examples/app/ohlc/main.py
- examples/app/population.py
- examples/app/selection_histogram.py
- examples/app/simple_hdf5/main.py
- examples/app/spectrogram/main.py
- examples/app/surface3d/main.py
- examples/app/taylor.py
- examples/app/weather/main.py
Added docstrings on app\examples to tackle #11540 with additional note blocks in some of the files.
> Added docstrings on app\examples

- examples/models/file/widgets.py
Added metadata to `examples\models\file\widgets.py`
Fixing #11765
> Add metadata to widgets.py

- examples/plotting/file/airports_map.py
Fixing bokeh#11765
Added metadata to:
`examples/plotting/file/airports_map.py`
> Metadata for examples/plotting/file/airports_map.py

- bokehjs/src/lib/core/ui_events.ts
- bokehjs/src/lib/models/annotations/toolbar_panel.ts
- bokehjs/src/lib/models/tools/toolbar.ts
- bokehjs/src/lib/models/tools/toolbar_base.ts
- bokehjs/test/unit/models/tools/toolbar_base.ts
> Make auto-hidden toolbars' behaviour more robust

- bokehjs/src/lib/core/kinds.ts
- bokehjs/src/lib/core/util/iterator.ts
- bokehjs/src/lib/models/canvas/cartesian_frame.ts
- bokehjs/src/lib/models/plots/plot.ts
- bokehjs/src/lib/models/plots/plot_canvas.ts
- bokehjs/src/lib/models/ranges/data_range1d.ts
- bokehjs/src/lib/models/ranges/range.ts
- bokehjs/test/unit/core/util/iterator.ts
- bokehjs/test/unit/models/plots/plot.ts
- bokehjs/test/unit/models/ranges/data_range1d.ts
Move logic from `Plot` to `PlotView`, and make sure a plots clean up ranges after themselves.
> Improve life cycle of `DataRange1d.plots`

- bokehjs/package-lock.json
- release/build.py
> Update versions of all packages in `package-lock.json`

- bokeh/models/tools.py
> Fix typo in tools.py

- bokehjs/src/lib/core/ui_events.ts
- bokehjs/test/unit/regressions.ts
> Limit tool-related tap events to the frame

- bokehjs/package-lock.json
- release/build.py
Fixes issues introduced in PR #11932.
> Fix `package-lock.json` and `update_bokehjs_versions()`

- bokeh/models/tools.py
> Allow passing AnyRef to CustomJSHover

- bokehjs/src/lib/models/renderers/glyph_renderer.ts
- bokehjs/test/unit/regressions.ts
> Don't render if inspection indices didn't change

- sphinx/source/docs/user_guide/export.rst
> Clarify docs regarding necessity of Firefox

- .github/workflows/bokeh-ci.yml
- bokeh/util/tornado.py
- ci/environment-test-3.10.yml
- ci/environment-test-3.8.yml
- ci/environment-test-minimal-deps.yml
- tests/unit/bokeh/client/test_connection.py
- tests/unit/bokeh/server/test_server__server.py
- tests/unit/bokeh/server/test_tornado__server.py
> only patch the event loop policy on old versions of tornado

- bokeh/util/serialization.py
> Fix typo in timedelta conversion ValueError()

- bokehjs/src/lib/core/util/ndarray.ts
- bokehjs/test/unit/core/util/ndarray.ts
- bokehjs/test/unit/models/annotations/annotation.ts
Fixes `ndarray` related regressions introduced in PR #11960.
> Robustify initialization of ndarrays

- typings/flaky.pyi
- typings/ipykernel/comm/comm.pyi
- typings/selenium/webdriver/common/keys.pyi
- typings/selenium/webdriver/support/wait.pyi
> 12093 Update union syntax

- bokeh/core/property/either.py
- bokeh/sphinxext/bokeh_prop.py
- release/git.py
> Missing `f` prefix on f-strings fix

- bokeh/client/connection.py
- bokeh/command/subcommand.py
- bokeh/embed/bundle.py
- bokeh/embed/standalone.py
- bokeh/io/state.py
- bokeh/plotting/_tools.py
- bokeh/sphinxext/bokehjs_content.py
- bokeh/util/compiler.py
- scripts/sri.py
- tests/integration/widgets/test_numeric_input.py
- tests/integration/widgets/test_spinner.py
- tests/unit/bokeh/io/test_saving.py
- tests/unit/bokeh/util/test_compiler.py
Some very minor quality of life issues reported from https://codereview.doctor/bokeh/bokeh
> Minor cleanup issues

- release/git.py
> Fix typo in git.py

- bokeh/models/map_plots.py
- bokehjs/src/lib/models/plots/gmap_plot.ts
issues: fixes #12112 
Googles official recommendation is to use "weekly"
> Use weekly channel for gmap plots

- ci/build_docs.sh
- sphinx/source/_templates/layout.html
- sphinx/source/conf.py
This pr is a backport of #12134 to branch-2.4
> Backport docs ga fix

- bokehjs/src/lib/core/visuals/text.ts
This fixes a performance regression after PR #11929.
> Don't excessively check if fonts were loaded

- bokehjs/src/lib/core/has_props.ts
- bokehjs/src/lib/core/resolvers.ts
- bokehjs/src/lib/core/serialization/deserializer.ts
- bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts
- bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts
- bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts
- bokehjs/test/unit/core/has_props.ts
Simplifies and robustifies initialization of properties.
> Initialize properties in definition order

- bokehjs/make/tasks/scripts.ts
- bokehjs/package-lock.json
- bokehjs/src/compiler/linker.ts
- bokehjs/src/lib/package.json
> Resolve issues with MathJax 3.2.1

- README.md
> fixes #12150

- examples/models/file/choropleth.py
- examples/models/file/sliders.py
> 11765 Add metadata to choropleth.py and sliders.py

- ci/environment-release-build.yml
- ci/environment-test-3.10.yml
- ci/environment-test-3.8.yml
- ci/environment-test-3.9.yml
- ci/environment-test-minimal-deps.yml
- environment.yml
- sphinx/source/_static/custom.css
- sphinx/source/conf.py
- sphinx/source/docs/dev_guide.rst
- sphinx/source/docs/dev_guide/documentation.rst
- sphinx/source/docs/dev_guide/setup.rst
- sphinx/source/docs/first_steps.rst
- sphinx/source/docs/first_steps/installation.rst
- sphinx/source/docs/user_guide/concepts.rst
- sphinx/source/docs/user_guide/export.rst
- sphinx/source/docs/user_guide/graph.rst
- sphinx/source/docs/user_guide/jupyter.rst
- sphinx/source/index.rst
This PR removes the tabs and panel Sphinx extensions and replaces them with the sphinx-design extension (as discussed in https://pydata-sphinx-theme.readthedocs.io/en/stable/demo/kitchen-sink/web-components.html?highlight=panels#web-components). This PR partially fixes #12203.
> Replace panels and tabs extensions

- README.md
Expands the In-kind Support section to include support in the form of dev time and adds a link to makepath.
> Update readme support section

- sphinx/source/_static/custom.css
- sphinx/source/conf.py
This PR is related to #12203 and fixes some theme-related issues.
> Update docs CSS

- bokeh/models/tools.py
> Clarify edit tool helpstring

- sphinx/source/docs/first_steps/first_steps_7.rst
This PR updates the wording around output_file in the first steps guide (#12237)
> Update wording for output_file()

- bokeh/document/document.py
- bokeh/embed/standalone.py
- bokeh/embed/util.py
- tests/unit/bokeh/embed/test_standalone.py
> Don't defer buffer serialization in standalone mode

- bokehjs/src/lib/api/linalg.ts
- bokehjs/src/lib/core/util/random.ts
- bokehjs/test/unit/core/util/random.ts
> Move normal random generator from `np` to `Random`

- bokehjs/src/lib/core/util/throttle.ts
- bokehjs/test/unit/core/util/throttle.ts
> Allow to stop throttled functions

- .github/workflows/bokehjs-ci.yml
> Allow to run tests/lint even if build fails

- bokehjs/src/lib/core/dom_view.ts
- bokehjs/src/lib/core/ui_events.ts
- bokehjs/src/lib/core/util/menus.ts
- bokehjs/src/lib/models/annotations/toolbar_panel.ts
- bokehjs/src/lib/models/canvas/canvas.ts
- bokehjs/src/lib/models/tools/tool_button.ts
- bokehjs/src/lib/models/tools/toolbar.ts
> Don't permanently attach menus to the DOM

- bokeh/document/locking.py
- bokeh/io/doc.py
- bokeh/io/export.py
- pyproject.toml
- tests/unit/bokeh/document/test_callbacks__document.py
- tests/unit/bokeh/io/test_export.py
> Respect the current theme in `bokeh.io.export` APIs

- .github/workflows/bokeh-ci.yml
- ci/build_docs.sh
PR to test out saving built docs as a GH artifact
cc @bokeh/core
> Save CI docs as artifact

- bokeh/io/webdriver.py
- typings/selenium/webdriver/firefox/webdriver.pyi
> Resolve selenium 5.x webdriver related deprecations

- README.md
Adhered to the guidelines and fixed minor grammatical mistakes and improved a few sentences and made them concise.
I hope you don't mind me creating a pull request directly before creating an issue
> Grammatical fixes and improvisations

- bokeh/core/serialization.py
- tests/unit/bokeh/core/test_serialization.py
> Fail gracefully when serializing unsupported builtins

- bokeh/models/formatters.py
- tests/unit/bokeh/models/test_formatters.py
> add deprecated FuncTickFormatter

- conda/environment-test-3.10.yml
- conda/environment-test-3.8.yml
- conda/environment-test-3.9.yml
- conda/environment-test-downstream.yml
- conda/environment-test-minimal-deps.yml
- tests/support/plugins/file_server.py
- tests/support/plugins/project.py
Fixes test failures in other PRs.
> Improve compatibility with Python 3.10.6 in tests

- src/bokeh/__init__.py
Mostly just a test of CI-level codecov config
> Hide top level import

- docs/bokeh/source/docs/user_guide/interaction/tooltips.rst
> Remove extraneous paragraph

- docs/bokeh/source/docs/dev_guide/python.rst
- docs/bokeh/source/docs/dev_guide/writing_tests.rst
- examples/plotting/README.md
Update paths in docs following https://github.com/bokeh/bokeh/pull/12338.
Fixes #12340
> Update paths in docs

- .github/workflows/bokeh-ci.yml
- .github/workflows/composite/test-setup/action.yml
- scripts/ci/build_conda_pacakge.sh
This PR switches from uploading and using the conda package for testing, to uploading and using the wheel for testing.
> Use wheel for testing

- bokehjs/make/package.json
- bokehjs/make/tasks/defaults.ts
- bokehjs/package-lock.json
- bokehjs/src/compiler/compile.ts
- bokehjs/src/compiler/compiler.ts
- bokehjs/src/compiler/linker.ts
- bokehjs/src/compiler/package.json
- bokehjs/src/compiler/transforms.ts
- bokehjs/src/lib/core/build_views.ts
- bokehjs/src/lib/core/kinds.ts
- bokehjs/src/lib/core/properties.ts
- bokehjs/src/lib/document/defs.ts
> Upgrade to TypeScript 4.8

- bokehjs/src/lib/models/text/math_text.ts
> Use more robust CSS length parsing in MathText

- bokehjs/src/lib/core/util/version.ts
- bokehjs/src/lib/document/document.ts
- bokehjs/test/unit/core/util/version.ts
- bokehjs/test/unit/document/document.ts
This should vix the version mismatch but we won't actually see until the next dev build
> fix pyifying versions in BokehJS

- docs/bokeh/source/docs/user_guide/examples/categorical_heatmap_periodic.py
> Fix periodic table example in user guide

- conda/environment-test-3.10.yml
- conda/environment-test-3.8.yml
- conda/environment-test-3.9.yml
- conda/environment-test-minimal-deps.yml
- src/bokeh/protocol/receiver.py
Fixes type checking errors with mypy 0.981, see e.g. https://github.com/bokeh/bokeh/actions/runs/3130384957/jobs/5080698260.
> Upgrade to mypy 0.981

- docs/CODE_OF_CONDUCT.md
- docs/bokeh/source/docs/dev_guide.rst
- docs/bokeh/source/docs/first_steps.rst
##Proposed changes
Update docs
Basic grammar mistakes
> Grammar changes to the docs

- docs/bokeh/source/docs/dev_guide/setup.rst
Fix a number in a headline in the contributor guide
> Fix number in headline

- docs/bokeh/source/docs/dev_guide.rst
> Update Julia bindings in contributing docs

- docs/bokeh/source/docs/releases/3.0.0.rst
I will be collecting relevant missing change log entries in this PR.
> Update 3.0.0 change log

- examples/advanced/extensions/ion_range_slider.ts
- examples/advanced/extensions/widget.py
> Update ion range slider example

- src/bokeh/models/plots.py
> Modify renderers helpstring

- examples/server/app/server_auth/README.md
- examples/server/app/server_auth/app.py
- examples/server/app/server_auth/auth.py
- examples/server/app/server_auth/login.html
> clarify the scope of the server_auth example

- bokehjs/src/less/dialogs.less
- bokehjs/src/less/inspector.less
> Allow scroll in inspector's model/property panels

- examples/styling/mathtext/latex_blackbody_radiation.py
> Fix units in blackbody example

- docs/bokeh/source/docs/releases/3.0.0.rst
- docs/bokeh/source/docs/releases/3.0.1.rst
- docs/bokeh/switcher.json
- examples/plotting/checkout_form.py
Anaconda wants a 3.0.1 will try to get this out today (rc1 first) cc @bokeh/core
> updates for 3.0.1 release

- tests/support/plugins/bokeh_server.py
- tests/test_examples.py
> replace python with sys.executable

- .github/workflows/bokeh-ci.yml
- .github/workflows/bokehjs-ci.yml
- bokehjs/test/devtools/devtools.ts
- docs/bokeh/source/docs/dev_guide/bokehjs.rst
> Correctly grant clipboard permissions in tests

- src/bokeh/__init__.py
- tests/codebase/test_importlib_metadata.py
> Clean up importlib.metadata properly

- release/deploy.py
> upload switcher.json during release

- docs/bokeh/source/_static/custom.js
This needs to be backported for 3.0.2 For expediency I will probably just cherry pick this commit directly to the branch, and note it in the other backport PR.
> Fix docs custom.js for switcher

- conda/environment-test-downstream.yml
- conda/environment-test-minimal-deps.yml
- pyproject.toml
> Update min numpy to 1.16

- README.md
- docs/bokeh/source/docs/first_steps.rst
- docs/bokeh/source/docs/first_steps/installation.rst
> Neutral POV for install instructions

- .github/codecov.yml
> Ignore tmp test modules for codecov

- src/bokeh/io/export.py
- tests/unit/bokeh/io/test_export.py
> Fix export with fractional CSS lengths
