bokeh/models/expressions.py, bokehjs/src/lib/core/properties.ts, bokehjs/src/lib/models/expressions/expression.ts, bokehjs/src/lib/models/expressions/stack.ts, bokehjs/test/models/expressions/stack.coffee
This makes `v_compute` on the base class to do the caching, and delegate to `_v_compute`. If users make a subclass a subclass with `v_compute` it will now no longer cache. They can implement `_v_compute` if they desire that (docs updated accordingly). This is definitely more sensible.
=> have expressions respond properly to stream/patch

bokehjs/src/lib/models/grids/grid.ts, bokehjs/test/models/grids/grid.coffee
Does not fix the flickering issue, going to punt on that. But makes sure the ends are always alternating from the first full band:
=> make grid bands handle ends correctly

bokeh/command/subcommands/tests/test_serve.py, bokehjs/gulp/tasks/test.ts, bokehjs/package-lock.json, bokehjs/package.json, bokehjs/test/core/visuals.ts
ref: #7865
@mattpap this is a minimal PR that seems to get tests running again on mocha 4, I agree BokehJS unit tests need a top-to-bottom overhaul but that will have to be after this release.
=> Work around various test stupidity

bokehjs/test/core/util/templating.ts, examples/plotting/file/image.py, sphinx/docserver.py, sphinx/source/docs/user_guide/examples/tools_hover_tooltips_image.py, sphinx/source/docs/user_guide/plotting.rst, sphinx/source/docs/user_guide/tools.rst
This PR follows on from #7651 to add an example, an entry in the user guide, other miscellaneous documentation (e.g a pointer from the image glyph section) and unit tests.
In the first commit a new ``tools_hover_tooltips_image.py`` example is added which looks like this:
I'm open to suggestions on how to improve this example. In particular, @bryevdv suggested that the bit mask would look better if the two colors contrasted less.
=> Image hover documentation and tests

bokehjs/src/less/main.less, bokehjs/src/lib/models/tiles/tile_renderer.ts
As described in https://github.com/bokeh/bokeh/issues/7908, the attribution text for tile sources is currently quite distractingly large, particularly for small plots:
After applying this PR, the text should still be readable, but is less distracting:
Open issue: Is there a way to avoid coloring the link text blue?  It's very difficult to read in certain cases (see the black and white Stamen example above), and it's hard to make a background color that works well for both black and bright blue text when combined with various elements that might be in the map tiles.  I can see how to change any CSS elements that apply to the general text here, but not for link anchors.
=> Made tile attributions less distracting

bokeh/embed/standalone.py, bokeh/embed/tests/test_util.py, bokeh/embed/util.py
Thought the safest way to check this is on static HTML generation. Does not warn when generating JSON though, but don't think it is needed. You can test this functionality with this snippet:
``` python
from bokeh.io import curdoc, show
from bokeh.models.widgets import Button
from bokeh.models import CustomJS
from bokeh.events import ButtonClick
from IPython import embed
plot = figure(plot_height=400, plot_width=400)
click_button = Button()
change_button = Button()
event_button = Button()
change_js_button = Button()
event_js_button = Button()
def handler(*args):
print('Clicked!')
def handler2(attr, old, new):
print('Clicked!')
js_handler = CustomJS(code='console.log("JS:Click")')
click_button.on_click(handler) …
```
=> Fixes #3596: Warn on generating static HTML with Python callbacks

bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts, bokehjs/test/models/tools/edit/poly_draw_tool.ts
Small fix to allow the PolyDraw tool to edit a data source containing typed array paths, which have been added after starting to edit the data source when the arrays are usually converted.
=> Ensured the PolyDraw tool correctly handles typed array paths

bokeh/command/subcommands/serve.py, bokeh/command/subcommands/tests/test_serve.py, bokeh/server/server.py, bokeh/server/tests/test_tornado.py, bokeh/server/tornado.py, sphinx/source/docs/releases/0.13.0.rst
I was going to raise the min Tornado version to 4.5 but @bdarnell advised that earlier versions will just silently ignore the value rather than error out, so I have merely documented this fact. 
The tests
=> add option to set websocket_max_message_size

bokeh/command/subcommands/serve.py, bokeh/command/subcommands/tests/test_serve.py, bokeh/core/property_mixins.py, bokeh/models/tests/utils/property_utils.py, bokehjs/src/lib/core/property_mixins.ts, sphinx/source/docs/releases/0.13.0.rst
In every case where I can detect a difference from the current value, the change is an improvement.  E.g. from a [TriMesh example](https://holoviews.org/reference/elements/bokeh/TriMesh.html), before:
and after:
(see all the spurious corners along the top edge of the image above, and how they disappear on the bottom image.)
Thanks to @bryevdv for the code.
=> Changed default line_join from miter to bevel

bokehjs/src/lib/models/layouts/layout_dom.ts, bokehjs/test/models/plots/plot.coffee
No extra CSS is required. `embed/embed_responsive_width_height` works. @Karel-van-de-Plassche's example works as well (to my surprise), but there are some off by a few pixels errors, that make plots cover CSS borders. This seems to be unrelated to the core of the issue and more to CSS box model we use (there is an issue for that).
fixes #7978
=> Don't make assumptions on DOM/CSS in LayoutDOM.get_width_height()

sphinx/source/docs/user_guide/examples/styling_linear_mappers.py, sphinx/source/docs/user_guide/styling.rst
fixes:  #7995
This is an update to the "Styling Visual Attributes page" to document the use of the mappers along with an example. 
A picture of the page (built locally) is attached here as well if folks just want to provide feedback on the text. 
This includes an example where 10 circles are drawn with an diverging color palette based on the y-axis. This pairs nicely with "Using Palettes" the first entry on the page. 
thanks
=> Using mappers documentation update

bokehjs/src/lib/core/util/math.ts, bokehjs/src/lib/models/glyphs/wedge.ts, bokehjs/test/core/util/math.ts
Corrects the issues discussed in #7428 and #2080. Namely the incorrect behaviour when the direction is set to clock, and also improving hover tool tip display position for wedge glyphs.
Might be some changing required depending on the exact intention of using angle_between.
=> Fix hit testing issues for wedge and annular wedge

sphinx/source/docs/user_guide/tools.rst
Closes https://github.com/bokeh/bokeh/issues/8000.  Nothing fancy, just cleaning up some docs.  Current version lives [here](bokeh.pydata.org/en/latest/docs/user_guide/tools.html)
=> Corrected docs for `dimensions` parameter to BoxZoomTool

bokeh/core/templates.py
This PR fixes a bug concerning the interaction between Bokeh and PyInstaller by using Jinja2's `FileSystemLoader` instead of `PackageLoader` (which is currently not supported by PyInstaller), and adjusting the path to the `_templates` folder. It should also fix issues with other freezing tools (like py2exe in #799). However, PyInstaller is probably the most widely used freezing tool and is still actively maintained (unlike e.g. py2exe, whose last release is almost four years old).
Since the changes are in an `if getattr(sys, 'frozen', False)` block (as described in the [PyInstaller documentation](http://pyinstaller.readthedocs.io/en/stable/runtime-information.html)), this PR shouldn't break anything for the "live" use.
PyInstaller itself does not copy the `bokeh/core/_templates` folder …
=> Make Bokeh work in frozen scripts

bokeh/document/document.py, bokeh/util/tornado.py
The #7992 issue originates from the fact that `_callback_objs_by_callable` in document.py and `_next_tick_removers_by_callable` etc. in tornado.py are retaining references, as dictionary keys, to callable objects (and their wrapped versions, correspondingly), passed to `add_next_tick_callback` etc. document methods. I guess, the intention was to group multiple next tick or timeout callbacks for the same callback function in `defaultdict(set)`s. Though, the wrapped callbacks of the same callback function are already different objects and "won't stack" in `_next_tick_removers_by_callable`, while passing different callback functions will aggregate in both location, thus doubling the captured reference count.
This PR is fixing it by removing the `key, value` pairs completely, once the `value` …
=> bokeh server: reference leak fix

bokeh/core/json_encoder.py, bokeh/core/properties.py, bokeh/core/property_mixins.py, bokeh/core/tests/test_json_encoder.py, bokeh/models/glyphs.py, bokeh/models/ranges.py, bokeh/models/tests/test_ranges.py, bokeh/util/serialization.py, bokeh/util/tests/test_serialization.py
Noticed quite a bit of silliness in working on those two issues, so added some other cleanup. This PR:
* adds proper handling for Pandas `Period` and `PeriodIndex`, also making sure the binary protocol is used for Pandas series when it should be
* clarifies internally that time delta values are not datetimes
* allows Range1d to accept time delta values
* allows DataRange1d to also accept datetimes and time delta values (cannot think of any reason they should not)
* fixes the bizarre `url = NumberSpec` type on `ImageURL`
Thanks to @miccoli for discussion and prompting
=> handle Pandas PeriodIndex and Timedelta properly

bokeh/core/templates.py
A better treatment for freezing bokeh with pyinstaller.
The `_templates` dir should better stay in its original subdirectory than in the project root as implemented in #8008, as it better fits pyinstaller directory layout: as documented [here](https://pythonhosted.org/PyInstaller/hooks.html), `collect_data_files()` as opposed to `--add-data` doesn't support the destination path.
See my [PR3607](https://github.com/pyinstaller/pyinstaller/pull/3607) with the associated pyinstaller hook file which uses the new _templates location.
=> improved support for pyinstaller

bokeh/__init__.py, bokeh/tests/test___init__.py
With this change, (Bokeh) warnings are now streamlined:
```
In [5]: from bokeh.models import ColumnDataSource; source = ColumnDataSource(data=dict(a=[1], b=[1,2]))
BokehUserWarning: ColumnDataSource's columns must be of the same length. Current lengths: ('a', 1), ('b', 2)
```
The rationale for dropping the line and lineno is that warnings are typically emitted deep in Bokeh library code, which is not helpful, and also often as part of validation, so that raising the stacklevel is also not useful or practical. 
Non-Bokeh warnings should continue to function as normal.
=> format Bokeh warnings more nicely

bokeh/core/validation/errors.py, bokeh/models/plots.py, bokeh/models/tests/test_plots.py, bokeh/models/tests/test_sources.py
Also cleans up some other minor test and formatting issues. 
Generates this sort of error:
```
In [7]: p = figure()
In [8]: p.xaxis.x_range_name = "junk"
In [9]: check_integrity([p])
ERROR:bokeh.core.validation.check:E-1020 (BAD_EXTRA_RANGE_NAME): An extra range name is configued with a name that does not correspond to any range: x_range_name='junk' [LinearAxis(id='db4bc5d5-79cf-4d64-89c2-39b7db443848', ...)]```
=> add validation on extra range names

bokehjs/src/lib/models/glyphs/annulus.ts
Corrects annulus hit testing where outer diameter is specified in screen units. 
Coincidently I noticed you can specify an annulus with an inner diameter greater than the outer diameter, in that case hover fails.
- [] tests passed
=> fix annulus hit testing with screen units

bokehjs/src/lib/models/glyphs/box.ts, bokehjs/src/lib/models/glyphs/hbar.ts, bokehjs/src/lib/models/glyphs/vbar.ts
OP code now generates:
Tested manually with `hbar`. Need to verify hover, etc is not impacted. Also need to add at minimum, unit tests for the viewport clamp function, but would like to add some selenium tests on travis directly.
=> clamp bar endpoints to viewport

bokehjs/src/lib/models/tools/edit/box_edit_tool.ts, bokehjs/test/models/tools/edit/box_edit_tool.ts, bokehjs/test/models/tools/edit/poly_draw_tool.ts
This PR adds a simple check to ensure the BoxEditTool does not draw when the tool is inactive. Also adds unit tests to avoid regressions.
=> Ensure BoxDrawTool does not draw when tool inactive

bokeh/models/tools.py, bokehjs/src/lib/models/tools/gestures/tap_tool.ts
The Tap Tool doesn't expose any direct access to the calculated range-specific x and y data coordinates. This is available in all the Select tools, and in the Hover tool. 
The method used here is similar to the approach used in the Select and Hover tools in that we step outside the Geometry classes and define a naked object to hold all the values. Most user-side js code will not reference or understand these internal classes and will access the values directly.
=> Added x and y values to the geometries property of cb_data for TapTool

examples/plotting/file/pie.py
pie chart example - http://bokeh.pydata.org/en/latest/docs/gallery/pie_chart.html can be simplified by 
removing `Counter` and use `data['value'].sum()`
=> REF: Simplify pie example #8086

bokehjs/src/lib/models/glyphs/step.ts
Copied over the code in `line.ts`. Not sure if this maybe can/should be generalized and/or extended to the other line-like glyphs, e.g. arc and bezier.
=> Fixes 7890: Do not draw line if value is NaN in step

examples/howto/layouts/words_and_plots.py, examples/plotting/file/hover_glyph.py, sphinx/source/docs/user_guide/examples/plotting_box_annotation.py, sphinx/source/docs/user_guide/examples/styling_glyph_hover.py
In continuation to #8104 and #8105
=> REF: Use .loc instead of .ix in examples

bokeh/models/tests/test_sources.py
As soon as an exception is caught, the enclosing with context is broken. So, the assertions are never reached. You can test this by putting assert 0 somewhere
=> Fixed Exception raising tests of test_sources

bokeh/models/sources.py, bokeh/models/tests/test_sources.py, sphinx/source/docs/user_guide/data.rst
Both df.index and df.columns can be a pd.MultiIndex. Bokeh
expects a 'flat' table. This change uses the pandas API to
flatten, solving some issues with naming + being more consistent
with pandas
Supersedes https://github.com/bokeh/bokeh/pull/8002
=> Fixes #6770. Flatten pandas columns and index explicitly on CDS creation

sphinx/source/docs/user_guide/notebook.rst
Add documentation, instructions, and a reference implementation for using bokeh server in a JupyterHub environment.
=> Update notebook.rst instructions using JupyterHub + Bokeh.

bokeh/models/annotations.py
Providing a clearer explanation on the usage of the ``dimensions`` property in the classes Band, Span, and Whisker.
=> Updating the docstring for the dimensions property for Band, Span and Whisker

bokeh/models/map_plots.py, bokehjs/src/lib/models/plots/gmap_plot.ts, bokehjs/src/lib/models/plots/gmap_plot_canvas.ts
Relevant Google Groups discussion: https://groups.google.com/a/continuum.io/forum/#!msg/bokeh/Ko66-4PbhNc/0TEpR3S1CQAJ
I am trying to add support for the `tilt` option for GMapPlot.
Without knowing exactly what I'm doing I have added the `tilt` option analogous to the `scale_control` option.
There are two open issues:
1) I don't see how my added option is ever sent to the API, so I doubt this will actually have any effect yet. Please help me understand how this should work.
2) In the current state, using a non default tilt parameter (i.e. `tilt=0`) breaks the plot with the following error:
```
Uncaught Error: property GMapOptions.tilt wasn't declared
at t.u.setv (bokeh-1.0.0dev4.min.js:31)
at t.u [as constructor] (bokeh-1.0.0dev4.min.js:31)
at t.i [as constructor] …
```
=> Add tilt option to GMapOptions

bokeh/models/tools.py, bokehjs/src/lib/models/tools/edit/box_edit_tool.ts, bokehjs/src/lib/models/tools/edit/edit_tool.ts, bokehjs/src/lib/models/tools/edit/point_draw_tool.ts, bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts, bokehjs/test/models/tools/edit/box_edit_tool.ts, bokehjs/test/models/tools/edit/point_draw_tool.ts, bokehjs/test/models/tools/edit/poly_draw_tool.ts, sphinx/source/docs/user_guide/tools.rst
This PR addresses a feature requested from the existing drawing tools, which is to overwrite the last drawn glyph. This is useful when you only want to draw a single box or polygon.
The spelling to enable this behavior is to set the new property ``overwrite=True``, suggestions for alternative spelling would be welcome (@jbednar?).
=> Allow ability to overwrite existing glyphs in drawing tools

bokeh/_testing/plugins/bokeh.py, tests/integration/test_server.py
This is an initial stab at a workflow for adding selenium tests for bokeh server apps. Some things will probably change, but this is enough to support other currently ongoing work.
Some questions (to be addressed in later PRs):
* should server tests e.g. for widgets, be located with all the other widget tests? Or should the be segregated? If so, in what sort of layout
* Should `single_plot_page` etc jsut be made to support server apps out of the box? Or should `bokeh_server_page` remain distinct?
Also note the workarounds for https://github.com/bokeh/bokeh/issues/7970 that should be removed when that issue is resolved. 
cc @philippjfr
=> initial work to support server selenium tests

bokeh/core/properties.py, bokeh/core/property/bases.py, bokeh/core/property/tests/test_bases.py, bokeh/core/tests/test_properties.py
This allows users to control whether or not they want validate checks when
updating properties.
Examples
--------
with validate(False):
...
or
@without_property_validation
def update(attr, old, new):
...
Fixes #8138
=> Add context manager and decorator to control property validation

bokeh/core/_templates/file.html
=> Define {css,js}_resources blocks in the correct order

bokehjs/src/lib/models/glyphs/line.ts, bokehjs/src/lib/models/glyphs/multi_line.ts, bokehjs/src/lib/models/glyphs/utils.ts
ensures the vline/hline segments completely envelope the target line in the transverse direction (even if the line is vertical or horizontal)
=> handle vline/hline hover in corner cases

bokeh/models/annotations.py, bokehjs/src/lib/models/annotations/legend.ts, bokehjs/src/lib/models/annotations/legend_item.ts, bokehjs/src/lib/models/renderers/glyph_renderer.ts, examples/plotting/file/multi_legend.py, sphinx/source/docs/user_guide/annotations.rst, sphinx/source/docs/user_guide/examples/plotting_legends_multi_index.py
This was raised on Gitter and falls under the category of low hanging but valuable fruit. This PR allows users to specify an explicit `index` on legend items, so that e.g. annotating each line in a multi_line is possible. With a little more follow-on work, #2603 would be within reach. Later work might also add a convenience API to `multi_line` and `patches` to make creating the legend items less manual. 
Unfortunately I can't think of a good direct test for this with the current view architecture, but I have added an expample that will show up under image diff tests. 
```
from bokeh.plotting import figure, output_file, show
from bokeh.models import Legend, LegendItem
p = figure()
r = p.multi_line([[1,2,3], [1,2,3]], [[1,3,2], [3,4,3]],
color=["orange", "red"], line_width=4)
legend = …
```
=> support specifying representative point from legend items

scripts/deps.py
Build is currently failing due to an apparent python 3.7 issue, which has uncovered that the current method of installation will always use the most recent python, instead of what is explicitly specified and intended. 
The issue is having an unversioned "python" in the conda install line:
This PR addresses that by removing "python" if it is present (it has to remain in the recipe, so our only option is to filter it out)
=> don't report unversioned python in deps.py output

bokeh/application/handlers/script.py
Using 'utf-8' codec to open python 3 scripts in bokeh app.
=> Using 'utf-8' codec to open python 3 scripts in bokeh app

bokeh/_testing/plugins/log_file.py
This PR initially set about to ensure we used humane naming throughout, but as it turns out the small amount of relevant code is actually no longer needed at all and can just be removed altogether.
=> remove dead testing code

.travis.yml
See title. Not sure if python3.7 support is premature at this point, but I found some functions failing that worked in python3.6, so this is the first step in testing compatibility.
=> Added unit/integration tests for python3.7

bokeh/util/serialization.py, bokeh/util/tests/test_serialization.py
Not sure why this:
> C:\projects\bokeh\bokeh\util\serialization.py:516: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
1911  array = np.fromstring(b64, dtype=data['dtype'])
is only showing up on tentative windows builds on Appveyor (see #8213) but might as well fix it up now. `np.frombuffer` appears in the NumPy 1.7.x docs:
https://docs.scipy.org/doc/numpy-1.7.0/reference/generated/numpy.frombuffer.html
so there should be no need to change our `REQUIRES`
=> use np.frombuffer instead of deprecated np.fromstring

bokehjs/src/lib/api/plotting.ts, bokehjs/src/lib/core/util/serialization.ts, bokehjs/src/lib/models/sources/columnar_data_source.ts, bokehjs/test/core/util/serialization.ts, bokehjs/test/models/sources/column_data_source.coffee
This PR adds a `clear` method to BokehJS CDS. Additionally:
* removes duplicative `column_names` property (use `columns()` consistently)
* fixes a bug preventing direct init of CDS from typed arrays
=> add clear method to CDS

bokehjs/src/lib/models/glyphs/glyph.ts
Test code:
```
from bokeh.io import show
from bokeh.models import GMapOptions, ColumnDataSource
from bokeh.plotting import figure, gmap
map_options = GMapOptions(lat=37.76, lng=-121.9, map_type="roadmap", zoom=11)
plot = gmap(google_api_key="AIzaSyAM1OHVm6Yr_i54Kt01mylfxyNxQdxmxHQ", map_options=map_options)
source = ColumnDataSource( data = dict(
y=[ 37.762260 ],
x=[-121.96226],
ym01=[37.762290 ],
xm01=[-121.86189 ],
))
plot.segment(x0="x", y0="y", x1="xm01", y1="ym01",line_color="green", line_width=2, source=source)
plot.circle(x=[-121.96226, -121.86189], y=[37.762260, 37.762290], size=8)
show(plot)
```
Result:
=> project coords for segment glyphs on gmaps

bokehjs/package-lock.json, bokehjs/package.json
@mattpap this appears to resolve the CVE noted by GH regarding the `cryptiles` package. By updating `requests` we no longer pull in `cryptiles` at all. Is this the best way? I guess my only question is about adding it to "dependencies" since AFAIK it is a second order dependency.
=> update requests min version

.gitignore, bokeh/application/handlers/tests/test_notebook.py, bokeh/command/tests/test_util.py, bokeh/core/tests/test_templates.py, bokeh/io/tests/test_util.py, bokeh/models/tests/test_sources.py, bokeh/server/tests/test_server.py, bokeh/util/compiler.py, bokeh/util/tests/test_browser.py
Python version      :  3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)]
IPython version     :  6.5.0
Bokeh version       :  1.0.0dev6-14-g463049309
BokehJS static path :  g:\pythonworkspace\bokeh\bokeh\server\static
node.js version     :  v8.9.3
npm version         :  6.4.1
===== 4 failed, 2999 passed, 698 deselected, 1 warnings in 106.19 seconds =====
=> Windows platform test corrections

bokeh/application/handlers/document_lifecycle.py, bokeh/application/handlers/lifecycle.py, bokeh/application/handlers/server_lifecycle.py, bokeh/application/handlers/tests/test_document_lifecycle.py, bokeh/document/document.py, bokeh/server/server.py, sphinx/source/docs/user_guide/server.rst
As described in #8247 this adds a way to define ``on_session_destroyed`` callbacks on the Document which are executed by a ``DocumentLifeCycleHandler`` which is added to all ``Application`` instances by default.
Two things that need to be decided before I'm happy with this:
* Naming of the `DocumentLifeCycleHandler`
* Who is responsible for adding the `DocumentLifeCycleHandler`, currently the `Server` adds this handler to all applications (at minimum it might want to check whether the application already has such a handler)
Once these items have been decided I'll add some tests and add a bit about this in the server docs.
=> Add DocumentLifeCycleHandler and Document.on_session_destroyed

examples/embed/server_session/templates/embed.html
`.html` files are git ignored under `examples` to prevent accidentally committing example output to the repo, but that cuts the opposite direction when adding HTML files is intended.
=> add missing embed tempate

sphinx/source/docs/user_guide/embed.rst
Issue #8160 stated that there was a mismatch in `{css,js}_ressources` both in `file.html` template and documentation.
PR #8161 fixed only the mismatch in `file.html` template.
This PR fixes the mismatch in the documentation.
Have a nice day!
fixes #8160
=> Fix {css,js}_resources block mismatch

bokehjs/src/lib/models/tools/tool_proxy.ts, bokehjs/test/models/tools/toolbar_box.coffee
Fixes missing icons on merged toolbars which use ToolProxy.
=> Add computed_icon getter to ToolProxy

bokehjs/src/lib/core/ui_events.ts, bokehjs/src/lib/models/layouts/layout_dom.ts, bokehjs/src/lib/models/plots/plot_canvas.ts
As promised in the [memory leak issue discussion](https://github.com/bokeh/bokeh/issues/5355), here is a PR for properly removing event listeners registered by BokehJS views on **window** and **document** global objects.
Because they constitute an active reference to the view, these listeners prevent garbage collection of most (all ?) of a Bokeh document's memory footprint after it has been entirely removed from the DOM.
I don't know what kind of testing is expected from such a PR. All I can say is these changes don't evidently break bokehjs' behavior and now re-running again and again the same cell in Jupyter Notebook shows the memory still increasing short-term, but being properly garbage-collected afterwards.
=> Remove global event listeners when deleting views to prevent memory leaks

bokeh/models/tickers.py, bokehjs/src/lib/models/tickers/fixed_ticker.ts
This PR attempts to add an optional minor_ticks option for FixedTicker. 
Subsequently, one should be able to pass FixedTicker a list of minor tick values analogous to how one would pass a list of major tick values. 
```python
p.axis.ticker = FixedTicker(ticks=[0, 5, 10], minor_ticks=[1,2,3,4, 6,7,8,9])
```
past behavior should still work because `minor_ticks=[]` by default
I am new to typescript, so please doublecheck the work! Not sure where else to update (e.g. in [tests](https://github.com/bokeh/bokeh/blob/master/bokehjs/test/models/tickers/fixed_ticker.ts) or in docs)
```python
from bokeh.io import show, output_file, output_notebook
from bokeh.models.tickers import FixedTicker
#data (will not be plotted!)
major_data = [0.1, 1, 10, …
```
=> add minor ticks "minor_ticks=" option in FixedTicker

bokeh/layouts.py, examples/plotting/file/histogram.py, examples/plotting/file/legend.py, examples/plotting/file/rect.py
This PR removes unnecessary arbitrary arg/kwarg processing in `gridplot` in favor of standard Python optional args 
Now get for unknown arg:
```
TypeError: gridplot() got an unexpected keyword argument 'n_cols'
```
=> use standard args for gridplot

scripts/ci/install, tests/integration/widgets/test_password_input.py, tests/integration/widgets/test_text_input.py
This PR removes the package pin for Pillow now that Pillow 5.3 is available, and also disables a flaky integration test.
=> Small build tasks

bokeh/_testing/util/api.py
issues: fixes #8300
new output:
```
self = <bokeh._testing.util.api.verify_all.<locals>.Test___all__ object at 0x1168ebd68>
def test___all__(self):
if isinstance(module, string_types):
mod = importlib.import_module(module)
else:
mod = module
assert hasattr(mod, "__all__")
>       assert mod.__all__ == ALL, "for module %s, expected: %r, actual: %r" % (mod.__name__, set(ALL)-set(mod.__all__), set(mod.__all__)-set(ALL))
E       AssertionError: for module bokeh.core.properties, expected: {'Angdle'}, actual: {'Angle'}
```
=> improve verify_all fail message

bokeh/models/graphs.py, bokeh/models/tests/test_graphs.py
=> update from_networkx for fixed layout

bokehjs/src/lib/models/tools/toolbar_box.ts, bokehjs/test/models/tools/toolbar_box.coffee
Bokeh helpfully supports the option of deduplicating tools in a layout by creating tool proxies for any tool type that is added more than once. This is appropriate for tool types such as pan/zoom/save/help etc. but not for others such as the drawing tools.
For now this PR explicitly skips multi-gesture tools which is the ``event_type`` used by the drawing tools and ``CustomAction`` tools. This may not be the best approach and/or may not cover all the tool types that should be skipped during deduplication. 
I don't think you will generally want multiple navigation tools (BoxZoomTool, PanTool, WheelZoomTool, WheelPanTool, ZoomInTool), select tools (BoxSelectTool, LassoSelectTool, PolySelectTool , TapTool), inspection tools (HoverTool, CrosshairTool), or action tools (SaveTool, UndoTool, …
=> Only deduplicate some tool types

bokeh/models/sources.py, bokehjs/src/lib/models/sources/ajax_data_source.ts, bokehjs/src/lib/models/tools/toolbar_base.ts, bokehjs/test/models/sources/ajax_data_source.coffee, examples/howto/ajax_source.py
This small PR adds an `adapter` property to `AjaxDataSource` that accepts a `customJS` that will convert any arbitrary JSON response into Bokeh CDS data format. The `ajax_source.py` is updated and simplified to demonstrate this new fearture.
=> Add adapter property to AjaxDataSource

bokeh/document/document.py, bokeh/themes/__init__.py, bokeh/themes/_caliber.py, bokeh/themes/_dark_minimal.py, bokeh/themes/_light_minimal.py, bokeh/themes/theme.py, scripts/ci/install, sphinx/source/docs/reference/themes.rst
This PR moves the YAML theme definitions into strings in python modules, rather than external files. This is to support better integration with "freeze" tools like cx_freeze and pyinstaller. As a side effect it probably shaves a small amount off general import times 
This PR also pins sphinx to 1.7 as it was noticed 1.8 results in broken static image links.
=> load themes from python modules instead of json files

bokeh/application/handlers/directory.py, bokeh/command/subcommands/serve.py, bokeh/core/has_props.py, bokeh/embed/util.py, bokeh/io/export.py, bokeh/server/contexts.py, bokeh/server/tornado.py, bokeh/server/views/ws.py
Noticed in test output that `log.warn` is deprecated. This PR replaces all instances with `log.warning` as indicated.
=> replace log.warn with log.warning

bokeh/util/compiler.py
Simplified implementation for loading cached compiled models until we settle on a public API. Works by allowing users to set a cache hook which should return the compiled code given the uncompiled implementation. Offers public methods to get and set this hook, available as:
```
bokeh.util.compiler.get_cache_hook
bokeh.util.compiler.set_cache_hook
```
Also splits the compilation code a bit so that it is easier for an external library to pre-compile a model and load it in the cache hook it registers.
=> Allow loading cached compiled models using hook

bokeh/core/property/color.py, bokeh/core/property/tests/test_color.py
Fairly heavy-weight regex that allows the Color property to accept rgb(a) strings like:
```python
'rgb(10, 20, 30)'
'rgba(10, 20, 30, 1)'
'rgba(10, 20, 30, 0.5)'
```
Includes checks for bounds of both RGB and A values. Fixes the bug I observed in #4096, https://github.com/ioam/holoviews/issues/2777 and https://github.com/ioam/holoviews/issues/3107.
Would of course be happy to replace it with something simpler, e.g. a combined regex:
```
rgba?\(((25[0-5]|2[0-4]\d|1\d{1,2}|\d\d?)\s*,\s*?){2}(25[0-5]|2[0-4]\d|1\d{1,2}|\d\d?)\s*,?\s*([01]\.?\d*?)?\)
```
but that would not error on ``rgba(0, 0, 0)`` and ``rgb(0, 0, 0, 0.5)``, but apparently even github renders those correctly, so maybe that's not an issue.
=> Color property now accepts css rgb(a) strings

bokehjs/src/lib/models/glyphs/ellipse_oval.ts
Not sure how we can currently test this effectively, absent view-models, but open to suggestion. Otherwise I'd like to embark on a plan of moving view logic into testable view models in 2019.
=> pass _angle value when rendering legends for EllipseOval

bokeh/application/handlers/document_lifecycle.py, bokeh/application/handlers/tests/test_document_lifecycle.py, bokeh/document/document.py
Handles exceptions in Document.on_session_destroyed callbacks and discards them once they have been processed.
=> Improved handling of DocumentLifeCycleHandler callbacks

bokehjs/src/lib/models/markers/scatter.ts
This skips rendering the legend glyph entry if the scatter glyph is empty. Alternatively we could simply default to a circle but that may be misleading and the legend does update if you subsequently set or stream data to the scatter.
Here is an image of a plot with two scatter glyphs each with empty data:
and then I set some data:
Not sure what the best way is to test actual rendering of plots.
=> Skip rendering legend glyph for empty scatter

sphinx/source/docs/user_guide/server.rst
In section about Apache reverse proxy there was a wrong module name: `http_proxy` changed to `proxy_http`.
=> Update server.rst: wrong apache module name

sphinx/source/docs/user_guide/bokehjs.rst
Call to gridplot needs a nested list as argument. Should fix #8428.
=> Fix gridplot example with pie charts in BokehJS docs

bokehjs/src/lib/models/widgets/tables/cell_formatters.ts, examples/app/dash/main.py, examples/integration/widgets/data_table_customization.py
The text_align attribute of table cell text's span is set but does not take effect because it does not fill the container width of table cell's div.  This trivial fix is in the base StringFormatter which also addresses NumberFormatter, allowing numeric columns/cells to be defined with proper right-alignment.
=> Fix text_align in table cell formatters

bokeh/models/markers.py, bokehjs/src/lib/models/glyphs/circle.ts
Fixes: #626
This PR completes the functionality proposed in #626 which was partially addressed in commit ee8de73.
**Description:**
This PR adds two additional dimensions to radius_dimension, 'min' and 'max'
'min' dynamically selects either the x and y dimension off which to calculate the radius value, choosing whichever results in a smaller size, while 'max' does the same thing but chooses the maximum.
=> Add min/max radius dimensions

sphinx/source/docs/contribute.rst, sphinx/source/docs/dev_guide/documentation.rst, sphinx/source/docs/dev_guide/env_vars.rst, sphinx/source/docs/dev_guide/server.rst, sphinx/source/docs/dev_guide/setup.rst, sphinx/source/docs/installation.rst, sphinx/source/docs/user_guide.rst, sphinx/source/docs/user_guide/annotations.rst, sphinx/source/docs/user_guide/bokehjs.rst, sphinx/source/docs/user_guide/categorical.rst, sphinx/source/docs/user_guide/data.rst, sphinx/source/docs/user_guide/embed.rst, sphinx/source/docs/user_guide/extensions.rst, sphinx/source/docs/user_guide/extensions_gallery/latex.rst, sphinx/source/docs/user_guide/extensions_gallery/widget.rst, sphinx/source/docs/user_guide/interaction/callbacks.rst, sphinx/source/docs/user_guide/server.rst
Fixes various typo/spelling/formatting mistakes in the documentation. Other than fixing things as I read through, I mostly used a spellchecker to find mistakes, so there may be more I missed.
=> Spelling and formatting fixes in docs

sphinx/source/docs/user_guide/examples/interaction_callbacks_for_selections.py
Updates documentation example of lasso selection to make it work
with bokeh version 1.0.1. Thank you @philippjfr for pointing to/adding solution.
Ref: https://github.com/bokeh/bokeh/issues/8393
Tested new example and produces expected figure:
=> Update lasso example documentation (#8393)

examples/app/export_csv/download.js
Export csv now discovers column heading names in data table before downloading csv file.
@jni went to some effort to work out how we could do this for datatables with arbitrary numbers of columns and column headings. It's a very neat solution.
=> Bokeh export csv example now discovers column heading names

sphinx/source/docs/user_guide/embed.rst
in the introductory paragraphs of ["Embedding Plots and Apps"](https://bokeh.pydata.org/en/latest/docs/user_guide/embed.html#embedding-plots-and-apps) on the distinction between bokeh apps and standallone HTML, IMHO the text reads better if "to execute that execute" is changed to just "that execute":
>These are Bokeh documents that are backed by a Bokeh Server. In addition to all the features of standalone documents, it is also possible to connect events and tools to real Python callbacks, ~to execute~ that execute in the Bokeh server. …
=> DOC: remove extra "to execute" from embed

bokeh/util/sampledata.py
This changes the S3 bucket to use one under the control of the Bokeh AWS account. 
I had hoped to make a new bucket, rename the old `bokeh_data` bucket , then change the new bucket name to `bokeh_data`, so that the URL would not be different. However, this is no longer possible. AWS has restricted the namespace for buckets, new bucket names may no longer contain underscores at all. 
I have not changed or deleted the old bucket, and have no plans to, but cannot guarantee it will exist in perpetuity.
=> update sampledata bucket URL

bokehjs/src/lib/models/tools/edit/poly_draw_tool.ts
Straightforward fix the PolyDrawTool simply checks whether it is actually active before drawing vertices.
=> Disable show_vertices when PolyDrawTool inactive

examples/plotting/file/range_tool.py
This tiny commit fixes a typo in the range_tool.py example. It is my first pull request.
The contributing guidelines state that tests must be performed. I did not do any tests, because I only changed the name of one variable and made sure the code still runs fine.
=> Fix typo 'range_rool' in range_tool.py

LICENSE.txt, bokeh/tests/test___init__.py, bokehjs/LICENSE, tests/codebase/test_js_license_set.py
Moves the declaration of vendored JS libraries to the `bokehjs/LICENSE` file, which makes more sense. 
cc @dwt FYI for your reference
=> move BokehJS license details to bokehjs/LICENSE

bokeh/_testing/util/selenium.py, bokehjs/package-lock.json, bokehjs/package.json, bokehjs/src/lib/models/widgets/tables/data_table.ts, tests/codebase/test_code_quality.py, tests/integration/widgets/tables/test_cell_editors.py, tests/integration/widgets/test_copy_paste.py
Use slickgrid external copy paste manager to add copy paste support for bokeh datatables.
=> Enable copy paste for datatables

bokeh/_testing/util/examples.py, bokeh/themes/theme.py, bokeh/util/sampledata.py
Replaces all usage of `yaml.load` with `yaml.safe_load`
Checked codebase:
```
~/work/bokeh/bokeh bryanv/8541_yaml_safe_load
(base) ❯ grip yaml |grep load
266 :         examples = yaml.safe_load(f.read())
131 :                 json = yaml.safe_load(f)
109 :         config = yaml.safe_load(open(join(bokeh_dir, 'config')))
```
If there was anything else like `from yaml import load` it would show up in the above output.
=> use only yaml.safe_load

bokeh/application/handlers/notebook.py, bokeh/application/handlers/tests/test_notebook.py
First cut at addressing #8513.
Using this tiny notebook called 'Test.ipynb':
On master, running `bokeh serve --show Test.ipynb` gives you:
With this PR:
Right now this is a first cut. Things to think about:
```python
foo = 2
4 \
%foo
```
I suppose we could make an explicit blacklist of the most common magics to be safe?
=> Preprocessor to strip out IPython magics from notebooks

bokeh/application/handlers/notebook.py, bokeh/application/handlers/tests/test_notebook.py
This PR is an alternative fix to the one implemented in #8555. Based on a suggestion from @philippjfr, it seems like it might be best to always encode to utf8 as nbconvert is templated to always use that encoding.
=> Safer alternative fix for unicode notebook issue in Python 2

bokeh/util/compiler.py, bokeh/util/tests/test_compiler.py, bokehjs/make/linker.ts
If windows compile bokehjs => the path separator in bokeh.json is `\\` instead of `/`
Then when a custom module extension with lines like :
`import * as p from "core/properties"` 
is compiled it failed because available module in bokeh.json is `core\\properties`
=> Ensure compilation of custom model works with bokehjs compiled on win

scripts/ci/appveyor/install.ps1
Conda 4.6.1 is causing issues on Appveyor (https://github.com/appveyor/ci/issues/2822)
=> pin conda versions with CONDA_REQS on appveyor too

bokeh/client/session.py
In [documentation for bokeh.client.session](https://bokeh.pydata.org/en/latest/docs/reference/client/session.html) under ClientSession object, mysession and session objects should maybe be the same?
```
with pull_session(url=app_url) as session:
script = server_session(session_id=mysession.id, url=app_url)
return render_template("embed.html", script=script, template="Flask")
```
=> Possible typo in documentation for bokeh.client.session. 

bokeh/models/sources.py
Fixed a docstring typo as raised in #8589
=> #8589 Fixes docstring typo in patch method of sources.py

examples/custom/parallel_plot/parallel_plot.py, examples/custom/parallel_plot/parallel_reset.py, examples/custom/parallel_plot/parallel_reset.ts, examples/custom/parallel_plot/parallel_selection_tool.py, examples/custom/parallel_plot/parallel_selection_tool.ts
I am at a stage where I do not really think I can go on without any help
Current features
Feature wanted :
I think I need to replace Rect glyph for selection by BoxAnnotations. It will allow to change cursor when hovering. However if I know how to add one to the layout I didn't succeed to remove it.
[demo](https://xavartley.github.io/bokeh/parallel_plot)
=> Create custom example to plot parallel plot

bokehjs/src/lib/models/tiles/tile_renderer.ts, bokehjs/src/lib/models/tiles/tile_source.ts, bokehjs/test/models/tiles/tile_renderer.coffee
Upgrades ``TileSource`` attributes to properties and add events to clear cache and rerender when a property changes. Let me know if my assumption that attributes need to be properties to trigger model change events is wrong.
=> Invalidate TileSource cache on property changes

bokehjs/src/lib/models/sources/data_source.ts, sphinx/source/docs/user_guide/examples/interaction_callbacks_for_selections_lasso_mean.py, tests/integration/models/test_sources.py
The signals were set up to trigger when the `selected` model itself change (i.e. if it was replaced wholesale). This updates to watch changes on properties of the `Selection` (e.g. `indices`) This does not handle the case if a selection is in fact wholesale replaced but I would consider that unsupported and would support making the selection model read only in future releases.
=> Fix CDS callback property callbacks

bokehjs/src/lib/models/grids/grid.ts
There was an unnecessary `ctx.fill()` after the `ctx.fillRect(...)` to draw the bands. When the cross grid line color is `None` this actually supresses stroking and resetting some paths, and presumably this allowed a bad path accumulate for the `ctx.fill()`.
=> remove extraneous ctx.fill for bands

.travis.yml, scripts/ci/install, scripts/ci/install.build, scripts/ci/install.downstream, scripts/ci/install.test, scripts/ci/install.unit
This PR attempts to update conda and conda-build but also preserve Python 3.5 jobs, but switching to a dedicated non-root env for testing during install.
=> use test env for running CI jobs

examples/app/stocks/main.py
A line from an older version sneaked in the example. 
On change from selection runs in the following way now. 
ource.selected.on_change('indices', selection_change)
Related to the issue
fixes #8633
=> Fix app/stocks example

bokeh/command/subcommands/serve.py, bokeh/command/subcommands/tests/test_serve.py, bokeh/server/server.py, bokeh/server/tests/test_server.py, bokeh/server/tests/test_tornado.py, bokeh/server/tornado.py, bokeh/server/views/root_handler.py
This is a useful little feature in and of itself, but specifically I need it to set up a new demo site on Elastic Beanstalk without having to run nginx separately.
=> add --index option to specify site index template

bokehjs/src/lib/models/sources/cds_view.ts
This fixes the particular case of `CDSView.source`. The issue will be fixed completely in #8597.
fixes #8686
=> Connect CDSView.source's slots after late initialization

bokehjs/src/lib/core/dom.ts, tests/baselines/examples/plotting/file/css_classes
@philippjfr, can you try this out? This should resolve issue with unnecessary wrapping.
fixes #8654
=> Compute content size with subpixel precision

bokeh/models/annotations.py, bokeh/models/tests/test_annotations.py
I've changed the specs of `base`, `lower` and `upper` to a less restrictive `UnitSpec` as `DistanceSpec` did not permit negative values for these parameters. I'm not sure whether it would make sense to create a new spec class explicitly for this.
=> Change Whisker and Band parameters to UnitSpec

bokehjs/src/less/buttons.less
Updated test script to cover all buttons
```
from bokeh.io import show
from bokeh.layouts import widgetbox
from bokeh.models.widgets import Button
from bokeh.core.enums import ButtonType
buttons = [Button(label=x, disabled=True, button_type=x) for x in ButtonType]
show(widgetbox(*buttons))
```
Current output:
cc @mattpap @jsignell I think this looks pretty reasonable but open to suggestion
=> darken and desat disabled buttons

bokeh/application/handlers/directory.py
At the start of it's modify_doc, the directory handler checked it's `failed` property and returned immediately if it was true. The `failed` property checked the `failed` properties of the embedded `_main_handler` and `_lifecycle_handler`. Checking `_main_handler.failed` and bailing immediately meant that any failure in the user's script would never be cleared, and the bokeh server would have to be restarted. Now we only check `_lifecycle_handler.failed`, which we do want to bail on.
fixes #8577 
[wiki](https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-manageme …
=> Stops the directory handler from bailing inappropriately.

bokeh/colors/util.py, bokeh/core/tests/test_validation.py, bokeh/core/validation/__init__.py, bokeh/core/validation/check.py, bokeh/models/tests/test_callbacks.py, bokeh/tests/test_transform.py, sphinx/source/docs/reference/core/validation.rst
Implementing configurable warning silencer as suggested by @bryevdv: https://github.com/bokeh/bokeh/issues/8725#issuecomment-470586707.
```python
import bokeh
from bokeh.layouts import row
from bokeh.io import output_notebook, show
output_notebook(verbose=True)
empty_row = row([])
bokeh.core.validation.silence('EMPTY_LAYOUT')
show(empty_row) 
bokeh.core.validation.silence('EMPTY_LAYOUT', False)
show(empty_row)
```
=> Make warnings configurable

bokehjs/src/lib/core/util/math.ts, bokehjs/test/core/util/math.ts
This PR addresses #8742 by making `angle_between` be strict, i.e. it will return false if the `start` and `end` angles are identical. 
New result of MRE with this change:
For reference, as of this PR, `angle_between` is only used in the `wedge` and `annular_wedge` glyphs:
```
❯ grin angle_between
./core/util/math.ts:
17 : export function angle_between(mid: number, lhs: number, rhs: number, direction: Direction): boolean {
./models/glyphs/annular_wedge.ts:
9 : import {angle_between} from "core/util/math"
127 :       if (angle_between(-angle, -this._start_angle[i], -this._end_angle[i], direction)) {
./models/glyphs/wedge.ts:
10 : import {angle_between} from "core/util/math"
104 :       if (angle_between(-angle, -this._start_angle[i], -this._end_angle[i], direction)) {
```
=> make angle_between strict

bokehjs/src/lib/core/visuals.ts, bokehjs/test/core/visuals.ts
This PR generalizes the notion of whether a "visual" should be drawn or not. Currentlty only a single attribute (typically color, e.g. `fill_color`) is checked against `null` to determine whether canvas operations should be skipped or not. This removes the generic code that checks the single configured attribute, with an abstract `doit` property getter on the base, that is specialized for each visual subclass. New behavior is summarized below:
* fill: skip if color is null, or alpha is 0
* line: skip if color is null, or alpha or width is 0
* text: skip if color is null, or alpha is 0
The new code is more explicit and seems to be an improvement from a maintenance POV as well. 
Also it was noticed that the visual classes have almost no tests, despite being very low level and in use in many …
=> Specialize visuals 'doit' getters

bokehjs/src/lib/core/util/templating.ts, bokehjs/src/lib/models/glyphs/image.ts, bokehjs/src/lib/models/glyphs/image_base.ts, bokehjs/src/lib/models/glyphs/image_rgba.ts, bokehjs/src/lib/models/tools/inspectors/hover_tool.ts, examples/plotting/file/image.py, examples/plotting/file/image_rgba.py
As far as I can tell, this has been broken forever, possibly since the image glyphs were created. This PR removes the code that modifies the default bounds based on the spatial index, since these are already correct as-is. 
It might be nice to add some image or integration tests to verify this change. We could also update some of the gallery examples to not set ranges explicitly (but they would need to set `range_padding`  to 0 instead). 
Finally, I don't think things will behave well with `dw_units` or `dh_units` set to "screen" but things are clearly currently already broken in that case, by inspection. I would support deprecation being able to set units on these for 2.0 cc @bokeh/dev
=> compute image bounds correctly

bokeh/model.py, bokeh/models/plots.py, bokeh/models/tests/test_plots.py
- [ x] issues: fixes #8723 
- [ x] tests added / passed: added to test_bad_extra_range_name in models/tests/test_plots
Most significant change is a modified version of bokeh.model.collect_models. The new collect_filtered_models gets to reject a object *and* discontinue exploration of its children depending on a test function provided in the tests. The old collect_models now calls on the new function.
=> correcting validation for BAD_EXTRA_RANGE_NAME (#8723)

bokehjs/src/lib/models/widgets/spinner.ts, tests/integration/widgets/test_spinner.py
@xavArtley @mattpap  please comment. I understand what the logic in the older version was for, but I am not sure why it is necessary. Setting min/max/step on the input will already keep the spinner from going outside min/max. We just need to set the value carefully by counting significant digits of step, which I have now done explicitly with a function (an ugly one, but it is clear what it is for). 
We can certainly consider revisiting the logic later, but with this code, the example in the issue and several variants all perform exactly as I would expect them to. This is explicitly a big improvement, so I would like to merge this for 1.1 (I did realize that the snapping of 8 to 8.2 with (min, max, step) == (1, 20, 0.3) is instrinsic to the HTML element operation, not due to our code. So …
=> simplify spinner logic

bokeh/application/application.py
This pull request fixes a small bug in application.py, causing the application to crash with a cryptic error, by trying to index `kwargs.keys()`.
It is probably a leftover from Python 2 times.
=> Fixes trying to index dict_keys

bokehjs/make/prelude.ts, bokehjs/make/tasks/all.ts, bokehjs/make/tasks/index.ts, bokehjs/package-lock.json, bokehjs/package.json, bokehjs/test/models/glyphs/glyph_utils.ts
Upgrades the compiler, fixes `npm audit` complaints and resolves an issue with bokehjs integration tests after PR #8782.
=> Upgrade to TypeScript 3.4

bokeh/models/tools.py, bokehjs/src/lib/models/tools/gestures/range_tool.ts, bokehjs/test/models/tools/gestures/range_tool.ts, examples/plotting/file/range_tool.py, tests/integration/tools/test_range_tool.py
This is WIP, intend to add both unit and integration tests, as well as refactor complicated and duplicated code in *range_tool.ts*.
* dragging the box will function if one side of the range is out of bounds
* dragging one side over the other will automatically flip the range
* box annotation is clipped wnen a side is out of bounds
=> Fix range tool interaction issues

bokehjs/src/lib/core/layout/layoutable.ts
I'm not particularly happy how aspect management works right now, but at least this fixes `scale_height` sizing mode. I will need to revisit this code later on.
fixes #8821
=> Improve aspect management with scale_height mode

bokeh/_testing/util/selenium.py, bokehjs/src/less/menu.less, bokehjs/src/lib/models/widgets/autocomplete_input.ts, tests/integration/widgets/test_autocomplete_input.py
cc @danielrmeyer @mattpap 
This is a WIP PR to start discussion. This PR implements the following behaviour: when an autocomplete menu is opened, the first item starts off highlighted. The arrows keys can be used to move the highlighted element up and down. Hitting enter with an open menu sets the value to the highlighted element. 
As a consequence, it is not possible to enter values outside the completions list. Is this desirable? What about the fact that the initial value is not validated, Should we issue a warning or even an exception if it is not? Or should users be able to explicitly enter non-completion values (possibly as a mode?)
Assuming we like this behvaivour (or get to a point where we do) I will add integration tests.
=> add keys support to autocomplete

.gitignore
My goal is to have `.gitignore` files reduced to the bare minimum. Anything that's not project related (so e.g. editor/IDE temporary files) should be configured locally by the user. All entries (or groups of entries) must have an annotation why we ignore or what generate those (a good example is `.cache/`). If entries are specific to a subdirectory, they should be moved to a specific `.gitignore` file.
fixes #8433
=> Clean up .gitignore files

bokeh/io/export.py
This PR enables Firefox to be used as a webdriver by disabling logs. 
It can then be used like this:
```
from selenium.webdriver import Firefox, FirefoxOptions
options = FirefoxOptions()
options.headless = True
webdriver = Firefox(options=options)
export_png(item, path, webdriver=webdriver)
```
It _may_ be a starting point to fix this issue: https://github.com/bokeh/bokeh/issues/8176
=> Fix the exports when using Firefox as a webdriver.

examples/app/crossfilter/main.py
Line 55 `len(set(df[color.value])) > N_SIZES` should be `len(set(df[color.value])) > N_COLORS`
=> Update main.py in example crossfilter

examples/howto/server_embed/README.md, examples/howto/server_embed/tornado_embed.py
The examples in server_embed have requirements that may not be apparent to new users. This README should help avoid confusion.
=> Create README to explain server_embed usage

bokehjs/src/lib/models/glyphs/image_url.ts
This pull request contains an easy fix to issue #8889. 
I removed the error causing if statement, since the image will be tested to not be null 
before rendering anyway.
=> #8889 fixed, removed unnecessary clause

examples/plotting/file/stacked_area.py
Updates the  stacked_area.py example to show how to display the legend with entries in the same order as the stacked glyphs.
=> Enable the legend for the stacked area example

bokeh/layouts.py, bokeh/tests/test_layouts.py
This PR passes the `kwargs` given to `layout()` down to the underlying `row()` or `column()` calls in `bokeh.layouts`.  This fixes the behavior described in #8903.
=> pass layout kwargs to underlying objects

bokeh/models/widgets/sliders.py, bokehjs/src/lib/models/widgets/abstract_slider.ts, examples/app/clustering/main.py, examples/howto/layouts/dashboard.py, examples/plotting/file/color_sliders.py, examples/plotting/file/slider.py, examples/plotting/file/slider_callback_policy.py, sphinx/source/docs/user_guide/examples/extensions_example_widget.py, sphinx/source/docs/user_guide/examples/interaction_callbacks_for_widgets.py, tests/integration/widgets/test_slider.py
This adds `value_throttled` to sliders, which obeys the callback policy for both JS and Python callbacks. Examples are updated to use this where appropriate, and additionally all slider examples are updated to use `value` or `value_throttled` for callbacks instead of the deprecated `callback` property.
=> add value_throttled property to sliders

bokeh/model.py, bokehjs/src/lib/core/signaling.ts, bokehjs/src/lib/model.ts
This PR ensures that when ``js_on_change`` is called a ``ModelChangedEvent`` is triggered and the callbacks are updated on the frontend. The main problem I'm currently facing is that I haven't yet figured out how to disconnect previous callbacks since at least in theory callbacks could be deleted as well as added. If we don't expect them ever to be deleted we could also simply keep track of callbacks that have been connected and skip them the second.
=> Ensure that js_property_callbacks can be updated

bokeh/models/plots.py, sphinx/source/docs/releases/2.0.0.rst
Picking a small issue to get started. This is mostly to prove out running CI on the long-running `landing-2.0` branch.
=> remove vestigal plot symmetry options

bokeh/io/export.py, conda.recipe/meta.yaml
Turns out pillow had already been added as a dependency at some point. Accordingly, did not add migration note to release notes. However, did clean up some cruft that checked imports or explicitly listed a test dep.
=> assume pillow installed

.travis.yml, bokeh/command/subcommands/serve.py, bokeh/command/subcommands/tests/test_serve.py, bokeh/server/server.py, bokeh/server/tests/test_server.py, bokeh/server/tornado.py, bokeh/server/views/tests/test_ws.py, bokeh/server/views/ws.py, bokeh/util/tornado.py, conda.recipe/meta.yaml, setup.py, sphinx/docserver.py, sphinx/source/docs/releases/2.0.0.rst
cc @bokeh/core I'd like to check with folks before just merging this one. By the time the 2.0 landing branch is merge, Tornado 5.0 will be ~18 months old. I am definitely strongly +1 on making 5.x the new minimum version as it integrates very naturally with `asyncio` which I suspect will be valuable to more users over a fairly short time span.
=> Make Tornado 5 the minimum version

bokeh/util/serialization.py
This check only applied to Numpy < 1.7 and that's already our min
=> remove legacy datetime check

bokeh/util/tests/test_compiler.py
Calling `show` in a test opens a browser tab on test run which is super annoying. Confirmed `save` failed when it should and passes when it should.
=> don't call show in tests

bokeh/core/property/bases.py, bokeh/core/property/descriptors.py, bokeh/core/property/instance.py, bokeh/core/property/tests/test_bases.py, bokeh/core/property/tests/test_instance.py, bokeh/models/graphs.py, bokeh/models/sources.py, bokeh/models/tests/test_sources.py, examples/integration/glyphs/selection_nonselection.py, examples/integration/widgets/data_table_preselection.py, sphinx/source/docs/releases/2.0.0.rst
`s.selected` is now read only
`s1.data = s2.data` now throws an error
=> Restrict CDS property changes

bokehjs/src/lib/core/util/templating.ts, bokehjs/test/core/util/templating.ts, examples/plotting/file/customjs_hover.py, sphinx/source/docs/releases/2.0.0.rst, sphinx/source/docs/user_guide/examples/tools_hover_tooltip_formatting.py, sphinx/source/docs/user_guide/tools.rst
This PR changes the specification format for hover formatters to require the keys in the `formatters` dict to strictly match the format from the tooltips, including any `@` or `$` prefix:
```
hover.tooltips = "@foo{%s}   @{foo bar}{0.00}   $x{%F}"
hover.formatters = {
"@foo"       : "printf",
"@{foo bar}" : "numeral",
"$x"         : "datetime",
}
```
Previously, just a column name e.g. "foo" was expected. 
This change means that formatting specification can now apply uniformly to "special variables" such as "$x" and also reduces confusion by making it clear that the column and special variable names are what formatters apply to. (There were several support requests due to attempting to match up labels instead)
This PR also simplifies and corrects some broken logic int he templating code.
=> more explicit hover formatter specs

bokehjs/src/lib/models/widgets/abstract_slider.ts
We don't want the `toggleTooltip` happening when tooltip is set to `false`.
This solves errors with accessing style attribute of a `null`.
- [n/a] tests added / passed
- [n/a] release document entry (if new feature or API change)
=> Toggle tooltip only when it is enabled in Slider

bokeh/core/properties.py, bokeh/core/property/pandas.py, bokeh/core/property/tests/test_pandas.py, bokeh/core/tests/test_properties.py, bokeh/models/sources.py, bokeh/models/tests/test_sources.py, examples/app/population.py, examples/app/stocks/main.py
@mattpap it occurred to me that we could possibly tighten up the pandas "properties" more by making them specialized to raise errors if they were actually added to models. But I think the documentation is sufficient, unless you have a strenuous objection.
=> allow source.data set from pandas types

bokeh/_testing/util/selenium.py, bokehjs/src/lib/models/widgets/tables/cell_editors.ts, bokehjs/src/lib/models/widgets/tables/data_table.ts, tests/integration/widgets/tables/test_copy_paste.py
Tests coming tomorrow. The issues here:
* permuted indices can end up re-ordered from row order, they just need to be sorted so that the rows that are selected are copied out in order
* `container` is a jQ object, `appendChild` does not exist (use `append`)
=> fix table selection issues

bokeh/util/sampledata.py
This PR changes the sampledata download URL to point at a new CDN distribution at http://sampledata.bokeh.org  This should be both faster as well as cheap for the project (a large chunk of S3 egress is for running `bokeh sampledata` on CI jobs)
Note that HTTP is used in stead of HTTPS because HTTP requests are cheaper on cloudfront and there is no reason AFAIK that it should matter (no data to protect, apps running, or javascript)
=> use sampledata.bokeh.org CDN

scripts/issues.py
Our automation is not really set up to handle long-running parallel dev branches like `landing-2.0`. This PR excludes issues and PRs with that tag from `CHANGELOG` generation. Right before 2.0 we will need to explicitly *add* them (even overriding the `-p <tag>` option) and then after 2.0 restore things to their original state.
=> exclude landing-2.0 issues from changelog for now

bokeh/models/widgets/inputs.py, bokehjs/src/lib/models/widgets/file_input.ts, examples/plotting/file/file_input.py, tests/baselines/examples/plotting/file/file_input
Replaces the `file` attribute in the FileInput widget with separate `value` and `mime_type` attributes. Also adds a `filename` attribute.
=> extend FileInput with more attributes.

bokeh/models/widgets/inputs.py, bokehjs/src/lib/models/widgets/text_input.ts
Adds the possibility to use the "input" event for the TextInput event listener. The "change" event is still default, and the "input" event is accessible by setting the new variable "wait_commit" as False.
=> New event listener for TextInput

sphinx/source/docs/installation.rst
It is evidently impossible to adequately convey the ephemeral nature and absence of any guarantees around dev build resources, which can lead to confusion and problems for users. Additionally, looking back, the actual benefit from making public announcements of dev builds (in terms of actionable feedback received from the public at large) has been negligible over the years. This PR removes public-facing instructions for installing from the `bokeh/dev` channel, and in the future no announcements will be made when dev builds or rcs are published to it.
=> Remove Dev Build installation instructions

conda.recipe/meta.yaml, scripts/ci/build, scripts/ci/install, scripts/deps.py
`deps.py run` was not actually returning runtime dependencies from `setup.py` This was exposed in `landing-2.0` where "pillow? was moved from test to runtime deps. It was no longer getting installed and tests were failing on PIL imports. (It's possible recent pyyaml and conda-build revs changed something that worked previously)
Also bumps default Python version, if unspecified, to 3.7 (e.g. build phase)
=> compute runtime deps correctly

sphinx/source/conf.py
Get the name of the version from the git tag instead of using Read the
Docs version's name.
This fixes the problem when the commit is a tagged and Read the Docs
is building `latest` version for example. With this commit, we are
setting the CDN version to use as the tag name instead of the Read the
Docs version's name, which is the correct name.
=> Use BokehJS from CDN when the commit is tagged

.travis.yml, bokeh/command/subcommands/serve.py, bokeh/command/subcommands/tests/test_serve.py, bokeh/core/json_encoder.py, bokeh/io/notebook.py, bokeh/io/output.py, bokeh/io/saving.py, bokeh/io/state.py, bokeh/io/tests/test_output.py, bokeh/io/tests/test_saving.py, bokeh/resources.py, bokeh/server/server.py, bokeh/server/tests/test_server.py, bokeh/settings.py, bokeh/sphinxext/_templates/settings_detail.rst, bokeh/sphinxext/bokeh_settings.py, bokeh/sphinxext/templates.py, bokeh/tests/test_resources.py, bokeh/tests/test_settings.py, bokeh/util/browser.py, bokeh/util/serialization.py, bokeh/util/tests/test_browser.py, scripts/ci/install, sphinx/source/conf.py, sphinx/source/docs/dev_guide/env_vars.rst, sphinx/source/docs/reference/settings.rst, sphinx/source/docs/user_guide/server.rst
This one went a bit afield. I finally got fed up with the existing `bokeh.settings` and inconsistencies in settings preference order, that I redid the whole thing so that:
* the order for checking settings is documented and consistent 
* settings can be auto-documented 
* support for settings config files
There's still work to do (for 2.0 to make sure this new settings system is applied consistently and that there are conventions about who has responsibility for what.
=> Add SSL termination and revamped settings system

.travis.yml
As the title says this PR removes the slack notification token from the .travis.yml since it causes a lot of clutter and most core developers no longer have access to the Slack feed it is posted to anyway.
=> Remove the slack notification token from .travis.yml

bokehjs/src/lib/models/sources/geojson_data_source.ts, bokehjs/test/models/sources/geojson_data_source.ts
OP test code
```
import geopandas as gpd
from bokeh.palettes import Reds
from bokeh.models import GeoJSONDataSource, LinearColorMapper
from bokeh.plotting import figure, show
geodf = gpd.read_file("provinces.geojson")
geodf.loc[6, 'index'] = np.nan
print(geodf)
color_mapper = LinearColorMapper(palette=Reds[9][::-1], nan_color='black')
p = figure()
geo_source = GeoJSONDataSource(geojson=geodf.to_json())
p.patches('xs', 'ys', fill_alpha=1,
fill_color={'field': 'index', 'transform': color_mapper},
line_color='white', line_width=0.5,
source=geo_source)
show(p)
```
Now produces:
=> ensure null values in geoJSON are rendered as NaNs in the data source

bokehjs/src/lib/core/util/math.ts, bokehjs/test/core/util/math.ts
This PR makes sure that `angle_norm` only returns 0 for initial angle=0, and 2pi for any positive or negative multiples. Additionally d=2pi is special cased in `angle_between` since the direction is degenerate in that case. 
Results of OP example as well as current GH repo example:
=> handle angle between 0, 2pi correctly

sphinx/source/docs/user_guide/export.rst
The sentence seems outdated because the new notation is `output_backend = 'webgl'` and saving plots as PNG with `output_backend = 'canvas'` works well.
=> Outdated sentence removed from docs

bokeh/application/handlers/code_runner.py, bokeh/client/session.py, bokeh/command/tests/test_util.py, bokeh/command/util.py, bokeh/core/enums.py, bokeh/core/json_encoder.py, bokeh/core/property/dataspec.py, bokeh/document/document.py, bokeh/io/state.py, bokeh/models/layouts.py, bokeh/plotting/figure.py, bokeh/plotting/helpers.py, bokeh/sampledata/les_mis.py, bokeh/server/tornado.py, bokehjs/src/lib/core/util/refs.ts, bokehjs/src/lib/models/annotations/label.ts, bokehjs/src/lib/models/glyphs/webgl/markers.ts, bokehjs/src/lib/models/tickers/fixed_ticker.ts, bokehjs/src/lib/models/tools/tool.ts, sphinx/source/docs/dev_guide/server.rst, sphinx/source/docs/dev_guide/setup.rst, sphinx/source/docs/releases/0.12.15.rst, sphinx/source/docs/releases/0.12.5.rst, sphinx/source/docs/releases/1.1.0.rst, sphinx/source/docs/user_guide/categorical.rst, sphinx/source/docs/user_guide/plotting.rst, sphinx/source/docs/user_guide/server.rst
Fixed some typos in docs, comments, string literals, etc.
=> Fix typos in docs, comments, etc

sphinx/source/docs/user_guide/export.rst
I think the "additional dependency" `pillow` should be removed from this section because it is already a bokeh dependency
=> Pillow is already a bokeh dependency

bokeh/_testing/util/filesystem.py, bokeh/application/application.py, bokeh/command/subcommands/serve.py, bokeh/command/subcommands/tests/_dummy_auth.py, bokeh/command/subcommands/tests/test_serve.py, bokeh/server/auth_provider.py, bokeh/server/contexts.py, bokeh/server/tests/test_auth_provider.py, bokeh/server/tests/test_contexts.py, bokeh/server/tests/test_tornado.py, bokeh/server/tornado.py, bokeh/server/views/auth_mixin.py, bokeh/server/views/doc_handler.py, bokeh/server/views/root_handler.py, bokeh/server/views/session_handler.py, bokeh/settings.py, bokeh/tests/test_settings.py, examples/howto/server_auth/README.md, examples/howto/server_auth/app.py, examples/howto/server_auth/auth.py, examples/howto/server_auth/login.html, sphinx/source/docs/reference/server/auth_provider.rst, sphinx/source/docs/reference/server/views.rst, sphinx/source/docs/user_guide/server.rst
This is WIP, would like to get some early feed back on how the usage feels.
You can now supply an auth modue, e.g. 
```
import tornado
from tornado.web import RequestHandler
def get_user(request_handler):
return request_handler.get_secure_cookie("user")
login_url = "/login"
class LoginHandler(RequestHandler):
def get(self):
try:
errormessage = self.get_argument("error")
except:
errormessage = ""
self.render("login.html", errormessage=errormessage)
def check_permission(self, password, username):
if username == "bokeh" and password == "bokeh":
return True
return False
def post(self):
username = self.get_argument("username", "")
password = self.get_argument("password", "")
auth = self.check_permission(password, username)
if auth:
self.set_current_user(username) …
```
=> Auth features for server

bokehjs/src/lib/models/glyphs/image_base.ts
This ensures that the `ImageIndex` generated by hover correctly inverts the indexes when the axis range is inverted. The initial attempt at fixing this (https://github.com/bokeh/bokeh/pull/8031/) did not invert the index.
=> Fixed image hover value on inverted axes

bokeh/sphinxext/_templates/palette_group_detail.html, sphinx/source/docs/reference/palettes.rst
This PR fixes two issues with the `bokeh.palettes` documentation pages:
* palette names were at `<h2>` which put them above the enclosing `<h3>` section headers. They are now `<h4>` which will play much better with the upcoming search crawler
* Functions entries were duplicated at the bottom due to `:members:` (we explicitly call autofunction earlier) This has been removed
=> fix structure issues in palette docs

scripts/build_upload.py
All assets with the path prefix in Amazon Cloudfront
CDN are invalidated in its cache.
=> Invalidate assets in folder and subfolders

bokeh/embed/standalone.py, bokeh/resources.py, sphinx/source/docs/installation.rst, sphinx/source/docs/user_guide/embed.rst, sphinx/source/docs/user_guide/quickstart.rst
Most browsers will not load http scripts from https pages. A few links were already using https, but some were not. http://cdn.pydata.org redirects to https://cdn.pydata.org so the loaded scripts will be the same.
=> Consistently use https protcol for cdn.pydata.org URLs

bokeh/server/django/__init__.py
Currently channels in only availeble on pip, but not conda.
Thus the conda install mentioned in the developer guide will not install it.
To run pytest -m codebase (mentioned in the developer guide) to be added as
git pre-commit hook will fail, giving first-time-contributers a bad experience
Point the users to install it via pip instead
=> Improve error message if import of channels fails.

bokehjs/src/compiler/prelude.ts
This was introduced in the compiler/extensions PRs. For now I copied the license into the prelude module, because making the import work is too much at this point.
=> Include license in bokehjs bundles

bokeh/embed/bundle.py
This is a quick fix that affects only new-style extensions. Proper solutions include allowing lazy module loading in bokehjs and redesign of resource management with extension (among other things) in mind, both which I intend to do for 2.0.
fixes #9343
=> Resolve all dependencies of an extension

scripts/issues.py
Reverts bokeh/bokeh#9082
Now that `landing-2.0` is merged this temporary measure should be reverted.
=> Revert "exclude landing-2.0 issues from changelog for now"

setup.py
This is necessary to support some advanced types that were introduced after Python 3.6. This dependency was supposed to be added in an earlier PR, but somehow got removed. CI doesn't fail, because `mypy` incidentally installs this package as well.
=> Add missing typing_extensions dependency

bokeh/client/session.py, bokeh/command/subcommands/serve.py, bokeh/embed/server.py, bokeh/server/auth_provider.py, bokeh/server/django/__init__.py, bokeh/server/django/consumers.py, bokeh/server/tornado.py, bokeh/sphinxext/bokeh_plot.py, bokeh/util/dependencies.py, examples/app/gapminder/main.py, examples/app/stocks/main.py, examples/embed/arguments/bokeh_server.py, examples/models/file/trail.py, examples/plotting/file/histogram.py, examples/plotting/file/us_marriages_divorces_hover.py, sphinx/source/conf.py, tests/unit/bokeh/io/test_export.py, tests/unit/bokeh/io/test_webdriver.py, tests/unit/bokeh/test_ext.py
Removing some last Python 2 bits. What remains to change is:
- `bokeh/colors/util.py`
When Python2 support is dropped, this will no longer be necessary.
- `bokeh/server/auth_provider.py`
TODO (bev) make this an ABC but wait until Bokeh 2 / drop Python 2.7
Those can be addressed in separate PRs, especially that I'm not sure what to do about both cases. I suppose use `Enum` in the former. However, the later is not a good candidate for using abstract classes, given the choice of implementation of different methods.
addresses #8666
=> Remove last Python 2 compatibility bits

bokeh/models/tools.py
Small change to documentation to reflect that issue #7419 is still open
=> Include step in the list of glyphs that HoverTool does not work with

bokeh/core/has_props.py, bokeh/events.py, bokeh/model.py, bokeh/sphinxext/bokeh_model.py, bokehjs/test/model.ts, scripts/spec.py, sphinx/source/docs/reference/model.rst, tests/unit/bokeh/embed/test_util__embed.py, tests/unit/bokeh/test_model.py, tests/unit/bokeh/test_objects.py, tests/unit/bokeh/test_resources.py, tests/unit/bokeh/test_themes.py
This PR drops `_MetaEvent` and `MetaModel`. I will work on `HasPropsMeta` separately as it's a bigger chunk of work.
addresses #8666
=> Replace metaclasses with `__init_subclass__`

bokeh/core/property/dataspec.py, bokeh/palettes.py, bokeh/plotting/helpers.py, examples/plotting/file/texas.py, sphinx/source/docs/releases/2.0.0.rst, tests/unit/bokeh/test_palettes.py
cc @p-himik @mattpap 
Needs a migration guide update and I would like to take the opportunity to add more tests.  I think there's typing things that can be refined as well. Just noting in passing some things we give up:
* can't call `palette.reverse()`
* palette groups are necessarily mutable (no built-in `frozendict`)
=> remove module hack for palettes

bokeh/embed/standalone.py, bokeh/resources.py
I'm at a bit of a loss, I really thought this had already been done. Not a huge deal, but annoying. Definitely would have preferred to have the last py2 release pulling from the actual `cdn.bokeh.org` location rather than using the redirect from `cdn.pydata.org` in perpetuity.
=> Update to cdn.bokeh.org

conda.recipe/meta.yaml
Guess this got overlooked when the python transpilation code was removed.
=> remove errant pscript dep

bokehjs/src/lib/models/mappers/log_color_mapper.ts, bokehjs/test/models/mappers/log_color_mapper.ts
Fixes #8724.
LogColorMapper would (for now) use plain old `Math.log`, which means it is consistent with LogTicker etc. and the current documentation. At least for the time being people won't unwittingly create plainly wrong colormaps anymore.
Long-term, I think @jlstevens' #8743 and #8765 would be much better suited to address issues such as scales blowing up when outliers near zero are present.
Before:
After:
```
from bokeh.io import show
from bokeh.models import ColorBar, LogTicker
from bokeh.models.sources import ColumnDataSource
from bokeh.models.mappers import LinearColorMapper, LogColorMapper
from bokeh.palettes import Viridis6, Viridis3
x = np.linspace(1e-4, 1e-1, num=2500)
y = np.random.normal(size=2500) * 2 + 5
source = …
```
=> Replace log1p by log in LogColorMapper

bokeh/models/glyphs.py, bokeh/plotting/helpers.py, bokehjs/src/lib/api/plotting.ts
Ni! This PR replaces `_pop_colors_and_alpha` with a new function `_pop_visuals` that works on all visuals in a more generic fashion. Details are documented in the code. As discussed in issue #8893, changes in property inheritance behavior should be noted in the release. In particular, visuals for a non prefixed glyph now serve as base for their prefixed counterparts (`hover_line_color` defaults to `line_color` if that is set), and aliases now work for all property traits ('selection_{y}' is an alias for 'selection_{x}_{y}' for any (x, y) where x is a visual feature).
Implemented and tested in `/bokeh/plotting/helpers.py`.
Implemented and not tested in `bokehjs/src/lib/api/plotting.ts`.
@bryevdv
=> Convert _pop_colors_and_alpha to _pop_visuals

bokeh/models/axes.py, bokeh/models/grids.py, bokeh/plotting/helpers.py, bokehjs/src/lib/models/grids/grid.ts, bokehjs/test/models/grids/grid.ts, tests/unit/bokeh/models/test_grids.py, tests/unit/bokeh/plotting/test_figure.py
After adding this line to the `iris.py` example:
p.xaxis.ticker = [1,3,7]
The output is:
Also confirmed explicitly setting a ticker on the grids works to take precedence. Not sure if there are any other docs or explicit examples needed.
=> allow grids to delegate ticking to an axis

.github/workflows/bokeh-ci.yml
This PR disables the windows builds for now. I expect there are lots of changes that we will want to make to these configurations but I would like to get a stable, green master first and foremost, then fix issues in follow-on PRs.
cc @ammarnajjar
=> Temp disable windows builds for GH CI

README.md
It is documented [here](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/configuring-a-workflow#adding-a-workflow-status-badge-to-your-repository), but it seems like using the absolute path to the action yml file did not work, but using the workflow name instead works:
before:
after:
=> docs: correct the gh-actions badge in readme

.github/workflows/bokeh-ci.yml
Forcing triggers on push and on pull_request.
**but** to be aware the default type of PR  activity triggers are only (opened, synchronize, or reopened).
there are other PR activities available which are disabled by default:
- assigned
- unassigned
- labeled
- unlabeled
- edited
- closed
- ready_for_review
- locked
- unlocked
- review_requested
- review_request_removed
in order to enable them, we need to do that specifically => [docs](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/events-that-trigger-workflows#pull-request-event-pull_request)
please advise
=> force trigger gh-actions on pull_request

bokeh/sphinxext/bokeh_palette_group.py
Sphinx extension for palette groups should just assume and use JQ and Bootstrap from the theme (in particular the docutils.js for search requires an ancient JQ version)
=> palettes docs can assume jq and bs

conda.recipe/bld.bat, conda.recipe/build.sh
Including an `Examples` directory in a conda package was due to an ancient anaconda env idea that supposed many packages would want to include examples. Though the feature still "works" it was never actually publicized or encouraged, and looking at a current set of Anaconda envs, not a single other package adds anything to Examples besides Bokeh. I think we can safely stop bothering with this, make our packages slightly smaller and our builds slightly faster.
=> don't include Examples dir in conda pkg

conda.recipe/meta.yaml
pins ipython to 7.9 
cc @mattpap
=> pin ipython max version

examples/howto/server_embed/flask_gunicorn_embed.py
Fixes #9476 seen when trying to stop gunicorn via Ctrl-C.
=> Mark flask_gunicorn_embed.py worker thread as a daemon.

bokehjs/src/lib/models/plots/plot_canvas.ts
For now without tests, because there is no good way to test this at the moment. However, it's possible to use device emulation mode in chrome's devtools to test this with various pixel ratios. This requires some additional work on bokehjs' integration testing framework.
fixes #9483
=> Fix WebGL rendering on high DPI displays

bokehjs/src/lib/models/widgets/file_input.ts
issues: fixes #9485 
Updated the code to fix the issue for FileInput not getting disabled. 
```
render(): void {
if (this.dialogEl == null) {
this.dialogEl = document.createElement('input')
this.dialogEl.type = "file"
this.dialogEl.multiple = false
this.dialogEl.onchange = (e) => this.load_file(e)
this.el.appendChild(this.dialogEl)
}
if (this.model.accept != null && this.model.accept != '')
this.dialogEl.accept = this.model.accept
this.dialogEl.style.width = `{this.model.width}px`
this.dialogEl.disabled = this.model.disabled
}
```
Thanks.
=> Disable option in FileInput not working #9485

bokeh/resources.py, bokeh/util/version.py, scripts/sri.py, sphinx/source/conf.py, tests/unit/bokeh/util/test_version.py
Addresses #8397 
This PR does some more incremental work towards supporting SRI hashes for BokehJS.  Primarily:
* adds a `verify_sri_hashes` func that can be used with full-release packges to verify that computed SRI hashes match the hash manifest
* adds an`sri.py` script that can update the hash manifest (takes care to preserve ordering) 
*incidentally, adds an `is_full_release` predicate in `bokeh.util.version`
cc @mattpap @jakirkham @tommycarstensen
=> More SRI hash work

examples/app/README.md
remove the pivot from the readme since it's not a supported example anymore
=> Pivot is not a supported app anymore

sphinx/source/docs/user_guide/server.rst
I found the user guide a little sparse around customising the Bokeh Server's Jinja templating, so I've expanded the content into its own subsection. Quite open to moving it later in the user guide.
Final subsubsection, entitled 'Custom Jinja templates and Threading' describes what causes #9435, and suggests a workaround (using a load balancer).
Running `make clean html serve` in the sphinx dir builds the documentation. 
Not sure if I should run the full test suite for the project, given there are no code changes?
=> Adding dedicated subsection to docs on Bokeh Server Jinja templating

bokehjs/src/lib/models/tools/toolbar_base.ts
This removes the `HelpTool` from a special privileged position next to the logo and just makes it behave as a normal action tool, which I am 100% fine with. 
Could not see a good way to test as we are not set up to test Bokeh views at all, really.
=> don't duplicate helpool

bokeh/embed/bundle.py, tests/unit/bokeh/embed/test_bundle.py
cc @mattpap please confirm this works for you. I did not want to go back to having things "work" by existing resource objects magically mutate themselves, so this is a fix similar to https://github.com/bokeh/bokeh/pull/9415 for the server case. 
Note the tests are not quite as nice/specific as I would have liked because custom extension resource tests leave alot of cruft in `js_raw`, `js_files`, etc.
=> allow env vars to override bundle resources

bokeh/models/glyph.py, bokeh/models/glyphs.py, bokeh/models/markers.py
This attempts to fix a fragile potential circular import situation between `bokeh.models.glyphs` and `bokeh.models.markers`. 
This was reported by LGTM, but I have definitely run in to problems on numerous occasions where a seemingly innocuous change suddenly results in tests failing with "Duplicate Model definition". So in truth, this probably does not go far enough. We should  possibly restructure the repo layout, and codify best practices, e.g. 
* move all the actual implementations to `bokeh._models.xyz`
* in those modules, avoid importing from other model modules at the top level except for base classes
* generally, internally only import from `bokeh._models`
* tests only import from public `bokeh.models`
We could provide stub `bokeh.models.ranges` that just import from …
=> fix circular import between glyphs and markers

.github/workflows/bokeh-ci.yml, bokeh/server/tornado.py
* issues: fixes #9507 
This PR adds unit test builds for Python 3.8 and should also run the CI workflow on pushes to master. 
Also addresses a real failure on win/py38
=> test on python 3.8

bokehjs/package-lock.json, bokehjs/package.json, bokehjs/src/lib/document/document.ts, bokehjs/src/lib/version.ts, bokehjs/test/unit/document/document.ts, scripts/deploy.py, scripts/deps.py
This changes the dev version format in bokehjs package, to match npm's requirements (e.g. `2.0.1-dev5` -> `2.0.1-dev.5`). It's unfortunate, but this is how it works. I've been using this pattern in `jupyter_bokeh` and `ipywidgets_bokeh`. I also switched package name from `bokehjs` to `@bokeh/bokehjs`. This isn't strictly necessary at this point, but it's useful to start using this pattern.
=> Allow to publish dev bokehjs packages

bokehjs/src/lib/core/ui_events.ts
Hammer.js has several issues related to Pointer Event implementation.
iOS 13 delivered built-in PointerEvents in Safari which made Hammer's touch recognisers (pan, pinch, swipe) behave incorrectly in certain cases.
However, most of problems may be addressed with Hammer's constructor options.
`Hammer.TouchMouseInput` does a trick for Pinch and Pan Tools in Bokeh.
=> Touch events on iOS 13.x workaround

.github/workflows/bokeh-ci.yml, bokeh/command/subcommands/file_output.py, bokeh/command/subcommands/png.py, bokeh/command/subcommands/svg.py, bokeh/core/validation/__init__.py, bokeh/core/validation/check.py, bokeh/embed/standalone.py, bokeh/io/export.py, bokeh/io/util.py, bokeh/io/webdriver.py, bokeh/settings.py, bokeh/util/dependencies.py, bokehjs/src/lib/models/plots/plot_canvas.ts, conda.recipe/meta.yaml, setup.cfg, sphinx/source/docs/dev_guide/setup.rst, sphinx/source/docs/dev_guide/testing.rst, sphinx/source/docs/installation.rst, sphinx/source/docs/user_guide/export.rst, tests/integration/tools/test_freehand_draw_tool.py, tests/unit/bokeh/command/subcommands/test_svg.py, tests/unit/bokeh/io/test_export.py, tests/unit/bokeh/io/test_webdriver.py, tests/unit/bokeh/test_settings.py, tests/unit/bokeh/util/test_dependencies.py
This adds support for geckodriver/firefox and chromedriver/chromium, and removes support for obsolete phantomjs. The former pair is now the default, primarily because both geckodriver and firefox are available from conda-forge, so installation process is straightforward. The later pair can be used alternatively. I plan to add support for auto-detection of available drivers and headless browsers, and make bokeh use what's available, so that we don't force users to install new web browsers needlessly. Especially because there should be a viable browser available on modern systems.
=> Switch to geckodriver/firefox in bokeh.io

bokehjs/src/lib/models/annotations/tooltip.ts
Try it out:
```python
from bokeh.plotting import figure, output_file, show, ColumnDataSource
from bokeh.models import HoverTool
output_file("toolbar.html")
source = ColumnDataSource(data=dict(
x=[1, 2, 3, 4, 5],
y=[2, 5, 8, 2, 7],
desc= ['bbb'] + ['aaaaa ' * 100 for i in range(4)]
))
hover = HoverTool(tooltips=[
("index", "$index"),
("(x,y)", "($x, $y)"),
("desc", "@desc"),
])
p = figure(tools=[hover],sizing_mode="stretch_both",
title="Mouse over the dots")
p.circle('x', 'y', size=20, source=source)
show(p)
```
=> Prevent hover from overflowing on right side of screen

bokeh/io/saving.py
template is passed through ot bokeh.embed.file_html, argument
documentation copied from there.
Also fixed indentation of 'state' argument in docstring.
I'm not super sure I should first create an issue first or should add any tags/metadata here. The PR blurb says 
> All pull requests must have an associated issue in the issue tracker
, BEP-1 says 
> If the PR does not need a discussion (trivial fixes, tasks, etc), you can avoid the opening of an associated Issue, but you have to add a type, a reso, a milestone and, optionally, a tag label as with any other common Issue. Also, you have to add this reference issues: none at the top of the first message/post. These Issues/PRs are commonly know as standalone PRs and they have to be exceptions (low frequency situation).
which does not seem to …
=> Update docstring with missing argument 'template'

conftest.py, tests/unit/bokeh/application/handlers/test_directory.py, tests/unit/bokeh/application/handlers/test_document_lifecycle.py, tests/unit/bokeh/application/handlers/test_handler.py, tests/unit/bokeh/application/handlers/test_server_lifecycle.py, tests/unit/bokeh/application/handlers/test_server_request_handler.py, tests/unit/bokeh/client/test_states.py, tests/unit/bokeh/protocol/test_receiver.py, tests/unit/bokeh/server/test_auth_provider.py, tests/unit/bokeh/server/test_contexts.py, tests/unit/bokeh/server/test_server__server.py, tests/unit/bokeh/server/test_tornado__server.py, tests/unit/bokeh/server/views/test_ws.py, tests/unit/bokeh/test_client_server.py
Expanding a bit on top of PR #9635. Currently an async test requires both `async` modifier and `asyncio` marker. With this PR only async modifier is needed. Note this uses pytest's test collection hooks, so only appropriate test functions will be marked. I will update this and mark as ready when PR #9536 is merged.
=> Implicitly apply pytest.mark.asyncio to async defs

bokeh/core/properties.py, bokeh/core/property/dataspec.py, bokeh/core/property/wrappers.py, bokeh/models/annotations.py, sphinx/source/docs/releases/2.0.0.rst, tests/unit/bokeh/core/test_properties.py
This PR cleans up some unusual/bad usage of super:
* in `wrappers.py` we can just call the method directly on `dict`, that is the actual intent, and clearer
* in `dataspec.py` the wonky situation with unit spec subclasses is improved as described below
=> remove bad super usage

bokeh/models/widgets/sliders.py, bokehjs/src/lib/models/widgets/abstract_slider.ts, bokehjs/src/lib/models/widgets/date_slider.ts, bokehjs/src/lib/models/widgets/range_slider.ts, bokehjs/src/lib/models/widgets/slider.ts, tests/integration/widgets/test_range_slider.py
Fixes #9469 as a non-general solution. A better solution would be to be to implement a general formatter attribute which takes a TickFormatter instance.
Now we can do following:
```python
from bokeh.io import output_file, show
from bokeh.models.widgets import RangeSlider
from bokeh.models.formatters import BasicTickFormatter
output_file("range_slider.html", mode="inline")
range_slider_small = RangeSlider(start=1e-7, end=10e-7, value=(1e-7,8e-7), step=1e-7, title="Bla", format="0[.]00") 
range_slider_large = RangeSlider(start=1e7, end=10e7, value=(2e7,8e7), step=1e6, title="Bla", format="0a")
range_slider_custom = RangeSlider(start=1e-7, end=10e-7, value=(1e-7,8e-7), step=1e-7, title="Bla",
formatter=BasicTickFormatter(precision=2))
range_slider_default = …
```
=> Support TickFormatter instances in RangeSlider

bokeh/io/webdriver.py, tests/unit/bokeh/io/test_export.py
cc @mattpap  This forces the chrome webdriver to always use standard RGB color profile. Otherwise, on OSX PIL images come back with an explicit ICC profile attached that causes the raw bytes to be different than expected. With this change, all unit tests can now be run successfully on OSX. 
This PR also removes the "or" values in export tests that were previously compensating for some difference in OSX. Now all platforms are identical.
=> force srgb color profile on chrome

bokehjs/src/lib/core/util/canvas.ts, bokehjs/src/lib/models/canvas/canvas.ts
This is unlikely to improve anything with regards to issue #8478, but it's a good thing to do anyway.
addresses #8478
=> Drop usage of backingStorePixelRatio API

bokeh/model.py, tests/unit/bokeh/test_model.py
Enchances js_link functionality to allow a user to index into a subscriptable attr value. For example one could now do `RangeSlider.js_link('value', other, other_attr, attr_selector=0)` to access the start value of the range.
=> js_link feature update to allow attr indexing

bokeh/layouts.py, bokeh/models/tools.py, bokehjs/src/lib/api/gridplot.ts, bokehjs/src/lib/models/tools/toolbar_box.ts
This establishes a relationship between `ProxyToolbar` and `Toolbar` models, where the former requires the later to be initialized first. Previously `ProxyToolbar` knew only about individual tools, thus toolbars owning those tools could be initialized at any point, including after `ProxyToolbar`. This is a minimal change I could come up with to resolve this issue. There are better solutions possible, and more impactful on the overall design, but I will leave that for after 2.0.
fixes #9699
=> Ensure Toolbar is initialized before ProxyToolbar

bokeh/_testing/util/selenium.py, bokeh/core/property/container.py, bokeh/core/property/datetime.py, bokeh/models/widgets/sliders.py, tests/integration/widgets/test_daterange_slider.py, tests/integration/widgets/test_dateslider.py, tests/integration/widgets/test_range_slider.py, tests/unit/bokeh/core/property/test_datetime.py, tests/unit/bokeh/models/widgets/test_slider.py
This fixes the issue with the `DaterangeSlider`. The underlying issue was that untransformed `Date` objects were making it in to the JSON-ish Document representation, which `JSONEncoder` serializes as ISO strings. This PR resolves that be adding a `serializable_value` to the `DatetimeProperty`, and then also modifies `Tuple` to also specialize `serializable_value` over its contents. 
Arguably having tuple behave that way is correct, but I don't love this PR as is, because it's a bit of a partial measure. I might look at making a dedicate `DatetimeRange` subclass of `Tuple` so that everything else can remain undisturbed, and leave more extensive rehab of the property system to later.
=> fix for broken daterange slider

bokeh/sphinxext/_templates/model_detail.rst
Now that glyphs are split out on to separate pages this change is less onerous. I am sure there are further improvements to make (e.g. pruning out some things users probably have no reason to ever care about) but this will dp for now.
=> Inherited members for refdocs

bokehjs/src/lib/models/annotations/tooltip.ts
I introduced #9717 in #9634. @bryevdv recommended this fix: https://github.com/bokeh/bokeh/issues/9717#issuecomment-590191046 and I've verified that the original issue is still fixed, so I wanted to just open this PR.
=> Use auto so that the tooltip doesn't stretch to the left

MANIFEST.in
This PR changes the MANIFEST:
* removes extra static assets (map files, json files)
* removes the docs source
* removes the examples
* only includes unit tests
Afterwards the sdist package size is 8.4M
cc @mattpap
=> Reduce sdist size

bokeh/command/subcommands/serve.py, bokeh/embed/util.py, bokeh/settings.py, examples/howto/notebook_comms/Numba Image Example.ipynb, sphinx/source/docs/user_guide/categorical.rst, sphinx/source/docs/user_guide/geo.rst, sphinx/source/docs/user_guide/jupyter.rst, sphinx/source/docs/user_guide/layout.rst, sphinx/source/docs/user_guide/server.rst
Fixes spelling mistakes in docs.
Related issue: https://github.com/bokeh/bokeh/issues/8448
=> Fix spelling mistakes in documentation

bokeh/resources.py, tests/unit/bokeh/test_resources.py
Resources checks for incompatible arguments should only consider passed-in args, not env var values like BOKEH_CDN_VERSION. (Otherwise INLINE, etc will blow up if any env var is set).
=> only check resource passed-in args

bokeh/core/_templates/autoload_nb_js.js, tests/unit/bokeh/core/test_templates.py
Previously we only added an empty script tag that copied over the Bokeh autoload tag, since it was specifying a `src` attribute. Now the autoload request tag has a script as text content, which also needs to be copied over.
=> include script text in notebook publish

_setup_support.py, setup.py
The previous build process already double-built BokehJS. This would go to triple to compute SRI unless things are change. This PR allows sdists to be built by calling `--install-js` which will allow BokehJS to be built once up front.
=> allow sdist to --install-js

bokeh/models/widgets/inputs.py, bokehjs/src/lib/models/widgets/file_input.ts
**This PR replaces PR #9728**
The PR amends the capability of multi-file selection to bokeh's FileInput widget.
It adapts the property types of class FileInput in
- inputs.py
and adapts the help-texts.
It extends the TS-code in
- file_input.ts
to ensure complete file reading/upload and return of either scalars (single file API) or Arrays (multi file API).
=> File input multi2

bokeh/server/tornado.py
This PR updates when we set the event loop policy to ensure that we continue to avoid using `asyncio.WindowsProactorEventLoopPolicy` on Windows and Python 3.8+ (which is incompatible with tornado https://github.com/tornadoweb/tornado/issues/2608), but also avoids clashing with other applications that use `bokeh` and also need to use custom event loop policies. This is a similar approach that was [taken over in Jupyter](https://github.com/jupyter/notebook/blob/f354740e57f206d67bfb077a9f23bb8d22b6b311/notebook/notebookapp.py#L1741-L1755).
=> Update setting asyncio event loop policy

sphinx/source/docs/user_guide/export.rst
Fixes missing `-c conda-forge` in guidance about additional dependencies for exporting plots.
=> Correct guidance on additional dependencies to export plots

bokeh/core/__init__.py, sphinx/source/docs/dev_guide/server.rst, sphinx/source/docs/reference/core/properties.rst
Fixes typos and adds missing words to documentation.
Related issue: #8448
=> Fixes typos and adds missing words to documentation

bokeh/command/subcommands/serve.py
Minor addition which allows downstream libraries (e.g. Panel) to subclass the `bokeh serve` CLI subcommand to add additional server_kwargs, e.g. to add additional tornado RequestHandlers. 
(Apologies I don't know how best to tag this)
=> Allow subclasses of Serve subcommand to modify server_kwargs

bokehjs/src/compiler/prelude.ts
This is required to allow bokehjs external imports from webpack bundles (e.g. from extensions packed with webpack). Webpack can support such workflow, but only through their convoluted approach, i.e. one can't just rewrite `import {HasProps} from "@bokehjs/core/has_props"` as `const {HasProps} = Bokeh.require("@bokehjs/core/has_props")`, which we currently support, but it must be `const {HasProps} = window["Bokeh"]["loader"]["@bokehjs/core/has_props"]`. The indexing part is fixed in webpack and can't be changed through configuration, but can be worked around with a `Proxy`. This isn't supported in IE, but given this is need for ipywidgets support, IE is not in the picture anyway.
=> Add support for Bokeh.loader["@bokehjs/module/name"]

sphinx/source/docs/dev_guide/setup.rst
This is a fix for #9816, with one additional "turorial" corrected to "tutorial."
=> fixed typos and git pre-commit hook instructions

bokeh/models/sources.py
In #9823 I reported being confused that the constructor of `ColumnDataSource` no longer accepts a `selected` argument as of v2.0, even though it is listed as one of the class properties [in the reference docs](http://docs.bokeh.org/en/latest/docs/reference/models/sources.html?highlight=columndatasource#bokeh.models.sources.ColumnDataSource.selected).
This PR proposes a small addition to the documentation to emphasize that `ColumnDataSource.selected` is now read-only.
=> Docs: clarify that ``DataSource.selected`` is read-only

bokeh/core/property/color.py, bokeh/core/property/visual.py
This PR aims to replace all `.regex `module callbacks with the new` .string` module, and hence remove deprecation message.
=> Updated files to use new String module

bokeh/embed/bundle.py, bokeh/server/urls.py, bokeh/server/views/multi_root_static_handler.py
So far, extensions compiled ahead of time (new-style extensions) can be embedded only inline. This PR allows to serve compiled bundles by bokeh server and consume extensions' resources from CDN (unpkg.com). This is an early preview and I will need to redesign this to allow serving other resources (e.g. fonts). This is needed to finalize https://github.com/bokeh/ipywidgets_bokeh/pull/5.
=> Allow to serve extensions' bundles and related resources

bokehjs/src/lib/models/glyphs/webgl/base.ts, bokehjs/test/baselines/Plot__with_webgl_backend__should_allow_empty_circle_glyphs, bokehjs/test/baselines/Plot__with_webgl_backend__should_allow_empty_line_glyphs, bokehjs/test/devtools/template.html, bokehjs/test/integration/index.ts
=> Skip painting empty indices when using webgl backend

bokeh/plotting/figure.py
Minor docstring typos fixed in `plotting/figure.py` file.
=> Fixed some minor docstring typos

bokeh/transform.py
Fixes a minor typo in bokeh.transform reference docs
> **cumsum(field, include_zero=False)**
>    &nbsp; &nbsp; Create a Create a DataSpec dict to generate a CumSum expression for a ColumnDataSource.
The `Create a` occurs twice.
=> Fix minor typo in bokeh.transform reference docs

bokeh/io/export.py, bokehjs/make/tasks/scripts.ts, bokehjs/make/tasks/test.ts, bokehjs/src/compiler/linker.ts, bokehjs/src/compiler/prelude.ts, bokehjs/src/lib/embed/notebook.ts, bokehjs/src/lib/version.d.ts, bokehjs/src/lib/version.ts, release/git.py
Currently when bokehjs is loaded from bundles it stores an instance of its main bundle's entry point as `Bokeh` global. If multiple versions of bokehjs are loaded, then they overwrite that global and it's impossible to use any version than the last. This PR makes only the first bundle to touch `Bokeh`. The first and all other bundle will register themselves as `Bokeh[version]` (so the first one can be accessed by both), where `version` is the version of bokehjs as defined in `package.json`.
fixes #9812
=> Allow to use multiple versions of bokehjs on one page

bokeh/core/_templates/autoload_js.js
No need to fail if `elementid` wasn't found and completely ignore this check in the notebook, as `autoload_nb_js` has its own logic.
fixes https://github.com/bokeh/jupyter_bokeh/issues/49
=> Relax elementid check in autoload.js

bokeh/embed/__init__.py
Checked out the docs build with the newly released Sphinx 3.0 and we had one warning that failed the build. It was valid and was causing all the functions in the `bokeh.embed` refguide show up twice.
=> Sphinx 3.0 compat

bokeh/_testing/util/filesystem.py
`makedirs_ok_if_exists` in private `_testing` module duplicated stdlib capability and was also not implemented ideally.
=> remove pointless util function

bokehjs/src/lib/models/ranges/factor_range.ts
`null` is the right choice for the "lack of an actual value" marker, instead of `undefined`, which has special meaning within the properties' system. At some point I will disallow usage of `undefined` at the type system level.
addresses #9879
=> Use null instead of undefined in FactorRange.{mids,tops}

bokeh/palettes.py
Correcting outdated link to colorcet repo in /bokeh/palettes.py.
=> Updating link to colorcet repo.

examples/howto/Hover callback.ipynb, examples/howto/Linked panning.ipynb, examples/howto/Range update callback.ipynb, examples/howto/notebook_comms/Basic Usage.ipynb, examples/howto/notebook_comms/Continuous Updating.ipynb, examples/howto/notebook_comms/Jupyter Interactors.ipynb, examples/howto/notebook_comms/Numba Image Example.ipynb
=> Manually edited nbformat_minor in notebooks to fix validation errors (issue #9892)

bokeh/server/views/auth_mixin.py, bokeh/server/views/root_handler.py, bokeh/server/views/session_handler.py, tests/unit/bokeh/server/test_auth_provider.py
This makes a the auth methods method overrides explicit, rather than depending delicately on base class order. Additionally a lingering `@gen.coroutine` was replaced with a native coroutine, and also fixes some small issues in the auth provider tests.
=> make auth method overrides explicit

bokeh/layouts.py, tests/unit/bokeh/test_layouts.py
This suppresses some LGTM false positives for loop capture. I am not surprised they are missed, it's not easy to tell statically that the enclosing functions will evaluate the lambdas immediately. 
However, @mattpap what I actually ~very much desire~ intend to do is to deprecate `GridSpec` now, and slate it for removal in 3.0. This class is: 
* completely undocumented
* without any tests whatsoever
* not used or demonstrated by anything, anywhere:
```
(dev) ❯ grin GridSpec
./bokeh/layouts.py:
39 :     'GridSpec',
212 :             ncols. OR an instance of GridSpec.
486 : class GridSpec(object):
555 :         elif len(args) == 1 and isinstance(args[0], GridSpec):
./bokeh/plotting/__init__.py:
38 :     'GridSpec',
78 : from ..layouts import gridplot, GridSpec; gridplot, GridSpec
```
This is …
=> suppress gridspec warning

conda.recipe/meta.yaml, examples/embed/custom_server/color_scatter_server.py, tests/unit/bokeh/embed/test_server__embed.py, tests/unit/bokeh/embed/test_standalone.py, tests/unit/bokeh/test_resources.py
Fixes broken tests after bs4 4.9 release which subtly changed the behavior of `.text` property.
=> Fix bokeh's unit tests after bs4 update

bokeh/tile_providers.py, setup.py
Noticed the tile provider docs were both confusing and missing examples for all the new tile sources. This is a quick update to make the page at least serviceable.
=> Improve tile provider docs

.github/workflows/bokeh-release.yml, release/__main__.py
@bokeh/dev Just a heads up. `repository_dispatch` events only trigger off master. I will probably be making various commits straight to master when working on this to reduce the iteration cycle time. I'll make sure to run codebase tests first, which is all that should matter. Here's an outline of what I would like to work eventually:
* Trigger release "build" event. Could be via script, or via Postman, etc. This will require a repository scoped PAT but we may want to layer in some additional validation of the user issuing the event
* The build workflow runs checks, and assuming they all pass, executes the build
* A release deployment tarball is uploaded as an artifact. 
At this point BokehJS has been uploaded to CDN and the repo has been provisionally tagged, but no packages or docs have …
=> release build first steps

bokeh/plotting/_renderer.py
If a new glyph adds a legend item, two patches are
sent to the BokehJS documents - one for the renderer
and the other for the legend item. The renderer one
must arrive first, otherwise the newly created legend
item will have an invalid model reference.
=> Fix adding glyphs with legend args dynamically

bokehjs/src/lib/models/widgets/tables/table_column.ts
I thought I should just go ahead and make the change. This most probably will work fine as the library would use column field name instead if the title is not externally given.
=> Add field name to column name if title not given

bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/document/document.ts
I don't think it's possible to add a reliable test case for this. The manifestation of the bug depends on the iteration order over a map, which is intrinsically undefined. And I really don't think we should make it defined by sorting something because performance matters.
=> Delay connect_signals during initialization

bokehjs/src/lib/core/util/color.ts, bokehjs/src/lib/core/visuals.ts
Based on a suggestion in another PR (I can't find it right now), I checked what's the performance impact of all those comparisons in `core/visuals.ts`, and there is a visible negative impact for large datasets. I tested in Chrome and FF. For example, `plotting/file/color_catter` with `N=100_000` has its run time reduced by roughly 100ms (700->600ms in Chrome and 1100->1000 in FF). There's quite a bit of dispersion though (not unexpected with JIT and GC), so I started working on benchmarking tooling for bokehjs, so that we could get consistent and statistically significant results. Though it will take awhile to finish this.
=> Speed up setting up of visuals

bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/core/types.ts, bokehjs/src/lib/core/util/data_structures.ts, bokehjs/src/lib/core/util/text.ts, bokehjs/src/lib/document/document.ts, bokehjs/src/lib/document/events.ts, bokehjs/src/lib/model.ts, bokehjs/test/unit/document/document.ts, bokehjs/test/unit/document/events.ts
Backport of PR #9836. ~~This is based on PR #10004. I will rebase on top of `master` when that is merged~~. Note this PR doesn't replace all occurrences of `{[key: string]: V}`. Further incremental changes will be needed.
=> Use Map<K, V> or Set<V> instead of {[key: string]: V}

bokehjs/src/lib/models/glyphs/image.ts, bokehjs/src/lib/models/glyphs/image_base.ts, bokehjs/src/lib/models/glyphs/image_rgba.ts
`Image` and `ImageRGBA` already have a common base, but they still repeat quite a bit of their implementations. This PR resolves this by pulling most of the common code into `ImageBase` class.
=> Refactor implementation of Image and ImageRGBA glyphs

sphinx/source/docs/dev_guide/documentation.rst
Sphinx docs build fails  when GOOGLE_API_KEY environment variable is not set up. 
Adding proper documentation on Dev guid, documentation section.
=> Fix documentation section

bokeh/themes/__init__.py, bokeh/themes/_contrast.py, bokeh/themes/_night_sky.py
No tests added for the themes.
Here are the previews:
**Contrast**
**Night Sky**
=> Adding 2 more themes: night_sky, contrast [ci disable examples]

bokehjs/src/lib/core/build_views.ts, bokehjs/src/lib/core/selection_manager.ts, bokehjs/src/lib/core/types.ts, bokehjs/src/lib/document/document.ts, bokehjs/src/lib/models/annotations/legend.ts, bokehjs/src/lib/models/layouts/grid_box.ts, bokehjs/src/lib/models/layouts/layout_dom.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/src/lib/models/renderers/graph_renderer.ts, bokehjs/src/lib/models/tools/edit/edit_tool.ts, bokehjs/src/lib/models/tools/gestures/select_tool.ts, bokehjs/src/lib/models/tools/gestures/tap_tool.ts, bokehjs/src/lib/models/tools/inspectors/hover_tool.ts, bokehjs/src/lib/models/tools/toolbar_base.ts, bokehjs/test/unit/models/annotations/color_bar.ts, bokehjs/test/unit/models/axes/axis.ts, bokehjs/test/unit/models/grids/grid.ts, bokehjs/test/unit/models/plots/plot.ts, bokehjs/test/unit/models/tools/actions/zoom_in_tool.ts, bokehjs/test/unit/models/tools/actions/zoom_out_tool.ts, bokehjs/test/unit/models/tools/edit/box_edit_tool.ts, bokehjs/test/unit/models/tools/edit/freehand_draw_tool.ts, bokehjs/test/unit/models/tools/edit/point_draw_tool.ts, bokehjs/test/unit/models/tools/edit/poly_draw_tool.ts, bokehjs/test/unit/models/tools/edit/poly_edit_tool.ts, bokehjs/test/unit/models/tools/gestures/box_zoom_tool.ts, bokehjs/test/unit/models/tools/gestures/wheel_pan_tool.ts, bokehjs/test/unit/models/tools/gestures/wheel_zoom_tool.ts
Slowly chipping away usage of plain objects (`{[key: string]: T}`), in favour of `Map<K, V>`.
=> Use Map instead of {} as view storage

bokehjs/src/lib/core/util/types.ts, bokehjs/src/lib/models/glyphs/multi_line.ts, bokehjs/src/lib/models/glyphs/patches.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/src/lib/models/tickers/continuous_ticker.ts
All code paths that still used `isStrictNaN()` work on `number`s, so there should be no difference anymore.
fixes #5744
=> Drop isStrictNaN in favour of built-in isNaN

bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/core/types.ts, bokehjs/src/lib/core/ui_events.ts, bokehjs/src/lib/core/util/array.ts, bokehjs/src/lib/core/util/arrayable.ts, bokehjs/src/lib/core/util/object.ts, bokehjs/src/lib/document/document.ts, bokehjs/src/lib/model.ts, bokehjs/src/lib/models/annotations/color_bar.ts, bokehjs/src/lib/models/annotations/legend.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/src/lib/models/ranges/data_range1d.ts, bokehjs/src/lib/models/tickers/composite_ticker.ts, bokehjs/src/lib/models/tiles/tile_source.ts, bokehjs/src/lib/models/tools/gestures/select_tool.ts, bokehjs/src/lib/models/tools/gestures/tap_tool.ts, bokehjs/src/lib/models/widgets/selectbox.ts, bokehjs/src/lib/polyfill.ts, bokehjs/test/unit/models/ranges/data_range1d.ts
This fixes broken selections after PR #10054. There reason for breakage was a stray `in` operator. I fixed that and took a stab at removing as many `for-in` loops and usage of `in` operator as I could in one sitting. I think two more PRs and bokehjs' codebase will be cleaned up.
=> Reduce usage of for-in loop an in operator

bokeh/server/server.py, bokeh/server/tornado.py, examples/plotting/file/color_data_map.py, release/credentials.py, tests/unit/bokeh/server/test_server__server.py
@mrocklin In the interest of saving you some time I made a new PR with the additional changes needed to get tests passing. Can you test out this branch and verify that is satisfies your needs?
=> Move some functions from Server to BaseServer and BokehTornado

bokehjs/src/less/toolbar.less
cc @bokeh/dev 
The color here is chosen purely by experimentation. Open to any other suggestions for CSS styling to improve. Ultimate I think perhaps we should expose properties on the toolbar to control bg color and possibly blend mode.
=> use semi-stranparent button background highlight

ci/install_bokeh_package.sh
Not sure whats up, everything passed multiple times in PR but now on master reliably installs the wrong (release) version of Bokeh in three tests. This attempts to make sure that only the local artifact package is ever installed.
=> only use local bokeh package in tests

bokeh/util/serialization.py, bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/core/types.ts, bokehjs/src/lib/core/util/ndarray.ts, bokehjs/src/lib/core/util/serialization.ts, bokehjs/src/lib/document/document.ts, bokehjs/src/lib/document/events.ts, bokehjs/src/lib/models/glyphs/image_base.ts, bokehjs/src/lib/models/sources/column_data_source.ts, bokehjs/src/lib/models/sources/columnar_data_source.ts, bokehjs/test/unit/core/has_props.ts, bokehjs/test/unit/core/util/index.ts, bokehjs/test/unit/core/util/ndarray.ts, bokehjs/test/unit/core/util/serialization.ts, bokehjs/test/unit/models/sources/column_data_source.ts
This extends typed arrays with `dtype` and `shape`, and allows to handle shapes by arrays, instead of globally. This allows to support ndarrays and base64/binary encoding everywhere (not only in `data`), and removes custom serialization code, etc. Note this is a stop gap measure, and not how I intend ndarrays to look like and work in bokeh 3.0, but backwards compatibility and the lack of ability to override `[]` operator makes proper changes impossible right now. Tentatively adding to 2.1, but it may need to be postponed, depending on how badly it breaks things.
=> Improve support for ndarray serialization

bokehjs/src/lib/core/view.ts, bokehjs/src/lib/models/expressions/expression.ts, bokehjs/src/lib/models/filters/boolean_filter.ts, bokehjs/src/lib/models/filters/filter.ts, bokehjs/src/lib/models/filters/index_filter.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/src/lib/models/ranges/data_range1d.ts, bokehjs/src/lib/models/ranges/factor_range.ts, bokehjs/src/lib/models/renderers/glyph_renderer.ts, bokehjs/src/lib/models/tools/toolbar_base.ts, bokehjs/src/lib/models/widgets/selectbox.ts, bokehjs/test/unit/models/ranges/factor_range.ts
In particular this rewrites `FactorRange` using `Map` as mappings instead of plain objects. Additionally I removed all usage of `HasProps.id` that isn't completely necessary (e.g. where `toString()` can be used instead in error/log formatting, etc.).
=> More usage of Map<K, V> and Set<V>

bokeh/models/widgets/inputs.py, bokehjs/src/lib/models/widgets/autocomplete_input.ts, tests/integration/widgets/test_autocomplete_input.py
I've added case insensitive completion to the AutocompleteInput widget. I figured the case_sensitive property should be False (case insensitive matching) by default but lmk if it should be the inverse. I've added two tests, one for case_sensitivity and one for case_insensitivity. This functionality was requested in issue #9922. I should note I've been using this new version of the AutocompleteInput widget for a covid-19 dashboard I built https://speediedan.github.io/covid19/county_covid_explorer.html for several weeks without issue. Thanks for this immensely useful library! This is my first PR on the project but I'm really impressed by the community here!
Dan
- test_autocomplete_input.py::Test_AutocompleteInput::test_case_insensitivity
- …
=> AutocompleteInput case insensitive completion functionality added per #9922 request

bokehjs/src/lib/core/layout/html.ts, bokehjs/src/lib/models/widgets/markup.ts
When tested with:
```py
from bokeh.models import Div
from bokeh.layouts import column, row
from bokeh.io import save
def divs(i):
return [ Div(text=f"Text i={i} j={j}") for j in range(20) ]
c0_0 = column(divs(1))
c1_0 = column(divs(10))
c2_0 = column(divs(100))
c3_0 = column(divs(1000))
c0_1 = column(divs(2))
c1_1 = column(divs(20))
c2_1 = column(divs(200))
c3_1 = column(divs(2000))
r0 = row(c0_0, c1_0, c2_0, c3_0)
r1 = row(c0_1, c1_1, c2_1, c3_1)
c = column(r0, r1)
save(c)
```
gives ~4x speed improvement.
fixes #9515
=> Cache measurements in HTML-based widgets

bokeh/models/tools.py
Very simple addition, adding String to the acceptable EditTool.empty_value types.
=> Allow using string for EditTool empty_value

CHANGELOG, bokeh/server/server.py, bokeh/server/util.py, bokeh/server/views/ws.py, sphinx/source/docs/user_guide/server.rst, tests/codebase/test_python_execution_with_OO.py, tests/unit/bokeh/server/test_util.py
This PR removes our usage of the names `whitelist` and `blacklist`. 
This affects two util functions:
*  `check_whitelist`
* `create_hosts_whitelist`
These are technically public (dev) API, but in practice there is no reason for anyone to use these outside the library internals.
=> Prefer inclusive language

bokehjs/src/lib/core/util/arrayable.ts, bokehjs/src/lib/models/glyphs/image_url.ts, bokehjs/src/lib/models/glyphs/multi_line.ts, bokehjs/src/lib/models/glyphs/multi_polygons.ts, bokehjs/src/lib/models/glyphs/patches.ts, bokehjs/src/lib/polyfill.ts, bokehjs/test/unit/core/util/arrayable.ts
`NaN` is now ignored in `min()` and `max()`, which simplifies code that uses those functions. Added `minmax()` where `min()` and `max()` was used previous on the same data, to reduce number of iterations over data.
=> Redefine min()/max() and introduce minmax() function

bokehjs/src/lib/models/glyphs/annular_wedge.ts, bokehjs/src/lib/models/glyphs/annulus.ts, bokehjs/src/lib/models/glyphs/circle.ts, bokehjs/src/lib/models/glyphs/ellipse_oval.ts, bokehjs/src/lib/models/glyphs/hex_tile.ts, bokehjs/src/lib/models/glyphs/image_base.ts, bokehjs/src/lib/models/glyphs/multi_polygons.ts, bokehjs/src/lib/models/glyphs/patches.ts, bokehjs/src/lib/models/glyphs/segment.ts, bokehjs/src/lib/models/glyphs/wedge.ts, bokehjs/src/lib/models/markers/marker.ts, bokehjs/src/lib/models/selections/selection.ts
@bryevdv, this PR is more of a question rather than a task right now. Why indices were sorted by distance in `Glyph._hit_point()`, especially given that they are ultimately stored in a `Selection`, which doesn't specify any explicit (well, besides the natural) order? No other geometry has any similar behavior.
=> Don't sort indices by distance in _hit_point()

bokeh/server/server.py, tests/unit/bokeh/test_client_server.py
=> Websocket local origin: use port returned by bind_sockets

bokehjs/src/lib/core/util/spatial.ts, bokehjs/src/lib/models/glyphs/bezier.ts, bokehjs/src/lib/models/glyphs/box.ts, bokehjs/src/lib/models/glyphs/glyph.ts, bokehjs/src/lib/models/glyphs/harea.ts, bokehjs/src/lib/models/glyphs/hbar.ts, bokehjs/src/lib/models/glyphs/hex_tile.ts, bokehjs/src/lib/models/glyphs/image_base.ts, bokehjs/src/lib/models/glyphs/image_url.ts, bokehjs/src/lib/models/glyphs/multi_line.ts, bokehjs/src/lib/models/glyphs/multi_polygons.ts, bokehjs/src/lib/models/glyphs/patches.ts, bokehjs/src/lib/models/glyphs/quad.ts, bokehjs/src/lib/models/glyphs/quadratic.ts, bokehjs/src/lib/models/glyphs/segment.ts, bokehjs/src/lib/models/glyphs/varea.ts, bokehjs/src/lib/models/glyphs/vbar.ts, bokehjs/src/lib/models/glyphs/xy_glyph.ts, bokehjs/test/unit/models/glyphs/glyph.ts
Currently data indexing is very inefficient, because it doesn't work in fixed memory, doesn't use typed arrays and creates a lot of intermediate objects. However, the underlying spatial indexing library (`flatbush`) is very efficient.
This PR does the following:
- no intermediate objects are created during indexing
- data is transferred directly from data arrays to the index (typed array to typed array)
- the index is pre-allocated and doesn't require intermediate reallocations
The size of the index is defined as the length of the shortest column in a data source (all columns should be of the same length in general, but this still isn't enforced).
~~This is based on PR #10161~~.
=> Reduce memory footprint of data indexing

bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/core/util/types.ts
This is a back port of the first two commits from https://github.com/bokeh/bokeh/issues/10153
=> return typed arrays as lists

bokehjs/package-lock.json, bokehjs/package.json, bokehjs/src/lib/models/glyphs/webgl/base.ts, bokehjs/src/lib/models/glyphs/webgl/gloo.ts, bokehjs/src/lib/models/glyphs/webgl/line.ts, bokehjs/src/lib/models/glyphs/webgl/markers.ts, bokehjs/src/lib/models/glyphs/webgl/utils/buffer.ts, bokehjs/src/lib/models/glyphs/webgl/utils/index.ts, bokehjs/src/lib/models/glyphs/webgl/utils/program.ts, bokehjs/src/lib/models/glyphs/webgl/utils/texture.ts
I think that if we want to commit to improving the webgl backend, we need to stop treating its implementation as a blackbox. The first step towards this direction is to get rid of the nasty auto-generated code and replace it with something that can be actually read and modified. Thus this PR rewrites gloo auto-generated code with TypeScript and adds it to bokehjs (dropping the dependency on `@bokehjs/gloo2`). For now I just did a straight rewrite to modern ES and reasonably statically typed the code. I didn't do any attempts to simplify or improve the implementation otherwise.
=> Rewrite gloo in TypeScript and add it to bokehjs

bokeh/models/annotations.py, bokehjs/src/lib/core/property_mixins.ts, bokehjs/test/unit/core/visuals.ts
=> Fix bokehjs' property mixins to match bokeh

bokehjs/src/lib/models/annotations/arrow.ts
=> Update Arrow when the data source is changed

bokehjs/src/lib/models/annotations/band.ts
=> Update Band when the model is changed

bokeh/plotting/gmap.py, sphinx/source/docs/reference.rst, sphinx/source/docs/reference/plotting.rst, sphinx/source/docs/releases/0.12.7.rst, sphinx/source/docs/user_guide/annotations.rst, sphinx/source/docs/user_guide/categorical.rst, sphinx/source/docs/user_guide/data.rst, sphinx/source/docs/user_guide/geo.rst, sphinx/source/docs/user_guide/plotting.rst, sphinx/source/docs/user_guide/quickstart.rst
A new version of Sphinx has broken the docs build on the main branch. Our usage of `figure` as a function name and as a submodule under `bokeh.plotting` confuses it, but it seems fine to simply document the transitively imported function directly at this point. 
An issue with documenting GMapOptions was also improved.
=> Fixes for sphinx 3.1.1

bokehjs/src/lib/core/has_props.ts
This is a quick and easy change to improve initialization speed, because when `silent === true`, we can skip all the `setv()` logic and get to updating values of properties directly.
=> Optimize `HasProps.setv(attrs, {silent: true})`

bokehjs/src/lib/models/glyphs/annular_wedge.ts, bokehjs/src/lib/models/glyphs/bezier.ts, bokehjs/src/lib/models/glyphs/glyph.ts, bokehjs/src/lib/models/glyphs/harea.ts, bokehjs/src/lib/models/glyphs/hbar.ts, bokehjs/src/lib/models/glyphs/hex_tile.ts, bokehjs/src/lib/models/glyphs/multi_line.ts, bokehjs/src/lib/models/glyphs/multi_polygons.ts, bokehjs/src/lib/models/glyphs/patches.ts, bokehjs/src/lib/models/glyphs/quad.ts, bokehjs/src/lib/models/glyphs/quadratic.ts, bokehjs/src/lib/models/glyphs/segment.ts, bokehjs/src/lib/models/glyphs/text.ts, bokehjs/src/lib/models/glyphs/varea.ts, bokehjs/src/lib/models/glyphs/vbar.ts, bokehjs/src/lib/models/glyphs/wedge.ts, bokehjs/src/lib/models/glyphs/xy_glyph.ts, bokehjs/test/unit/models/glyphs/glyph.ts, sphinx/source/docs/releases/2.2.0.rst
`Patches._build_discontinuous_regions()` is very inefficient, especially memory utilization-wise, due to high GC churn. It's more efficient to just iterate over `NaN` separated regions and use `TypedArray.subarray()` to create data views for other functions to use. Additionally I also merged `scenterx()` and `scentery()` into one method, as those often had repeated logic and required computing things twice.
=> Improve performance by replacing _build_discontinuous_regions()

bokehjs/src/compiler/linker.ts
At this point this is a partial fix. The other part is dealing with luma's strange attitude to bypass standard module imports and go straight to CJS modules from ES modules.
addresses #10230
=> Handle type="module" w/o entry point packages

bokeh/client/connection.py, bokeh/client/session.py, bokeh/client/states.py, tests/unit/bokeh/test_client_server.py
As mentioned in issue #3653 the error messages from
ClientSession.pull and ClientSession.push did not take the cause of the
connection loss into account.
Therefore we add different Disconnected States to the client/states.py
to distinguish the reason of the connection loss and store information
about the error itself (error id, error message). Those information is
accessible through the ClientConnection class and is used in the
ClientSession to create more descriptive error messages.
=> ClientSession: Add different error messages (Close #3653)

bokeh/sphinxext/bokeh_plot.py, bokeh/sphinxext/bokeh_prop.py, bokehjs/src/lib/core/util/pretty.ts
This silences deprecation warnings in the docs build that show up when documenting deprecated things in the reference guide (cc @p-himik I think you had asked about this). My position is that once something is deprecated, it should generally *only* be documented in the reference guide, so an attempt has been made to allow deprecation warnings to still show in other cases. As of this PR, the docs build is 100% clean. 
This also clears the [one LGTM warning we currently have](https://lgtm.com/projects/g/bokeh/bokeh/snapshot/fe2ff065437c33d13b6916e1a679ab1be9bba816/files/bokehjs/src/lib/core/util/pretty.ts?sort=name&dir=ASC&mode=heatmap#xea8aa1d026c79741:1) cc @mattpap I assume you know and intend things to be as they are in this case but noting, just in case.
=> Misc warnings cleanup

sphinx/source/docs/user_guide/embed.rst, sphinx/source/docs/user_guide/interaction/legends.rst
This PR is intended to fix a typo found in `bokeh/sphinx/source/docs/user_guide/interaction/legends.rst`
It originally contained "automatically group do no yet work with the".
I have replaced it with "automatically group do not yet work with the".
This is intended to help with efforts in #8448.
Related issue: #8448
=> #8448 Fix typo "do no yet work" -> "do not yet work" in bokeh/sphinx/source/docs/user_guide/interaction/legends.rst

bokeh/embed/elements.py, tests/unit/bokeh/embed/test_standalone.py
ref: https://github.com/bokeh/bokeh/issues/10268#issuecomment-655190968
@mattpap since the "only replace single quotes" is only needed in one place I just used `str.replace` plus a (now-appropriately-called) stdlib `html.escape`
=> fix over-quoting by components

.github/workflows/bokeh-ci.yml, ci/run_downstream_tests.sh, sphinx/source/docs/dev_guide/setup.rst, sphinx/source/docs/dev_guide/testing.rst, sphinx/source/docs/releases/1.0.0.rst
The `pytest` command has been the recommended entry point since pytest 3.0,
cf. https://github.com/pytest-dev/pytest/issues/1629
=> Change all references of 'py.test' to 'pytest'

bokehjs/src/lib/core/util/arrayable.ts, bokehjs/src/lib/models/mappers/eqhist_color_mapper.ts, bokehjs/src/lib/models/mappers/scanning_color_mapper.ts
Continues the incomplete work from #8765. This PR is currently working but a few important issues need to be addressed so it should be considered WIP. This PR is branched off @mattpap's work which will allow the colormapping to dynamically update in response to viewport and selection events.
PR #8765 attempted to bring the functionality of datashader's histogram equalization (originally from scikit image) to Bokeh. While a lot of work was done in that PR to port the algorithm as closely as possible to Typescript with some success, the PR did not achieve the correct mapping as the transform applied by datashader and required by Bokeh for colormapping are two different things.
The datashader (and scikit image) algorithm are designed to distort the *image data* while the goal here is to …
=> Corrected EqHistColorMapper with inverted colormap edge transform

bokeh/palettes.py, bokeh/sphinxext/bokeh_palette_group.py
Adds a palette based on the Bokeh colorway provided by Chris G in the #brand Slack channel. 
Also removes a stray " that was appearing on the palettes doc page.
=> Add bokeh logo palette; remove rogue double-quote from template

ci/environment-test-3.6.yml, ci/environment-test-3.7.yml, ci/environment-test-3.8.yml, environment.yml, release/config.py
Definitely my goal to add a full test suite for release automation but let's sort out the new branching model first. 
```
In [5]: from release.config import Config
In [6]: version = "2.2.0dev4"
In [7]: config = Config(version=version)
In [8]: config.js_version
Out[8]: '2.2.0-dev.4'
```
Edit: defaults picked up isort 5 finally so I had to pin it here
=> don't dupe version extension in bokehjs version

bokehjs/eslint.json, bokehjs/src/lib/api/plotting.ts, bokehjs/src/lib/base.ts, bokehjs/src/lib/core/dom.ts, bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/core/logging.ts, bokehjs/src/lib/document/document.ts, bokehjs/src/lib/embed/index.ts, bokehjs/src/lib/models/sources/ajax_data_source.ts, bokehjs/src/lib/models/sources/column_data_source.ts, bokehjs/src/lib/models/sources/geojson_data_source.ts, bokehjs/src/lib/models/tools/toolbar.ts, bokehjs/src/lib/models/tools/toolbar_base.ts, bokehjs/src/lib/models/tools/toolbar_box.ts, bokehjs/test/codebase/size.ts, bokehjs/test/defaults/index.ts, bokehjs/test/unit/core/properties.ts, bokehjs/test/unit/document/document.ts
This is a follow up on issue #10320 and several other. No more for-in loops, especially unguarded by `hasOwnProperty()`, after this PR. Use for-of loop in combination with `keys()`, `values()` and/or `entries()` from `core/util/object` module instead.
=> Replace for-in loop with for-of and keys()/values()/entries()

sphinx/source/docs/dev_guide/bindings.rst, sphinx/source/docs/dev_guide/bokehjs.rst, sphinx/source/docs/dev_guide/documentation.rst, sphinx/source/docs/dev_guide/env_vars.rst, sphinx/source/docs/dev_guide/models.rst, sphinx/source/docs/dev_guide/server.rst, sphinx/source/docs/dev_guide/setup.rst, sphinx/source/docs/dev_guide/testing.rst
Fixes typos in Developer Guide, partially fixes issue #8448.
Based on pull request #10269 (Fix typos in the User Guide), I have fixed several typos in the Developer Guide.
The same basic assumptions apply here as well, i.e. this pull request is focussing exclusively on fixing errors such as misspelled words, omitted words, superfluous words, capitalization inconsistencies and some punctuation issues (see [this comment](https://github.com/bokeh/bokeh/pull/10269#issuecomment-656485540)).
This commit includes all my changes, this pull request is status: ready!
=> Fix typos in Dev Guide

bokeh/document/document.py, bokeh/events.py, bokehjs/src/lib/core/bokeh_events.ts, bokehjs/src/lib/document/document.ts, bokehjs/src/lib/model.ts, bokehjs/test/unit/document/document.ts, tests/unit/bokeh/test_events.py
Implements #10265 by adding a `Document.on_event` method to subscribe to a new class of `DocumentEvent` types the first of which is a `DocumentReady` event, which fires when the Document is done rendering.
=> Add DocumentReady event

tests/codebase/test_eslint.py
Adds `node make lint` test to `tests/codebase`. This is slightly duplicative since the BokehJS-CI job also runs eslint, but I want to make sure that `py.test tests/codebase` passing locally means a guarantee that no linter-related fails will happen on CI.
=> Perform eslint checks on codebase tests

bokeh/server/views/ws.py, tests/unit/bokeh/server/views/test_metadata_handler.py, tests/unit/bokeh/server/views/test_root_handler.py, tests/unit/bokeh/server/views/test_session_handler.py
Ensures that user authentication occurs before opening the websocket.
=> Require auth on WSHandler

sphinx/source/docs/dev_guide.rst
Add links to BEP 6 and BEP landing page to developer docs
Solves issue #10347 
This pull request adds some more information about Bokeh Enhancement Proposals (BEPs). It also explicitly links the two BEPs that I think are the most important ones for developers to be aware of (BEP 1 and BEP 6).
I'm looking forward to some feedback, especially from @bryevdv and other authors (and users) of BEPs, to make sure this short text is in line with your intentions.
=> Add more info about BEPs

bokehjs/src/lib/core/enums.ts, bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/core/kinds.ts, bokehjs/src/lib/core/layout/types.ts, bokehjs/src/lib/core/properties.ts, bokehjs/src/lib/models/layouts/layout_dom.ts, bokehjs/src/lib/models/widgets/abstract_slider.ts, bokehjs/test/integration/glyphs/markers.ts, bokehjs/test/unit/core/enums.ts
Currently bokehjs' properties consist of property declarations (`Props` type/interface) and property definitions (`HasProps.define()`), which implement properties at run time. The former are fairly well typed (up to `nul` handling), as they use TypeScript's type system. However, the later are not, with a lot of `p.Any` and/or poorly typed definitions or mismatches with `Props`. This PR attempts to fix this, filling in the gaps which will allow more robust validation, etc. Given the design, this may also allow to remove property type declarations, because with this approach, such declarations can be inferred from definitions.
=> Fill in the gaps in bokehjs' property definitions

bokeh/models/tools.py
Still lists image glyphs as unsupported
=> Update out of date HoverTool docstring

bokehjs/src/lib/models/annotations/band.ts, bokehjs/src/lib/models/annotations/upper_lower.ts, bokehjs/src/lib/models/annotations/whisker.ts, bokehjs/src/lib/models/markers/marker.ts, bokehjs/src/lib/models/markers/scatter.ts, bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts, bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts, bokehjs/src/lib/models/tools/gestures/pan_tool.ts, bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts, bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts, bokehjs/src/lib/models/transforms/dodge.ts, bokehjs/src/lib/models/transforms/jitter.ts, bokehjs/src/lib/models/transforms/range_transform.ts, bokehjs/test/unit/models/tools/actions/zoom_in_tool.ts, bokehjs/test/unit/models/tools/actions/zoom_out_tool.ts
Decided to try out [`jscpd`](https://www.npmjs.com/package/jscpd#html) for detecting duplicated code and it seems pretty nice. Maybe we should consider integrating it in to our automation at some point. 
This PR is just to try and remove some of the worst/easies targets. It removes about 150 lines of dupe and shaves ~1k off the bundle size. The tool reports there are still 1100+ lines of duped code in blocks of size 5 or greater.
=> Code dupe experiements

bokeh/models/widgets/tables.py, bokehjs/src/lib/models/widgets/tables/cell_formatters.ts, bokehjs/test/unit/models/widgets/tables/cell_formatters.ts
Adds a `nan_format` option to the DataTable NumberFormatter.
=> Add nan_format option to DataTable NumberFormatter

bokehjs/eslint.json, bokehjs/examples/burtin/burtin.ts, bokehjs/examples/stocks/stocks.ts, bokehjs/src/compiler/linker.ts, bokehjs/src/compiler/transforms.ts, bokehjs/src/lib/core/util/svg.ts, bokehjs/src/lib/models/annotations/color_bar.ts, bokehjs/src/lib/models/annotations/legend_item.ts, bokehjs/src/lib/models/glyphs/bezier.ts, bokehjs/src/lib/models/glyphs/webgl/line.ts
This adds an AST transformer specific to ES5 and `core/util/ndarray` module, which "fixes" the TypeScript emitted NDArray constructors, so that they work under ES5. This completes the task of fixing legacy bundles, but I expect there may be still some issues in corner cases.
fixes #10233
=> Make *NDArray classes work with legacy bundles under ES5

bokehjs/src/lib/models/tools/inspectors/hover_tool.ts, sphinx/source/docs/user_guide/examples/tools_hover_tooltips_image.py
Only image case didn't support `$name`.
fixes #10319
=> Support `$name` special variable with image tooltips

tests/unit/bokeh/io/test_webdriver.py
`tests/unit/bokeh/io/test_webdriver` fails regularly on macos and windows due to webdriver's unreliability.
=> Mark webdriver's tests as flaky

bokeh/models/widgets/tables.py, bokehjs/src/lib/models/widgets/tables/cell_formatters.ts, bokehjs/test/unit/models/widgets/tables/cell_formatters.ts, sphinx/source/docs/releases/2.2.0.rst
Adds `nan_format` to both `ScientificFormatter` and `DateFormatter` after having added it to NumberFormatter in #10375. Also turns `DateFormatter` into a `StringFormatter` subclass to expose some of the other string formatting options which are already supported for the Scientific and Date formatters. I'm not sure `nan_format` is the most accurate on the `DateFormatter` since technically there shouldn't be NaNs, only nulls and there is no NaT type in JS, but in this case I vote for consistency over precision in the naming.
=> Implemented nan_format for other CellFormatters

bokehjs/src/lib/models/widgets/tables/cell_formatters.ts, bokehjs/test/unit/models/widgets/tables/cell_formatters.ts
Handles `nan_format` for NaT types on the DataTable DateFormatter.
=> Implement nan_format for NaT types on DateFormatter

sphinx/source/docs/user_guide/embed.rst
=> Fix the typo in the Autoload Scripts docs section

bokeh/models/widgets/inputs.py, bokehjs/src/lib/models/widgets/autocomplete_input.ts, tests/integration/widgets/test_autocomplete_input.py
One of the main purposes of the AutocompleteInput widget is to select a
value from a long list (for short lists, one could use Select). However,
lists tend to become long when people keep adding to them.
Previously, AutocompleteInput would not accept text input that was not
present in the list of completions, thus excluding users from the
process of building the list.
This PR adds a `restrict_value` option (default: True), which allows
developers to lift the restriction of values to the list of completions.
P.S. While reading through the contributing guidelines, I noticed that they [recommend making a PR against the `master` branch](https://github.com/bokeh/bokeh/blob/branch-2.3/.github/CONTRIBUTING.md#creating-a-pull-request-pr), which does not exist.
=> AutocompleteInput: allow user-defined value

bokehjs/src/lib/core/view.ts, bokehjs/src/lib/models/annotations/annotation.ts, bokehjs/src/lib/models/axes/axis.ts, bokehjs/src/lib/models/layouts/layout_dom.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/test/framework.ts
Results in one fewer `as any` cast.
=> Strictly type View.serializable_state()

bokehjs/src/lib/models/plots/gmap_plot_canvas.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/src/lib/models/plots/range_manager.ts, bokehjs/src/lib/models/renderers/glyph_renderer.ts, bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts, bokehjs/src/lib/models/tools/gestures/pan_tool.ts, bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts, bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts
Range management is a complex piece of logic that takes 25% of `PlotCanvas`' implementation, and as such deserves to be treated as an independent unit, thus this refactoring. This PR is the first step out of many towards the goal of making plots composable, allowing multiple plots per canvas, plots-in-plots, implementing color bar in terms of plot building blocks (layout, frame, glyphs, axes), etc. Code and module structure should be treated as WIP, which I will be refining as work progresses (within 2.3 timeframe).
=> Split off range management code from PlotCanvas

tests/integration/widgets/test_autocomplete_input.py
Add a test for restrict=True (default) ensuring that random text input
does not end up in the input.value
=> AutocompleteInput: add more tests

sphinx/source/docs/dev_guide/setup.rst, sphinx/source/docs/dev_guide/testing.rst
Dropped the TOC which were present in developer documents in the Getting started and Testing sections
as mentioned in the issue #10467
=> Dropped redundant TOC in developer docs

sphinx/source/conf.py
Currently, the year that is displayed in the documentation's footer is hardcoded as '2019' into the sphinx configuration file. This pull request uses the Python datetime library to always use the current year instead. Fixes issue #10529.
=> Dynamically create year for footer in docs

sphinx/source/bokeh/static/custom.css
As part of Google's Season of Docs, this pull request slightly changes the colors of inline code and links for Bokeh's documentation. The goal is to increase legibility and increase compliance with the [WCAG's contrast criterion](https://www.w3.org/TR/WCAG21/#contrast-minimum). As discussed with @bryevdv, @hyles-lineata, and @pavithraes.
=> Improve inline/link colors for docs

ci/environment-test-3.6.yml, ci/environment-test-3.7.yml, ci/environment-test-3.8.yml, environment.yml, sphinx/source/bokeh/static/custom.css, sphinx/source/conf.py, sphinx/source/index.rst
As part of Google's Season of Docs, this pull request restructures the [landing page for Bokeh's documentation](https://docs.bokeh.org/en/latest/). As discussed with @bryevdv, @hyles-lineata, and @pavithraes.
=> Restructure documentation landing page

sphinx/source/bokeh/static/custom.css
As noted by @pavithraes in #10519, the boxes with examples at the bottom of the page are not displayed on very small screens. This pull request fixes the CSS to display those boxes correctly.
=> [Docs] Fix display of example boxes on very small screens

sphinx/make.bat
When building the docs on a Windows system with Bokeh's `make.bat` file (e.g. `make.bat html`), Windows unnecessarily prompts the user to overwrite existing files. Adding the option `/y` to the .bat-file's xcopy command will automatically overwrite those files.
Solves #10551
=> Remove overwrite prompt for windows make.bat

sphinx/source/docs/user_guide/jupyter.rst
A fairly thorough edit of the Jupyter section of the User Guide. This should hopefully make the doc easier to read, though it's by no means a final take and feedback is very much welcome. I'd be happy to make further edits to this and other docs accordingly.
I also have a couple of questions, which are specific to this doc:
Line **228** has a sentence that says *"|push_notebook| **described above**"*. It isn't, however. It is mentioned, sure, but never defined within the document itself. It would be ideal if we could make a cross-doc reference to where it is in fact defined, but I'm unsure how to do that nor do I know where to look for the definition, yet. Removed that bit for the time being.
Line **277** says *"Notebook comms examples"*. Could you please clarify what "comms" mean?
=> Task #10539: Jupyter notebook edits

bokehjs/src/lib/core/signaling.ts, bokehjs/src/lib/core/util/callback.ts, bokehjs/src/lib/core/util/defer.ts, bokehjs/src/lib/core/util/throttle.ts, bokehjs/src/lib/embed/index.ts
This PR does two things:
1. Removes `requestAnimationFrame`'s polyfill, because all supported browsers implement it.
2. Replaces incorrect usage of `requestAnimationFrame` in bokehjs, especially in `defer()`, which is replaced with an efficient (zero delay) implementation using `postMessage` technique.
=> Clean up usage of `requestAnimationFrame`

environment.yml
The Sphinx extension sphinx-panels has [recently become available](https://github.com/conda-forge/staged-recipes/pull/12517) on conda forge. Therefore, it is no longer necessary to install this extension with pip.
=> Switch sphinx-panels from pip to conda

bokehjs/src/lib/core/util/templating.ts, bokehjs/src/lib/models/callbacks/open_url.ts, bokehjs/test/unit/core/util/templating.ts
=> Don't escape raw strings in replace_placeholders() by default

bokeh/models/annotations.py, bokeh/models/arrow_heads.py, bokehjs/src/lib/models/annotations/arrow.ts, bokehjs/src/lib/models/annotations/arrow_head.ts, bokehjs/src/lib/models/annotations/whisker.ts, sphinx/source/docs/releases/2.3.0.rst, tests/unit/bokeh/models/test_annotations.py
Currently arrow head models mix model and view code, so this PR addresses this issue. Additionally arrow heads are currently annotations, but they aren't used like ones (the interface is not fulfilled), so I changed their base to `Model`. In future I will add a proper `Graphics`  (or something like that) base classes, to group paintable objects that aren't glyphs nor annotations.
=> Implement views for arrow head models

bokeh/models/ranges.py, bokeh/models/tools.py, bokehjs/src/lib/core/signaling.ts, bokehjs/src/lib/core/view.ts, bokehjs/src/lib/models/ranges/data_range.ts, bokehjs/src/lib/models/ranges/data_range1d.ts, bokehjs/src/lib/models/tools/gestures/select_tool.ts, bokehjs/src/lib/models/tools/inspectors/hover_tool.ts, bokehjs/src/lib/models/util.ts, bokehjs/test/unit/_util.ts, bokehjs/test/unit/models/util.ts, bokehjs/test/unit/regressions.ts, sphinx/source/docs/releases/2.3.0.rst
This fixes also fixes memory leak when connecting views' slots and adds support for selectively disconnecting senders, which could be generalized to disconnect signals of removed models.
fixes #10612
=> Invalidate computed renderers when HoverToolView.plot_model.renderers changes

ci/environment-release-build.yml, ci/environment-test-3.6.yml, ci/environment-test-3.7.yml, ci/environment-test-3.8.yml, environment.yml, sphinx/source/conf.py
As part of Google's Season of Docs, this pull request will add [OpenGraph metadata](https://ogp.me/) to Bokeh's docs. OpenGraph metadata is used by services like Facebook, Twitter, LinkedIn or Discourse to generate rich previews of links.
=> Add OpenGraph metadata to docs

bokehjs/src/lib/core/ui_events.ts, bokehjs/src/lib/core/util/bbox.ts, bokehjs/src/lib/models/annotations/color_bar.ts, bokehjs/src/lib/models/annotations/slope.ts, bokehjs/src/lib/models/annotations/tooltip.ts, bokehjs/src/lib/models/axes/axis.ts, bokehjs/src/lib/models/canvas/canvas.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/src/lib/models/plots/state_manager.ts, bokehjs/src/lib/models/tools/actions/redo_tool.ts, bokehjs/src/lib/models/tools/actions/undo_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts, bokehjs/src/lib/models/tools/gestures/box_select_tool.ts, bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts, bokehjs/src/lib/models/tools/gestures/lasso_select_tool.ts, bokehjs/src/lib/models/tools/gestures/pan_tool.ts, bokehjs/src/lib/models/tools/gestures/poly_select_tool.ts, bokehjs/src/lib/models/tools/gestures/tap_tool.ts, bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts, bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts, bokehjs/test/unit/core/ui_events.ts, bokehjs/test/unit/models/plots/plot.ts
Continuing on top of PR #10491, this PR:
=> Factor out code from PlotView

bokeh/models/graphs.py, bokehjs/src/lib/models/graphs/graph_hit_test_policy.ts, bokehjs/test/unit/models/graphs/graph_hit_test_policy.ts
If you have any thoughts about `GraphRendere.get_selection_manager` let me know and I will update the PR. Perhaps it should just raise an error (i.e. things should go through the sub-renderers always instead)
=> Add EdgesOnly selection policy

bokeh/core/_templates/autoload_nb_js.js, bokehjs/src/lib/api/plotting.ts, bokehjs/src/lib/core/kinds.ts, bokehjs/src/lib/core/util/eq.ts, bokehjs/src/lib/core/util/object.ts, bokehjs/src/lib/core/visuals.ts, bokehjs/src/lib/models/sources/geojson_data_source.ts, tests/unit/bokeh/core/test_templates.py
In particular this approach works with prototype-less plain objects (i.e. `Object.create(null)`).
=> Use the correct variant of hasOwnProperty check

bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/core/types.ts, bokehjs/src/lib/core/util/color.ts, bokehjs/src/lib/core/visuals.ts, bokehjs/src/lib/models/annotations/annotation.ts, bokehjs/src/lib/models/annotations/arrow.ts, bokehjs/src/lib/models/annotations/arrow_head.ts, bokehjs/src/lib/models/annotations/color_bar.ts, bokehjs/src/lib/models/annotations/label.ts, bokehjs/src/lib/models/annotations/label_set.ts, bokehjs/src/lib/models/annotations/title.ts, bokehjs/src/lib/models/annotations/upper_lower.ts, bokehjs/src/lib/models/glyphs/center_rotatable.ts, bokehjs/src/lib/models/glyphs/ellipse_oval.ts, bokehjs/src/lib/models/glyphs/glyph.ts, bokehjs/src/lib/models/glyphs/image_base.ts, bokehjs/src/lib/models/glyphs/image_url.ts, bokehjs/src/lib/models/glyphs/multi_line.ts, bokehjs/src/lib/models/glyphs/rect.ts, bokehjs/src/lib/models/glyphs/segment.ts, bokehjs/src/lib/models/glyphs/text.ts, bokehjs/src/lib/models/glyphs/webgl/markers.ts, bokehjs/src/lib/models/plots/plot.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/src/lib/models/renderers/glyph_renderer.ts, bokehjs/src/lib/models/renderers/renderer.ts, bokehjs/test/unit/core/has_props.ts, bokehjs/test/unit/core/visuals.ts, bokehjs/test/unit/models/annotations/annotation.ts
Previously visuals were initialized twice, first by `Glyph.set_data()` and then by `Visuals.warm_cache()`. Additionally, handling of subset indices, etc., were done separately, causing bugs and regressions. Now glyphs are fully responsible for data management and visuals only apply data to a canvas context. As a side effect, visuals now apply to views and not models. Note that within a glyph, there are still separate `set_data()` and `set_visuals()`, this will be sorted out in the following 1~2 PRs.
=> Unify initialization of visuals and data

.github/workflows/bokeh-ci.yml, .github/workflows/bokeh-release-build.yml, .github/workflows/bokeh-release-deploy.yml
Hopefully will fix:
```
Error: Unable to process command '::add-path::/usr/share/miniconda3/condabin' successfully.
Error: The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```
=> Migrate CI {goanpeca->conda-incubator}/setup-miniconda

bokeh/models/tools.py
The backwards compatibility alias was misnamed (`Inspect` instead of the actual old name `Inspection`) so that the old import no longer works and breaks downstream libraries.
=> Fix backwards compatibility alias for InspectTool

bokeh/models/tools.py, bokehjs/src/lib/models/tools/actions/custom_action.ts, bokehjs/src/lib/models/tools/actions/help_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts, bokehjs/src/lib/models/tools/button_tool.ts, bokehjs/src/lib/models/tools/edit/edit_tool.ts, bokehjs/src/lib/models/tools/edit/line_edit_tool.ts, bokehjs/src/lib/models/tools/gestures/box_select_tool.ts, bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts, bokehjs/src/lib/models/tools/gestures/pan_tool.ts, bokehjs/src/lib/models/tools/gestures/wheel_pan_tool.ts, bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts, bokehjs/src/lib/models/tools/inspectors/crosshair_tool.ts, bokehjs/src/lib/models/tools/tool.ts, bokehjs/test/unit/models/tools/actions/zoom_in_tool.ts, bokehjs/test/unit/models/tools/actions/zoom_out_tool.ts, bokehjs/test/unit/models/tools/edit/box_edit_tool.ts, bokehjs/test/unit/models/tools/edit/freehand_draw_tool.ts, bokehjs/test/unit/models/tools/edit/point_draw_tool.ts, bokehjs/test/unit/models/tools/edit/poly_draw_tool.ts, bokehjs/test/unit/models/tools/edit/poly_edit_tool.ts, bokehjs/test/unit/models/tools/gestures/box_zoom_tool.ts, bokehjs/test/unit/models/tools/gestures/wheel_pan_tool.ts, bokehjs/test/unit/models/tools/gestures/wheel_zoom_tool.ts, sphinx/source/docs/releases/2.3.0.rst
This PR also deprecates all "custom" description/tooltip properties, i.e. `action_tooltip`, `help_tooltip`, `custom_tooltip`.
fixes #10662
=> Add support for Tool.description property

release/build.py, release/deploy.py, release/remote.py, release/stages.py
This assumes `NPM_TOKEN` was configured as an [automation token](https://github.blog/changelog/2020-10-02-npm-automation-tokens/), which means OTP is not going to be needed in CI.
=> Add support for publishing npm packages

bokehjs/package-lock.json, bokehjs/package.json, sphinx/source/docs/dev_guide/bokehjs.rst, tests/codebase/test_js_license_set.py
npx from npm 7.1 stopped quoting arguments, making `test_js_licenses` fail.
=> Manually quote arguments to npx

bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
=> Restore 'index' argument to HoverTool.callback

bokehjs/src/lib/models/widgets/spinner.ts
I haven't open an issue related to this.
But I noticed when we press spinner arrows to increment it, with the laptop pad, the number increment twice
To correct it I add a timeout before setting the interval.
@mattpap I noticed KeyboardEvent.keyCode is deprecated what is the recommended way to handle it now?
=> [Spinner] Avoid twice incrementation with laptop pad

bokehjs/src/lib/api/plotting.ts, bokehjs/src/lib/models/annotations/arrow.ts, bokehjs/src/lib/models/annotations/color_bar.ts, bokehjs/src/lib/models/annotations/label_set.ts, bokehjs/src/lib/models/annotations/legend.ts, bokehjs/src/lib/models/annotations/poly_annotation.ts, bokehjs/src/lib/models/annotations/slope.ts, bokehjs/src/lib/models/annotations/text_annotation.ts, bokehjs/src/lib/models/annotations/upper_lower.ts, bokehjs/src/lib/models/glyphs/image.ts, bokehjs/src/lib/models/plots/gmap_plot_canvas.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/src/lib/models/ranges/data_range1d.ts, bokehjs/src/lib/models/renderers/renderer.ts, bokehjs/src/lib/models/tools/gestures/select_tool.ts, bokehjs/test/unit/regressions.ts
This makes paint invalidation process more selective, allowing to have glyphs on multiple layers, where updating a glyph on one layer doesn't force repaint on other layers. For now we have two implicit layers (base and overlays), but I will get this generalized in near future, so that the user will be able to create his own layers and stack them, allowing to take advantage of the full potential of this change.
fixes #10784
=> Request paint only for changed renderers

bokeh/models/tools.py, bokehjs/src/lib/core/dom.ts, bokehjs/src/lib/models/tools/inspectors/hover_tool.ts, bokehjs/test/unit/models/tools/inspectors/hover_tool.ts, sphinx/source/docs/user_guide/tools.rst
I updated the code as requested. I defined a new special variable called "swatch" which decouples the swatch functionality from the color field. Now, you can add the swatch element to any field you want. In addition, the code is backwards compatible so that the swatch option continues to work for the color field. For bad input handling, I was not sure what the preferred behavior is. Right now, I hide the swatch element and just display text.
I can update the documentation if the behavior looks good. In terms of testing, I looked around and couldn't finding existing tests for testing specific special variables used in the hover_tool. Do we need tests for this case?
=> Decouple Color Swatch

sphinx/source/docs/user_guide/annotations.rst, sphinx/source/docs/user_guide/examples/plotting_label.py
Remove the level attribute from the LabelSet example as it is broken (at least as used in example).
Fixes #10819.
=> Fix example of LabelSet in user manual

bokeh/models/widgets/tables.py
Update to DataTable documentation as suggested on the Discourse. 
@philippjfr or @mattpap it looked like the functionality on the `fit_columns` param was duplicated/replaced by the `autosize_mode` param, so I just marked the `fit_columns` one as legacy to avoid confusion. CCing you for verification-- if this is wrong, let me know.
=> Updated DataTable fit_columns docstring

bokehjs/src/lib/models/tools/edit/poly_edit_tool.ts, tests/integration/tools/test_poly_edit_tool.py
Proposed (partial) fix for #10670
This adds a listener to the PolyEditTool's first renderer's data source.  The listener updates the `vertex_renderer` appropriately when the data source is updated.
An alternative implementation would add such listeners to _all_ of the renderers present, rather than just the first.  However, I don't think this is required, because:
1) In most (all?) use cases, all the renderers will share the same data source
2) It will always be possible to update the `vertex_renderer` appropriately via the first renderer's data source
This is a partial fix, as it doesn't cover the edge case where you want to change the length of the data source (i.e the number of points) while simultaneously editing with the PolyEditTool.  In this case, #10670 persists in the same …
=> Update vertex_renderer properly in PolyEditTool

bokeh/core/properties.py, bokeh/core/property/container.py, bokeh/models/filters.py, tests/unit/bokeh/core/property/test_container.py, tests/unit/bokeh/core/test_properties.py
Add `RestrictedDict` (a subclass of `Dict`) which raises an error if a disallowed key is passed.
Change `args = Dict(...)` to `args = RestrictedDict(disallow=(), ...)` in CustomJSFilter.
TODO: Add unit test.
I'm unsure about the unit tests can someone guide me on how it is to be added?
Thanks!
fixes #9958
=> Fix CustomJSFilter args dict: warn if disallowed key is passed

bokeh/command/subcommands/serve.py, bokeh/server/tornado.py, bokeh/server/views/ws.py, tests/codebase/test_js_license_set.py, tests/unit/bokeh/command/subcommands/test_serve.py, tests/unit/bokeh/server/test_tornado__server.py
This PR makes it possible to enable WebSocket compression but does not enable it by default.
=> Make Websocket compression configurable on Tornado server

bokehjs/src/lib/models/glyphs/circle.ts, bokehjs/src/lib/models/plots/plot.ts, bokehjs/src/lib/models/sources/web_data_source.ts, bokehjs/test/unit/models/sources/ajax_data_source.ts, bokehjs/test/unit/regressions.ts, examples/howto/ajax_source.py
This is more a workaround than a solution to the underlying data size determination issue, but at least it fixes web data sources and broken examples.
fixes #10853
=> Properly derive `WebDataSource` from `ColumnDataSource`

bokehjs/make/index.js, bokehjs/package-lock.json, bokehjs/package.json, release/build.py
- URL fixing is not needed anymore in `npm@7`
- require `npm >= 7.4` due to `npx` regressions (`test_js_license_set` failures)
- makes release scripts set bokehjs version in `package-lock.json` (v2) correctly
=> Miscellaneous bokehjs build changes 

sphinx/source/conf.py
Numpy's intersphinx inventory has moved from` https://docs.scipy.org/doc/numpy/` to `https://numpy.org/doc/stable/`. This pull request updates the URL in `conf.py`. This takes care of a warning message that Sphinx currently shows with every docs build ("`intersphinx inventory has moved: https://docs.scipy.org/doc/numpy/objects.inv -> https://numpy.org/doc/stable/objects.inv`").
=> Update URL for numpy intersphinx inventory

bokeh/core/properties.py, bokeh/core/property/bases.py, bokeh/core/property/descriptors.py, bokeh/models/plots.py, bokeh/models/tools.py, bokeh/models/widgets/inputs.py, bokeh/models/widgets/sliders.py, bokeh/plotting/figure.py, bokehjs/src/lib/models/plots/plot.ts, bokehjs/src/lib/models/tools/toolbar_base.ts, bokehjs/src/lib/models/widgets/slider.ts, tests/unit/bokeh/core/property/test_nullable.py, tests/unit/bokeh/models/widgets/test_slider.py
=> Followup fixes after PR #10842

sphinx/source/docs/dev_guide/models.rst
This pull request adds a note about the deprecated marker classes to the figure in the section "Bokeh Models" of the Developers Guide. It complements #10885 and also fixes #10875.
=> Add note about deprecated marker classes.

sphinx/source/docs/user_guide/server.rst
I assume this is invalid value: `--allow-websocket-origin=acme:com`
=> Update server.rst - "acme:com"?

bokeh/plotting/figure.py
Fixes #10906 by changing `x` keyword argument to `y` in `hbar_stack` example.
=> Fix broken hbar_stack example

bokehjs/src/lib/models/renderers/glyph_renderer.ts, bokehjs/test/unit/regressions.ts
@mattpap this fails the test with the expected out-of-bounds error without the changes, and passes the test with the changes. It also behaves well with more extensive dask operations e.g. 
```
In [2]: import dask.array as da
...:
...: X = da.random.random((2000000, 100), chunks=(100000, 100)).persist()
...: u, s, v = da.linalg.svd_compressed(X, k=5)
In [3]: v.compute()
```
and as far as I can tell, the graph looks correct (nodes later after "processing" nodes are marked "waiting" etc.) cc @quasiben 
I am sure the code could be cleaner or make use of better APIs I am just unfamiliar with. Please do one of two things first things in the morning:
* make any small changes or improvements, then merge, or
* merge as-is if you are content with it
I do still plan to release tomorrow with this fix …
=> consider view for legend representatives

bokeh/sphinxext/bokeh_releases.py
Fixes: https://github.com/bokeh/bokeh/issues/10934
Now the list comprehension only cares about .rst files, and also we don't sort non-related file names.
=> Optimization when processing docs

sphinx/source/docs/first_steps/first_steps_9.rst
A comma was missing from a code example in First Steps 9 making the code invalid. This pr fixes the typo.
=> Add missing comma in example code

sphinx/source/docs/user_guide/jupyter.rst
The `jupyter-server-proxy` package is the new version of `nbserverproxy` and should be used to enable the embedding of Bokeh servers in Jupyter notebooks through JupyterHub.
=> Mention jupyter-server-proxy instead of nbserverproxy in docs

bokeh/sphinxext/bokeh_releases.py
Fixes: "TODO (bev) get rid of old style string substituion"
=> replaced old-style string substitution

ci/install_downstream_packages.sh, ci/run_downstream_tests.sh
Currently bokeh-related tests for `dask/distributed` are tested as part of the downstream CI build. This PR ensures that the same happens for `dask/dask`.
=> Add dask/dask to downstream tests

sphinx/source/docs/dev_guide/documentation.rst
The Documentation section of the Developers guide had some incorrectly implemented references. This PR fixes these issues.
=> [Docs] Fix references in Docs section

bokehjs/src/lib/api/index.ts
Adds `Bokeh.Palettes` to the API, exposing the color palettes to the user. Useful when working with `ColorMapper` objects, which cannot currently use strings as they are defined in the base `bokeh.js`
Unless there are plans to provide support for named palettes in the `ColorMapper` objects when the API has been loaded, we may want to update docs as well, to reflect this API difference.
=> exposes Palettes

bokehjs/src/less/_mixins.less, bokehjs/src/less/buttons.less, bokehjs/src/less/menus.less, bokehjs/src/less/tabs.less, bokehjs/src/less/toolbar.less, bokehjs/src/less/widgets/inputs.less
All supported browsers support non-prefixed standard version, so there's no point in keeping this around.
=> Drop unnecessary -webkit- prefixes from flexbox

bokeh/core/has_props.py
Could see an warning message was missing the f in f-string so added them. Needed to change `_` to `class_name` in input to get a working f-string.
=> Fixed missing f in f-string

bokehjs/src/lib/core/visuals/fill.ts, bokehjs/src/lib/core/visuals/hatch.ts, bokehjs/src/lib/core/visuals/line.ts, bokehjs/src/lib/models/annotations/band.ts, bokehjs/src/lib/models/annotations/box_annotation.ts, bokehjs/src/lib/models/annotations/label_set.ts, bokehjs/src/lib/models/annotations/legend.ts, bokehjs/src/lib/models/annotations/poly_annotation.ts, bokehjs/src/lib/models/annotations/text_annotation.ts, bokehjs/src/lib/models/glyphs/annular_wedge.ts, bokehjs/src/lib/models/glyphs/annulus.ts, bokehjs/src/lib/models/glyphs/box.ts, bokehjs/src/lib/models/glyphs/circle.ts, bokehjs/src/lib/models/glyphs/defs.ts, bokehjs/src/lib/models/glyphs/ellipse_oval.ts, bokehjs/src/lib/models/glyphs/harea.ts, bokehjs/src/lib/models/glyphs/hex_tile.ts, bokehjs/src/lib/models/glyphs/multi_polygons.ts, bokehjs/src/lib/models/glyphs/patch.ts, bokehjs/src/lib/models/glyphs/patches.ts, bokehjs/src/lib/models/glyphs/rect.ts, bokehjs/src/lib/models/glyphs/utils.ts, bokehjs/src/lib/models/glyphs/varea.ts, bokehjs/src/lib/models/glyphs/wedge.ts, bokehjs/src/lib/models/grids/grid.ts, examples/custom/gears/gear.ts
This substitutes the most commonly appearing pattern:
```ts
if (this.visuals.line.doit) {
this.visuals.line.set_vectorize(ctx, i)
ctx.stroke()
}
```
with
```ts
this.visuals.line.apply(ctx, i)
```
=> Simplify rendering code with visuals.apply()

bokehjs/make/tasks/test.ts, bokehjs/test/devtools/baselines.ts, bokehjs/test/devtools/devtools.ts
For example:
```
node make test:integration --ref HEAD~5
```
or
```
node make test:integration --ref origin/branch-2.4
```
This is particularly useful when checking out other people's work when baselines were already updated (so, there is no difference between working tree and `HEAD`).
=> Allow to test against a provided git reference

sphinx/source/docs/user_guide/interaction/widgets.rst
Just a minor fix in the docs for widget callbacks.
=> Fix python3 incompatible print in callback docs

bokehjs/src/lib/core/layout/grid.ts, bokehjs/src/lib/models/layouts/layout_dom.ts
This is more a workaround than a fix, but it seems it works (unless I missed some cases).
fixes #11057
=> Fix recent layout regressions

bokeh/models/tools.py, bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts
Initially added in #7683 for the WheelZoomTool, it makes sense to also
provide the option for the ZoomOutTool, as currently trying to zoom out at
the border of a graph leads to no zooming out happening.
=> Add "maintain_focus" parameter to zoom_base_tools

bokehjs/make/tasks/scripts.ts, bokehjs/src/compiler/linker.ts, bokehjs/src/lib/core/selection_manager.ts, bokehjs/src/lib/core/types.ts, bokehjs/src/lib/core/util/buffer.ts, bokehjs/src/lib/core/util/ndarray.ts, bokehjs/src/lib/core/util/serialization.ts, bokehjs/src/lib/document/document.ts, bokehjs/src/lib/models/glyphs/webgl/markers.ts, bokehjs/src/lib/models/sources/columnar_data_source.ts, bokehjs/test/unit/core/util/buffer.ts, bokehjs/test/unit/core/util/serialization.ts
This is a followup on PR #10707. This PR finishes the job and enables cycle detection by default in bokehjs' build.
=> Remove all cyclic dependencies from bokehjs

bokeh/events.py, bokehjs/src/lib/core/bokeh_events.ts, bokehjs/src/lib/document/document.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/src/lib/models/plots/state_manager.ts, bokehjs/src/lib/models/tools/actions/redo_tool.ts, bokehjs/src/lib/models/tools/actions/reset_tool.ts, bokehjs/src/lib/models/tools/actions/undo_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts, bokehjs/src/lib/models/tools/gestures/box_zoom_tool.ts, bokehjs/src/lib/models/tools/gestures/pan_tool.ts, bokehjs/src/lib/models/tools/gestures/range_tool.ts, bokehjs/src/lib/models/tools/gestures/wheel_zoom_tool.ts, bokehjs/src/lib/models/tools/tool.ts, bokehjs/test/unit/core/ui_events.ts, examples/howto/events_app.py, examples/howto/js_events.py, tests/integration/models/test_plot.py, tests/integration/tools/test_pan_tool.py, tests/integration/tools/test_reset_tool.py, tests/integration/tools/test_wheel_zoom_tool.py, tests/integration/tools/test_zoom_in_tool.py, tests/integration/tools/test_zoom_out_tool.py
Some notes: 
* I made it so that this event only fires when a wheel zoom "finishes". It seems to me that if you want all the intermediate range values you could register for the `MouseWheel` event and change range. Otherwise, if `RangesUpdate` fires on "intermediate" range updates, then there would be no way to get the "final" range value (which is what I think will people actually want)
* It's getting near (past?)  time that the collection of "interactive_foo" properties on Document be factored out into something more sensible. 
* I had to make undo / redo methods return the state that was popped, so that this event can fire only when that state actually includes a range change
* Thoughts on testing @mattpap ? I can definitely add/expand the selenium tests for this, but if there is some …
=> Add RangesUpdate event

bokeh/models/formatters.py, bokehjs/src/lib/models/formatters/log_tick_formatter.ts, bokehjs/test/unit/models/formatters/log_tick_formatter.ts
This is the JS side to enable "min_exponent" if an axis is logarithmic.
=> Update "LogTickFormatter" to accept "min_exponent"

bokehjs/test/.gitignore, bokehjs/test/devtools/devtools.ts, bokehjs/test/devtools/metrics.html, bokehjs/test/devtools/report.html, bokehjs/test/devtools/server.ts
This finally takes advantage of devtools' protocol beyond simple remote execution of javascript, and allows collection of certain performance metrics during evaluation of integration tests (e.g. JS heap utilization, DOM node count, event listener count, etc.).  Metrics are collected after each test. Results are available at http://localhost:5777/integration/metrics (similarly test report http://localhost:5777/integration/report). One can view metrics for specific platform with `?platform=linux` (or `windows`, `macos`).
The presentation is very rudimentary at this time.
=> Collect performance metrics during integration tests

bokeh/core/has_props.py, bokeh/core/properties.py, bokeh/core/property/_sphinx.py, bokeh/core/property/alias.py, bokeh/core/property/auto.py, bokeh/core/property/bases.py, bokeh/core/property/color.py, bokeh/core/property/container.py, bokeh/core/property/dataspec.py, bokeh/core/property/descriptor_factory.py, bokeh/core/property/descriptors.py, bokeh/core/property/either.py, bokeh/core/property/enum.py, bokeh/core/property/instance.py, bokeh/core/property/nullable.py, bokeh/core/property/visual.py, bokeh/models/glyph.py, bokeh/plotting/_renderer.py, bokeh/sphinxext/bokeh_options.py, bokeh/sphinxext/bokeh_prop.py, bokeh/util/_sphinx.py, tests/unit/bokeh/core/property/test_alias.py, tests/unit/bokeh/core/property/test_dataspec.py, tests/unit/bokeh/core/property/test_descriptors.py, tests/unit/bokeh/core/test_has_props.py, tests/unit/bokeh/core/test_properties.py, tests/unit/bokeh/test_objects.py
This is the final PR for now to clean up and simplify `HasProps`:
* Consolidates `BasicPropertyDescriptor` down in to `PropertyDescriptor`. 
* Gets all the private sphinx links code outside of HasProps. This is also better because inheritance was the wrong tool for this. We need a default that can be overridden in isolated type, but not necessarily subtypes.
* Made `Alias` a proper property, removed gorpy special casing inside `HasProps`
* Adds `difflib` property typo suggestions to `__getattr__`
Finally this PR improves all the caching and property methods on `HasProps`. The basis is a new `properties` method that returns a dict that maps names to actual property objects. @mattpap it occurred to me that this this the best compromise since using this dict in a list context will preserve …
=> More HasProps cleanup

bokeh/core/validation/__init__.py, bokeh/core/validation/check.py, bokeh/document/document.py, bokeh/settings.py, tests/unit/bokeh/core/test_validation.py, tests/unit/bokeh/models/test_annotations.py, tests/unit/bokeh/models/test_mappers.py, tests/unit/bokeh/models/test_plots.py, tests/unit/bokeh/models/test_ranges.py, tests/unit/bokeh/models/widgets/test_slider.py, tests/unit/bokeh/test_layouts.py, tests/unit/bokeh/test_settings.py
Work in progress for issue #10733 
Added exception raising for validation errors and warnings and replaced env variable BOKEH_STRICT with BOKEH_VALIDATION_EXCEPTIONS
In a comment on the issue page (https://github.com/bokeh/bokeh/issues/10733#issuecomment-735002152), it was initially recommended for check_integrity to only be for returning messages, and to punt the potential exception raising downstream to the caller to avoid a muddled API. 
However, after changing BOKEH_STRICT to  BOKEH_VALIDATION EXCEPTIONS as recommended in this comment (https://github.com/bokeh/bokeh/issues/10733#issuecomment-735003520), I noticed that if potential exception raising was left in the caller, I wouldn't be able to access messages to check for a warning or error. In the original pull request made for this …
=> Add exception raising for validation errors

bokehjs/src/lib/models/glyphs/webgl/dash_cache.ts, bokehjs/src/lib/models/glyphs/webgl/line_gl.ts, bokehjs/src/lib/models/glyphs/webgl/markers.ts, bokehjs/src/lib/models/glyphs/webgl/rect.ts, bokehjs/src/lib/models/glyphs/webgl/regl_line.frag, bokehjs/src/lib/models/glyphs/webgl/regl_line.vert, bokehjs/src/lib/models/glyphs/webgl/regl_wrap.ts, bokehjs/src/lib/models/glyphs/webgl/types.ts, bokehjs/src/lib/models/glyphs/webgl/utils/math.ts, bokehjs/src/lib/models/glyphs/webgl/webgl_utils.ts
This PR fully types the WebGL/ReGL code which previously contained many `any`s.  There is no associated issue but was last discussed/requested in PR #11159.  I have also removed the debug mesh renderer in `line_gl.ts` as it is no longer needed and certainly doesn't need typing.
The new `interface`s in `types.ts` are very useful; less so are the repeated
```typescript
u_canvas_size: regl.prop<Props, 'canvas_size'>('canvas_size'),
u_pixel_ratio: regl.prop<Props, 'pixel_ratio'>('pixel_ratio'),
u_antialias: regl.prop<Props, 'antialias'>('antialias'),
```
in `regl_wrap.ts`, but they are not difficult to understand or change so we may as well tolerate them.
I have tried not to make unrelated changes, so we are left with some duplication of code.  This will all be improved in the long run as the …
=> Full typescript for WebGL code

sphinx/source/docs/dev_guide/documentation.rst
fixes #11242
Clarify and simplify instructions for setting GOOGLE_API_KEY in the Documentation section of the developers guide.
=> Clarify instructions for GOOGLE_API_KEY

bokehjs/src/compiler/compiler.ts, bokehjs/src/compiler/tsconfig.json, bokehjs/src/lib/tsconfig.json
Early WIP. Reduces compilation time of bokehjs from 20s to 12s (from second run), however increases compilation time in tests.
=> Add support for incremental TypeScript builds

sphinx/source/docs/first_steps.rst
Updates a link in https://docs.bokeh.org/en/latest/docs/first_steps.html to point to the more detailed [installation details](https://docs.bokeh.org/en/latest/docs/first_steps/installation.html#installation) page.
=> Update installation link

bokehjs/src/lib/models/canvas/canvas.ts, bokehjs/src/lib/models/glyphs/circle.ts, bokehjs/src/lib/models/glyphs/line.ts, bokehjs/src/lib/models/glyphs/rect.ts, bokehjs/src/lib/models/glyphs/scatter.ts, bokehjs/src/lib/models/glyphs/webgl/line_gl.ts, bokehjs/src/lib/models/glyphs/webgl/markers.ts, bokehjs/src/lib/models/glyphs/webgl/rect.ts, bokehjs/src/lib/models/glyphs/webgl/regl_wrap.ts, bokehjs/src/lib/models/glyphs/webgl/types.ts
ReGL recommends that the underlying WebGLRenderingContext should not be used directly (https://github.com/regl-project/regl/blob/gh-pages/API.md#unsafe-escape-hatch).  There were a few uses in `bokehjs/src/lib/models/canvas/canvas.ts` to set the viewport, set the scissor box and clear the WebGL rendering buffer; this PR moves the functionality to `ReglWrapper`.
The `canvas.ts` `WebGLState` type now stores a `ReglWrapper` rather than a `WebGLRenderingContext` and this is what is passed to the various WebGL glyph constructors.
=> Move WebGLRenderingContext use to ReGL

bokehjs/src/lib/models/glyphs/webgl/base.ts, bokehjs/src/lib/models/glyphs/webgl/line_gl.ts, bokehjs/src/lib/models/glyphs/webgl/regl_wrap.ts, bokehjs/src/lib/models/glyphs/webgl/types.ts
Improvements to WebGL line glyphs to reuse `Float32Array` and ReGL `Buffer` objects rather than recreating them frequently. No change in functionality or rendered output.  Partially addresses the 5th item of issue #11052, but I need to do similar changes to the WebGL `rect` and `marker` glyphs to complete that item.
The motivation is performance improvement.  To demonstrate this I am tentatively stepping into the realm of benchmarking, but in a somewhat manual and rudimentary way.  I am using this modified version of the 10k lines example
```python
np.random.seed(8417)
from bokeh.plotting import figure, curdoc
N = 500_000
backend = 'webgl'
p = figure(width=800, height=800, output_backend=backend, title=backend, lod_threshold=None)
x = np.linspace(0, 10*np.pi, N)
y = …
```
=> WebGL line glyphs reuse arrays and buffers

bokeh/server/auth_provider.py
fixed typo : login_url in the error message instead of logout_url
=> Fix typo in AuthProvider._validate error message. login_url instead of logout_url

sphinx/source/docs/user_guide/extensions.rst
As discussed in https://discourse.bokeh.org/t/compiled-components-final-step-help-needed-removing-nodejs-from-the-build-process/7668/4, this PR adds a note to the extensions chapter of the user guide.
=> Add 'experimental' note to extensions chapter

sphinx/source/docs/dev_guide/setup.rst
Adds the required `-f` option to the developers guide section explaining the use of `conda env` to create a local development environment. 
Partially fixes #11334
=> Add -f option for conda env

bokehjs/src/lib/models/glyphs/glyph.ts, bokehjs/src/lib/models/glyphs/scatter.ts
Candidate fix for issue #11288.
Scatter glyphs using `output_backend="webgl"` have more complicated initialization that other WebGL glyphs as their marker types can be changed dynamically and it is necessary to check if our WebGL code supports the required marker type.  Currently when the marker type is set or changed then `ScatterView._set_data()` is called and this creates or recreates the `MarkerGL` as required.  However, this only occurs for the `base` glyph of the `GlyphRendererView`; other glyphs such as the selection glyph are not updated via `set_data` and so selection, etc, revert to using the canvas backend.
I've opted for the minimal change which is to move the `MarkerGL` update from `Glyph.set_data()` to `Glyph.set_visuals()` as all the glyphs are updated by the latter.
I have …
=> Correctly initialize WebGL non-base marker/scatter glyphs

bokeh/embed/bundle.py, tests/unit/bokeh/embed/test_bundle.py
=> Use an exact extension's version in a CDN URL

ci/environment-release-build.yml, ci/environment-test-3.7.yml, ci/environment-test-3.8.yml, ci/environment-test-3.9.yml, environment.yml
This pull request fixes a problem with pip dependencies in `environment.yml`. We used to have two subsections listing pip dependencies, but yml only parses one pip subsection. This pr consolidates all pip dependencies in one subsection.
=> Consolidate pip dependencies

bokeh/embed/util.py, bokeh/models/tools.py, bokeh/util/compiler.py, examples/app/fourier_animated.py, examples/embed/embed_multiple.py, examples/plotting/file/burtin.py, scripts/sri.py, tests/unit/bokeh/embed/test_standalone.py
As of Python 3.7 standard  `dict` objects always retain insertion order. This small PR replaces all internal use of `OrderedDict` with `dict`. Additionally, one of the affected examples, `fourier_animated.py`, was also greatly simplified and streamlined, shaving off 100+ lines of code.
=> Remove OrderedDict

bokeh/models/annotations.py, bokeh/plotting/_docstring.py, sphinx/source/docs/user_guide/annotations.rst, sphinx/source/docs/user_guide/examples/plotting_legends_item_visibility.py
This PR adds a section on toggling visibility for legend items. This is a follow-up to #11412 and also fixes #9261.
cc @bryevdv
=> Add legend item visibility to user guide

bokeh/application/handlers/code_runner.py, bokeh/sphinxext/_templates/gallery_detail.rst, bokeh/sphinxext/bokeh_plot.py, bokeh/sphinxext/example_handler.py, examples/plotting/file/iris.py, sphinx/source/docs/user_guide/examples/js_events.py, tests/unit/bokeh/application/handlers/test_code_runner.py
Parses docstrings by adding a `doc` property to both ExampleHandler and CodeRunner, adding the example's docstring as a formatted element on the gallery detail page, and then stripping the redundant docstring out of the source code that appears along with the plot.
=> Parse docstrings in examples for gallery detail pages

release/deploy.py
Dev docs will now be publised at `/en/dev-2.4/`, `/en/dev-2.5/` etc based on the current release level, instead of generic `/en/dev/`
=> publish dev docs with release level

examples/plotting/file/sprint.py, tests/codebase/test_js_license_set.py, tests/codebase/test_license.py
This PR is to address an issue with the codebase license checks failing on Windows.
Ultimately decided just to skip the license tests in Windows.
~For _tests/codebase/test_js_license_set.py_, I found a quick fix of `shell=True`. I've read online there are possible security concerns with this, so I'm not sure if this is acceptable or not.~
~For _tests/codebase/test_license.py_, I found a couple issues:~
1.  ~The command began with `"diff"` instead of `"git diff"`. I found OS X can interpret `"diff"` alone but Windows cannot.~
2.  ~The test asserted `proc.returncode == 0`, which I found is `True` whether the two LICENSE.txt are different or not. Instead I asserted the output `diff = proc.stdout.decode('utf-8')` should be blank.~
~These changes appear to work on my mac as well, so hopefully …
=> License tests compatible with Windows

bokeh/model.py, bokeh/models/layouts.py, bokeh/sphinxext/_templates/sri_table.html, bokeh/sphinxext/bokeh_directive.py, bokeh/sphinxext/bokeh_enum.py, bokeh/sphinxext/bokeh_gallery.py, bokeh/sphinxext/bokeh_jinja.py, bokeh/sphinxext/bokeh_model.py, bokeh/sphinxext/bokeh_options.py, bokeh/sphinxext/bokeh_palette_group.py, bokeh/sphinxext/bokeh_plot.py, bokeh/sphinxext/bokeh_prop.py, bokeh/sphinxext/bokeh_releases.py, bokeh/sphinxext/bokeh_settings.py, bokeh/sphinxext/bokehjs_content.py, bokeh/sphinxext/collapsible_code_block.py, bokeh/sphinxext/templates.py, sphinx/source/_static/custom.css, sphinx/source/_templates/scripts.html
OK ostensibly this fixes (or at least improves) the jumpy anchors. But I wanted to take the opportunity to also clean up many things in `bokeh.sphinxext`. Some highlights:
* improve jumpy anchors
* fix broken collapsible SRI hash tables (discovered during this PR)
* use consistent code pattern for custom node visitors
* refactor `bokeh-plot` into smaller functions
There's plenty more that could still be improved but this seemed like a good stopping point for now. @hyles-lineata please build the docs locally with this PR and check them out. Things look good to me but a second pair of eyes would be good. Additionally please leave any comments or questions on the changes themselves.
=> Cleanup bokeh.sphinxext

tests/unit/bokeh/io/test_export.py
Skips `test_get_svg_no_svg_present()` of `tests/unit/bokeh/io/test_export.py` due to unknown diff in `xlink:href` of output. This is currently causing universal failure of Bokeh-CI unit tests.
ref: #11460
=> Skip svg export test

bokeh/models/renderers.py, bokeh/plotting/_graph.py, bokeh/plotting/_renderer.py, bokehjs/src/lib/api/plotting.ts, bokehjs/src/lib/models/renderers/glyph_renderer.ts, bokehjs/test/unit/models/renderers/glyph_renderer.ts, tests/unit/bokeh/plotting/test__graph.py, tests/unit/bokeh/plotting/test__renderer.py
Muted glyphs are only handled if "muted_" properties were specified. This conflicts with `plot.legend.click_policy = 'mute'` since the click policy can be set without "muted_" glyph properties.
Handle `muted_glyph` in the same manner as `nonselection_glyph` - unconditionally created, and if no "muted_" properties are specified, the default `muted_glyph` has the same properties as the main glyph, except alpha overridden at 0.2.
=> Add default muted glyph unconditionally

bokeh/core/property/bases.py, bokeh/core/property/container.py, bokeh/core/property/descriptors.py, tests/unit/bokeh/core/property/test_bases.py, tests/unit/bokeh/core/property/test_container.py
After a little back and forth, I think this is the most minimal change, that also makes no new public API commitments. I contemplated making `validate` accept a `hint` directly but that would have required a huge number of tedious changes, opened up a new public parameter, and also left open what to do if inapplicable hints were passed to the wrong targets. 
With this change the benchmark from the OP is now ~constant independent of the number of columns (about 1-2 ms on my laptop) cc @JulianHirsch
Here is the lightly updated benchmark:
<details>
```python
#Using Bokeh==2.3.0 as server app
import pandas as pd
from bokeh.plotting import figure, curdoc, show
from bokeh.models import ColumnDataSource
from bokeh.layouts import layout
import random
import time
N_test = 3 …
```
=> Make prepare_value more efficient for hinted ColumnData events

conda.recipe/meta.yaml, setup.py
While updating the [CI section](https://docs.bokeh.org/en/latest/docs/dev_guide/testing.html#continuous-integration) of the dev docs, I noticed some outdated information in `meta.yaml` (e.g. `sphinx >=1.8`).
This PR removes the sections `test` and `extra` that are no longer needed.
cc @bryevdv
=> Remove test and extra sections from meta.yaml

ci/run_downstream_tests.sh
As the title says. Can also finally switch to pytest for HoloViews tests as soon as I tag a HoloViews 2.0 dev release.
=> Add panel to downstream tests

bokeh/document/document.py, bokeh/server/callbacks.py
[take three, new branch]
ref: #11486
This smaller PR removes the reference cycles introduced by our wrappers for Tornado's callbacks:
* The wrappers had a back-reference to `document` that is completely unused and unnecessary. This was removed.
* Removes the `_callback_objs_by_callable` cruft that has documents referencing session callback wrappers directly
Before this change,  uncollected documents could occur with referrers through the methods for these callback wrappers:
```
2021-08-09 13:15:08,752   uncollected Documents: 1
2021-08-09 13:15:08,757 [[<bokeh.document.document.Document object at 0x19de9efd0>], <bound method Document.add_next_tick_callback of <bokeh.document.document.Document object at 0x19de9efd0>>, <bound method Document.add_periodic_callback of …
```
=> Document Refs Cleanup (part 2)

.gitignore, bokeh/application/handlers/code.py, bokeh/core/query.py, bokeh/document/document.py, bokeh/document/events.py, bokeh/document/models.py, bokeh/document/modules.py, bokeh/embed/util.py, bokeh/io/notebook.py, bokeh/model/model.py, bokeh/sphinxext/example_handler.py, sphinx/source/docs/releases/2.4.0.rst, tests/unit/bokeh/core/test_query.py, tests/unit/bokeh/document/examples.log, tests/unit/bokeh/document/test_document.py, tests/unit/bokeh/document/test_events__document.py, tests/unit/bokeh/document/test_models.py, tests/unit/bokeh/document/test_modules.py, tests/unit/bokeh/server/test_session__server.py
This continues preparatory cleanup work to improve Document event handling. This PR factors a few hundred lines out of `Document` by:
* delegating module handling to a new `DocumentModuleManager`
* delegating model ("all models") handling to a new `DocumentModelManager`
* consolidates processing (incoming JSON,  outgoing JSON, event objects to trigger) all on the event classes
as well as a few smaller cleanup moves. 
The new classes have full tests which makes these low-level corners of Bokeh more well-covered. 
cc @mattpap If you have time to take a quick look please do, but assuming downstream tests continue to look good, I plan to merge this tomorrow (unless there is some serious concern)
As an aside, for 3.0 I think we should work to disentangle some concepts from the very overloaded …
=> Document Refs Cleanup (part 3)

tests/unit/bokeh/util/test_version.py
I don't think this is a great solution but I also don't think hours of back and forth trying to diagnose on CI is a worthwhile use of anyone's time. 
FWIW `__version__` is literally just `get_version()` on import so the only explanation I can even plausibly come up with is that the unit tests are run in one process and something is dumping a non-ignored file into the repo in some earlier test. But I can't repro anything like that locally.
=> Quick fix for CI version check issue

bokeh/resources.py, tests/unit/bokeh/test_resources.py
After #11506 running no longer picked up the "most recent" CDN version prior to the local dev/tag version. This resolves  that.
Noting, the reason tests did not pick up on it is because the parameterized test versions in `test_resources.py` were hard coded. Ideally there would be a way to maintain that our test versions are in fact the correct style (now pep440, previously git-describe).
=> Update resources for pep440 dev versions

.github/workflows/bokeh-ci.yml, bokeh/tile_providers.py, ci/environment-test-3.7.yml, ci/environment-test-3.8.yml, ci/environment-test-3.9.yml, environment.yml, sphinx/source/conf.py, sphinx/source/docs/user_guide/examples/geo_xyzservices.py, sphinx/source/docs/user_guide/geo.rst, tests/unit/bokeh/test_tile_providers.py
Adding support of `xyzservices.TileProvider` as an input of `get_provider` following the suggestion 1) from #11500.
=> Support xyzservices.TileProvider as an input of get_provider

bokeh/models/glyphs.py
This PR adds a note to the docstring of Line about a limitation of HTML canvas with coordinates far outside the viewport.
(partially) fixes #11498
=> Add note about canvas limitation for Line

bokehjs/src/lib/models/widgets/file_input.ts, bokehjs/test/unit/models/widgets/file_input.ts
**Fix simultanous assignment of filenames, values and mime_types of the FileInput widget**
**Visual test:**
```python
from bokeh.models import FileInput, CustomJS, TextInput
from bokeh.io import curdoc
myFileNames = TextInput(value="", title="Number of file names:")
myFileValues = TextInput(value="", title="Number of file values:")
myFileInput = FileInput(accept='.pdf',multiple=True)
myFileInput.js_on_change("value", CustomJS(args=dict(myFileNames=myFileNames, myFileValues=myFileValues), code="""
// get number of file names
myFileNames.value = this.filename.length.toString();
// get number of file values
myFileValues.value = this.value.length.toString();
"""))
curdoc().add_root(column(myFileInput, myFileNames, myFileValues))
```
Before (v2.3.3):
After …
=> Fix simultaneous assignment properties in `FileInput` widget

bokeh/command/subcommands/serve.py, tests/unit/bokeh/command/subcommands/test_serve.py
Very simple extension which will allow frameworks which build on Bokeh (e.g. Panel) to extend the `bokeh serve` subcommand by modifying `applications` dictionary in the serve subcommand. I realize this is probably very narrowly useful for Panel in particular but would allow me to avoid various hacks/workarounds to add a monitoring application in `panel serve`.
=> Allow extensions to modify applications in serve subcommand

bokehjs/src/lib/models/widgets/numeric_input.ts
Partial fix to suspected socket conflict in `widgets/numeric_inputs.ts` when the JS side assigns `model.value` the at the same time as the Python side.
Currently, `model.value` is reassigned at every `high.change` or `low.change` event, though this isn't necessary if `model.value` is already within those bounds.
This doesn't fully fix the issue because the conflict will arise if `model.value` is indeed _outside_ the new bounds and is correctly re-assigned on the JS side. Perhaps a bounding method on the Python side could help too?
- [X ] issues: partially addresses #11504
=> Reassign value on numeric_input high-low change only if needed

bokeh/embed/bundle.py, tests/unit/bokeh/embed/test_bundle.py
Currently only bokeh resources served by the `StaticHandler` get a version hash appended ensuring that they are not cached when the version changes. Here we add an equivalent hash to any bokeh extensions served on the `/static/extensions/` endpoint of the server.
Ideally we would try to use the `StaticHandler.append_version` but that computes a version from the `settings.bokehjsdir()` and the bundling code is currently not structured in a way that makes this straightforward.
=> Add version as request argument to extension to avoid browser caching

bokehjs/src/lib/core/types.ts, bokehjs/src/lib/core/util/canvas.ts, bokehjs/src/lib/core/util/ndarray.ts, bokehjs/src/lib/core/util/pretty.ts, bokehjs/src/lib/core/util/types.ts, bokehjs/src/lib/models/glyphs/circle.ts, bokehjs/src/lib/models/widgets/button_group.ts, bokehjs/src/lib/polyfill.ts, bokehjs/test/unit/core/util/pretty.ts
=> Fix IE/legacy compatibility issues with bokeh 2.4

sphinx/source/_static/custom.css
Quick fix for https://github.com/pydata/pydata-sphinx-theme/issues/464
=> Better formatting for args lists in docstrings

bokeh/core/property/string.py, bokeh/embed/bundle.py, bokeh/models/text.py, bokehjs/src/lib/models/axes/axis.ts, bokehjs/src/lib/models/text/utils.ts, bokehjs/test/unit/models/axes/axis.ts, tests/unit/bokeh/embed/test_bundle.py, tests/unit/bokeh/models/test_axes.py
Strings with MathJax default TeX delimiters are now converted into TeX object.
Bokeh's bundler will check for those delimiters and include `bokeh-mathjax`.
Discussion on bundler and finding mathstrings #11589
=> Mathstring conveniences for axis_labels and tick labels

bokehjs/src/lib/core/graphics.ts, bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/model.ts, bokehjs/src/lib/models/axes/axis.ts, bokehjs/src/lib/models/text/base_text.ts, bokehjs/src/lib/models/text/math_text.ts, bokehjs/src/lib/models/text/plain_text.ts, bokehjs/src/lib/models/text/utils.ts, bokehjs/test/unit/core/util/eq.ts, bokehjs/test/unit/models/axes/axis.ts, bokehjs/test/unit/models/text/utils.ts
This also addresses some of my concerns from recent "math text" PRs. I also found a glaring bug in `HasProps` equality, which I fixed in this PR, but I still need to investigate a document unit test failure.
fixes #10391
=> Don't use regular expressions for parsing delimited strings

bokeh/_testing/util/project.py, bokeh/application/application.py, bokeh/application/handlers/directory.py, bokeh/application/handlers/handler.py, bokeh/application/handlers/request_handler.py, bokeh/protocol/__init__.py, bokeh/protocol/message.py, tests/codebase/__init__.py, tests/codebase/test_eslint.py, tests/codebase/test_flake8.py, tests/codebase/test_isort.py, tests/codebase/test_json.py, tests/codebase/test_license.py, tests/codebase/test_no_client_server_common.py, tests/codebase/test_no_ipython_common.py, tests/codebase/test_no_selenium_common.py, tests/codebase/test_no_tornado_common.py, tests/codebase/test_python_execution_with_OO.py, tests/codebase/test_windows_reserved_filenames.py
This PR removes unnecessary imports of tornado and refines the "no tornado test" to be much more comprehensive, covering every module unless explicitly noted in an allow-list. In the process other "no import tests" were also made more precise. 
This could certainly be backported, and presumably we will finish the mathtext work on `branch-2.4` so I will add the backport label.
=> Reduce Tornado imports

setup.cfg
Don't display report on successful flaky tests. Flaky will report only on tests that failed or failed intermittently.
=> Don't report successful flaky tests

sphinx/source/docs/dev_guide/setup.rst
Fixes path typo in dev guide setup instructions for Windows. Already discussed with @tcmetzger
=> Correct path in dev guide server instructions

bokehjs/src/lib/models/renderers/glyph_renderer.ts
This reduces render time from a few seconds to hundreds of milliseconds (based on the example from issue #11629). Further optimisations are possible.
fixes #11629
=> Compute indices' set difference more efficiently

bokeh/core/has_props.py, bokehjs/src/lib/base.ts, bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/core/util/cloneable.ts, bokehjs/src/lib/document/defs.ts, bokehjs/test/unit/core/has_props.ts, bokehjs/test/unit/core/util/cloneable.ts, bokehjs/test/unit/document/defs.ts, bokehjs/test/unit/models/text/utils.ts, tests/unit/bokeh/document/test_document.py
Allows code like this to work:
```py
from bokeh.core.properties import Instance
from bokeh.models.sources import ColumnDataSource
from bokeh.layouts import Row
from bokeh.plotting import Figure, show
from bokeh.model import DataModel
class Base(Row, DataModel):
cds = Instance(ColumnDataSource)
def __init__(self, **kwargs):
super().__init__(**kwargs)
self.cds = ColumnDataSource(data={'x': [0, 1], 'y': [2, 3]})
class Sub(Base):
def __init__(self, **kwargs):
super().__init__(**kwargs)
fig0 = Figure(width=200, height=200)
fig0.line(self.cds.data['x'], self.cds.data['y'], line_color="red")
self.children.append(fig0)
fig1 = Figure(width=200, height=200)
fig1.line(self.cds.data['x'], self.cds.data['y'], line_color="green")
self.children.append(fig1)
show(Sub())
```
Also improves handling of …
=> Allow data models to inherit from non data models

.github/workflows/bokeh-ci.yml, _setup_support.py, ci/verify_pip_install_from_sdist.sh, setup.py
This PR fixes argument checking to allow `setup.py bdist_wheel` to proceed FROM an sdist, using the pre-built BokehJS inside the sdist, without any additional command line arguments. As a consequence, `pip install .` now also works from inside an sdist. 
Steps have been added to confirm that all of the following function:
* `python setup.py sdist --install-js`  (what WE used to build official sdist)
* `python setup.py bdist_wheel --install-js` (what WE use  to build official wheel)
* `pip install .` from exploded sdist (what OTHERS use to re-package)
Additionally some of the extremely gorpy logic in the `setup.py` and `_setup_support.py` was streamlined and simplified. 
cc @ocefpaf
```
~/work/bokeh/dist bryanv/11658_sdist_pip_install*
piptest ❯ cd bokeh-2.4.0+13.gf4a36c48c.dirty …
```
=> Support "pip install ."

_setup_support.py, setup.py, sphinx/source/docs/dev_guide/setup.rst
With this PR The following is possible
```
python setup.py install
python setup.py develop
python setup.py sdist
python setup.py bdist_wheel
pip install .
```
Flags `--build-js` or `--install-js` can be added to any of the above to be explicit. 
Additionally, building from sdist will still use the packaged BokehJS and warn/fixup if either `--build-js` or `--install-js` is supplied.
=> build BokehJS by default

bokehjs/src/lib/models/widgets/autocomplete_input.ts, tests/integration/widgets/test_autocomplete_input.py
Issue: If `AutocompleteInput(...restrict=False)`, the input value would be assigned twice when selecting a valid completion.
Here's the solution in pseudocode:
```
if (this._open && this.menu.children.length > 0) {
// valid completion options are available, set value from menu
} else if (!this.model.restrict) {
// not restricted, so set as normal text input
}
```
=> Fix duplicate value change in autocomplete_input

bokehjs/src/lib/core/view.ts, bokehjs/test/integration/regressions.ts
This greatly simplifies tests that rely on updates to models and views.
=> Update root `View`'s `ready` promise along its descendants

examples/models/file/transform_jitter.py
The `transform_jitter.py` example was broken by https://github.com/bokeh/bokeh/pull/11400 however that example previously "demonstrated" the `Jitter` model in a way that no one should ever really emulate. I've updated the example to show proper usage (which also works with the change in #11400)
=> fix transform jitter example

examples/models/file/daylight.py
This adds a metadata block for one example script among the Bokeh examples.
=> Add metadata to examples/models/file/daylight.py (#11765)

bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/models/tools/edit/edit_tool.ts, bokehjs/src/lib/models/tools/edit/point_draw_tool.ts, bokehjs/test/unit/document/document.ts, sphinx/source/docs/releases/3.0.0.rst
This seems like a big omission and it always worked like this. Maybe there was historically a reason for this? Testing locally didn't show any issues with this change.
fixes #10621
=> Push to server only actually changed properties

.github/workflows/bokeh-docker-build.yml, .gitignore, bokehjs/make/tasks/test.ts, ci/docker/Dockerfile, ci/docker/bokeh_docker_build.sh, ci/docker/bokeh_docker_test.sh, ci/docker/entrypoint.sh
This partially addresses issue #11352 in providing the means to build a docker image for Bokeh development. Using the files here `docker build` and `docker run` work locally for me. The idea is to use github actions `workflow_dispatch` to build the image on demand via the github UI. For this to work, the workflow apparently needs to be in the default branch (`branch-3.0`), so this PR needs to be merged before I can correctly write the github action and test the docker image more widely. Therefore there will be at least one other PR to finalise this work, and probably another (with @tcmetzger's help) containing documentation.
Brief summary of docker image:
* It is based on Ubuntu 20.04, one of our officially supported platforms.
* Because docker isn't a fully-featured OS, neither `apt …
=> Docker dev image (#11352)

bokeh/command/subcommands/info.py, sphinx/source/docs/dev_guide/setup.rst, tests/unit/bokeh/command/subcommands/test_info.py
As discussed in https://github.com/bokeh/bokeh/pull/11795#discussion_r747914910, this PR adds OS information to the `bokeh info` command.
related to #11791
=> Add OS to bokeh info

sphinx/source/conf.py
The change in his PR successfully adds a cache-busting version to the `custom.css` link:
```html
<link rel="stylesheet" type="text/css" href="_static/custom.css?v=3.0.0dev1+19.g860b2c4d3.dirty">
```
This will hopefully prevent any need for force-reloads when dev docs are re-published to a fixed branch URL or when  a new version is published to `latest`. 
However, I don't love the implementation, which just brute force appends a query string to the filename. AFIK it relies on some assumptions about Sphinx behavior that  are not actually defined, and that I could imagine changing in the future (sphinx could start adding their own query strings, conflicting, or adding the query string here could interfere with filename detection, etc). 
@tk0miya Is there a "proper" way to do something like …
=> add a version query to custom.css

bokehjs/src/lib/client/connection.ts, bokehjs/src/lib/client/session.ts, bokehjs/src/lib/embed/notebook.ts, bokehjs/src/lib/protocol/message.ts, bokehjs/src/lib/protocol/receiver.ts, bokehjs/test/unit/protocol/message.ts
This PR is a side effect of stricter analysis of conditional expressions (PR #11763). The primary task of this PR is to establish the structure of partial messages, i.e. if `header`, `metadata` and `content` can be `null`. The secondary concern is to allow better static typing of messages' contents (`any` -> type parameterized).
=> Clarify handling and internal types of partial messages

bokehjs/src/lib/models/glyphs/webgl/dash_cache.ts, bokehjs/src/lib/models/glyphs/webgl/line_gl.ts, bokehjs/test/integration/glyphs/line.ts
Fixes item 6 of issue #11050.
Line dash patterns with an odd length were not handled correctly in the WebGL output backend, this PR fixes that. Correct behaviour to match the canvas backend is to repeat the dash pattern so that its length is even. Fix motivated by comment from @mattpap https://github.com/bokeh/bokeh/pull/10861#discussion_r592985851.
Dash patterns coming from Python are already sanitised before they reach the WebGL code, so this is only an issue for direct use of BokehJS.
I have modified an existing visual test that was using a dash pattern of `[4, 4]` to now use `[4]`. The PNG output is therefore the same as before, but is obtained by a slightly different code path. So strictly speaking this is not a full test in that it does not fail before the fix. I am happy to add an …
=> Correctly handle odd-length dash patterns in WebGL

.github/workflows/bokeh-ci.yml, .github/workflows/bokehjs-ci.yml
Renames `master` to `main` and adds `branch-*` to bokehjs-ci's configuration (I noticed that CI is not run for bokehjs on push, only PRs).
=> Update branches in CI workflow configurations

.github/workflows/bokeh-ci.yml, .github/workflows/bokehjs-ci.yml, bokehjs/src/lib/core/settings.ts, bokehjs/src/lib/models/canvas/canvas.ts, bokehjs/test/devtools/test.html
This will fail in HeadlessChrome/96.0.4664.45 due to `canvas.getContext("webgl")` (or `"webgl2"`) returning `null`. Things work in non-headless Chrome (same version).
=> Force webgl backend when requested for testing

.github/workflows/bokeh-ci.yml, ci/environment-test-3.10.yml, ci/environment-test-3.7.yml, ci/environment-test-3.8.yml, ci/environment-test-3.9.yml, classifiers.txt, tests/examples.yaml
This PR adds Python 3.10 to the unit testing matrix. This PR also removes numba and opencv from all test environments:
* they are the most problematic test dependencies
* the numba example runs w/o numba, just slowly — testing w/ numba adds nothing for us
* functionality in the opencv example is exercised in other examples
=> add Python 3.10 to CI

bokehjs/src/lib/client/connection.ts, bokehjs/src/lib/core/deserializer.ts, bokehjs/src/lib/core/has_props.ts, bokehjs/src/lib/document/defs.ts, bokehjs/src/lib/document/document.ts, bokehjs/src/lib/document/events.ts, bokehjs/src/lib/models/plots/plot.ts, bokehjs/test/unit/document/document.ts, bokehjs/test/unit/document/events.ts, bokehjs/test/unit/regressions.ts
This is a proof of concept. This removes `Document._compute_patch_since_json()` and changes when document is attached to models during initialization. This way we can use ordinary handling of model change events to propagate changes, that happen during initialization of models, to server.
fixes #11803
=> Robustify detection of changes during initialization

sphinx/source/docs/user_guide/examples/customizing_tools_icon.py, sphinx/source/docs/user_guide/examples/customizing_tools_tooltip.py, sphinx/source/docs/user_guide/tools.rst
Added documentation based on #11640, had a problem with adding icons from an URL, tried PNG icons it gave the following error `icon given the invalid value` in the dev tool.
Tried passing a PIL Image object, and it gave me this error `Object of type Image is not JSON serializable`
So I need help figuring out if the way I'm trying to change the icon is correct, and if you got any feedback on the PR.
=> bokeh/bokeh#11640 Document Tool.icon in user guide

bokehjs/src/lib/models/glyphs/webgl/markers.ts
Fixes item 5 of issue #11051.
The original conversion of the WebGL code to ReGL used a temporary fix for `circle` markers to deal with their dual nature of either having a `radius` in data units or a `size` in screen units. This PR removes that temporary fix as it is no longer needed.
Most of the work here is not the code removal but the checking that it is OK to remove it.
=> Remove temporary WebGL circle fix

bokeh/models/widgets/sliders.py, sphinx/source/docs/user_guide/examples/styling_math_text_latex_slider_widget_title.py, sphinx/source/docs/user_guide/interaction/widgets.rst, sphinx/source/docs/user_guide/styling.rst
This is a follow-up to #11815 and updates the user guide to describe adding mathtext to Sliders. 
Related to #11355.
=> Update docs for Slider, RangeSlider

.github/workflows/bokeh-docker-build.yml, ci/docker/docker_run.sh, ci/docker/entrypoint.sh
This PR updates the docker image to the point that it is usable, although probably not by end users yet. It closes issue #11352.
I will write a new "Working document" in the wiki to explain how it is used and built. Here is a summary of the improvements:
* Image is built on demand in github actions using `.github/workflows/bokeh-docker-build.yml`. There is an option to build and run the tests or not, if you do then the failed visual test images are saved in an artifact as usual.
* Image is tagged with 3 tags: `latest`, the date of building and major version of chrome. So a new image built today would be known as all of `bokeh-dev:latest`, `bokeh-dev:chrome_96` and `bokeh-dev:2021-12-06`.
* Image is stored in an artifact for download. Need to add option to upload to docker hub.
* Use of …
=> Docker image build and use

bokeh/models/graphs.py, bokehjs/src/lib/models/graphs/graph_hit_test_policy.ts, bokehjs/test/unit/models/graphs/graph_hit_test_policy.ts, examples/models/file/graphs.py, sphinx/source/docs/releases/3.0.0.rst, sphinx/source/docs/user_guide/examples/graph_interaction.py, sphinx/source/docs/user_guide/examples/graph_interaction_edgeslinkednodes.py, sphinx/source/docs/user_guide/examples/graph_interaction_nodesadjacentnodes.py, sphinx/source/docs/user_guide/examples/graph_interaction_nodeslinkededges.py, sphinx/source/docs/user_guide/graph.rst
The NodesAndAdjacentNodes policy highlights the adjacent nodes (those which are connected by a linked edge) of an inspected/selected node. A single selection is set with all adjacent nodes and the inspected/selected node, with the inspected/selected node as the last entry to identify it from its adjacent nodes. If a node does not have any adjacent nodes, only the inspected/selected node is set in the selection.
I added a brief explanation of the policy that gets pulled into the reference guide, and an associated unit test similar to those for the NodesAndLinkedEdges and EdgesAndLinkedNodes selection policies.
=> Add policy to find adjacent nodes by selecting node

bokeh/colors/color.py, bokeh/colors/hsl.py, bokeh/colors/rgb.py, tests/unit/bokeh/colors/test_color__colors.py
Fixes #11845 
This PR was developed with @cuevasm1
`Color.lighten()` and `Color.darken()` originally converted the object to an `HSL` object then adjusted the luminescence. However, this conversion triggered `HSL`'s deprecation warning.
In order to combat this warning, `Color.lighten()` and `Color.darken()` works as follows:
1. converts the object to an `RGB` object
2. extracts the hue, saturation, and luminescence using `colorsys.rgb_to_hls()`
3. adjusts the luminescence from **2.**
4. retrieves the new r, g, b value using `colorsys.hls_to_rgb()`
5. updates the `RGB` object from **1.** with the r, g, b values from **4.**
6. returns `self.from_rgb(<RGB object from **5.**>)`
However, this process destroyed the hue and saturation conservation when an HSL object was fully lightened or …
=> Color.lighten() and Color.darken() using RGB instead of HSL

bokeh/core/_templates/autoload_request_tag.html, bokeh/core/_templates/autoload_tag.html, bokeh/core/_templates/css_resources.html, bokeh/core/_templates/file.html, bokeh/core/_templates/js_resources.html, bokeh/core/_templates/notebook_load.html, bokeh/core/_templates/plot_div.html, bokeh/core/_templates/script_tag.html, bokeh/core/templates.py, sphinx/source/docs/user_guide/embed.rst, tests/unit/bokeh/core/test_templates.py
WIP - I'm not currently happy with how this looks because the templates still aren't "clean" - there's still manual wrangling to get the line breaks mostly right. And even then, there are still a couple unnecessary line breaks. So far my approach has been:
1. Set `trim_blocks=True, lstrip_blocks=True` in the Jinja environment
2. Add tests for immediate issue of white space at the top of HTML, and scripts being pulled up to the previous line
3. Remove most block indentation from `file.html`
4. Manually wrangle whatever didn't look right by selectively adding `{% -%}` or `{%- %}` or `indent(x)`
<details>
<summary>
Initial before/after comparison
</summary>
Before:
After:
</details>
=> Cleaner white space/indentation in templates

environment.yml
On a fresh environment this leaves me with node.js v16.13.0
=> Cap node version below v17

bokeh/models/plots.py, bokehjs/src/lib/models/plots/plot.ts, bokehjs/test/unit/models/plots/plot.ts, sphinx/source/docs/first_steps/first_steps_4.rst, sphinx/source/docs/releases/3.0.0.rst, sphinx/source/docs/user_guide/tools.rst, tests/unit/bokeh/models/test_plots.py
Notes:
- Added tests for `add_tools()` as well
- `add_tools()` was demonstrated twice in the docs, so replaced the latter with a demonstration of `remove_tools()`
- Added imports to the docs for additional clarity
=> add plot.remove_tools() method

.github/workflows/bokeh-release-build.yml, .github/workflows/bokehjs-ci.yml, bokehjs/package.json, ci/environment-build.yml, ci/environment-release-build.yml, ci/environment-release-deploy.yml, ci/environment-test-3.10.yml, ci/environment-test-3.7.yml, ci/environment-test-3.8.yml, ci/environment-test-3.9.yml, ci/install_node_modules.sh, conda.recipe/meta.yaml, environment.yml, sphinx/source/docs/dev_guide/setup.rst
Upgrading to the most recent LTS version (which will be valid until October 2022). Also requires npm@8 for the sake of consistency.
=> Require nodejs 16.* LTS for dev and testing

bokeh/models/map_plots.py, bokehjs/src/lib/models/plots/gmap.ts, bokehjs/src/lib/models/plots/gmap_plot.ts, bokehjs/src/lib/models/plots/gmap_plot_canvas.ts, bokehjs/src/lib/models/plots/index.ts, bokehjs/src/lib/models/plots/plot_canvas.ts, bokehjs/test/defaults/index.ts
GMaps' support was broken on multiple-levels by a few 3.0 PRs. This PR restores the support and removes any special handling of GMaps from `PlotCanvasView`.
=> Fix gmaps' support and remove special handling

bokeh/core/property/bases.py, bokeh/core/property/dataspec.py, bokeh/core/property/descriptors.py, bokeh/core/property/either.py, bokeh/core/property/instance.py, tests/unit/bokeh/core/test_properties.py, tests/unit/bokeh/test_objects.py
For example, `Nullable(Instance(Model))` does not have an unstable default. This avoids pointless serialization of e.g. `Renderer.coordinates`, which previously was always present in the serialized output, despite having `None` default value.
=> Make `_may_have_unstable_defaults()` more robust

bokeh/models/sources.py, tests/unit/bokeh/models/test_sources.py
I've already had the annoying experience of fixing up example code from support questions to be able to test with `branch-3.0` at least a half a dozen times. I think we need to be more gentle with users about removing `CDSView.source`. 
cc @mattpap
=> Deprecate CDSView.source more gracefully

release/build.py, release/config.py, release/git.py, release/stages.py
Will need to cut a release build to actually test this out, but this PR should:
* keep explicit track of files that have been modified by build steps
* only commit those files to the release branch (and make sure modified files not *new* files)
* verify that the repo is clean after files marked modified are commited
=> Track modified files in release build more carefully

bokeh/server/session.py
dask.distributed intermittently logs:
`RuntimeWarning: coroutine '_needs_document_lock.<locals>._needs_document_lock_wrapper' was never awaited`
with this wrapper it will be possible to see which method wasn't
awaited
=> add functools.wraps to _needs_document_lock_wrapper

sphinx/source/_templates/layout.html
This PR fixes the extra whitespace described in #11987 by adding an additional block (`docs_toc`) to our `layout.html` file.
=> Update Sphinx template to remove whitespace

ci/environment-release-build.yml, ci/environment-test-3.10.yml, ci/environment-test-3.8.yml, ci/environment-test-3.9.yml, environment.yml, sphinx/source/conf.py
This PR adds the [sphinx_copybutton](https://sphinx-copybutton.readthedocs.io/en/latest/index.html) extension to the docs.
I have used a pretty standard configuration, the only customization is to enable stripping of command prompts (https://sphinx-copybutton.readthedocs.io/en/latest/use.html#strip-and-configure-input-prompts-for-code-cells). This is relevant for some examples in the Reference guide (e.g. http://localhost:5009/en/latest/docs/reference/layouts.html).
=> Add sphinx_copybutton

bokeh/document/locking.py, sphinx/source/docs/user_guide/server.rst, tests/unit/bokeh/document/test_locking.py
Remove references to `tornado.gen.coroutine` in docs in favor of async functions.
Change `bokeh.document.locking.without_document_lock` to work for async functions and functions decorated with `asyncio.coroutine`.
=> Remove references to gen.coroutine from docs and update without_document_lock decorator

examples/app/README.md, examples/app/gapminder/main.py, examples/app/spectrogram/description.html, examples/custom/parallel_plot/parallel_selection_tool.ts, examples/embed/arguments/README.md, examples/embed/server_session/serve.py, examples/howto/Categorical Data.ipynb, examples/howto/Linked panning.ipynb, examples/howto/ipywidgets/README.md, examples/howto/layouts/words_and_plots.py, examples/howto/notebook_comms/Continuous Updating.ipynb, examples/howto/notebook_comms/Numba Image Example.ipynb, examples/howto/server_embed/flask_gunicorn_embed.py, examples/howto/server_embed/notebook_embed.ipynb, examples/models/file/iris_splom.py, examples/plotting/file/bessel.py, examples/plotting/file/box_annotation.py, examples/plotting/file/custom_layout.py, examples/plotting/file/latex_blackbody_radiation.py, examples/plotting/file/les_mis.py, examples/plotting/file/ridgeplot.py, examples/plotting/file/tile_source.py
This PR fixes part of #11765, supersedes #11901, and also includes typo fixes for various files under the `examples` directory.
=> Add metadata to tile_source.py and fix various typos

bokehjs/examples/hover/hover.ts, bokehjs/src/lib/models/glyphs/harea.ts, bokehjs/src/lib/models/glyphs/varea.ts, bokehjs/src/lib/models/tools/inspectors/hover_tool.ts
This PR adds tooltip support for Patch and Area glyphs. Hit testing for both glyphs was already added, and so this PR is largely updating the handling of the hit test result to determine _what_ to show in the tooltip.
**Considerations**
Based on initial [discussions](https://github.com/bokeh/bokeh/discussions/11979) and follow up via Slack there are possibly some different ideas about how this could be implemented and what use cases would be addressed.
My use case relates to viewing stacked time series data, specifically using a VArea. One example is viewing web traffic to different marketing channels overtime and being able to stack the data for each channel so you can visually see the changes in proportion of time. Being able to then hover and see extra contextual information - value of …
=> Hover tooltips for Patch and Areas

bokeh/core/has_props.py, bokeh/core/property/_sphinx.py, bokeh/core/property/bases.py, bokeh/core/property/descriptors.py, bokeh/core/property/instance.py, bokeh/model/model.py, tests/unit/bokeh/core/property/test_descriptors.py, tests/unit/bokeh/core/property/test_instance.py, tests/unit/bokeh/core/test_has_props.py, tests/unit/bokeh/document/test_document.py, tests/unit/bokeh/document/test_events__document.py
Serialization of unstable properties is different depending on what `HasProps` methods were called. e.g.:
Before this PR:
```py
In [1]: from bokeh.models import *
In [2]: p = Plot()
In [3]: p._to_json_like(include_defaults=False)
Out[3]: {}
In [4]: p._to_json_like(include_defaults=False)
Out[4]: {}
In [5]: p.references(); # this touches all values, thus resolves unstable defaults
In [6]: p._to_json_like(include_defaults=False)
Out[6]: 
{'y_scale': LinearScale(id='1005', ...),
'toolbar': Toolbar(id='1007', ...),
'x_range': DataRange1d(id='1002', ...),
'y_range': DataRange1d(id='1003', ...),
'x_scale': LinearScale(id='1004', ...),
'title': Title(id='1006', ...)}
```
After this PR:
```py
In [1]: from bokeh.models import *
In [2]: p = Plot()
In [3]: p._to_json_like(include_defaults=False) …
```
=> Discover unstable defaults in `HasProps.__init__()`

sphinx/source/docs/user_guide/server.rst
It's just a 1 character typo fix. Do with it as you wish :)
=> Fixed typo: s/server/serve/

examples/plotting/file/airports_map.py, examples/plotting/file/multi_line.py, examples/plotting/file/rect.py, examples/plotting/file/scatter_selection.py, examples/plotting/file/toolbar_autohide.py, examples/plotting/file/twin_axis.py
This PR adds metadata to 5 more examples and corrects metada in one example.
New are:
- toolbar_autohide.py
- rect.py
- scatter_selection.py
- twin_axis.py
- multi_line.py
Changes are in:
- airports_map.py
=> 11765 add metadata to examples

bokeh/embed/util.py
WIP starting with `RenderRoot`. I have yet to do a survey for more opportunities. Note I preserved the default empty string and empty list for `name` and `tags`, respectively. Let me know if `Unspecified` would be more desirable here.
=> RenderRoot dataclass

bokeh/models/glyphs.py
As @ianthomas23 noticed, the docs for `HexTile` are missing help for `aspect_scale` and `orientation`. This PR adds those texts.
=> Update docs for HexTile

bokeh/models/glyphs.py, tests/unit/bokeh/models/test_glyphs.py
=> Fix passing of kwargs in Image glyph's constructor

bokeh/sphinxext/bokeh_plot.py, examples/models/file/basic_plot.py, examples/models/file/widgets.py, examples/plotting/file/airports_map.py, examples/plotting/file/periodic_shells.py, examples/plotting/file/unemployment.py, examples/plotting/file/us_marriages_divorces_hover.py
While working on #12066 I found some missing "sampledata" tags, one was added without loading sampledata and some typos are corrected. Additional the "bokeh-example-metadata" is added for "periodic_shells.py" and "us_marriages_divorces_hover.py".
I want to merge this into main because I am not sure how my progress on #12066 will be.
=> 11765 typos in metadata documentation

bokehjs/src/lib/models/glyphs/annular_wedge.ts, bokehjs/src/lib/models/glyphs/wedge.ts, bokehjs/test/unit/models/glyphs/annular_wedge.ts, bokehjs/test/unit/models/glyphs/wedge.ts
This changes the hit-test calculations in Wedge and AnnularWedge so they are performed in screen-space, since the glyphs are rendered as circles in screen space.
This doesn't add any tests yet, but I'll work on that soon.
=> Fix Wedge and AnnualWedge glyph hitboxes

bokeh/models/widgets/tables.py, bokehjs/src/lib/models/widgets/tables/cell_formatters.ts, bokehjs/test/unit/models/widgets/tables/cell_formatters.ts
Note that this PR fixes the error when passing in a null value to the ScientificFormatter. The output is now the exact same as when you use a NumberFormatter:
=> 11965 fixes that null value with unspecified nan_format crashes table rendering

bokehjs/src/lib/models/glyphs/webgl/line_gl.ts
This is a minor refactor of the WebGL line code to remove unnecessary code duplication for ReGL calls and remove an unnecessary member variable. There is no functional change.
This work is part of the CZI round 3 extension.
=> WebGL line refactor

bokehjs/src/lib/models/glyphs/annular_wedge.ts, bokehjs/src/lib/models/glyphs/wedge.ts, bokehjs/test/unit/models/glyphs/annular_wedge.ts, bokehjs/test/unit/models/glyphs/wedge.ts
When Wedge and AnnularWedge glyphs go all the way around a full circle,
the hit test would always fail. This is because `angle_between()`
normalizes between 0 and 2*pi, then returns false if they are equal.
This adds an additional check in the glyph's hit testing such that if
the start and end angle are more than a full circle apart, it is
considered a hit because the wedge is going all the way around in a
circle.
I chose to add a check in each glyph's hit test rather than modify `angle_between()` because I'm not sure where else that function is used, and I'm not sure if that would be appropriate behavior for that function.
feature. …
=> Fix full-circle wedge hit test

examples/models/file/buttons.py
Adding metadata to examples/models/file/buttons.py. I need help for filling the refs attributes in the file. Even the API's, I got them from the document section and dot (.) operation to the classes. Let me know this is correct process or there is a specific place to checkout the API's as well. I am asking to contribute to more examples.
=> Adding metadata to examples/models/file/buttons.py #11765

sphinx/source/docs/first_steps/installation.rst
This PR updates the version in the URL of the CDN example links in the installation docs page. Fixes #12144.
=> Fix versions in js cdn links

sphinx/source/docs/user_guide/server.rst
Addresses #12152 
Reorganize section on load balancing to include configuration for Apache, remove trailing slash in Apache proxy config.
=> Add load balancing implementation for Apache in documentation

bokehjs/src/less/widgets/inputs.less, bokehjs/src/lib/models/widgets/input_widget.ts
A follow up after PR #12154. In this PR, instead of toggling visibility of description icon, opacity is changed instead. Here's the default look:
The opacity changes to full when hovered or clicked.
This is technically configurable on CSS level. It could be made configurable through a property if needed so.
=> Toggle opacity not visibility of descriptions

bokehjs/src/lib/core/util/zoom.ts, bokehjs/src/lib/models/tools/actions/zoom_base_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_in_tool.ts, bokehjs/src/lib/models/tools/actions/zoom_out_tool.ts, bokehjs/test/unit/models/tools/actions/zoom_in_tool.ts, bokehjs/test/unit/models/tools/actions/zoom_out_tool.ts
Proper inverse factors for the way we compute things (about a center):
```python
```
I have updated the zoom-in and zoom-out tests to mirror each other as inverses.
=> use correct zoom scale factors

bokeh/models/formatters.py, bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts, bokehjs/test/unit/models/formatters/datetime_tick_formatter.ts, examples/models/file/daylight.py, sphinx/source/docs/user_guide/examples/categorical_scatter_jitter.py
Incredibly, no tests were disturbed the these changes 😲 
This PR also exposes `strip_leading_zeros` as a public property.
I do intend one more commit to add tests, at least for the new deprecation codepath, but hopefully some long overdue unit tests of the implementation itself. 
CC @bokeh/dev it would probably be reasonable to review the default formats at this time. FWIW, looking over the old code, when there was a list of formats, the one that resulted in the shortest formatted tick was always chosen.
=> Simplify DatetimeTickFormatter scale format type

ci/environment-test-3.10.yml, ci/environment-test-3.8.yml, ci/environment-test-3.9.yml, ci/environment-test-minimal-deps.yml, environment.yml, sphinx/.gitignore
Selenium 4.3 was just released, which breaks a large number of our integration tests. Nothing in the [`CHANGELOG`](https://github.com/SeleniumHQ/selenium/blob/trunk/py/CHANGES) really stands out, and the failures are assertion failures, not exceptions or errors. Until the root problem can be identified, pin to version 4.2
=> Pin Selenium 4.2

bokeh/core/enums.py, bokeh/models/formatters.py, bokehjs/src/lib/core/enums.ts, bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts, bokehjs/test/unit/core/enums.ts, bokehjs/test/unit/models/formatters/datetime_tick_formatter.ts, examples/plotting/file/hover_glyph.py, sphinx/source/docs/user_guide/examples/styling_datetime_tick_context.py, sphinx/source/docs/user_guide/styling.rst, tests/unit/bokeh/core/test_enums.py
cc @bokeh/dev @jbednar @RiccardoGiro @carve11
This PR adds three new properties to `DatetimeTIckFormatter` that can be used to add additional context:
```python
context = Nullable(Either(String, Instance("DatetimeTickFormatter")), default=None, help="""
A format for adding context to the tick or ticks specified by ``context_which``.
""")
context_which = Enum(ContextWhich, default="start", help="""
Which tick or ticks to add a formatted context string to.
""")
context_location = Enum(LocationType, default="below", help="""
Relative to the tick label text baseline, where the context should be
rendered.
""")
```
This value controls what context is displayed. Values can  be:
* None, no context is added
* A standard `DatetimeTickFormatter` format string, the single format is used across all …
=> Add context formatter for datetime axes

sphinx/source/_static/custom.css
This PR partially fixes some small CSS issues mentioned in https://github.com/bokeh/bokeh/issues/12203
Specifically:
=> Minor 3.0 docs updates

bokeh/sphinxext/_templates/gallery_page.rst, bokeh/sphinxext/bokeh_gallery.py, sphinx/source/docs/gallery.json
This PR adds support for an "alt" field in the `gallery.json` details. This optional field is rendered as an HTML alt tag in the corresponding gallery thumbnail images:
@pavithraes once this is merged, there is a "place" to make placeholder edits for the alt-text PR for gallery examples (other `image` directives will need to have placeholders added manually)
cc @tcmetzger
=> Add support for alt tags for gallery thumbnails

bokeh/core/property_mixins.py, bokeh/models/glyphs.py, bokeh/models/selections.py, bokehjs/src/lib/core/property_mixins.ts, bokehjs/src/lib/core/util/templating.ts, bokehjs/src/lib/core/visuals/image.ts, bokehjs/src/lib/core/visuals/index.ts, bokehjs/src/lib/models/glyphs/image_base.ts, bokehjs/src/lib/models/selections/selection.ts, bokehjs/src/lib/models/tools/inspectors/hover_tool.ts, bokehjs/test/unit/core/util/templating.ts
This PR does two things: 
* Fixes image selection/nonselection highlighting (at least for point hit testing) by converting the awkward `global_alpha` property to be a proper "visual". Now if you specify `nonselection_alpha` on an image glyph it does what is expected:
* Exposes `Selection.image_indices` publicly, so that users may inspect detailed image selections. Additionally, `Selection.indices` is set with the top-level index (i.e. which image). 
I will look in to adding tests, but the implementation is complete and ready for review.
=> Improvements to image selection and highlighting

sphinx/source/docs/dev_guide/documentation.rst
This PR updates an intersphinx reference to the Sphinx docs that has become outdated after an update of the Spinx documentation.
=> Fix intersphinx doc reference

bokeh/models/widgets/sliders.py, bokehjs/src/lib/models/widgets/abstract_slider.ts, bokehjs/src/lib/models/widgets/date_range_slider.ts, bokehjs/src/lib/models/widgets/date_slider.ts, bokehjs/test/unit/models/widgets/slider.ts, sphinx/source/docs/user_guide/interaction/widgets.rst, tests/integration/widgets/test_dateslider.py
- Updated `_calc_to()` in `DateRangeSliderView` as suggested by @ianthomas23
- In  `AbstractBaseSliderView` I exposed `steps` from the noUiSlider API so we could unit test down to the slider level
- I don't have selenium on my machine at the moment, so I'll wait and see if integration tests break in CI. May be useful to add a new integration test to demonstrate fewer change events as the slider is dragged?
=> Convert DateRangeSlider/DateSlider step to days

bokeh/transform.py, ci/install_downstream_packages.sh, sphinx/source/docs/first_steps/examples/first_steps_5_color_mapping.py, sphinx/source/docs/user_guide/examples/styling_linear_mappers.py
ref: #12223 
cc @mattpap 
This PR reverts the parameter name change of `field_name` -> `field` for functions in `bokeh.transforms`. I do think that `field` is very slightly more terminologically preferable, however:
* Dask does depend on passing `field_name` by keyword in places
* It appears before other positional parameters, so there is no smooth or clean way to enact a deprecation
Rather than potentially grief all Dask users and maintainers over a minuscule change, I am reverting it.
=> Revert field_name rename

bokeh/core/properties.py, bokeh/core/property/factors.py, bokeh/core/property/nullable.py, bokeh/core/property/required.py, bokeh/models/annotations/html/labels.py, bokeh/models/annotations/labels.py, bokeh/models/callbacks.py, bokeh/models/dom.py, bokeh/models/expressions.py, bokeh/models/filters.py, bokeh/models/map_plots.py, bokeh/models/selectors.py, bokeh/models/sources.py, bokeh/models/text.py, bokeh/models/textures.py, bokeh/models/tickers.py, bokeh/models/tiles.py, bokeh/models/tools.py, bokeh/models/transforms.py, bokeh/models/ui/dialogs.py, bokeh/models/ui/icons.py, bokeh/models/ui/menus.py, bokeh/models/ui/tooltips.py, bokeh/models/widgets/buttons.py, bokeh/models/widgets/sliders.py, bokeh/models/widgets/tables.py, examples/custom/font-awesome/fontawesome_icon.py, tests/unit/bokeh/core/property/test_nullable.py, tests/unit/bokeh/core/property/test_required.py, tests/unit/bokeh/core/test_properties.py
So that we can avoid `from bokeh.core.properties import NonNullable as Required`. This rename makes sense, because `null`/`None` has no significance in bokeh's type system anymore. In fact in the long term, it would be better to use more symbols/domain specific singletons. I kept `NonNullable` deprecated for backwards compatibility (it as added in 2.3).
=> Rename `NonNullable` to `Required`

examples/app/surface3d/templates/index.html
Small PR to update `surface3d` example to load latest `vis.js` package using SRI hashes and also using the CDN location that the official docs currently specify. Addresses:
* https://github.com/bokeh/bokeh/security/code-scanning/18
=> add SRI hash for vis.js

bokeh/themes/_caliber.py, bokeh/themes/_contrast.py, bokeh/themes/_dark_minimal.py, bokeh/themes/_light_minimal.py, bokeh/themes/_night_sky.py, sphinx/source/docs/releases/3.0.0.rst, tests/unit/bokeh/test_themes.py
The addition of `ContourColorBar` changed the class hierarchy for color bars. I updated the bokehjs themes for this at the time, but did not update the Python themes. This PR fixes it.
Before and after screenshots using code from #12250:
I haven't added a test for this as I see no easy way of doing so. A bokehjs integration test with PNG output does not help as that already worked. A visual test from Python would work for this but that is not something that we do. Hence the manual test images above.
=> Support themes on Python side for ContourColorBar

ci/environment-release-build.yml, ci/environment-test-3.10.yml, ci/environment-test-3.8.yml, ci/environment-test-3.9.yml, ci/environment-test-minimal-deps.yml, environment.yml
Otherwise fails with:
```
sphinx.errors.ExtensionError: Handler <function _process_docstring at 0x7fb3ba4ab550> for
event 'autodoc-process-docstring' threw an exception (exception: pop from an empty deque)
```
=> Pin sphinx to version >=5,<5.1

sphinx/source/docs/first_steps/first_steps_7.rst
Based on discussions in #12237 and #12241, this PR further updates wording about file naming for HTML output files.
=> Add random filename description

bokehjs/src/lib/core/util/types.ts, bokehjs/test/unit/assertions.ts, bokehjs/test/unit/core/util/types.ts
This allows tests like this:
```ts
await expect(async () =>
await build_view(frame, {parent: null})
).to.throw()
```
Extracted from PR #12083.
=> Add support for async `expect().to.throw()`

bokehjs/src/lib/embed/notebook.ts
A workaround that addresses a bug "Problem copying a plot from one jupyter cell to another" from this discussion:
https://github.com/bokeh/bokeh/discussions/12195
=> Remove id attribute of bk-root after plotting

bokeh/colors/color.py, bokeh/colors/util.py, bokeh/palettes.py, tests/unit/bokeh/colors/test_color__colors.py, tests/unit/bokeh/colors/test_util__colors.py, tests/unit/bokeh/test_palettes.py
This PR adds a new `single_color_palette` function to create a palette of a single color but linearly varying alpha. There are 2 use cases, datashader and contouring, listed in discussion #12202. Given the support for `alpha` within `fill_color` and so on, it is not difficult for users to create a palette themselves and pass it to `ColorMapper` or `figure.contour` but this function makes it a one-liner in user code.
Example code:
```python
from bokeh.models import ColorBar, ColumnDataSource, LinearColorMapper
from bokeh.palettes import single_color_palette
from bokeh.plotting import figure, show
p = figure(width=300, height=150, background_fill_color="orange", border_fill_color="orange")
p.xgrid.visible = False
p.ygrid.visible = False
palette = …
```
=> varying_alpha_palette helper function

bokeh/core/properties.py, bokeh/core/property/any.py, bokeh/core/property/bases.py, bokeh/core/property/container.py, bokeh/core/property/dataspec.py, bokeh/core/property/descriptors.py, bokeh/core/property/either.py, bokeh/core/property/enum.py, bokeh/core/property/factors.py, bokeh/core/property/instance.py, bokeh/core/property/json.py, bokeh/core/property/nothing.py, bokeh/core/property/nullable.py, bokeh/core/property/numeric.py, bokeh/core/property/primitive.py, bokeh/core/property/readonly.py, bokeh/core/property/required.py, bokeh/core/property/serialized.py, bokeh/core/property/string.py, pyproject.toml, sphinx/source/docs/releases/3.0.0.rst, tests/unit/bokeh/core/property/test_bases.py, tests/unit/bokeh/core/test_properties.py
This is based on PR #12271, so only the last commit is relevant.
This PR removes `serialized` and `readonly` from properties' `__init__`, and replaces them with existing `Readonly()` and new `NotSerialized()`. Those `__init__` attributes only complicate the API, having to be passed through long inheritance chains, only to be used in `Property` base class. Due to this, many properties don't implement them at all or implement them incorrectly. However, they aren't being used anyway, especially since `Readonly()` was introduced. Thus my proposal is to drop them now. It should be a low impact breaking change.
=> Drop `serialized=False/readonly=True` for `NotSerialized/Readonly`

sphinx/source/docs/user_guide.rst
I've grammatically updated the tech docs.
Changed from "with Bokeh, you should first **completed** the steps described in" to "with Bokeh, you should first **complete** the steps described in".
=> grammatically updated the tech docs

.github/workflows/bokeh-release-build.yml
To help figure out current issues with `bokeh-release-build`. It looks like wrong version of nodejs is picked up when upgrading npm.
=> Add post install status to bokeh-release-build

pyproject.toml, setup.cfg
This PR moves a little closer to consolidating project config in `pyproject.toml` and being able to get rid of `setup.cfg` eventually:
* removes unused `doc8` section
* moves `pytest` config to `pyproject.toml`
Additionally the `mypy` config in `pyproject.toml` was cleaned-up and `strict=true` was added. Values that we redundant (due to `strict` mode, or because they are already the standard default) were removed.
=> Cleanup / condense project configs

bokehjs/src/lib/models/axes/axis.ts, bokehjs/src/lib/models/axes/categorical_axis.ts, bokehjs/src/lib/models/grids/grid.ts, bokehjs/src/lib/models/mappers/log_color_mapper.ts, bokehjs/src/lib/models/ranges/data_range1d.ts, bokehjs/src/lib/models/scales/log_scale.ts
Whilst looking at the colormapper/axis/scale bokehjs code I identified some changes to equations that are functionally identical but result in less code that should be faster to run.
There are 3 changes:
1. Where there is a `dimension` `i` that can only be `0` or `1`, the other dimension `j` is given by `j = 1-i` rather than the longer `j = (i+1)%2`.
2. `log(a) - log(b)` is more simply expressed as `log(a/b)` and this only requires one `log` calculation rather than two.
3. `log(a) / log(10)` is more simply expressed as `log10(a)`.
The log identities are listed at https://en.wikipedia.org/wiki/List_of_logarithmic_identities.
=> BokehJS maths improvements

MANIFEST.in
This makes `bokeh` a typed package in the eyes of mypy.
=> Add `py.typed` marker file for mypy

ci/environment-release-build.yml, ci/environment-test-3.10.yml, ci/environment-test-3.8.yml, ci/environment-test-3.9.yml, ci/environment-test-minimal-deps.yml, environment.yml
Fix https://github.com/pydata/pydata-sphinx-theme/issues/860 and addresses a checkbox here #12203.
See https://github.com/sphinx-doc/sphinx/issues/10594
You need 5.1.1+ due to a napoleon issue (#12265):
https://github.com/sphinx-doc/sphinx/issues/10594
=> Remove double colons from field lists

sphinx/source/docs/dev_guide/setup.rst
Based on the changes from  #12306, one superfluous sentence from the documentation needs to be removed ("This script is located at the top level of the *source checkout* directory.").
=> Update dev setup docs

MANIFEST.in
Cleans up some cruft from `MANIFEST.in` that (according to the setuptools docs and my tests) does not need to be present.
=> clean up MANIFEST.in

.github/workflows/bokeh-ci.yml, bokeh/command/subcommands/serve.py
In Panel we extend the `bokeh serve` command in quite significant ways already but it's always been quite difficult to perform any modifications of the `Server` object before we actually run it. Here I implement a `customize_server` (in line with the `customize_applications` and `customize_kwargs` methods that already exist).
=> Provide method to modify Server before start

src/bokeh/util/package.py, tests/unit/bokeh/util/test_package.py
This PR adds a helper module `bokeh.util.package` that can assist with minimal baseline validation of built packages:
* check that the package reported version is good/as expected
* check that BokehJS files are present / as expected
I intend to use this in CI for the test and release build steps. I will install all three packages (sdist, wheel, and conda) into clean envs and run this validator on them. (I'll update the workflows separately in a later PR) 
cc @bokeh/core are there any other checks that would be good to add?
=> Add package validation helper

.github/workflows/bokeh-ci.yml, MANIFEST.in, scripts/ci/build_conda_pacakge.sh, scripts/ci/verify_conda_install.sh, scripts/ci/verify_pip_install_from_sdist.sh, scripts/ci/verify_pip_install_using_sdist.sh, scripts/ci/verify_pip_install_using_wheel.sh, setup.py, src/bokeh/util/package.py
I am not entirely sure what is different from previous attempts at using proper setuptools commands, but this seems to work in all the following cases:
```
python -m build .
pip install -v . --config-settings quiet=true
pip install -v . -e --config-settings quiet=true
BOKEHJS_ACTION=install python -m build .
BOKEHJS_ACTION=install pip install -v . --config-settings quiet=true
BOKEHJS_ACTION=install pip install -v . -e --config-settings quiet=true
```
Assuming this passes basic CI and good report, I will go on to add a basic package build validation steps based on #12337 
Edit: OK, well, clearly not passing basic CI. I would like to figure out what this discrepancy is, so I will keep poking at this a little longer.
=> Use proper setuptools command extensions

.github/workflows/bokeh-ci.yml, .github/workflows/bokeh-release-build.yml, .github/workflows/bokeh-release-deploy.yml, .gitignore
cc @bokeh/core This PR adds support for the GH codecov upload action and applies it to the Python unit and integration tests. You can see our repo reports at
https://app.codecov.io/gh/bokeh/bokeh
Additionally, codecov can add a comment to the top of PRs (AFAICT it adds a single comment and updates that as needed). There are plenty of options we can play with, but I am inclined to merge this PR as-is to see how it perfoms and then we can consider what if any tweaks we want to make. 
FYI @mattpap codecov can accept and merge reports for multiple languages, so we could potentially generate BokehJS coverage reports as well in the future.
=> Test out codecov action

release/build.py, scripts/ci/verify_conda_install.sh
This is small PR to align some build/validation scripts for use by both Test CI and Release Build jobs. 
Eventually I would like t re-use the entire `python -m release build` machinery for the CI Test  build, so that the release build codebase is executed continuously.
=> Align CI/release build more closely

.pre-commit-config.yaml
This is slightly more work to maintain in case there are new codebase tests added, but that is rare. This PR splits up the codebase checks into individual hooks for more fine-grained output:
The method of running the codebase test in CI, i.e. by simply invoking `pytest tests/codebase` to grab all the tests automatically, has not changed. 
cc @tcmetzger I am not sure if there is anything in the docs that would need to change, installation etc. should be the same.
=> make precommit config more fine-grained

src/bokeh/models/widgets/buttons.py
ref: https://github.com/bokeh/bokeh/discussions/12360
@mattpap this PR undeprecates the *\*on_click* for all of Button, Toggle, and Dropdown, but perhaps only Button is advised.
=> Consider undeprecating *on_click helpers

docs/bokeh/source/docs/first_steps.rst
Fixes broken links in the new grid-item-card that was introduced when updating to this extension (links are handled differently than with the extension we were using before).
Fixes #12378
=> Fix broken links

src/bokeh/core/properties.py, src/bokeh/core/property/alias.py, src/bokeh/core/property/bases.py, src/bokeh/core/property/container.py, src/bokeh/core/property/either.py, src/bokeh/core/property/instance.py, src/bokeh/core/property/struct.py, src/bokeh/core/property/text_like.py, src/bokeh/models/sources.py, src/bokeh/plotting/_figure.py, src/bokeh/plotting/_plot.py, tests/unit/bokeh/core/property/test_container.py, tests/unit/bokeh/core/property/test_either.py, tests/unit/bokeh/core/property/test_instance.py, tests/unit/bokeh/core/property/test_nullable.py, tests/unit/bokeh/core/property/test_primitive.py, tests/unit/bokeh/core/test_properties.py, tests/unit/bokeh/plotting/test_figure.py
```py
In [1]: from bokeh.plotting import figure
In [2]: figure(x_axis_typ="linear")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 figure(x_axis_typ="linear")
File ~/repo/bokeh/src/bokeh/plotting/_figure.py:181, in figure.__init__(self, *arg, **kw)
179 for name in kw.keys():
180     if name not in names:
--> 181         self._raise_attribute_error_with_matches(name, names | opts.properties())
183 super().__init__(*arg, **kw)
185 self.x_range = get_range(opts.x_range)
File ~/repo/bokeh/src/bokeh/core/has_props.py:339, in HasProps._raise_attribute_error_with_matches(self, name, properties)
336 if not matches:
337     matches, text = …
```
=> Add attribute suggestions for `figure(**kwargs)`

conda/environment-release-build.yml, conda/environment-test-3.10.yml, conda/environment-test-3.8.yml, conda/environment-test-3.9.yml, conda/environment-test-minimal-deps.yml
This pins the pydata sphinx theme version to 0.9 (the newer version 1.0 doesn't work with our current customizations). This is a temporary fix - we should update our customizations to be compatible with version 1.0!
=> Pin pydata sphinx theme version

bokehjs/src/lib/core/kinds.ts, bokehjs/src/lib/core/util/iterator.ts, bokehjs/src/lib/models/widgets/autocomplete_input.ts, bokehjs/test/unit/core/kinds.ts, bokehjs/test/unit/core/util/iterator.ts, src/bokeh/models/widgets/inputs.py, tests/baselines/defaults.yaml
This implementation is the most basic one. An alternative (slightly more complicated, at least for me today!) would be to show X completion strings together with a scroll bar to explore the remaining ones (in that case, I don't know if the parameter as defined in this PR would be appropriate or if a parameter limiting the height in pixels of the completions should be preferred). This is my suggestion for now, happy to discuss about it more here or in the issue!
=> AutocompleteInput: add parameter to limit the number of completions displayed

bokehjs/test/defaults/index.ts, src/bokeh/core/has_props.py, tests/baselines/defaults.yaml, tests/support/defaults.py, tests/unit/bokeh/core/test_has_props.py
Makes `defaults.yaml` much smaller and easier to reason about.
=> Include only own and overriden defaults in defaults.yaml

bokehjs/src/lib/core/serialization/deserializer.ts, bokehjs/src/lib/core/serialization/reps.ts, bokehjs/src/lib/core/serialization/serializer.ts, bokehjs/src/lib/model.ts, bokehjs/test/unit/core/serialization.ts, src/bokeh/core/properties.py, src/bokeh/core/property/bases.py, src/bokeh/core/property/container.py, src/bokeh/core/property/either.py, src/bokeh/core/property/wrappers.py, src/bokeh/core/serialization.py, src/bokeh/model/model.py, src/bokeh/util/callback_manager.py, tests/baselines/defaults.yaml, tests/unit/bokeh/core/property/_util_property.py, tests/unit/bokeh/core/property/test_container.py, tests/unit/bokeh/core/property/test_descriptors.py, tests/unit/bokeh/core/property/test_wrappers__property.py, tests/unit/bokeh/core/test_properties.py, tests/unit/bokeh/core/test_serialization.py, tests/unit/bokeh/embed/test_util__embed.py, tests/unit/bokeh/model/test_model.py, tests/unit/bokeh/test_objects.py, tests/unit/bokeh/util/test_callback_manager.py
This was extracted from PR #12370. This PR:
- changes the type of `Model.subscribed_events` to reflect better the behavior of this property
- adds `Set(T)` property type and `PropertyValueSet` wrapper
- adds/finalizes support for serialization of sets
- prunes some duplicated/unnecessary code from parameterized properties
=> Change type of `Model.subscribed_events` to `Set(String)`

docs/bokeh/source/docs/user_guide/basic/data.rst
This add two missing words to the documentation.
=> Add two missing words to data.rst

src/bokeh/plotting/contour.py, tests/unit/bokeh/plotting/test_contour.py
Fixes issue #12506.
`from_contour` uses the presence of `line_color` and `fill_color` in its kwargs to identify if it should calculate and render contour lines and filled polygons respectively. Previously the code just checked if the keys were in the kwargs dictionary but this meant that `line_color=None` would pass the check when it should not have done. So this PR also checks if they are specified but `None`.
I am setting the milestone to 3.1 but I would be happy for it to be squeezed into 3.0 if that is acceptable.
=> Handle line_color=None and fill_color=None in from_contour

bokehjs/src/lib/core/has_props.ts, src/bokeh/model/model.py, tests/unit/bokeh/document/test_models.py, tests/unit/bokeh/model/test_model.py, tests/unit/bokeh/test_objects.py
This brings bokeh up to speed with bokehjs' handling initialization of models with explicit `id`. Using `Model(id="some", **properties)` is now disallowed, only `Model(**properties)` is permitted. Setting an explicit `id` is only permitted by using `Model.__new__(Model, id="some")`. Properties can be later initialized by using `Model.set_from_json(...)` (as `Deserializer._decode_object_ref()` does).
TODO:
=> Don't allow `Model(id="some", **properties)`

bokehjs/src/lib/api/io.ts, bokehjs/src/lib/core/dom.ts, bokehjs/src/lib/embed/dom.ts, bokehjs/src/lib/embed/index.ts, bokehjs/src/lib/embed/json.ts, bokehjs/src/lib/embed/notebook.ts, bokehjs/src/lib/embed/server.ts, bokehjs/src/lib/embed/standalone.ts, docs/bokeh/docserver.py, src/bokeh/models/plots.py, src/bokeh/util/serialization.py
This also allows to embed into document fragments and improves handling of embedding under shadow DOM.
fixes #12101
=> Allow `plt.show()` to append after a `<script>`

docs/bokeh/source/docs/user_guide/topics/hierarchical.rst
@bryevdv did you mean for the intro paragraph of the "Hierarchical data" section to be above the main headline?
If not, this PR moves the section underneath the main headline. Otherwise, feel free to simply close this PR!
=> Move intro paragraph

docs/bokeh/Makefile, src/bokeh/sphinxext/bokeh_model.py
The `-W` was removed from the docs build during the extensive re-org, but a problem has crept in in the mean time. THings are more stabilized now, so this PR restores the `-W` strict build option, and fixes the issue that cropped up with Model signatures. 
I am not sure what the root cause of the problem with Model signatures is at this time, I do not have time to chase it down. 
@mattpap FYI Sphinx computes a signature `id`:
I don't think this is quite right given your recent changes? I won't have time today to do anything about it. If you agree it isa problem please open an issues that describes exactly what should/should not appear in the refguide entries.
=> Restore strict docs build

src/bokeh/core/has_props.py, src/bokeh/model/model.py, tests/unit/bokeh/embed/test_bundle.py, tests/unit/bokeh/test_objects.py, tests/unit/bokeh/test_resources.py
This prevents sharing mutable class state, which can lead to inconsistencies at runtime. I kept `model_class_reverse_map` for now, but I will deprecate it and remove its usage in near future. `_ModelResolver` and `_default_resolver` are private for now (as `_` indicates).
fixes #12416
=> Robustify maintenance of models' registry

conda/environment-release-build.yml, conda/environment-test-3.10.yml, conda/environment-test-3.8.yml, conda/environment-test-3.9.yml, conda/environment-test-downstream.yml, conda/environment-test-minimal-deps.yml, pyproject.toml, tests/codebase/test_no_typing_extensions_common.py
This PR continues from #12538 and removes `typing_extensions` as a runtime dependency altogether.
=> Remove runtime dependency on typing_extensions

conda/environment-test-3.10.yml, conda/environment-test-3.11.yml, conda/environment-test-3.8.yml, conda/environment-test-3.9.yml, conda/environment-test-minimal-deps.yml, src/bokeh/core/templates.py
Fixes:
```
mypy 0.990 (compiled: yes)
src/bokeh/core/templates.py:78: error: Unused "type: ignore" comment
meipass: str = sys._MEIPASS # type: ignore[attr-defined]
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in 1 file (checked 719 source files)
```
=> Upgrade to mypy 0.990

.github/workflows/bokeh-ci.yml
This PR disables the integration tests job. Prior to #12571 there was typically one "expected" failure, but now there are many, and it is not possible to distinguish "normal" failure to "real" failure. Disabling until the test job can be fixed or replaced.
=> Disable Selenium integration tests for now

conda/environment-test-3.10.yml, conda/environment-test-3.11.yml, conda/environment-test-3.8.yml, conda/environment-test-3.9.yml, pyproject.toml, src/bokeh/plotting/_figure.py
Fixes:
> from numpy.typing import ArrayLike
ModuleNotFoundError: No module named 'numpy.typing'
See also:
* https://numpy.org/doc/stable/release.html#:~:text=numpy.typing%20is%20accessible%20at%20runtime
* https://github.com/kernc/backtesting.py/issues/805
=> Guard numpy.typing.ArrayType with `if TYPE_CHECKING`
